### ISSUE TITLE
dials.scale: No groups left with multiplicity >1, scaling not possible 

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1006]
The following two xia2 jobs failed in dials.scale using `module load dials/now`:
`xia2 pipeline=dials min_images=3 project=AUTOMATIC crystal=DEFAULT read_all_image_headers=False atom=S image=/dls/i03/data/2019/nt18231-17/tmp/2019-11-08/17-01-34-2fb5a533/ProtK_InSitu_Au_47_8_1_0001.cbf:1:25 dynamic_shadowing=False resolution.cc_half_significance_level=0.1`
and
`xia2 pipeline=dials min_images=3 project=AUTOMATIC crystal=DEFAULT read_all_image_headers=False atom=S image=/dls/i03/data/2019/nt18231-17/tmp/2019-11-08/17-01-34-2fb5a533/ProtK_InSitu_Au_47_6_1_00
01.cbf:1:25 dynamic_shadowing=False resolution.cc_half_significance_level=0.1`

Relevant dials.scale log files are here:
`/dls/i03/data/2019/nt18231-17/tmp/zocalo/tmp/2019-11-08/17-01-34-2fb5a533/ProtK_InSitu_Au_47_6_1_/f737cb8f-ac8c-435d-a021-9735e33c660d/xia2-dials/DEFAULT/scale/22_dials.scale.log`
`/dls/i03/data/2019/nt18231-17/tmp/zocalo/tmp/2019-11-08/17-01-34-2fb5a533/ProtK_InSitu_Au_47_8_1_/44353390-312e-4da8-88bd-1a90c23e3df8/xia2-dials/DEFAULT/scale/22_dials.scale.log`

Both failed with the same error message:
```
No groups left with multiplicity >1, scaling not possible.
# command line:
# dials.scale  '/dls/i03/data/2019/nt18231-17/tmp/zocalo/tmp/2019-11-08/17-01-34-2fb5a533/ProtK_InSitu_Au_47_8_1_/44353390-312e-4da8-88bd-1a90c23e3df8/xia2-dials/DEFAULT/SAD/SWEEP1/integrate/20_integrated.expt' '/dls/i03/data/2019/nt18231-17/tmp/zocalo/tmp/2019-11-08/17-01-34-2fb5a533/ProtK_InSitu_Au_47_8_1_/44353390-312e-4da8-88bd-1a90c23e3df8/xia2-dials/DEFAULT/SAD/SWEEP1/integrate/20_integrated.refl' 'nproc=20' 'model=auto' 'full_matrix=True' 'error_model=basic' 'outlier_rejection=standard' 'partiality_cutoff=0.4' 'outlier_zmax=6' 'output.html=22_scaling.html' 'output.experiments='22_scaled.expt'' 'output.reflections='22_scaled.refl''
```

**Comment by jbeilstenedmands** [comment]
I've had a quick look, seems that in dials2.0 for this dataset it doesn't do any actual scaling as there are no equivalents but the program still completes (all scales 1). So the behaviour here makes sense, but would probably be more helpful to still complete as it did in dials 2.0
