### ISSUE TITLE
Publishing DIALS releases

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#102]
May consider pushing our self-contained release builds (currently approx 1GB/release in total for Mac, Mac, Linux, Source) to Zenodo or archive.org. Discuss.

**Comment by graeme-winter** [comment]
That could work (alt: would work just fine) I see no down sides (open
source; BSD; gives DOI)

**Comment by Anthchirp** [comment]
Discussed this. Won't do Zenodo for now. Could do Zenodo for DIALS package only, but little gain.
