### ISSUE TITLE
Windows test failures checking output vs expected string

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1026]
As found by Oleg Kovalevskiy.

These tests check output against a string literal
https://github.com/dials/dials/blob/0831a65ae928842eae985f091105d3cd9bca6c67/test/command_line/test_export_best.py#L48-L62
https://github.com/dials/dials/blob/0831a65ae928842eae985f091105d3cd9bca6c67/test/command_line/test_merge.py#L152-L157
https://github.com/dials/dials/blob/0831a65ae928842eae985f091105d3cd9bca6c67/test/command_line/test_merge.py#L176-L181
https://github.com/dials/dials/blob/0831a65ae928842eae985f091105d3cd9bca6c67/test/command_line/test_show.py#L16-L72
https://github.com/dials/dials/blob/0831a65ae928842eae985f091105d3cd9bca6c67/test/command_line/test_show.py#L284

These fail on Windows because of the `\r\n` line endings

**Comment by dagewa** [comment]
This is suspicious because opening as text files should convert line endings. It could be some other difference in the string, but I can't currently check as the CCP4 7.1 Windows build seems broken.

**Comment by dagewa** [comment]
Nope, I've got the CCP4 build up and running and it really does look like line endings
```
>       assert (
            lines
            == """\
      181.8877       0.77       1.60
       63.1895       1.59       1.81
       38.2372       1.87       1.71
       27.4131       1.84       1.55
       21.3655       1.89       1.51
       17.5043       1.88       1.49
       14.8254       1.89       1.45
       12.8580       1.91       1.45
       11.3518       1.89       1.42
       10.1617       1.87       1.41
    """
        )
E       AssertionError: assert '  181.8877  ...     1.41\r\n' == '  181.8877   ...       1.41\n'
E         -   181.8877       0.77       1.60
E         ?                                 -
E         +   181.8877       0.77       1.60
E         -    63.1895       1.59       1.81
E         ?                                 -
E         +    63.1895       1.59       1.81
...       -    38.2372       1.87       1.71
E
E         ...Full output truncated (24 lines hidden), use '-vv' to show

test_export_best.py:48: AssertionError
========================== 1 failed in 46.86 seconds ==========================
```

**Comment by dagewa** [comment]
Ah, universal newlines became [default in Python 3](https://www.python.org/dev/peps/pep-3116/#text-i-o).

**Comment by dagewa** [comment]
test_export_best.py and test_merge.py are fixed easily by adding `.replace("\r" ,"")` to the LHS of the `assert`. test_show.py is more complicated; there's a leading `}` involved, The dials.show output is different between Linux and Windows in more than mere line endings.

```
E       AssertionError: assert '}\nExperiment...,0,1,0,0,0,1}' == 'Experiment 0:...,0,1,0,0,0,1}'
E         - }
E           Experiment 0:
E           Detector:
E           Panel:
E             name: Panel
E             type: SENSOR_PAD
E             identifier:...
E
E         ...Full output truncated (36 lines hidden), use '-vv' to show

test_show.py:140: AssertionError
```

**Comment by dagewa** [comment]
The full output of
```
ccp4-python C:\CCP4-7.1\7.1\Scripts\py.test-script.py --regression -s test\command_line\test_show.py
```
is attached. Looks like a lot of extra blank lines in the output on Windows...
[test.show.txt](https://github.com/dials/dials/files/3897961/test.show.txt)

**Comment by dagewa** [comment]
The output of `dials.show imported.expt` on Windows, after importing the `centroid_test_data`
[dials.show.txt](https://github.com/dials/dials/files/3899080/dials.show.txt). Don't see the blank lines here.

**Comment by dagewa** [comment]
But stdout on Windows has two extra lines at the start: :thinking: 
```bash
$ diff --strip-trailing-cr windows.txt linux.txt 
1,2d0
< 
< C:\ccp4temp>ccp4-python -Qnew -m  dials.command_line.show  imported.expt 
```
Think it might be a CCP4 dispatcher issue...

**Comment by Anthchirp** [comment]
Looks like you need to prefix the line `ccp4-python ...` in the dispatcher with an `@` to silence the echo.

**Comment by dagewa** [comment]
Confirmed, that simple change allows the test to pass on Windows :-) Thanks, I'll see about modifying the CCP4 build to add the `@` prefixes.
