### ISSUE TITLE
Remove dials dependency on xfel module

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#103]
The two dependencies that need to be relocated:
xfel.mono_simulation -> rstbx
xfel.command_line.frame_extractor -> ?

Then, revert change to libtbx_config.

**Comment by dagewa** [comment]
@phyy-nx Hi, is this still relevant?

**Comment by phyy-nx** [comment]
Yep!  I'd still like to track this.

**Comment by dagewa** [comment]
Another 12 months+ has passed, just wondering if this remains a current concern?

**Comment by phyy-nx** [comment]
I no longer think it's worth solving this nor do I have time to.  Xfel needs dials and dials needs xfel. 
 You'd never build xfel without dials.  Closing.

**Comment by graeme-winter** [comment]
Is the dependency truly circular?

**Comment by graeme-winter** [comment]
🤔 would much prefer cctbx dependencies to be a DAG rather than closed loops...

**Comment by phyy-nx** [comment]
Sure, I would too.  Not a priority though.
