### ISSUE TITLE
dials.refine trimming scans does not-the-right-thing for > 1 lattice

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1053]
This may feel a spot artificial but the use case of two lattices in the beam at different times feels like a core application for this. 

[indexed.zip](https://github.com/dials/dials/files/3915892/indexed.zip)

Example data attached - very small - indexed.(refl|expt) usual stuff works fine with scan varying refinement. 

Trimmed down indexed reflections with:

```
from dials.array_family import flex

data = flex.reflection_table.from_file("indexed.refl")

# prune only indexed reflections

data = data.select(data.get_flags(data.flags.indexed))
z = data["xyzobs.px.value"].parts()[2]

# take overlapping subsets of reflections from two lattices which do not
# fill the entire scan

sel = ((data["id"] == 0) & (z > 200)) | ((data["id"] == 1) & (z < 650))
trimmed = data.select(sel)

trimmed.as_file("indexed_trim.refl")
```

i.e. to get two lattices in place at different times in the scan. Scan 0 should be trimmed to the end of the run, scan 1 to the start. This is not what happens:

```
The reflections do not fill the scan range. The scan will be trimmed to images {197,850} to match the range of observed data
The reflections do not fill the scan range. The scan will be trimmed to images {197,662} to match the range of observed data
```

I can totally see why, but I thought putting a test case together would be courteous so we can prevent regressions in the future. This data was recorded from a small molecule called PdTEET as part of routine I19 commissioning so we can fill our boots with making public.

**Comment by dagewa** [comment]
I see, there is one scan but multiple crystals. I suppose `dials.refine` should ensure every crystal gets its own scan if scan-varying refinement is going to be done. This is sort of like #994, but duplicating scans rather than crystals.

**Comment by graeme-winter** [comment]
Very much so! I had naively assumed each one would have a scan, which is true, but did not recognise that the scans would be _the same_.

Perhaps more elegant would be if you are trimming a scan you make a copy of it, so that the ones which share a scan are still sharing if the scans are not modified. A copy-on-write so to speak.

**Comment by dagewa** [comment]
Yes, I started thinking about a more complicated change, but I think this sounds better.

**Comment by graeme-winter** [comment]
You want me to take a look? Probably the work of 5 minutes and I have the data handy

**Comment by graeme-winter** [comment]
oh right that was easy 

```
Grey-Area dials :) [master] $ git diff
diff --git a/algorithms/refinement/refiner.py b/algorithms/refinement/refiner.py
index cf81a3a83..43908cb47 100644
--- a/algorithms/refinement/refiner.py
+++ b/algorithms/refinement/refiner.py
@@ -214,7 +214,9 @@ def _trim_scans_to_observations(experiments, reflections):
                 )
             )
 
-            exp.scan.set_image_range((im_start, im_stop))
+            scan = copy.deepcopy(exp.scan)
+            scan.set_image_range((im_start, im_stop))
+            exp.scan = scan
 
     return experiments
```

**Comment by dagewa** [comment]
I've already got it.

**Comment by graeme-winter** [comment]
👍

**Comment by graeme-winter** [comment]
Propose we re-open and add a test case to prevent regressions 🙂

**Comment by dagewa** [comment]
We can produce this kind of test case on the fly from any suitable input in `dials_data`, i.e. using the code in your first comment. However, as noted might be good to update `dials_data` contents first, as discussed elsewhere

**Comment by graeme-winter** [comment]
@graeme-winter adding test
