### ISSUE TITLE
Image viewer beam centre crosshairs displayed incorrectly for multiple sweeps with different 2θ values

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#1058]
When you have multiple sweeps with different 2θ values and when scrolling through multiple sweeps, the image viewer doesn't update the beam centre mark correctly for the second and subsequent sweeps, retaining the position for the first sweep.

For example, using output from xia2 with joint indexing (as from `xia2.small_molecule`) on an example data set:
`dials.image_viewer DEFAULT/NATIVE/SWEEP1/index/*_SWEEP*_strong.*`
First sweep is OK:
![image](https://user-images.githubusercontent.com/11389015/70076704-4069c380-15f7-11ea-82bf-af14c89513f4.png)

However, on the first sweep to have a different 2θ value, the beam centre crosshairs do not move.  The dynamic mask and powder mask are correctly centred though, so it seems only the corsshairs are affected:
![image](https://user-images.githubusercontent.com/11389015/70076427-a9047080-15f6-11ea-9cb3-902158bb9f18.png)

Meanwhile, opening the affected sweep directly, the crosshairs are correctly displayed:
`dials.image_viewer DEFAULT/NATIVE/SWEEP1/index/*_SWEEP6_strong.*`
![image](https://user-images.githubusercontent.com/11389015/70076616-10222500-15f7-11ea-8efe-f19939554d32.png)

So it looks like this is just an issue with the display of the crosshairs.

**Comment by dagewa** [comment]
The crosshair display relies on this function call:
https://github.com/dials/dials/blob/5545dc29f89fac3534081908dc3742d0ab92c755/util/image_viewer/slip_viewer/frame.py#L338-L345
ultimately that gets the detector and beam from the imageset:
https://github.com/dials/dials/blob/5545dc29f89fac3534081908dc3742d0ab92c755/util/image_viewer/slip_viewer/frame.py#L35-L42
I'm not sure what that does in this multi-sweep case. Do we have a public test data set with which to demonstrate this?

**Comment by dagewa** [comment]
Ah, `get_detector()` is implicitly equal to `get_detector(0)`. Same for beam

**Comment by graeme-winter** [comment]
Fixing this is likely to be a mess, as the `chooser_wrapper` class I think is not really geared up to this...

I will have a look though

**Comment by graeme-winter** [comment]
🤔 resolution rings work fine

**Comment by graeme-winter** [comment]
Got this one
