### ISSUE TITLE
Mask generation very slow now

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1061]
Running on both `module load dials/latest` and my own python3, mask generation seems to be slow now, such that when running `dials.find_spots` there is a long wait before spotfinding begins e.g. between these two lines of output:
```
Extracting strong pixels from images
 Using multiprocessing with 5 parallel job(s)
```
I ran profiling and it seems to be in the pre-spotfinding mask generation:

![image](https://user-images.githubusercontent.com/529963/70320526-dc284900-181c-11ea-8072-f738e183b8ef.png)

**Comment by graeme-winter** [comment]
See https://github.com/dials/dials/pull/980 as probable source

**Comment by graeme-winter** [comment]
Uuuhh I think this is silently a massive problem? Discuss?

**Comment by graeme-winter** [comment]
Trying to find spots on an 8,000 image grid and spin-up time taking $ages of mankind.

**Comment by dagewa** [comment]
suggested workaround, use the first 1000 images only to look for hot pixels. Until we have a fast way of doing this through the whole sweep

**Comment by graeme-winter** [comment]
workaround of `use_trusted_range=false` gets the spot finding going straightaway...

**Comment by graeme-winter** [comment]
@dagewa reasonable however even 1k hot pixel search is time consuming. Not sure of the right solution here but I think it is fair to say that the current solution is not right.

**Comment by dagewa** [comment]
Original code simply used the first image. That was no good. Even just look at first and last image would be much better

**Comment by graeme-winter** [comment]
Or a “large” random selection drawn from the data set… yes

Large as in, “I can’t be bothered to count that many"

**Comment by dagewa** [comment]
Or, indeed, don't add trusted range into the mask. Isn't it effectively masked anyway, by being an "overload" shoebox?

**Comment by Anthchirp** [comment]
massive regression on DIALS 2.1
for beamline spotfinding plots this adds 66 seconds/img * 250 images per data collection = 4.6 CPU hours.

**Comment by dagewa** [comment]
Ouch, actually just read @Anthchirp's comment properly - 66 seconds _per image_! The 100 image workaround is still no good then

**Comment by dagewa** [comment]
@rjgildea points out this is possibly because per image analysis treats every image separately and may well then be running this whole mask calculation (which touches every image) repeatedly

**Comment by dagewa** [comment]
#1084 is now faster. Is this a sensible way to go?

**Comment by graeme-winter** [comment]
as a stop-gap - `use_trusted_range=false` - ?
