### ISSUE TITLE
dials.image_viewer sum_images should show summed statistics, shoeboxes across range

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#107]
Split off from https://github.com/dials/dials/issues/55

* sum intensities for status bar across images
* accumulate spot list i.e. if you have frames 1...10 then we need spots with centroids z=[0,10) to be plotted also.

**Comment by graeme-winter** [comment]
This turns out to be hard if you have to show the mask flattened down as well :(

**Comment by graeme-winter** [comment]
Happy now that this works

**Comment by graeme-winter** [comment]
<img width="385" alt="screen shot 2016-06-08 at 15 31 01" src="https://cloud.githubusercontent.com/assets/1241716/15897872/0b7f3844-2d8e-11e6-9797-19fc7436e986.png">
