### ISSUE TITLE
The gain calculated by dials.estimate_gain is unrealistic

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1071]
The gain calculated by dials.estimate_gain is unrealistic for any detector that has significant correlation between local pixels, like phosphor-taper-CCDs. Because the results may be suspect, we are hesitant to calculate this automatically. There isn't really a foolproof method to determine the gain, although looking at the variance of a single pixel in a region of background down a stack of images is likely to be better than looking at the variance in a region of interest on a single image (as long as background is slowly changing with time or the trend can be removed).

The best approach, of course, is to know the gain from technical specifications of the detector or careful experiments and to write it into the Format class. Whenever this is done, there should be no need for a gain=auto.

_Originally posted by @dagewa in https://github.com/dials/dials/issues/245#issuecomment-256358635_

**Comment by dagewa** [comment]
This keeps coming up (conversation with user). I would like to investigate a new mode of operation for `dials.estimate_gain`, which uses variance down a stack of images rather than in a local area to address these issues. A stack of say 20 contiguous images would provide a very large number of "time series" of pixel values, which can be de-trended to remove overall scale change and then investigated to see how they vary in comparison with Poisson statistics

**Comment by asmit3** [comment]
Hi David,

I was curious what your experience has been when using ```dials.estimate_gain``` for phospor-taper CCDs ? I am working on a Rayonix-170 dataset (4x4 binning) and have been told a different gain value (0.75) by the manufacturer compared to what I get using estimate_gain (0.23). The value calculated by ```dials.estimate_gain``` also changes with change in binning (when it should not).

**Comment by dagewa** [comment]
Hi @asmit3, right, this is exactly the issue. `dials.estimate_gain` does not work well for phosphor-taper-CCDs. The binning affects the size (in pixels) of the point spread. Larger binning means apparently more variance in the local region of pixels and a higher estimated gain, which as you say should not be the case! It is not just `dials.estimate_gain`, Mosflm and XDS both use the same flawed method to estimate gain, and both seriously underestimate it.

We've known about this issue for a long time (#23) and now set the gain to "known" values for detectors we specifically recognise. See `_get_rayonix_gain` in https://github.com/dials/dxtbx/blob/7504f5f0c9e16bed5965011311aa52bf8bb11edc/format/FormatTIFFRayonix.py#L285-L288 

I think it would be appropriate to add the relevant details for Rayonix-170 in here. I will try to fix `dials.estimate_gain` at some point - however it is actually very hard to get right. Even if you have a method that is not affected by the point spread function, you are stuck with the fact that integrating detectors don't follow Poisson statistics, which simply sets the lower limit for the variance.

By the way, 0.75 is unusual. Most CCDs have a gain set purposely > 1.0, so that ADUs are more fine-grained than photons. This reduces the effect of digitisation error in the signal.
