### ISSUE TITLE
dials.combine_experiments & dials.scale clobber archaic imageset_ids, messing up display in image_viewer and reciprocal_latice_viewer

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#1093]
Four experiment lists and reflection tables from four sweeps after integration:
![image](https://user-images.githubusercontent.com/11389015/72431512-eaa74000-378c-11ea-899a-421ca32d00cf.png)

After applying `dials.combine_experiments` to the same four integrated experiment lists and reflection tables:
![image](https://user-images.githubusercontent.com/11389015/72432059-124ad800-378e-11ea-93d7-f57630a1d188.png)

It is worth noting that the first sweep is displayed correctly but all subsequent sweeps are incorrectly displayed, perhaps because they are using (part of)? the experiment model from the first sweep:
![image](https://user-images.githubusercontent.com/11389015/72431857-b1bb9b00-378d-11ea-9297-809390d3346d.png)

For DIALS East developers, there is example data at `/dls/tmp/ekm22040/directories/vEPi8Bi8` where the example data files are
- `DEFAULT/NATIVE/SWEEP1/integrate/25_integrated.expt`
- `DEFAULT/NATIVE/SWEEP2/integrate/30_integrated.expt`
- `DEFAULT/NATIVE/SWEEP3/integrate/35_integrated.expt`
- `DEFAULT/NATIVE/SWEEP4/integrate/40_integrated.expt`
- `DEFAULT/NATIVE/SWEEP1/integrate/25_integrated.refl`
- `DEFAULT/NATIVE/SWEEP2/integrate/30_integrated.refl`
- `DEFAULT/NATIVE/SWEEP3/integrate/35_integrated.refl`
- `DEFAULT/NATIVE/SWEEP4/integrate/40_integrated.refl`
and
- `combined_experiments/combined.expt`
- `combined_experiments/combined.refl`

**Comment by benjaminhwilliams** [comment]
Sorry, I stand corrected, if you do `dials.combine_experiments` on the integrated data, you see the same effect.  This isn't a bug in `dials.scale`, just in `dials.reciprocal_lattice_viewer`.

**Comment by benjaminhwilliams** [comment]
Ah, @ndevenish and I have just found the root of the problem.  `dials.reciprocal_lattice_viewer` distinguished between different sweeps based on the `'imageset_id'`.  `dials.combine_experiments` and `dials.scale` always produce combined reflection tables with all `'imageset_id'`s set to zero.  Sweeps are instead distinguished by `'id'` (which raises the question, why do we have both anyway?).

**Comment by ndevenish** [comment]
So after tracking this down with @benjaminhwilliams I think I've seen this problem before in `combine_experiments` - I even wrote a patch to fix I believe this issue in `combine_experiments` in https://github.com/ndevenish/dials/commit/e7140fbe01f42242e847a7f61c48473951c29979 - but being a low level data change wanted to get robust tests in place before jumping in as I wasn't sure the full implications.

**Comment by ndevenish** [comment]
I'm not sure why reciprocal lattice viewer and the reciprocal space mapping uses `imageset_id` _instead_ of ID - to the extent of deliberately wiping out the latter sometimes.

**Comment by benjaminhwilliams** [comment]
@dermen reports something that appears to be a manifestation of this issue, affecting stills data combined with `dials.combined_experiments`.  All reflection annotations in the image viewer are displayed on the first imageset (single images in that case), rather than their correct imagesets.

**Comment by dermen** [comment]
I started working on a branch in dials (multiple_stills_view) to address the issue of opening stills+combined.expt in the image_viewer. So far, it works for properly displaying spots (although loading combined.expt is rather slow depending on the underlying image formats) . The idea is to adjust the self.reflections object accordingly during the __init__ of SpotFrame .. Not sure if its the best way to go however..

**Comment by benjaminhwilliams** [comment]
A user complaint reminded me of this issue.  As a guide to how it manifests in `dials.image_viewer`, here are the first images from each of the first two sweeps of a multi-sweep data set.  All the spot annotations are overlaid on the images of the first sweep, instead of being overlaid on the relevant sweeps.

Sweep 1, image 1:
![image](https://user-images.githubusercontent.com/11389015/122795854-a68b6980-d2b5-11eb-8a54-d6cb0271e669.png)

Sweep 2 image 1:
![image](https://user-images.githubusercontent.com/11389015/122795749-88be0480-d2b5-11eb-9a36-08a328ab3a23.png)

**Comment by graeme-winter** [comment]
I note that this is workflow dependent - 

```
dials.import ../dmu24dnba_0*
dials.find_spots imported.expt 
dials.index imported.expt strong.refl 
dials.refine indexed.*
dials.integrate refined.*
dials.symmetry integrated.*
dials.scale symmetrized.*
dials.image_viewer scaled.*
```

Does what you would hope:

![Screenshot 2021-06-22 at 06 39 52](https://user-images.githubusercontent.com/1241716/122869842-bc844300-d324-11eb-9b0a-a7f817a5eacf.png)
![Screenshot 2021-06-22 at 06 40 01](https://user-images.githubusercontent.com/1241716/122869846-bf7f3380-d324-11eb-8cae-516377191fad.png)
![Screenshot 2021-06-22 at 06 40 08](https://user-images.githubusercontent.com/1241716/122869849-c017ca00-d324-11eb-9b33-79e2ba3ebf81.png)
![Screenshot 2021-06-22 at 06 40 16](https://user-images.githubusercontent.com/1241716/122869854-c148f700-d324-11eb-89a8-6316490ada2d.png)

**Comment by benjaminhwilliams** [comment]
@graeme I think we narrowed this problem down to `dials.combine_experiments`, so you're right that it is workflow dependent.  I think if you split and combine your `scaled.{e*,r*}` you may see the problem.

This is of course an issue for anyone who is using xia2 for multiple sweep data, since xia2 keeps experiment lists and reflection tables from each sweep separate throughout the pipeline, until finally combining at the very end.

**Comment by graeme-winter** [comment]
```
dials.split_experiments  scaled.*
dials.combine_experiments  split_*
dials.image_viewer  combined.*
```

still displays as above -> not denying that this is a bug in `xia2` but I think the point is the bug is in `xia2` rather than DIALS. Or if it is in DIALS, it is a side-effect of a graph which is this shape:

```
----\
-----+--->
----/
```

rather than this shape

```
    /-----\
--+-----+---->
    \-----/
```

i.e. data only ever meet one another at the end (so stupid stuff with `imageset_id` nonsense)

**Comment by graeme-winter** [comment]
🤔  when we combine data from multiple image sets all with `imageset_id=1` we should be doing some kind of re-unique-making stuff right?

**Comment by graeme-winter** [comment]
Minimal reproducer: 

```
mkdir 1 4 
cd 1
dials.import ../../dmu24dnba_01_00*
dials.find_spots imported.expt 
dials.index imported.expt strong.refl 
cd ../4
dials.import ../../dmu24dnba_04_00*
dials.find_spots imported.expt 
dials.index imported.expt strong.refl 
cd ..
dials.combine_experiments */indexed*
dials.show combined.refl 
```
-> max `imageset_id` is 0 not 1 -> can write a simple command-line test for this using data from any data with > 1 sweep.

**Comment by graeme-winter** [comment]
```
dials.data get l_cysteine_dials_output
```

includes 15 frames from each scan so that should be enough to reproduce the error above, investigating.

**Comment by ndevenish** [comment]
@benjaminhwilliams, do you have time to run over with your use-cases to check if this is now fixed? I think the last three commits should have been enough....

**Comment by benjaminhwilliams** [comment]
> @benjaminhwilliams, do you have time to run over with your use-cases to check if this is now fixed? I think the last three commits should have been enough....

Apologies and thanks @ndevenish and @jbeilstenedmands, I'm not sure how I missed this at the time.  I'm pleased to say I can no longer reproduce the issue.  Case closed.
