### ISSUE TITLE
dials.util.resolutionizer.Resolutionizer sometimes fails with empty resolution bins

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#1097]
When `dials.util.resolutionizer.Resolutionizer` is instantiated on data that result in one or more resolution bins containing no reflections (as seems to happen sometimes when passing it a number of reflections of order 1000 and asking it to apply the default 100 bins), it fails with an `iotbx.merging_statistics.StatisticsError`, arising here
https://github.com/cctbx/cctbx_project/blob/ded199b9344f44f8a3ef4e21a39fad46ea98b296/iotbx/merging_statistics.py#L241-L243

This is causes a failure in `dials.symmetry`, which uses this class to impose a resolution filter, as well as `dials.resolutionizer`, naturally.  Particularly seen on small-molecule data with few reflections.

I guess we could either try to fix this in `iotbx` (I'm not sure if I'm allowed to tread there), or catch the exception and try to do something graceful with it.

**Comment by benjaminhwilliams** [comment]
I notice this in xia2:

**Comment by benjaminhwilliams** [comment]
I'll add an equivalent fix in `dials.resolutionizer` and `dials.symmetry`, if you're happy with that as a fix @rjgildea.  Or did you want to fix it at source?

**Comment by benjaminhwilliams** [comment]
Ah, I see this has come up before in the same circumstances.
https://github.com/cctbx/cctbx_project/issues/17

**Comment by rjgildea** [comment]
The issue with the counting_sorted method is that if the number of reflections per bin is sufficiently small, you risk getting bins where the start and end d_star_sq is identical, leading to no reflections being included in that bin:
https://github.com/cctbx/cctbx_project/blob/42d9b7b7df5b988f2fb32f80102c1a4001b9f180/cctbx/miller/__init__.py#L1727-L1729

In dials.symmetry we override the default n_bins to 20, but even in some small molecule cases this is too many, as e.g. the input may only be ~300 reflections:
https://github.com/dials/dials/blob/c7679608d75fa43b8b4b1571141ed4550ee588df/algorithms/symmetry/__init__.py#L330-L336

**Comment by benjaminhwilliams** [comment]
Also affects [SCI-6476](https://jira.diamond.ac.uk/browse/SCI-6476).

**Comment by benjaminhwilliams** [comment]
On a similar note, intensity normalisation also sometimes fails for small spot counts (see [SCI-7272](/dls/tmp/ekm22040/directories/M3ztQIh3/DEFAULT/scale/87_dials.symmetry.log)).  We clearly need strategies for handling small numbers of reflections robustly in `dials.symmetry`.
