### ISSUE TITLE
MTZ output: space group labels

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1099]
Request from Clemens - 

we have problems running MRFANA on MTZ files exported from Dials:

From XIA2 0.6.354-gceb7eb98-dials-2.1, run on 15/01/2020 at 08:44:58
From DIALS 2.1.0-g40973e3ce, run on 2020-01-15 at 08:44:31 GMT

The problem seems to be that the spacegroup is written differently
into the MTZ file now: 'P1' instead of 'P 1' (the SG number is
obviously correct here):

* Space group = 'P1' (number      1)

This is different from previous versions of such MTZ files, ie. from

From XIA2 0.5.902-gffa11588-dials-1.14, run on 15/01/2020 at 10:10:25
From AIMLESS, version 0.7.4, run on 15/ 1/2020 at 10:09:52
From SORTMTZ 15/ 1/2020 10:09:05  using keys: H K L M/ISYM BATCH
From POINTLESS, version 1.11.21, run on 15/ 1/2020 at 10:09:04
From SORTMTZ 15/ 1/2020 10:08:36  using keys: H K L M/ISYM BATCH
From POINTLESS, version 1.11.21, run on 15/ 1/2020 at 10:08:33
From DIALS 1.14.13-g10ecfbb15-release, run on 2020-01-15 at 10:08:18 GMT

where we have

* Space group = 'P 1' (number      1)

Presumably, this will also affect other SGs, like "P 21 21 21" vs
"P212121" and "P 1 21 1" etc?

Although I agree that P1 and P21 is nicer than "P 1" and "P 1 21 1",
the normal CCP4/MTZ way would require the latter - and indeed, the
CCP4 libraries as called from (Fortran) MRFANA seem to get confused
with the space-less form.

Could you have a check about that? And while you're at it: would it be
possible to write those MTZ files out in "standard" sort order, namely
"H K L M/ISYM BATCH" as before? That would make it easier for users
wanting to run MRFANA on those files.

**Comment by rjgildea** [comment]
Space group name is set here:
https://github.com/cctbx/cctbx_project/blob/42d9b7b7df5b988f2fb32f80102c1a4001b9f180/iotbx/mtz/__init__.py#L274

The name that goes into the file is determined by this function `ccp4_symbol`:
https://github.com/cctbx/cctbx_project/blob/42d9b7b7df5b988f2fb32f80102c1a4001b9f180/iotbx/mtz/extract_from_symmetry_lib.py#L25-L66

which ultimately from a lookup in the `"symop.lib"` file:
https://github.com/cctbx/cctbx_project/blob/42d9b7b7df5b988f2fb32f80102c1a4001b9f180/iotbx/mtz/extract_from_symmetry_lib.py#L68-L82
