### ISSUE TITLE
Eliminate legacy 'imageset_id' in reflection tables

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#1104]
Move to determination of image set from experiment ID → experiment → imageset.

**Comment by ndevenish** [comment]
Do we have empty experiments pre-indexing now?

**Comment by benjaminhwilliams** [comment]
I don't know what the state of play is on that.  Who's plate is that on?

**Comment by ndevenish** [comment]
I mean, without being certain on that we can’t call this legacy? Because otherwise is required for unindexed reflections?

**Comment by rjgildea** [comment]
Currently the experiment "id" is overloaded to mean two different things:
1) After spotfinding to associate a strong spot with an imageset/uninded experiment
2) After indexing to associate an indexed reflection with an indexed experiment (with unindexed reflections set to -1)
After indexing there is no way just using experiment ids/identifiers to keep track of which imageset unindexed reflections belong to. This is the role that imageset_ids currently perform. As such I don't think we can state that these are "legacy" until we have a valid alternative.

**Comment by graeme-winter** [comment]
Humbly suggest that if we followed up on https://github.com/dials/dials/issues/1029 the problem would go away, as the old experiment ID would point at the imported experiment, the new one to the recently indexed reflections, so `imageset_id` would be truly redundant (and everything would be more easily understood)

**Comment by rjgildea** [comment]
> Humbly suggest that if we followed up on #1029 the problem would go away, as the old experiment ID would point at the imported experiment, the new one to the recently indexed reflections, so `imageset_id` would be truly redundant (and everything would be more easily understood)

I still don't see how this would allow you to get "all reflections on the first imageset", which the existing `imageset_id` approach _does_.
