### ISSUE TITLE
Add a simple ray casting algorithm

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#111]

**Comment by graeme-winter** [comment]
See rt0 in duelling profiles. Most of the code already exists in dials though need to consider modelling detector physics.

**Comment by graeme-winter** [comment]
Elementary modelling of detector physics is now in there...

**Comment by dagewa** [comment]
Is it worth keeping this issue open?

**Comment by dagewa** [comment]
> Is it worth keeping this issue open?

**Comment by dagewa** [comment]
> > Is it worth keeping this issue open?
