### ISSUE TITLE
halting problem in dev.dials.generate_tutorial_text

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#112]
I currently cannot decide whether dev.dials.generate_tutorial_text terminates or not (Turing, 1937).
It used to in the past. Now however:

```
dials.import /scratch/jenkins_slave/workspace/dials_documentation/dials-dev20160330/build/xia2_regression/test_data/i04_bag_training/th_8_2_0*cbf
6.055s
dials.find_spots datablock.json nproc=4
945.231s
dials.index datablock.json strong.pickle
88.734s
dials.refine_bravais_settings experiments.json indexed.pickle
134.631s
dials.reindex indexed.pickle change_of_basis_op=a,b,c
11.677s
dials.refine bravais_setting_9.json reindexed_reflections.pickle
49.382s
dials.refine refined_experiments.json refined.pickle scan_varying=true
135.689s
dials.integrate refined_experiments.json refined.pickle nproc=4
```

**Comment by graeme-winter** [comment]
Please could you check the reliability / speed of the file system you are operating on i.e. 

time md5sum /scratch/jenkins_slave/workspace/dials_documentation/dials-dev20160330/build/xia2_regression/test_data/i04_bag_training/th_8_2_0*cbf

as this seems to be very slow. step 2 of spot finding took 60s with 4 cores on my machine.

**Comment by Anthchirp** [comment]
Confirmed that the code under test works fine. Will look at improving the test to avoid Jenkins timeouts.

**Comment by Anthchirp** [comment]
Command now produces continuous output, thus avoiding Jenkins timeouts.
