### ISSUE TITLE
dials.integrate should die early if the mosaicity is egregiously large

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#1123]
Prompted by some recent very bad data at Diamond Light Source, it would be useful if `dials.integrate` failed early in cases where the mosaicity is very large.  How large is a moot point but we could be very conservative by default, continuing in all but the very worst cases.

**Comment by dagewa** [comment]
Would it not be better for `dials.integrate` to accurately estimate memory requirements and fail only in cases where there is not enough?

**Comment by dagewa** [comment]
Maybe this is effectively addressed by #1221?

**Comment by benjaminhwilliams** [comment]
> Maybe this is effectively addressed by #1221?

The `dials.integrate` memory use problem is an open one, but I think you're right that this issue is effectively rendered obsolete by #1221.
