### ISSUE TITLE
dials.search_beam_position uses a single detector and beam model

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1126]
Even when there are multiple imagesets and these have different detectors and beams

**Comment by rjgildea** [comment]
Actually that isn't quite true, as in `get_origin_offset_score()` it does apply the offset to the detector for each imageset:
https://github.com/dials/dials/blob/d9d4eed6dbcd7d8ca0d615e9d9da2767f3127b6f/command_line/search_beam_position.py#L280-L282

The algorithm uses the beam from the first imageset to define a basis for the refinement:
https://github.com/dials/dials/blob/d9d4eed6dbcd7d8ca0d615e9d9da2767f3127b6f/command_line/search_beam_position.py#L114-L120

which I presume is why there is a check that the beam intersects with the detector for the first imageset.

I think there is however a bug in the application of the optimised detector origin here, as all experiments end up with the same detector model for output:
https://github.com/dials/dials/blob/d9d4eed6dbcd7d8ca0d615e9d9da2767f3127b6f/command_line/search_beam_position.py#L597-L599

This function should probably just return the origin offset, which can then be applied separately to the detector for each experiment.
