### ISSUE TITLE
Saturation value for EIGER

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#113]
To get the saturation value for EIGER, we should first look at
/entry/instrument/detector/detectorSpecific/countrate_correction_count_cutoff
and, if missing, fall back to
/entry/instrument/detector/detectorSpecific/detectorModule_000/countrate_correction_count_cutoff.

However, the current code looks at /entry/instrument/detector/detectorSpecific/countrate_correction,
which is not present at all! Thus, the code always goes to "detectorModule_000", which is not accurate.

In dxtbx/format/FormatHDFEigerNearlyNexus.py:
```
create_scalar(
  handle['entry/instrument/detector'],
  "saturation_value",
  "int32",
  handle['/entry/instrument/detector/detectorSpecific/countrate_correction'])
```
should be
```
create_scalar(
 handle['entry/instrument/detector'],
 "saturation_value",
 "int32",
 handle['/entry/instrument/detector/detectorSpecific/countrate_correction_count_cutoff'])
```

**Comment by jmp1985** [comment]
@biochem-fan I was told by Dectris to use the following fields:

Until "/entry/instrument/detector/saturation_value" exists (from FW version 1.7, soon to come), the saturation value should be derived from "/entry/instrument/detector/detectorSpecific/countrate_correction".
 
Files written with FW < 1.5 do unfortunately not contain this value, so dxtbx would have to fall back to /entry/instrument/detector/detectorSpecific/detectorModule_000/countrate_correction_count_cutoff after all in that case.

**Comment by jmp1985** [comment]
Fixed in dxtbx commit
