### ISSUE TITLE
why scale filtering feature is supported only in multi-dataset scaling mode?

### ISSUE THREAD

**Issue by splintersu** [dials/dials#1161]
I consider this feature as potentially very useful, but it seems that it's only supported in multi-dataset scaling mode, even after set filtering.deltacchalf.mode=image_group

maybe I miss something- but everything works fine after I commented out line 340-345 in algorithms/scaling/algorithm.py

**Comment by jbeilstenedmands** [comment]
Hi, I think this is mainly an accident, the scaling and filtering was originally only implemented for filtering by removing whole datasets. Good to know that it works in this way, I'll look at making this validation only trigger for filtering in dataset mode and adding some tests and then we can look to adding this to an upcoming point release. Thanks.
