### ISSUE TITLE
find_spot_server ~3x slower with d_min specified

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1170]
Test script: https://gist.github.com/ndevenish/f0f9e624173ee0933a158e8c7c7661bf
```
$ do_test_find_spots_server.py
Rate:  2.45/s
$ do_test_find_spots_server.py filter.d_min=5
Rate:  0.86/s
```
### Cause
The mask is recalculated for each image, because `find_spots_server` cannot assume any consecutive images have the same geometry. It appears to apply a `d_min` by generating a mask for every pixel. This happens via calculating the resolution for every pixel and filtering that, but also involves calculating the parallax correction for every pixel in order to get the "correct" resolution. Profiling results for this:
![image](https://user-images.githubusercontent.com/529963/75176929-12df7280-572d-11ea-8604-7a0431c6e77e.png)

### Potential solutions
Couple of immediate ideas come to mind:
- Applying resolution masks per reflection centroid rather than per pixel. This would probably be the fastest however we'd either need to change the way this rejection works in spotfinder, or accept divergence between the implementations. Or a flag, but that's messy. This would obviously slightly change spotfinding results.
- Be "smarter" about calculating mask; we don't need to do full geometry calculations for each pixel in order to know where to blit a circle; we could do the calculation and just fill the mask. Parallax slightly complicates this, but I'm not convinced that this _ever_ makes a difference for pass/fail and could be compensated for if essential; only running the test for pixels that we weren't sure about. Depending how paranoid we are, this could or could not change things.

Thoughts on approach here?

**Comment by graeme-winter** [comment]
Verified, thank you for reporting this

```
Assuming spotfinder.filter.d_min was intended.

Rate: 1.32s 0.76/s 1.32s
Grey-Area i04_bag_training :) $ dials.python p1170.py 

Rate: 0.44s 2.26/s 0.44s
```

(with some slight hacking of the gist script) - with Pilatus images. With Eiger 16M images the problem is _far_ worse:

```
Assuming spotfinder.filter.d_min was intended.

Rate: 3.66s 0.27/s 3.66s
Grey-Area i03-grid-1d :) $ dials.python p1170.py 

Rate: 0.99s 1.01/s 0.99s
```

N.B. this is full frame not ROI mode, but even so...

**Comment by graeme-winter** [comment]
Looking at the code I can see a bunch of solutions. It's not at all obvious which ones are appropriate - 

 - we could use a divide-and-conquer approach to determining the masked pixels e.g. using the fact that the panels are planar and the resolution boundary is a conic section
 - we could filter on the centroids as suggested
 - we could make a coarse (though still almost certainly fine) approximation by ignoring the per-pixel corrections
 - we could come up with a mathematical transformation using the fact that the masked region is a conic section to transform a close approximation to the allowed region into a quick to compute selection

I personally favour option 4, so will have a quick look...

**Comment by graeme-winter** [comment]
Reasoning: option 4 is the minimal change from existing behaviour so has limited impact if e.g. there are artefacts outside the allowed range which cause us problems.

**Comment by graeme-winter** [comment]
Whilst looking carefully at this I found 

```
            if self.params.d_max is not None:
                logger.info("Generating low resolution mask:")
                logger.info(" d_max = %f" % self.params.d_max)
                d_min = self.params.d_max
                d_max = max(d_min + 1, 1e9)
                mask_resolution(d_min, d_max)
```

and found myself more than a spot confused 🤔

**Comment by graeme-winter** [comment]
Working on this in cos2-resolution-mask branch

Already twice as fast (well 2s per frame from 4s per frame) with changes in Python not C++ code.

**Comment by graeme-winter** [comment]
@ndevenish would you mind me reopening this to keep a flag that there is work left to do with this?

**Comment by ndevenish** [comment]
I’d prefer a new ticket for the more specific problem TBH
