### ISSUE TITLE
move release builds to RHEL7

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1173]
RHEL6 is nearing product retirement [(Nov 2020)](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates).

I would suggest that we move our build infrastructure to RHEL7 for versions 3.0 builds onwards, and keep 2.2 branch builds on RHEL6 for the lifetime of the branch. This would mean that the master branch would move to RHEL7 in about a month or so.

Does anyone feel strongly about this either way?

**Comment by graeme-winter** [comment]
+1 from me

**Comment by Anthchirp** [comment]
This should resolve itself with the move to conda compilers post-3.0. Will therefore not spend effort on this before the release

**Comment by Anthchirp** [comment]
release builds moved to RHEL7 for 3.1 onwards (DIALS 2.2 stays on RHEL6 till EOL)
