### ISSUE TITLE
Python 2.7 deprecation timeline

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1175]
As we are all aware Python 2.7 is now well [past its use-by date](https://pythonclock.org/).
DIALS will need to continue supporting Python 2.7 for a while as we still rely on this for a number of reasons (DLS operations, CCP4 bundling, Phenix bundling, ...)

This ticket outlines my proposal how we can support this critical need without obstructing ongoing development effort.

# Executive summary

On March 15 we will start the release branch for DIALS 2.2. DIALS 2.2 will support both Python 2.7 and 3.6. [Like DIALS 1.14](https://github.com/dials/dials/wiki/Version-history), this will be a long-term-supported (LTS) release, which means we will provide support and builds, initially until the end of the year. This may be extended if there is ongoing need for supported builds.

Meanwhile we will reduce the Python 2.7 compatibility in the master branch in a phased manner over a period of 6 months. This is to avoid a scenario where massive changes are introduced that then make it difficult to backport code to the 2.2 release branch.

# Phase 1 -- 15th of March 2020
> DIALS 2.2 branch date.

We stop officially providing or linking to any 2.7 nightly builds

We aim to keep Python 2.7 compatibility in dials, dxtbx, and xia2 `master` branches and refrain from any large-scale refactoring to not artifically make maintaining the 2.2 LTS release difficult. **Python-3-only code is allowed in new files and where retaining Python 2 support is unreasonable or impossible** (multiprocessing case). Where this causes tests to fail we will set up a _"skip-this-test-on-python-2"_ fixture.

We will reduce the MacOS testing regime at Diamond to reduce the demand on our build machine.

#### Jenkins
* Disable MacOS 2.7 builds for xia2
* Disable MacOS 2.7 DIALS regression builds
#### Travis
* no changes

<table><tr><th>repository</th><th>python 3 allowed in...</th><th>Python 2 testing coverage</th></tr>
<tr><td>dxtbx</td><td>new files and where Py2 support is unreasonable or impossible</td><td>Everything except newly excluded tests</td></tr>
<tr><td>dials</td><td>new files and where Py2 support is unreasonable or impossible</td><td>Linux: Everything except excluded, MacOS: No regression tests</td></tr>
<tr><td>xia2</td><td>new files and where Py2 support is unreasonable or impossible</td><td>Linux: Everything except excluded, MacOS: No test coverage</td></tr>
</table>

# Phase 2A -- 15th of May 2020
> This is 2 months after the initial 2.2 release.
> The projected current release is approx. DIALS 2.2.4
> This is the approximate branch date for DIALS 3.0.
> Python 2.7.18 has been released.

This is an intermediate step where only xia2 is affected. DIALS and dxtbx `master` remain in Phase 1 for 6 more weeks.

We end all effort for Python 2.7 compatibility in xia2. Any large-scale refactoring, such as mass-removal of `future`/`six` statements, should take the need for backporting fixes into the 3.0 release branch into account.

With concurrent 2.2 and 3.0 release builds we will have increased demand on our build systems, so responses may be slower than usual.

#### Jenkins
* Disable all 2.7 builds for xia2
#### Travis
* Disable 2.7 flake8 checks for xia2
* Disable 2.7 syntax checks for xia2
* Disable all 2.7 builds for xia2

<table><tr><th>repository</th><th>python 3 allowed in...</th><th>Python 2 testing coverage</th></tr>
<tr><td>dxtbx</td><td>new files and where Py2 support is unreasonable or impossible</td><td>Everything except newly excluded tests</td></tr>
<tr><td>dials</td><td>new files and where Py2 support is unreasonable or impossible</td><td>Linux: Everything except excluded, MacOS: No regression tests</td></tr>
<tr><td>xia2</td><td>no restrictions, keeping 3.0 support in mind</td><td>no test coverage</td></tr>
</table>

# Phase 2B -- 30th of June 2020
> This is 3.5 months after the initial 2.2 release.
> The projected current releases are approx. DIALS 2.2.7 and DIALS 3.0.2

We still aim to keep Python 2.7 compatibility in DIALS and dxtbx `master` where possible. We aim to avoid large-scale refactoring, particularly in dxtbx. **Python-3-only code is allowed where it provides a demonstrable benefit over 2.7-compatible code.**

With concurrent 2.2 and 3.0 release builds we will have increased demand on our build systems. We now reduce the testing regime, in particular we end the long-running regression tests for DIALS.

#### Jenkins
* Disable MacOS 2.7 DIALS builds
* Disable all 2.7 DIALS regression builds
* Disable MacOS 2.7 dxtbx regression builds
#### Travis
* Disable 2.7 flake8 checks for dxtbx and DIALS
* Disable 2.7 regression/slow tests for DIALS

<table><tr><th>repository</th><th>python 3 allowed in...</th><th>Python 2 testing coverage</th></tr>
<tr><td>dxtbx</td><td>new files and where there is demonstrable benefit</td><td>Linux: Everything except excluded, MacOS: No regression tests</td></tr>
<tr><td>dials</td><td>new files and where there is demonstrable benefit</td><td>Linux: No regression tests, MacOS: No test coverage</td></tr>
<tr><td>xia2</td><td>no restrictions</td><td>no test coverage</td></tr>
</table>

# Phase 3 -- 15th of July 2020
> This is 4 months after the initial 2.2 release.
> The projected current releases are approx. DIALS 2.2.8 and 3.0.3

We still aim to keep Python 2.7 compatibility in dxtbx `master`. **Python-3-only code is allowed where it would take additional effort to maintain Python 2.7-compatibility.**

We stop all 2.7 testing on DIALS and remove all test fixtures. However we bear Python 2.7 compatibility in mind, and patches to maintain Python 2.7 compatibility are welcome.

#### Jenkins
* Disable all 2.7 DIALS builds
* Disable all 2.7 dxtbx regression builds
* Disable MacOS 2.7 dxtbx builds
#### Travis
* Disable 2.7 syntax checks for DIALS
* Disable all 2.7 builds for DIALS
* Disable 2.7 regression/slow tests for dxtbx

<table><tr><th>repository</th><th>python 3 allowed in...</th><th>Python 2 testing coverage</th></tr>
<tr><td>dxtbx</td><td>where maintaining compatibility takes additional effort</td><td>Linux: No regression tests, MacOS: No test coverage</td></tr>
<tr><td>dials</td><td>where maintaining compatibility takes additional effort</td><td>no test coverage</td></tr>
<tr><td>xia2</td><td>no restrictions</td><td>no test coverage</td></tr>
</table>

# Phase 4 -- 15th of September 2020
> This is 6 months after the initial 2.2 release
> The projected current releases are approx. DIALS 2.2.13 and 3.1.2

**We end all Python 2.7 compatibility effort.**

#### Jenkins
* Disable all 2.7 dxtbx builds
#### Travis
* Disable 2.7 syntax checks for dxtbx
* Disable all 2.7 builds for dxtbx

<table><tr><th>repository</th><th>python 3 allowed in...</th><th>Python 2 testing coverage</th></tr>
<tr><td>dxtbx</td><td>no restrictions</td><td>no test coverage</td></tr>
<tr><td>dials</td><td>no restrictions</td><td>no test coverage</td></tr>
<tr><td>xia2</td><td>no restrictions</td><td>no test coverage</td></tr>
</table>

**Comment by graeme-winter** [comment]
I have self-assigned this to take forward to PIs

**Comment by Anthchirp** [comment]
As we are now in Phase 1 I've disabled Jenkins MacOS builds for xia2 and regression builds for DIALS as described. I have removed links to Python 2 nightly builds from https://dials.github.io/installation.html#development-builds

**Comment by Anthchirp** [comment]
I have amended the timeline above following a request to delay Phase 2 until the end of June as to facilitate XFEL work.

Since this is independent of xia2 I have split up Phase 2 into 2A (remaining at original date but for xia2 only) and 2B (end of June, everything else).

Further, I've changed the wording to make clear that 'large scale refactoring' includes the removal of `six`/`future` statements. It also includes addition of type annotation, f-strings, and all other Python 3.6+ goodness.

**Comment by Anthchirp** [comment]
Having just taken an inventory of all our Jenkins build configurations I would just like to make a note that we will also reduce the coverage of testing _at Diamond_ on `cctbx_project` in line with the timeline above:

<table>
<tr><th></th><th colspan="3">cctbx_python Python 2 test coverage at Diamond</th></tr>
<tr><th>from ... onwards</th><th>Linux</th><th>MacOS</th></tr>
<tr><td>Phase 1<br/>(15th March)</td><td>libtbx, scitbx, cctbx, iotbx, rstbx with phenix_regression provided</td><td>libtbx, scitbx, cctbx, iotbx, rstbx</td></tr>
<tr><td>Phase 2a<br/>(15th May)</td><td>libtbx, scitbx, cctbx, iotbx, rstbx with phenix_regression provided</td><td>libtbx, scitbx, cctbx, iotbx, rstbx</td></tr>
<tr><td>Phase 2b<br/>(30th June)</td><td>libtbx, scitbx, cctbx, iotbx, rstbx with phenix_regression provided</td><td>libtbx, scitbx, cctbx, iotbx, rstbx</td></tr>
<tr><td>Phase 3<br/>(15th July)</td><td>libtbx, scitbx, cctbx, iotbx, rstbx</td><td>not tested at Diamond</td></tr>
<tr><td>Phase 4<br/>(15th September)</td><td>not tested at Diamond</td><td>not tested at Diamond</td></tr>
</table>

Python 3 test coverage of `cctbx_project` at Diamond will stay at the current level, which is `libtbx`, `scitbx`, `cctbx`, `iotbx`, `rstbx` without additional repositories present.

Obviously nothing changes in terms of code committed to `cctbx_project` as that is a separate project with its own rules. However we may not proactively identify cases where Python 2 incompatible code is committed accidentally.

**Comment by Anthchirp** [comment]
We are now in Phase 2A, and I have disabled xia2 Jenkins builds accordingly. Whereas xia2 is now free to move on, the policy for dxtbx/dials remains at _"Python 3 allowed in new files and where Python 2 support is unreasonable or impossible"_ until the end of June.

**Comment by dagewa** [comment]
This proposal from the DIALS East group was agreed by representatives of DIALS West. It is only fair that this is made public here

>We will not actively support Python 2.7 beyond the DIALS 2.2 long term support branch already discussed however we will also not remove six / futures / from future import lines for foreseeable future on the master branch. New code will be Python 3 only. There will be no large scale refactoring on master until such time as it becomes clear the existing approach is unsustainable.
>
>We also offer to help to get Python 3 porting done, to get this done before Python 2.7 dependencies start to vanish - we concluded that these external forces would ultimately dominate the timescales for the move to Python 3 only.

**Comment by Anthchirp** [comment]
We are now in Phase 2B, and I have disabled the DIALS MacOS Python 2 Jenkins builds and the MacOS dxtbx regression builds accordingly. Travis no longer runs Python 2.7 flake8 checks and regression tests.

The policy for dxtbx/dials is now _"Python-3-only code is allowed where it provides a demonstrable benefit over 2.7-compatible code."_ until mid-July.

**Comment by Anthchirp** [comment]
We are now in Phase 3, and I have disabled the relevant Jenkins tests accordingly. Travis no longer runs Python 2.7 syntax checks and tests on DIALS. Test fixtures will be removed shortly.
We continue to run some basic testing on Jenkins for dxtbx with Python 2.7/Linux.

The policy for dxtbx/dials is now "**Python-3-only code is allowed where it would take additional effort to maintain Python 2.7-compatibility**". Although we no longer test on Python 2.7 any patches to retain 2.7-compatibility are welcome until mid-September.

**Comment by Anthchirp** [comment]
I have disabled Python 2.7 syntax checking on cctbx/dxtbx on Jenkins due to https://github.com/cctbx/cctbx_project/commit/9343e8aab926c2c06ff91d0a036c61cd17955d89.

**Comment by Anthchirp** [comment]
The 15th of September has finally arrived. It looks like the timeline was spot on, as some of the build job stages have started coming up with dependency package errors yesterday.

I have disabled all Jenkins Python 2 testing for cctbx and dxtbx, disabled the dxtbx travis testing, and removed associated code crutches. We can now move on.
