### ISSUE TITLE
Add Python 2.x deprecation warning post 2.2 branch

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1179]
After DIALS 2.2 is branched should put a deprecation warning in the top level `__init__.py` in DIALS which checks the system version and emits a deprecation warning if the major Python version is 2.

**Comment by Anthchirp** [comment]
Very good idea. We should then make it a warning for xia2 in [Phase 2](https://github.com/dials/dials/issues/1175), and for all other packages in [Phase 4](https://github.com/dials/dials/issues/1175).
