### ISSUE TITLE
sigma_m estimates depend on image width

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#119]
On the attached plot each point corresponds to a dataset, the three populations are three different crystals. For each dataset you see the frame width on the x-axis, and the sigma_m estimate according to dials.create_profile_model on the y-axis.

The light blue set was estimated from the same data, using
- the original 0.02 deg oscillation dataset
- a 0.04 deg osc dataset created by adding two images
- a 0.06 deg osc dataset created by adding three images
  (..)
- a 1.0 deg osc dataset created by adding 50 images

The datasets of the other two crystals are independent

![sigma_m](https://cloud.githubusercontent.com/assets/2102431/14701358/eda42bf2-079c-11e6-8fd3-6947a3ed3818.png)

How can we make the sigma_m estimate more stable?

**Comment by Anthchirp** [comment]
Jeppe Christensen recommended having a look at this paper http://journals.iucr.org/d/issues/2000/08/00/en0024/en0024.pdf

**Comment by graeme-winter** [comment]
If you could digest this & report a summary that would be exceedingly
welcome :)

**Comment by graeme-winter** [comment]
@jmp1985 this is of interest to our conversation just now ...

**Comment by jmp1985** [comment]
Plan is as follows:
1. Implement mosaicity estimate with maximum likelihood approach taking into account intensity of spots on image
2. Implement forward modelling onto detector with detector physics
3. Add additional parameters

**Comment by Anthchirp** [comment]
Orangey points are Amber's datasets. Blueish points are Mark&Markus.
Triangles and Xs Fructose,
Circles probably L-Cysteine, presumably from /dls/i19-1/data/2016/cm14476-2/140416/L-cysteine/screen_01* or _02*

**Comment by jmp1985** [comment]
Hi Markus,

Thanks for looking at this; however, I can't find the 0.02def oscillation dataset in /dls/i19-1/data/2016/cm14476-2/140416/L-cysteine/screen_01* or _02*. They appear to be 0.1 deg oscillations.

Thanks,

James

________________________________

**Comment by Anthchirp** [comment]
Judging from a google sheet I just rediscovered, within /dls/i19-1/data/2016/
Orange: mt13639-1/070 to 075.
Dark blue: cm14476-1/processed/20160310_collectionTest/ 12_* to 21_*
Light blue: one of mt13639-1/092alt16, probably run 1 or 4

**Comment by jmp1985** [comment]
Hi Markus,

That's great - I've found the light blue dataset.

Thanks,

James
________________________________

**Comment by Anthchirp** [comment]
Hi James, which one was it?

**Comment by Anthchirp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate whether James's improved mosaic spread model gives better results e.g. in i19.screen; also what effect this has on regular processing](https://trello.com/c/RT7xZgpc/10-investigate-whether-james-s-improved-mosaic-spread-model-gives-better-results-e-g-in-i19-screen-also-what-effect-this-has-on-reg)

**Comment by jmp1985** [comment]
Hi Markus,

I think it was this one (maybe):

/ramdisk/2016/mt13639-1/092alt16/092alt16_01_00001.cbf

James

________________________________

**Comment by graeme-winter** [comment]
Testing with manual DIALS script:

```
run=`basename $PWD`
data=mosaic/data/$run

dials.import $data/*cbf
dials.find_spots datablock.json nproc=20
dials.index datablock.json strong.pickle space_group=P212121
dials.refine scan_varying=true experiments.json indexed.pickle
dials.create_profile_model refined*
dials.create_profile_model refined* sigma_m_algorithm=extended
```

OK, default algorithm:

```
12_width_0-05s_0-05d_22-7att/run.sh.o66962:Sigma M: 0.049507
13_width_0-1s_0-1d_22-7att/run.sh.o66963:Sigma M: 0.064864
14_width_0-2s_0-2d_22-7att/run.sh.o66964:Sigma M: 0.087834
15_width_0-4s_0-4d_22-7att/run.sh.o66965:Sigma M: 0.113552
16_width_1s_1d_22-7att/run.sh.o66966:Sigma M: 0.136553
```

sigma M extended:

```
12_width_0-05s_0-05d_22-7att/run2.sh.o66967:Sigma M: 0.014442
13_width_0-1s_0-1d_22-7att/run2.sh.o66968:Sigma M: 0.015767
14_width_0-2s_0-2d_22-7att/run2.sh.o66969:Sigma M: 0.016803
15_width_0-4s_0-4d_22-7att/run2.sh.o66970:Sigma M: 0.018117
16_width_1s_1d_22-7att/run2.sh.o66971:Sigma M: 0.021546
```

Looks *much* more stable - though @Anthchirp  @jmp1985  we need to make sure that this is correctly interpreted as a traditional mosaic spread. 

Three actions 
 - we should make this the default in i19.screen
 - we should use IHR time to verify this
 - we should actually look at the integration shoeboxes derived from this estimate to make sure the results are actually right

**Comment by graeme-winter** [comment]
Looking at the shoeboxes now with #351 information

**Comment by graeme-winter** [comment]
The reference profiles look fairly uniform - whatever this is doing is consistent with what I would expect across the range 0.05, 0.1, 0.2, 0.4, 1.0 degrees:

```
[gw56@ws133 reference]$ for f in `find . -name 'reference_profiles.pickle'`; do echo $f; dev.xia2.check_mosaic $f; done | sed 's$/DEFAULT/SAD/SWEEP1/integrate/reference_profiles.pickle$$'
./14_width_0-2s_0-2d_22-7att
  1   7  24  54  85 100  85  54  24   7   1 
./12_width_0-05s_0-05d_22-7att
  1   7  23  51  84 100  84  51  22   6   1 
./15_width_0-4s_0-4d_22-7att
  1   8  25  55  86 100  86  54  25   8   1 
./16_width_1s_1d_22-7att
  1   8  26  55  86 100  86  55  25   8   1 
./13_width_0-1s_0-1d_22-7att
  1   7  24  53  85 100  86  53  24   7   1 
```

Therefore happy that this is now well behaved (though the profile doesn't appear to actually converge to 0... #discuss)
