### ISSUE TITLE
Weights for merging partial observations - not convinced correct

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1196]
Looking at https://github.com/dials/dials/blob/afd1fd866f1d0035903be94017f672391357141b/util/filter_reflections.py#L812 following from user report of a bug

Have a reflection where the intensity is 0 in two parts but the variance is != 0

However the total weight is working out at 0 so get / 0 error

Am not convinced this is correct 🙂

**Comment by graeme-winter** [comment]
Looked over some very old code which I implemented about a million years ago for this. It looks to be the same. How has this never happened before? 🤔

**Comment by jbeilstenedmands** [comment]
Is this now happening because I'm using it at the start of scaling? Before it was only in export, so these kind of reflections are probably filtered earlier?

**Comment by graeme-winter** [comment]
Checking

I think there are filtering steps missing from this pipeline.
