### ISSUE TITLE
Average cell for exported MTZ

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1199]
I got caught out by this in `dials.export` for multi-lattice cases
```
  WARN: Experiment crystals differ. Using first experiment crystal for file-level data.
```
I think it would be more appropriate to come up with an average cell for the MTZ rather than the first one. Maybe look at what `xia2.multiplex` does here.

**Comment by dagewa** [comment]
Just remembered this relates to #670

**Comment by rjgildea** [comment]
This should have been fixed by https://github.com/dials/dials/pull/1214
