### ISSUE TITLE
dials.reciprocal_lattice_viewer X window error

### ISSUE THREAD

**Issue by aaronfinke** [dials/dials#1233]
Trying to open dials.reciprocal_lattice_viewer in scientific linux 7 and keep getting this error:

[dials]$ dials.reciprocal_lattice_viewer datablock.json strong.pickle 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = datablock.json
  reflections = strong.pickle
}

/nfs/chess/sw/macchess/dials/dials-v2-2-1/modules/cctbx_project/wxtbx/segmentedctrl.py:46: wxPyDeprecationWarning: Using deprecated class. Use Control instead.
  name=name)
The program 'reciprocal_lattice_viewer.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 723 error_code 144 request_code 143 minor_code 4)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Version:
DIALS 2.2.1-g80a7d01a4-release
Python 3.6.10

**Comment by graeme-winter** [comment]
@aaronfinke do other openGL programs work correctly? E.g. coot, `glxgears`, `glxinfo`? Our main Linux OS is RHEL7 on x86-64 which should be very similar to your environment, so I am surprised by this.

**Comment by aaronfinke** [comment]
Yes, coot, `glxgears`, and `glxinfo` all load and run without issue.

**Comment by rjgildea** [comment]
I can reproduce this here with (e.g.) `module load dials/latest` after ssh-ing into my RHEL7 workstation:
```
$ dials.reciprocal_lattice_viewer /dls/science/groups/scisoft/DIALS/dials_data/centroid_test_data/{imported_experiments.json,strong.pickle}
```
When I exit the RLV I get the following error in the terminal:
```
The program 'reciprocal_lattice_viewer.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadCurrentWindow'.
  (Details: serial 15336 error_code 159 request_code 148 minor_code 103)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Actual operation of the program itself doesn't appear to be affected as far as I can tell.

**Comment by dagewa** [comment]
This is just a problem with GL over SSH, right?
