### ISSUE TITLE
add gemmi to dependencies?

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1266]
The Gemmi library (https://github.com/project-gemmi/gemmi) is developed by CCP4 and Global Phasing, and offers among other things a faster CIF parser and MTZ read/write capability in both C++ and Python bindings.

The package is [well-documented](https://gemmi.readthedocs.io/en/latest/), licensed under MPLv2 and LGPL. It is an active project with [proper releases](https://pypi.org/project/gemmi/#history) and is packaged on [conda-forge](https://github.com/conda-forge/gemmi-feedstock).

**Comment by dagewa** [comment]
I'm keen. I've just started using gemmi and have found it very easy to get into

**Comment by dagewa** [comment]
Another reason to use gemmi is that it handles unmerged mmcif, which will be useful when preparing files for deposition in future. #281 is a moving target and it would be useful to offload the heavy lifting.

**Comment by dagewa** [comment]
"Gemmi handles mmcif so we don't have to" is a strong argument to me.
https://project-gemmi.github.io/wasm/to_mmcif/

**Comment by graeme-winter** [comment]
I am not at all hostile to this. Personally I am not bothered about mmCIF, but I do wonder what it would do regarding regular CIF? Better MTZ file wrangling could be useful 🙂

**Comment by dagewa** [comment]
I have used it to read regular cif, with great success (it is very fast). The issue with mmCIF is that it is required for deposition and eventually will include unmerged data, including the mapping between multiple crystal data and the scaled/merged dataset that only the scaling program really knows about. It's true that "eventually" might be still a long way off, but I can see a possible need for DIALS tool to aid deposition, by writing the reflections part into the mmCIF from refinement.

**Comment by Anthchirp** [comment]
Sort of blocked by https://github.com/project-gemmi/gemmi/issues/42 and https://github.com/conda-forge/gemmi-feedstock/issues/20
