### ISSUE TITLE
Reflection table flags has no "scaled"

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1268]
`flex.reflection_table.flags` has indexed, integrated, many other things but not scaled. We can say that it was not scaled with `user_excluded_in_scaling` or `excluded_for_scaling` but that is not super helpful. 

Proposed solution:
 - define `flags.scaled`
 - use it 😉

**Comment by rjgildea** [comment]
I _assume_ that this is just the complement of `flex.reflection_table.flags.bad_for_scaling`, which is itself the combination of `UserExcludedInScaling | OutlierInScaling | ExcludedForScaling`:
https://github.com/dials/dials/blob/327a64b4f232dbd01fdb6616de6fa325a84e1a0a/array_family/reflection_table.h#L149

E.g.:
https://github.com/dials/dials/blob/4bdd392671c09e9d20794deaf90433c669e5f70b/util/filter_reflections.py#L643-L648

https://github.com/dials/dials/blob/505749539cce136fef4b0acb4ac1a3e9daa54c05/algorithms/scaling/algorithm.py#L318

**Comment by graeme-winter** [comment]
Does feel a bit ... cumbersome though right? ~which reflections are good~ these reflections are not bad for this reason and not bad for that reason too.

**Comment by dagewa** [comment]
What does it mean for a reflection to not be `scaled`? Every reflection output has a scaled intensity given by application of the scaling model. So a reflection is scaled if it exists in scaled.refl, right?

**Comment by graeme-winter** [comment]
```
from dials.array_family import flex
import sys

data = flex.reflection_table.from_file(sys.argv[1])

flags = data.flags.names

for f in sorted(flags):
    print(f"{f:40s} -> {data.get_flags(flags[f]).count(True)}")
```

Enumerate all possible flags, count how many reflections in a table are flagged, example output:

```
background_includes_bad_pixels           -> 9794
bad_for_refinement                       -> 0
bad_for_scaling                          -> 0
bad_reference                            -> 2762
bad_shoebox                              -> 0
bad_spot                                 -> 0
centroid_outlier                         -> 2463
dont_integrate                           -> 354
excluded_for_refinement                  -> 292
excluded_for_scaling                     -> 10262
failed_during_background_modelling       -> 23
failed_during_profile_fitting            -> 6577
failed_during_summation                  -> 5560
foreground_includes_bad_pixels           -> 5560
in_powder_ring                           -> 0
includes_bad_pixels                      -> 5382
indexed                                  -> 10526
integrated                               -> 27457
integrated_prf                           -> 27457
integrated_sum                           -> 28474
observed                                 -> 0
outlier_in_scaling                       -> 57
overlapped_bg                            -> 0
overlapped_fg                            -> 0
overloaded                               -> 0
predicted                                -> 36834
reference_spot                           -> 8055
strong                                   -> 10817
used_in_modelling                        -> 0
used_in_refinement                       -> 8061
user_excluded_in_scaling                 -> 4664
```

So none are "bad_for_scaling" as suggested by @rjgildea - some were excluded in scaling, 57 were identified as outliers in scaling (but evidently kept) so I think we do have a question to ask here. 

I.e. if I want to keep only the good scaled reflections getting them on a "scaled" flag would be really handy 😉

**Comment by rjgildea** [comment]
I think you have to do `data.get_flags(data.flags.bad_for_scaling, all=False).count(True)` as in the linked example usage above.

The `all` parameter to `flex.reflection_table.get_flags` isn't at all obvious to me, nor well-documented, as far as I can tell:
https://github.com/dials/dials/blob/5d87505dc31f6c5845bd18892bf9e2a186ea265e/array_family/boost_python/flex_reflection_table.cc#L170-L188

**Comment by jbeilstenedmands** [comment]
I've been having a think about the issue of flags for scaling and persistence of certain flags (relevant to #1275 also).

I propose this is what the behaviour _should_ be:
- have a .scaled flag. This is set at the end of a scaling process for all reflections which are 'good' from a scaling perspective (not outliers, excluded etc), and is reset at the start of each scaling job. For use by other programs to know which are the good scaled reflections.
- applied d_min, d_max cutoffs should persist from one scaling job to the next, unless a new limit is explicitly stated. This could be achieved by introducing a new flag, something like valid_resolution or in_resolution_range.
- similarly, when the image range is changed by excluding/including images, this should persist from one scaling job to the next, unless explicitly overwritten. This kind of behaviour is currently somewhat implemented by the valid_image_ranges property of a scan object, but this could be neater if set via a reflection table flag, perhaps in_valid_image_range?
- scaling outliers keep a separate flag, outlier_in_scaling, which persists between jobs until updated in a round of outlier rejection within scaling i.e. outliers are respected at the start of subsequent scaling until reevaluation.
- everything else that can be user controlled that selects a subset of the data (which I expect is rarely changed), which is currently partiality_cutoff, min_isigi, choice of prf/sum/combine intensities, share a flag such as excluded_for_scaling, which does not persist between scaling jobs. i.e. defaults back to the value in scaling params.

Discussion welcome.
