### ISSUE TITLE
Q: matrices B and UB

### ISSUE THREAD

**Issue by wojdyr** [dials/dials#1273]
Hi,
I'm working on depositing unmerged data in mmCIF format, trying to add as much information as possible using the current PDBx/mmCIF spec. (I know a new extension for this has been discussed since 3 years ago, but I'm trying to use what is available now).

mmCIF spec includes [orientation matrix UB](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v5_next.dic/Categories/diffrn_orient_matrix.html), which is not used currently in any PDB entry, but supposedly it could be used. I'm not familiar with the data processing and the symbols used, so I've been googling to find out what is what.
Matrix U is given in the MTZ batch headers, so I only need to calculate B to get UB.

In [Diffraction-geometry refinement in the DIALS framework][1] the reciprocal-space orthogonalization matrix B has reference [Busing & Levy, 1967][2], where I find B defined in (3). But that definition has zeros below the diagonal. An example of dials-report that I found:
https://dials.github.io/_downloads/dials-report.html
has 0.01 in the bottom left corner. Are these B matrices defined differently?

[1]: https://journals.iucr.org/d/issues/2016/04/00/gm5043/
[2]: https://www.psi.ch/sites/default/files/import/sinq/zebra/PracticalsEN/1967-Busing-Levy-3-4-circle-Acta22.pdf

**Comment by dagewa** [comment]
Hi Marcin,

The DIALS convention follows the PDB. Please see here for details: https://dials.github.io/documentation/conventions.html

**Comment by wojdyr** [comment]
Thanks, that's very helpful.

Is the UB matrix the same regardless of the convention used for B?

**Comment by dagewa** [comment]
The UB matrix depends on the definition of the laboratory frame, but it is free of the convention used for B. The U rotation matrix "corrects" for the choice of B

**Comment by wojdyr** [comment]
Do you know which B convention is appropriate if U is taken from the MTZ batch header (from [umat](http://www.ccp4.ac.uk/html/C_library/structbathead.html))?

**Comment by rjgildea** [comment]
Apparently we apply the goniometer fixed rotation matrix, F, to the DIALS U matrix, and then convert it into the MOSFLM convention before adding to this to the MTZ batch header:

https://github.com/dials/dials/blob/878feb23d7423655730206c6dac97a691d3c9bdd/util/export_mtz.py#L183-L201

https://github.com/dials/dials/blob/fbddfedbec235838c1120b3662e51ecc2a403d55/util/export_mtz_helpers.h#L181-L202

**Comment by dagewa** [comment]
It is quite possible that different programs are inconsistent here. However, I imagine the intention would have been to use MOSFLM's definition of the B matrix. I _think_ that corresponds to Busing & Levy but my notes on this are in a folder at the office...

**Comment by dagewa** [comment]
Good, so DIALS is adhering to the MOSFLM convention on output, which is what I believe the MTZ format expects

**Comment by wojdyr** [comment]
Thanks a lot! I added calculation of UB in the conversion of unmerged mtz to mmCIF.
If there is software that reads unmerged MTZ file and outputs (among other things) the UB matrix, let me know, I'd check if I calculated it correctly.

**Comment by dagewa** [comment]
Hi Marcin,
```bash
mtzdump hklin integrated.mtz <<+
BATCH
+
```
or
```
iotbx.mtz.dump -b integrated.mtz
```
will both give the orientation (**U**) part of the matrix for each image. The **B** matrix would have to be reconstructed from the cell.

We would like to have such a script to do this within the DIALS toolkit, but it hasn't been written yet. https://github.com/dials/dials/issues/1095
