### ISSUE TITLE
dials.reciprocal_lattice_viewer: does not show different sweep colours for integrated data

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1283]
Probably this goes "something something imageset id"

Indexed data:

![Screenshot 2020-06-03 at 09 49 05](https://user-images.githubusercontent.com/1241716/83616338-9eb03880-a57f-11ea-83ed-a2818b43a112.png)

Integrated data:

![Screenshot 2020-06-03 at 09 49 28](https://user-images.githubusercontent.com/1241716/83616354-a40d8300-a57f-11ea-9d22-575f18fd4d25.png)

This used to work...

**Comment by benjaminhwilliams** [comment]
We seem to have several little snags related to `imageset_id` versus experiment `id`.  There's also https://github.com/dials/dials/issues/1093 affecting combined experiments.  Is this issue a manifestation of that, or is it a separate issue with the RLV?  What was your workflow to arrive at those integrated data?  Did you combine individual experiments at any stage?

**Comment by graeme-winter** [comment]
@benjaminhwilliams 

```
dials.import ../data/PdTEET-another-monster_0?_????.cbf.gz
dials.find_spots imported.expt nproc=8
dials.index imported.expt strong.refl 
dials.refine indexed.*
dials.integrate refined* nproc=8
dials.scale integrated.*
dials.symmetry scaled*
dials.scale symmetrized.*
dials.export scaled.*
dials.reciprocal_lattice_viewer integrated.*
dials.reciprocal_lattice_viewer indexed.*
```

was my workflow - I combined nothing at any stage, very linear 🙂

**Comment by graeme-winter** [comment]
Turns out was a one liner https://github.com/dials/dials/pull/1284
