### ISSUE TITLE
Segmentation fault in dials.create_profile_model

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#1286]
I'm seeing a segmentation fault when running
`$ dials.create_profile_model indexed.{expt,refl}`
using the input files in this archive:  [indexed.tar.gz](https://github.com/dials/dials/files/4725198/indexed.tar.gz)

The problem is in the call to the `experiment_identifiers` method of the generated reflection table at https://github.com/dials/dials/blob/7b498f074f4c23303944cd15431c821659ea1322/array_family/flex_ext.py#L133
I haven't got further than that in figuring it out.  Not sure if it's related to the move to UID strings for experiment IDs.  It doesn't happen on other data that I've tried, so I imagine there's something specifically weird about running on these data.

**Comment by benjaminhwilliams** [comment]
The data are created by `screen19` from the `x4wide` regression test data (see https://github.com/dials/data/blob/master/dials_data/definitions/x4wide.yml).  If you're investigating this, you will want to update the image paths in the experiment list file to point to your own copy.

**Comment by benjaminhwilliams** [comment]
I convinced myself this was a PEBKAC and that I had somehow screwed up both my development builds, but after carefully rebuilding them, it truly looks to be an issue.  The latest release, 3.0.0, is unaffected.

**Comment by Anthchirp** [comment]
Do you get a stacktrace output from the segfault?

**Comment by benjaminhwilliams** [comment]
This is the entire output:
```
$ dials.create_profile_model indexed.*
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Processing reference reflections
 read 6928 strong spots
 removing 828 unindexed reflections
 removing 679 reflections marked as centroid outliers
 using 5421 indexed reflections
 found 1507 junk reflections
 masked neighbouring pixels in 326 shoeboxes

================================================================================

Predicting reflections

Prediction type: scan static prediction
Predicted 35412 reflections
Fatal Python error: Segmentation fault

Current thread 0x00007efc50b4c740 (most recent call first):
  File "/home/ekm22040/DIALS/modules/dials/array_family/flex_ext.py", line 133 in from_predictions_multi
  File "/home/ekm22040/DIALS/build/../modules/dials/command_line/create_profile_model.py", line 99 in run
  File "/home/ekm22040/DIALS/build/../modules/dials/command_line/create_profile_model.py", line 224 in <module>
Segmentation fault (core dumped)
```

**Comment by benjaminhwilliams** [comment]
But I chased it a bit further than that, until the call to C++ code (see above).  I probably need to refresh my memory on debugging Boost C++.  I haven't gone deeper than the pure Python yet.

**Comment by Anthchirp** [comment]
ah okay. I wasn't sure how much info the faulthandler stuff we introduced gives you.

**Comment by phyy-nx** [comment]
Hi, maybe this help.  I'm debugging a segfault in psana1 py3 now.  Here's
the trick I am using:

   - ulimit -c unlimited
   - # run program that segfaults, creates a core file
   - gdb core.####
   - sharedlibrary
   - bt

I get a backtrace from that.  I don't have the line number now but
recompiling with debug symbols should help.

-Aaron

**Comment by benjaminhwilliams** [comment]
Hmm... it looks like I may have accidentally been using an old `bootstrap.py`.  I can no-longer reproduce this with an up to date version.
