### ISSUE TITLE
dials.scale should use reflections that have been prf or sum integrated

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1293]
As far as I can tell, dials.scale only uses reflections that have been successfully both prf and sum integrated:
https://github.com/dials/dials/blob/06a5073e3d07a023b360250e33fde3264079a805/util/filter_reflections.py#L610-L618

It should probably also use reflections where either prf or sum integration succeeded.

See https://github.com/dials/dials/issues/1291#issuecomment-639644748

**Comment by biochem-fan** [comment]
Or even "partial" reflections too. A high fraction of reflections are partials in small-wedge multi-crystal datasets.

**Comment by rjgildea** [comment]
@biochem-fan it does use partial reflections above a cutoff of 0.4 by default, but you can modify this with the `cut_data. partiality_cutoff` parameter:
https://github.com/dials/dials/blob/505749539cce136fef4b0acb4ac1a3e9daa54c05/algorithms/scaling/scaling_options.py#L112-L116
dials.merge and dials.export do have higher default thresholds of 0.99, which is potentially confusing (see #1246):
https://github.com/dials/dials/blob/aeb5fcf457abd61f17730d4d6cb8fda9a0376b55/command_line/merge.py#L48
https://github.com/dials/dials/blob/a71b9581c309f7b63e46fd206db43acea8202dea/command_line/export.py#L97

**Comment by biochem-fan** [comment]
I see. Thanks for pointing out the different defaults.

**Comment by graeme-winter** [comment]
Can work out the relative weights for those where both are measured, and apply this with the filter on those which are only prf or sum integrated. Personally I feel that this is what the user would expect, it is what I would expect. Can probably get the estimate of `I` from the input data with a handful of flex selections?

**Comment by dagewa** [comment]
I'm not sure exactly what your comment means, but it seems to me there is no reason not to apply a scaling model to reflections that have only one of {I, IPR}, even if that model is determined only from reflections that have both.

**Comment by graeme-winter** [comment]
@dagewa yeh, I'm in the 6th zoom meeting of the day so I think my intelligence is suffering, sorry for not being coherent. 

There are two things in play here - 
 - getting I_int as weighted average of I_pr and I_sum with weight a function of I
 - getting and applying a scale factor 

I was commenting on the former, which assumes you have I_pr and I_sum. If you are missing one then the weight would be set to 0 for that and 1 for the other, rather than the computed weight. I appreciate this could have been clearer 😉

**Comment by dagewa** [comment]
Got it :-)
