### ISSUE TITLE
Profile fitting only succeeds if the bbox is entirely within the panel

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1294]
This is highly suboptimal, especially for multi-panel detectors such as the DLS I23 detector, where this can result in very few reflections actually being integrated (see https://github.com/dials/dials/issues/1291#issuecomment-639644748).

A check is made before attempting profile-fitting that the bbox is entirely within the panel:
https://github.com/dials/dials/blob/06a5073e3d07a023b360250e33fde3264079a805/algorithms/profile_model/gaussian_rs/modeller.h#L636-L657

This appears to be necessary because the whole of the shoebox is transformed into Kabsch space:
https://github.com/dials/dials/blob/06a5073e3d07a023b360250e33fde3264079a805/algorithms/profile_model/gaussian_rs/transform/transform.h#L241-L278

**Comment by biochem-fan** [comment]
See also #473.
