### ISSUE TITLE
Confusing hover labels in scaling.html plots (and others)

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1304]
e.g. when hovering over the plot the hover text doesn't match the X-axis.
(Thanks for reporting by John Beale on dials-support) 

<img width="594" alt="Screen Shot 2020-06-14 at 22 19 06" src="https://user-images.githubusercontent.com/529963/84651762-622af800-af02-11ea-897c-081272d74ee8.png">

I've seen this before, but don't know if is an inherent limitation of plotly or something we can fix? Presumably we could pre-scale the x-data instead of relabelling the axis?

**Comment by rjgildea** [comment]
I spent some time looking at this before and couldn't figure out how to override the hover labels in the same way that we override the xaxis tickvals. I'm not sure what you mean by "pre-scaling the x-data", but we need to plot the data in terms of 1/d**2 in order for the plot to look "correct", but we need the labels to be in terms of d (Å) for something easily understandable by the user.

https://github.com/dials/dials/blob/df6e538ed26fad59921f85e688582abf20bbab8a/report/plots.py#L645-L646

**Comment by ndevenish** [comment]
Right, the limiting factor here is the 1/d² scale axis. A log plot is close, but not close enough to the standard layout. A scaled-axis in log is probably the closest that could be gotten _in plotly_:
![image](https://user-images.githubusercontent.com/529963/84656978-76bfbe00-af0b-11ea-8bd0-fc72a02bbf0c.png)
which is just about... off... enough to be potentially confusing.

**Comment by ndevenish** [comment]
Closing due to plotly limitations (fixable upstream, but probably not important enough for us to do ourselves)

**Comment by benjaminhwilliams** [comment]
It seems to me that a satisfactory resolution of this issue depends on https://github.com/plotly/plotly.js/issues/4798.  Perhaps worth revisiting once that issue is closed.  I notice that it has been earmarked for [the next Plotly point release (1.55.0)](https://github.com/plotly/plotly.js/milestone/52), so perhaps it won't be too long before we can hope to see this working.

**Comment by ndevenish** [comment]
Interesting, I found [hoverformat](https://plotly.com/javascript/reference/#layout-xaxis-hoverformat) and wondered if that could be used to eliminate the label, but that looks a little more featured.
