### ISSUE TITLE
dials.import splits single SBGRID dataset into 3 scans (should be single scan)

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#131]
```
$ dials.import /dls/mx-scratch/gw56/sbgrid/5/dataset5/AS-T6P15_1_*.img 
DIALS 1.dev.242-ge647f80
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
DataBlock 0
  format: <class 'dxtbx.format.FormatSMVADSCSN.FormatSMVADSCSN'>
  num images: 70
  num sweeps: 3
  num stills: 0
Sorry: 
            More than 1 sweep was found. Two things may be happening here:

            1. There really is more than 1 sweep. If you expected this to be the
               case, set the parameter allow_multiple_sweeps=True. If you don't
               expect this, then check the input to dials.import.

            2. There may be something wrong with your image headers (for example,
               the rotation ranges of each image may not match up). You should
               investigate what went wrong, but you can force dials.import to treat
               your images as a single sweep by using the template=image_####.cbf
               parameter (see help).

$ dials.import /dls/mx-scratch/gw56/sbgrid/5/dataset5/AS-T6P15_1_*.img allow_multiple_sweeps=True
$ dials.show datablock.json | grep Scan -A 2
Scan:
    image range:   {1,1}
    oscillation:   {160,1}
--
Scan:
    image range:   {2,38}
    oscillation:   {161,1}
--
Scan:
    image range:   {39,70}
    oscillation:   {198,1}
```

**Comment by rjgildea** [comment]
It would be useful if dials.import could give more feedback on exactly why it decided there were multiple scans present. It currently is not easy to tell why it has decided as such.

**Comment by graeme-winter** [comment]
Problem here is the wavelength is "wiggling" which is seen from time to time when it is derived from a readback:


[gw56@cs04r-sc-com99-02 131]$ dials.show datablock.json  | grep wave
    wavelength: 0.97926
    wavelength: 0.97926
    wavelength: 0.97927

**Comment by graeme-winter** [comment]
This may not be the *only* problem :(

**Comment by graeme-winter** [comment]
Bug: wavelength tolerance is not respected given the input:

<pre>

[gw56@cs04r-sc-com99-02 131]$ dials.import /dls/mx-scratch/gw56/sbgrid/5/dataset5/AS-T6P15_1_*img tolerance.beam.wavelength=1 tolerance.detector.origin=1 allow_multiple_sweeps=true
DIALS 1.2.0-gc150620-release
The following parameters have been modified:

input {
  allow_multiple_sweeps = True
  datablock = <image files>
  tolerance {
    beam {
      wavelength = 1
    }
    detector {
      origin = 1
    }
  }
}

--------------------------------------------------------------------------------
DataBlock 0
  format: <class 'dxtbx.format.FormatSMVADSCSN.FormatSMVADSCSN'>
  num images: 70
  num sweeps: 2
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
</pre>

**Comment by rjgildea** [comment]
But the first two sweeps have the same wavelength! That doesn't explain why they are separated. It would be incredibly useful if dials.import was able to highlight the differences between sweeps in the case of multiple sweeps, otherwise it is not at all obvious to the user why it has seemingly misinterpreted their image headers.

**Comment by graeme-winter** [comment]
Beam centre also changes if you scan the headers => need to cope with origin shift of 0.4mm

**Comment by graeme-winter** [comment]
tolerance.detector.origin=1mm...

**Comment by graeme-winter** [comment]
I agree BTW about the usefulness thing...

**Comment by jmp1985** [comment]
I can try and add some sort of diff to the output when multiple experiments are found. I'll also investigate why wavelength tolerance isn't respected.

**Comment by jmp1985** [comment]
Should now be fixed
