### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1327]
I know the issue title is a bit provocative given that we don't even fully support 3.7+ yet (#1236)...

Conda-forge is due to retire Python 3.6 'really soon now' (already overdue - it was planned for the 23rd of June 2020).

Following this retirement existing conda-forge packages will remain available, however we will run into the same deprecation dilemma that we have with 2.7, which is that our environments will be cut off from package updates.
We should therefore begin to plot a path to retirement now. This has been mentioned many times in the past, so here's my suggestion:

#### Asssumptions
* I'm assuming we can get 3.7 support going, otherwise everything below is academic
* The current release schedule is ~5 minor releases per year, with patch releases following every 2 weeks.
* By default a minor release becomes EOL with the release of the next minor release.
* The only current exception is 2.2 (EOL: Dec 2020)

#### Suggested release/support model
* We make 3.7 the default Python version as soon as Azure demonstrates the environment is stable for a while
* When conda-forge drops 3.6 support the next minor release is the final release supporting Python 3.6. Call this version **3.H**
* After **3.H** is released we retire 3.6 support on `master`, and 3.7 language features become available immediately
* This **3.H** release starts off with a normal life cycle (patch releases **3.H.1**, **3.H.2**,.. every 2 weeks until the next minor release **3.H+1** is made)
* When **3.H+1** is released we aim to continue supporting **3.H** until the official Python 3.6 EOL (Dec 2021)
* _However_ from that point onwards patch releases will happen less frequently and on an on-demand basis. And we do not distribute binary builds for those patch releases.
* The **3.H+1** release supports only Python 3.7+, and follows a regular release schedule

#### Observations
* The described model is somewhat based on the CPython policy. For example there are no official binary installs for [Python 3.6.10](https://www.python.org/downloads/release/python-3610/), because 3.6 is no longer maintained outside of security patches.
* People can still download the relevant `bootstrap.py` and create their own binary installer if desired. Yet we do not have to keep Jenkins jobs around and deal with file uploads etc.
* The quality assurance happens via Azure builds within the release pull requests.
* If something unexpected happens and breaks this setup we can discontinue the support of **3.H** early.
* The process should be sufficiently lightweight to not cause a lot of headache in terms of build management.
* It also allows us to use modern language features in the development branch in a deterministic time frame.
* And avoids the issue with adding/updating dependencies that are not available for older Python versions altogether.

**Comment by graeme-winter** [comment]
I can see this causing problems:

 - After 3.H is released we retire 3.6 support on master, and 3.7 language features become available immediately

For the simple reasons that 

 - a lot of developers may only just be on 3.6
 - some developers could still be on 2.7
 - PHENIX builds are based on ??? I don't know what

The proposals above are reasonable in the general sense, but I can see them being problematic in this case. Also, I would say that getting 3.7 actually supported would be _a good thing_ obviously.

Most of our problem here is playing catch up after multiple years of Python 3 denial: it's meant that the change rate after actually making the move has to be much more rapid than if we'd moved to Python 3.X in a more timely manner...

**Comment by graeme-winter** [comment]
Following from the absence of any other feedback direct or otherwise I guess @Anthchirp your proposal stands: supporting the same Python versions as conda-forge supports seems reasonable. 

Discussion in dials-core meeting with CCP4 representation gets broad agreement that this is a reasonable approach.

**Comment by graeme-winter** [comment]
Further discussion with @phyy-nx  and @dwpaley  on 20200811 core meeting indicates collective agreement.

**Comment by graeme-winter** [comment]
Not stale, because we still _currently_ support 3.6 - should we continue to do so? I note we release on 3.8 and I develop on that platform.

**Comment by Anthchirp** [comment]
Reading the room, I did already get the feeling that some people would like to use newer language features sooner. We could consider swapping out the less well-defined conda-forge schedule and adopting NEP-29 instead as the basis for our support policy.

**Comment by phyy-nx** [comment]
Isn't 3.6 EOL not until [December](https://devguide.python.org/#status-of-python-branches)?  I had thought we were going to tie our schedules to that time table.  Not strongly opinionated on this though.

**Comment by Anthchirp** [comment]
With [DC-3](https://dials.github.io/kb/proposals/dc3) now adopted DIALS 3.6 (due in late August) will be the final version supporting Python 3.6.
