### ISSUE TITLE
32 bit centos 5 test failures

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#134]
The following two tests fail on 32 bit centos 5:
dials/test/algorithms/spot_prediction/tst_scan_static_reflection_predictor.py
dials/test/command_line/tst_integrate.py

The both fail with this error message:
AssertionError: Table has 1028 entries instead of 1996

Full build bot log is here:
http://cci-vm-6.lbl.gov:8010/builders/dials-nightly-regression-intel-linux-2.6-centos5/builds/415/steps/test%20dials/logs/stdio

**Comment by Anthchirp** [comment]
Out of those two _tst_scan_static_reflection_predictor.py_ is the smaller testcase that I wrote some time ago specifically for this failing _tst_integrate_ test. If I remember correctly @jmp1985 wanted to take a look at this.

**Comment by Anthchirp** [comment]
CentOS5 support ends March 2017. Let's be honest - this will not be fixed.

**Comment by phyy-nx** [comment]
For the Phenix side, Centos 5 32 bit will be supported past it's end of life, so it would be good if these two tests could be looked at.

In addition, it appears dials/test/command_line/tst_export_best.py is also failing on this system.

Developers can test this by logging into cci-vm-5.lbl.gov as builder.

Latest build log:
http://cci-vm-6.lbl.gov:8010/builders/dials-nightly-regression-intel-linux-2.6-centos5/builds/730/steps/test%20dials/logs/stdio

Thanks,
-Aaron

**Comment by jmp1985** [comment]
@phyy-nx Is this still a thing? @Anthchirp Do we have a centos 5 32 bit build machine?

**Comment by Anthchirp** [comment]
We do not.

**Comment by graeme-winter** [comment]
DIALS East wise I cannot imagine that investing effort in debugging things here is a good idea... 

32 bit is unsupported in most systems

RHEL5 / CENTOS5 is way past retirement

This ticket has also been around for 18 mo without anyone looking harder

Surely we have better things to do?

**Comment by graeme-winter** [comment]
Closing.

Unless someone has a really-very-good justification for this i.e. NNN DIALS users who *need* this

**Comment by phyy-nx** [comment]
These tests are passing on Centos5 32 bit now anyway.  Looks like it started passing around early Sept this year.  Cool!
