### ISSUE TITLE
dials.integrate: should not copy input to output

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1342]
Assert: in `dials.integrate` we should not copy the input data to the output file. Like `dials.find_spots`, `dials.integrate` is "special" in that it accesses the raw data. Currently it _copies_ all the input reflections to the output as well as adding the integrated reflection output. I believe that this is _not_ desirable behaviour - in export we need to strip them out, every time I _look_ at the output I have to strip them out. 

Not only is this unnecessary and inconvenient we pay for this in storage and run time

Storage
-------

To illustrate, stripping the unintegrated reflection data with:

```
import sys

from dials.array_family import flex

fin = sys.argv[1]
fout = fin.replace(".refl", "_strip.refl")

data = flex.reflection_table.from_file(fin)
data = data.select(data.get_flags(data.flags.integrated))
data.as_file(fout)
```

cuts a lot of data:

```
Silver-Surfer integrate :) $ du -hs 11*refl
962M	11_integrated.refl
761M	11_integrated_strip.refl
```

~ 25% of the file size which is replicated at _every_ step downstream e.g. symmetry and scaling to give a substantial aggregate improvement in disk usage. 

Time
----

Demonstration of the time saving by running `dials.symmetry` on the integrated data: the only difference here is the lack of need to read and write the unintegrated reflections:

```Silver-Surfer integrate :) $ for j in 1 2 3 ; do time dials.symmetry 11_integrated.expt 11_integrated.refl > /dev/null; done

real	1m35.731s
user	1m5.560s
sys	0m12.466s

real	1m34.454s
user	1m5.349s
sys	0m11.984s

real	1m34.085s
user	1m6.500s
sys	0m12.516s
```

vs.

```
Silver-Surfer integrate :) $ for j in 1 2 3 ; do time dials.symmetry 11_integrated.expt 11_integrated_strip.refl > /dev/null; done

real	1m28.774s
user	1m4.625s
sys	0m10.121s

real	1m21.750s
user	1m5.293s
sys	0m9.892s

real	1m20.753s
user	1m3.889s
sys	0m9.884s
```

So saving of ~ 14s on ~100s (which is substantial) as well as a saving in memory use. 

Proposal
--------

Propose the following fixes:
- by default do not include unintegrated reflections in the output reflection data
- add a PHIL parameter to copy input to output e.g. `copy_input_reflections`

I believe that this will also align the program with what a user may expect. Comments welcome, will prepare a PR for this.

**Comment by Anthchirp** [comment]
What is the use case for keeping unintegrated reflections?

**Comment by graeme-winter** [comment]
I should imagine something along the lines of "diagnostics when using `dials.stills_process`" would be in there - otherwise I think the use cases are pretty limited since all the information in there is strictly contained within the input files. 

`dials.stills_process` is special since it does not save intermediate files, however I believe since it does not use the command line API to `dials.integrate` it _should_ not be affected by these changes.

**Comment by rjgildea** [comment]
By doing:
```
data = data.select(data.get_flags(data.flags.integrated))
```
you are explicitly selecting _only_ those reflections that have been successfully integrated by both profile-fitting AND summation integration. As of #1300 dials.scale can also handle reflections that have been either profile-fitted OR summation integrated, so this particular filter is probably not the correct thing to do.
Also, too many reflections are flagged as not integrated, when they probably should be integrated (see #1297) so the savings in time/memory are likely to be less once this has been resolved.

**Comment by rjgildea** [comment]
> ```
> data = data.select(data.get_flags(data.flags.integrated))
> ```
Actually, this depends on whether or not you pass `all=False` or `all=True` to `get_flags()`, and I can never remember which is the default, or which value of `all` gives which behaviour.

**Comment by graeme-winter** [comment]
@rjgildea very valid point

```
print(data.get_flags(data.flags.integrated).count(True))
print(data.get_flags(data.flags.integrated, all=False).count(True))
print(data.get_flags(data.flags.integrated, all=True).count(True))
```

=>

```
1928635
2004295
1928635
```

in this example so it would look like `all=False` is the more permissive.

**Comment by Anthchirp** [comment]
Would it make sense to write two files, integrated.refl and unused.refl? My concern is that adding more options is not always helpful.

**Comment by graeme-winter** [comment]
> Would it make sense to write two files, integrated.refl and unused.refl? My concern is that adding more options is not always helpful.

Assert no, for the simple reason that these reflections are not useful for anything beyond diagnostics. While I recognise your concern for the option proliferation here I think in this case it is quite justified. The option name has been discussed in the PR and there is scope for clarification.

**Comment by ndevenish** [comment]
Wouldn't this mean that reports generated with dials-report will be incomplete/misleading in terms of the strong spots? Or is this the case for data anyway?

It's also nice to sometimes switch between integrated/not integrated on the image viewer when demonstrating DIALS and showing what has been going on, and presumably this would similarly exclude the unintegrated, unindexed reflections for viewing e.g. the reciprocal lattice.

I'd be happy to have an option to strip them, but at the moment feel like it's less unexpected to keep them in.

**Comment by phyy-nx** [comment]
FYI, I don't think dials.stills_process is impacted since it does indeed use algorithms/integration as an API.

```
cd $modules/dials/test/command_line
libtbx.pytest -n 3 test_stills_process.py
libtbx.ipython
from dials.array_family import flex
r = flex.reflection_table.from_file('/tmp/pytest-of-aaron/pytest-current/popen-gw2/test_sacla_h5_False_0/idx-0000_integrated.refl')
print(len(r))
b = r.get_flags(r.flags.integrated); print(b.count(True))
b = r.get_flags(r.flags.integrated_prf); print(b.count(True))
b = r.get_flags(r.flags.integrated_sum); print(b.count(True))
```
Output:
```
1283
0
0
1283
```
In other words, the reflections aren't marked at integrated (prolly a bug) but are marked as integrated_sum.  No other reflections in the file.

**Comment by graeme-winter** [comment]
For the moment the associated PR now gives an _option_ to not include unintegrated reflections, so could be merged as something concrete to test / discuss.
