### ISSUE TITLE
dials.plot_reflections - what does it do?

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1345]
I'm looking at the test failure in `test/test_plot_reflections.py` for new matplotlib versions >=3.3. Matplotlib now throws warnings when you pass unknown keyword arguments to plot functions (https://github.com/matplotlib/matplotlib/pull/17223/files), which causes the test to fail.

When I look at the test output all I see is:
![centroids-master](https://user-images.githubusercontent.com/2102431/88032288-a7f86300-cb35-11ea-9c39-a3bc4e9b9779.png)
which doesn't strike me as very useful.  I checked with DIALS 1.14 and the output is the same.

[The last non-maintenance commit on the dispatcher was in August 2016.](https://github.com/dials/dials/commits/master/command_line/plot_reflections.py)

Looks to me like this tool was broken a long time ago. It looks to me like the options are
1. fix the tool
2. if the tool isn't broken then amend the test so that it shows something useful
3. remove both tool and test

Opinions?

**Comment by rjgildea** [comment]
What are the keywords that matplotlib complains about? I don't see any obviously incorrect keyword arguments from scanning the code. And I don't think this is related to the lack of (visible) output, which is fixed by https://github.com/dials/dials/pull/1346).
