### ISSUE TITLE
Dials regression test failures on windows

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#135]
There are currently 9 test failures in dials regression on windows according to build bot.  I've lumped them all here, but I can split them out instead if desired.

Full build log here:
http://cci-vm-6.lbl.gov:8010/builders/dials-nightly-regression-intel-windows-x86_64/builds/83/steps/test%20dials/logs/stdio

Tests failing and snippets of exceptions:
- dials\test\algorithms\background\tst_mosflm_outlier_rejector.py

shoeboxes, masks = pickle.load(open(self.shoebox_filename, "r"))
    EOFError
- dials\test\algorithms\refinement\tst_refine_multi_stills.py

Pickling of "dials_algorithms_spot_prediction_ext.StillsDeltaPsiReflectionPredictor" instances is not enabled 
- dials\test\command_line\tst_combine_found_spots.py

'tee' is not recognized as an internal or external command,
      operable program or batch file.
- dials\test\command_line\tst_find_spots_server_client.py

pickle.PicklingError: Can't pickle <function start_server at 0x0000000003058898>: it's not found as **main**.start_server
    Traceback (most recent call last)
- dials\test\command_line\tst_idials.py

assert exists("10_integrated.mtz")
    AssertionError
- dials\test\command_line\tst_generate_mask.py

RuntimeError: Unquoted word expected, found 'ice_rings{filter=True;d_min=2}' (command line argument, line 1)
- dials\test\command_line\tst_slice_sweep.py

sliced_refs = pickle.load(f)
    EOFError
- dials\test\command_line\tst_stills_detector_hybrid_refine.py

The command line is too long.
- dials\test\util\tst_nexus.py

assert(data1.all_eq(data2))
    AssertionError

**Comment by graeme-winter** [comment]
Thanks Aaron 

Related to this we now have Windows box for builds. Are there get you going instructions some place?

Cheers Graeme

**Comment by graeme-winter** [comment]
Ps thanks also for reports some look easy to fix. Tee I'm looking at you.

**Comment by rjgildea** [comment]
Does an open(..., 'rb') instead of open(..., 'r') fix the pickle EOFError failures?

**Comment by phyy-nx** [comment]
Hi Graeme, I'm forwarding this on to Rob who might be able to provide
instructions.
Thanks,
-Aaron

**Comment by phyy-nx** [comment]
Hi Graeme,

The short answer is that there isn't any official guidelines as yet for 
running bootstrap on Windows. But it's on top of my todo list.

The setup we are using for nightlies in Berkeley works both for 
automated builds with buildbot as well as a manual standalone build on 
your PC.

There isn't a canonical protocol for building under Widnows. What I have 
developed works although it is rather quirky mostly due to Windows until 
now lacking OpenSSH. Instead we use the PuTTY suite which works fine but 
adds to the complexity of bootstrap.py. I have not tested other OpenSSH 
packages. End of this summer Microsoft should have an official port of 
OpenSSH ready which will simplify bootstrap.py.

For version control you will need an SVN client such as TortoiseSVN 
which integrates nicely with Windows Explorer and also has a 
command-line interface. Likewise you'll need Git for Windows. This can 
also be integrated nicely with Windows Explorer with TortoiseGit but is 
not necessary.

Both of these tools uses the PuTTY suite of programs. Putty contains 
Pageant which allows SVN access with public/private keys where seamless 
ssh or scp access is required. For setting up public/private keys for 
SVN access you need to generate an ssh key pair with the PuTTYgen 
program, copy the public key to the servers where files are checked out 
with ssh, create an environment variable SVN_SSH that points to the 
location of plink.exe (using forward slashes instead of back slashes) 
and also create an environment variable GIT_SSH that points to the 
location of plink.exe (using forward slashes instead of back slashes).

Pageant works similar to ssh_agent from OpenSSH and if you already have 
a set of public/private keys you can just convert them to the PuTTY 
format with the PuTTYgen program.

For the build you will need Python 2.7.x and Microsoft VS2008 that 
contains the VC++9.0 compiler. You can get it from the Windows7 SDK from 
the Microsoft website:
https://www.microsoft.com/en-gb/download/details.aspx?id=3138
It should be titled "Microsoft Windows SDK for Windows 7 and .NET 
Framework 3.5 SP1". There are newer versions of this SDK using more 
recent compilers. As these use a newer C-runtime library I suspect 
compiled programs may not binary compatible with Python 2.7 (which 
python.org insist on compiling with VS2008). You should still be able to 
build individual statically linked executables with those newer 
compilers. But whether or not compiled python modules can run without 
crashing using a newer runtime I don't know. After installing the 
compiler it can be invoked once environment variables have been set by 
calling scripts such as vcvars32.bat or vcvars64.bat.

For Phenix builds apart from zipping the build in to a large zip file we 
also package them as a graphical Windows setup program using Makensis 
from NullSoft. This may not be necessary for Dials. But if you decide it 
is you will need to tailor an installation script such as 
cctbx_project/libtbx/auto_build/mainphenixinstaller.nsi for the Makensis 
program to tell it which files to put in the installer it builds and 
where to place them on the users PC.

Finally you may want the equivalent of tee called wtee.exe for copying 
stdout to a file. But it unfortunately swallows any non-zero error code 
emitted by python if the build fails. Not ideal at all.

Assuming all the above prerequisite programs are present in the path of 
a cmd shell you can start a boostrap build as per the instructions in 
bootstrap.py. I have attached a simplified cmd script that does this.

On the positive side of things bootstrap.py doesn't need to build python 
or HDF5 from scratch. These two components have been build once, have 
been zipped up and are downloaded from cci.lbl.gov and installed by 
boostrap.py. The zipped up python is version 2.7.9 and contains all the 
modules currently necessary for dials and Phenix builds I believe.

Let me know if there are further questions.


Rob



On 06/05/2016 19:38, Aaron Brewster wrote:
> Hi Graeme, I'm forwarding this on to Rob who might be able to provide
> instructions.
> Thanks,
> -Aaron
> 
> On Fri, May 6, 2016 at 11:13 AM, Graeme Winter
> <notifications@github.com> wrote:
> 
>> Thanks Aaron
>> 
>> Related to this we now have Windows box for builds. Are there get
>> you going instructions some place?
>> 
>> Cheers Graeme
>> 
>>> On 6 May 2016, at 18:10, phyy-nx <notifications@github.com>
>> wrote:
>>> 
>>> There are currently 9 test failures in dials regression on
>> windows according to build bot. I've lumped them all here, but I can
>> split them out instead if desired.
>>> 
>>> Full build log here:
>>> 
>> 
> http://cci-vm-6.lbl.gov:8010/builders/dials-nightly-regression-intel-windows-x86_64/builds/83/steps/test%20dials/logs/stdio
>> [1]
>>> 
>>> Tests failing and snippets of exceptions:
>>> 
>>> dialstestalgorithmsbackgroundtst_mosflm_outlier_rejector.py
>>> shoeboxes, masks = pickle.load(open(self.shoebox_filename, "r"))
>>> EOFError
>>> 
>>> dialstestalgorithmsrefinementtst_refine_multi_stills.py
>>> Pickling of
>> 
> "dials_algorithms_spot_prediction_ext.StillsDeltaPsiReflectionPredictor"
>> instances is not enabled
>>> 
>>> dialstestcommand_linetst_combine_found_spots.py
>>> 'tee' is not recognized as an internal or external command,
>>> operable program or batch file.
>>> 
>>> dialstestcommand_linetst_find_spots_server_client.py
>>> pickle.PicklingError: Can't pickle : it's not found as
>> main.start_server
>>> Traceback (most recent call last)
>>> 
>>> dialstestcommand_linetst_idials.py
>>> assert exists("10_integrated.mtz")
>>> AssertionError
>>> 
>>> dialstestcommand_linetst_generate_mask.py
>>> RuntimeError: Unquoted word expected, found
>> 'ice_rings{filter=True;d_min=2}' (command line argument, line 1)
>>> 
>>> dialstestcommand_linetst_slice_sweep.py
>>> sliced_refs = pickle.load(f)
>>> EOFError
>>> 
>>> dialstestcommand_linetst_stills_detector_hybrid_refine.py
>>> The command line is too long.
>>> 
>>> dialstestutiltst_nexus.py
>>> assert(data1.all_eq(data2))
>>> AssertionError
>>> 
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly or view it on GitHub
>>> 
>> 
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub [2]
> 
> 
> 
> Links:
> ------
> [1]
> http://cci-vm-6.lbl.gov:8010/builders/dials-nightly-regression-intel-windows-x86_64/builds/83/steps/test%20dials/logs/stdio
> [2] https://github.com/dials/dials/issues/135#issuecomment-217518597


SET PLATFORM=%1
SET PHENIXVERSION=%2

IF DEFINED PLATFORM (
IF %PLATFORM% == x32 (
  call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars32.bat"
  set PYTHONEXE=C:\Python27_32\python.exe
)

IF %PLATFORM% == x64 (
  call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat"
  set PYTHONEXE=C:\Python27_64\python.exe
)
)

REM Get latest bootstrap from svn repo
svn export --force svn://svn.code.sf.net/p/cctbx/code/trunk/libtbx/auto_build/bootstrap.py 2>&1 | wtee build.log

REM             hot update base build
%PYTHONEXE% bootstrap.py --builder=phenix --sfuser=oeffner --cciuser=rdo20 --nproc=10 2>&1 | wtee -a ..\build%PHENIXVERSION%-%PLATFORM%.log

REM            run tests
%PYTHONEXE% bootstrap.py --builder=phenix --sfuser=oeffner --cciuser=rdo20 --nproc=10 tests 2>&1 | wtee -a ..\tests%PHENIXVERSION%-%PLATFORM%.log

REM            create installer
call build\bin\libtbx.create_installer.bat --binary --version %PHENIXVERSION% --install_script modules\phenix\phenix\installer\phenix_installer.py --license modules\phenix\LICENSE.txt --readme modules\phenix\CHANGES --readme modules\phenix\phenix\installer\README --readme modules\phenix\phenix\installer\SOURCES --dist_dir dist\%PHENIXVERSION% tmp\phenix-installer-%PHENIXVERSION%-win7vc90 2>&1 | wtee -a ..\CreateInstaller%PHENIXVERSION%-%PLATFORM%.log

**Comment by Anthchirp** [comment]
We now run Windows builds and tests regularly and are making good progress towards fixing broken tests, so I think this ticket can be closed.
