### ISSUE TITLE
dials.index: self.experiments used where should be self.refined_experiments?

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1351]
https://github.com/dials/dials/blob/e7e52924cfc8af04b78999b7b53b02dd4cc94401/algorithms/indexing/indexer.py#L708

@rjgildea  looks like this should _probably_ be self.refined_experiments

Saw this while working on other things

**Comment by rjgildea** [comment]
Probably, although I imagine this only makes a very minor difference to the mm-to-px mapping.

**Comment by graeme-winter** [comment]
Picked this up in the other PR anyways - it _should_ make a minor difference however could explain why sometimes re-running indexing gives a better answer than just indexing - because the second time around the mm / px transform is done with refined geometry

Agreed in vast majority of cases diffs will be minor
