### ISSUE TITLE
Trimming Scans Breaks Refinement With Multiple Image Sets

### ISSUE THREAD

**Issue by kmdalton** [dials/dials#1374]
If multiple image sets are affiliated with a single scan, the automatic [trimming](https://github.com/dials/dials/blob/d9e9629744be5cea3496fe70befe928fb4425795/algorithms/refinement/refiner.py#L155) in the current DIALS version can create new truncated scan objects. This will trigger a [sanity check](https://github.com/dials/dials/blob/d9e9629744be5cea3496fe70befe928fb4425795/algorithms/refinement/parameterisation/configure.py#L490) and cause scan varying refinement to fail. I put together a minimal [example](https://github.com/kmdalton/dials-example) to illustrate this behavior.

**Comment by graeme-winter** [comment]
I think the root error here is actually elsewhere - scan varying refinement with a single crystal model but multiple scans should have something like 

```
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.dev.156-g1c35257a9
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Duplicating crystal model for scan-varying refinement of experiment 1
Duplicating crystal model for scan-varying refinement of experiment 2
Duplicating crystal model for scan-varying refinement of experiment 3
Configuring refiner
```

at the top of the refinement - but this is not present in the example you sent, so 🤔

Quickly investigating now

**Comment by graeme-winter** [comment]
OK, I think the root problem is this:

```
dials.import \
    geometry.scan.oscillation=0,0.25
```

which means all the scans are the same, so the check whether a crystal is shared across multiple scans fails as the scans are the same scan, rather than being multiple copies of one scan. I assert that this is a bug in dials.import and hence simply fixed.

**Comment by graeme-winter** [comment]
Oh wait, ignore the thing above. 

```
dials.combine_experiments imported.expt strong.refl \
    reference_from_experiment.beam=0 \
    reference_from_experiment.scan=0 \
    reference_from_experiment.detector=0 \
    reference_from_experiment.goniometer=0 
```

👆 is the source of the problem - this is not doing anything useful as they all have the same detector etc. but more importantly this _breaks_ the detection of multiple scans as they have only one scan - I am not sure what the use case for combining the scan models is but 

```
Grey-Area dials-example :) [master] $ git diff
diff --git a/minimal_example.sh b/minimal_example.sh
index b0ea6ab..1e5458e 100755
--- a/minimal_example.sh
+++ b/minimal_example.sh
@@ -19,7 +19,6 @@ dials.find_spots imported.expt \
 
 dials.combine_experiments imported.expt strong.refl \
     reference_from_experiment.beam=0 \
-    reference_from_experiment.scan=0 \
     reference_from_experiment.detector=0 \
     reference_from_experiment.goniometer=0 
```

Makes the problem reported here go away 🙂

**Comment by graeme-winter** [comment]
@kmdalton from my perspective this is resolved however I'll leave you to close if you are happy. The other related issue needs fixing though - #1376

**Comment by kmdalton** [comment]
@graeme-winter, thanks for getting back so fast! 

I would argue there is a use case for `reference_from_experiment.scan=0`. In particular, the data I am working on are rotation series of still images. At each rotation step, we acquired multiple images before advancing to the next set. In the context of the example, all four `images/#_00001.tiff` emanate from the same sample at the same orientation and were acquired within milliseconds of one another. We rotated the goniometer and acquired `images/#_00002.tiff` immediately thereafter. Then we rotated and acquired `images/#_00003.tiff` and so forth. 

In my opinion, the data really are best represented as multiple image sets affiliated with a single scan. I want all the strong spots from all the images to constrain a single scan varying crystal model. I think your recommendation will lead to a separate scan varying model for each image set, which is not the behavior I'm after. (Let me know if I misinterpret)

I have treated the data this way successfully in past versions of DIALS, but this [call](https://github.com/dials/dials/blob/d9e9629744be5cea3496fe70befe928fb4425795/algorithms/refinement/refiner.py#L320) now breaks it. 

I worry I may not have done an adequate job explaining this issue initially. We can loop in @phyy-nx to help me plead my case if need be. He is also familiar with these data and helped me develop the data reduction code I'm using.

**Comment by dagewa** [comment]
Hi @kmdalton, the scan trimming code was introduced to stop autoprocessing failing when a crystal went out of the beam, otherwise refinement could crash if there were no data at the end (or beginning of a scan). As such, it is designed to mitigate against failures, rather than providing an important new feature. For that reason, I would be happy if that feature went under user control, so that you could switch it off for your atypical use case.

The alternative would be combining the reflections into a single experiment for the purposes of refinement, but while this may be more 'purist' approach to modelling this situation with DIALS, I can see how it would be more awkward for you.

**Comment by dagewa** [comment]
If this solution is acceptable, then the question is what to name the parameter? Unfortunately there is already a `refinement.reflections.trim_scan_edges` parameter, which has a slightly different intention. This was put there to allow users to remove _reflections_ within some limit from the edges of the scan, because these reflections have the worst Z centroids. It does not change the `Scan` object at all. I'm open to suggestions to improve the user interface. I won't work on it myself for a couple of weeks at least though, as that would indicate an even greater failure at taking annual leave than I am currently demonstrating.

**Comment by kmdalton** [comment]
Hi @dagewa, thanks for the suggestion. Yes, that'd be completely satisfactory to me. I can also appreciate why scan trimming is a good feature, and a sensible default. 

Maybe something like `refinement.disable_scan_trimming` or  `refinement.bypass_scan_trimming`?

**Comment by graeme-winter** [comment]
@kmdalton thanks for the reasoning - your use case makes sense here.

Do you expect to have *one* scan varying crystal model across all the scans then? I can see why you would want that.

**Comment by dagewa** [comment]
@kmdalton I prefer a positive named parameter, so the default is `do_something=True` rather than `do_not_do_something=False`

**Comment by dagewa** [comment]
Maybe `refinement.reflections.trim_scan_to_observations=True` as default would be okay. The existing parameter `refinement.reflections.trim_scan_edges` could get a better name, like `refinement.reflections.exclude_scan_edges` or something

**Comment by kmdalton** [comment]
@dagewa 
How about `refinement.reflections.trim_scan_edges` goes to
`refinement.reflections.remove_edge_reflections_within`
or
`refinement.reflections.remove_scan_edge_reflections_within`?
Are those too long?

I like `refinement.reflections.trim_scan_to_observations=True` just fine.

**Comment by kmdalton** [comment]
@graeme-winter, yes! the idea is to have a single scan varying crystal model for all the scans since they should all be in pretty much the same orientation for equivalent image numbers. this is pretty important to me, because the x-fel beam intensity during my experiment fluctuated pretty dramatically. trusting any single scan to constrain the model is ill advised.

**Comment by dagewa** [comment]
I should be able to look at this soon. Meanwhile I've come up with `scan_margin=0` as a replacement for `trim_scan_edges=0`. The new name doesn't imply any trimming of the scan object. The help string explains what the parameter does so I don't think a longer, more descriptive name is required.
