### ISSUE TITLE
dials.combine_experiments: reference_from_experiment.scan is not useful

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1376]
This is not an experiment model _per se_ rather a source of insight into the experiment which is not modified and should not be. Using this option caused #1374.

I do not think this option should exist for `dials.combine_experiments` 🙂

**Comment by kmdalton** [comment]
@graeme-winter, we decided that this option had a use case over on #1374. I move that this issue be closed lest it spuriously gain traction. Sounds reasonable?

**Comment by graeme-winter** [comment]
@kmdalton rarely will I complain 'bout closing tickets 🙂
