### ISSUE TITLE
dials.index weirdness from splitting one scan into two; finding spots in two chunks then combining

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#138]
directory 1

<pre>
dials.import template=../images_local_gz/thermc_1_####.cbf.gz image_range=1,3600
dials.find_spots datablock.json nproc=20
</pre>

directory 2

<pre>
dials.import template=../../images_local_gz/thermc_1_####.cbf.gz image_range=3601,7200
dials.find_spots datablock.json nproc=20
</pre>

Then in directory 3

<pre>
dials.combine_found_spots ../1/datablock.json ../1/strong.pickle ../2/datablock.json ../2/strong.pickle output.reflections=join.pickle
dials.index join.pickle combined_datablock.json
</pre>

gives idiosyncratic results...

<pre>
RMSDs by experiment:
----------------------------------------------
| Exp | Nref  | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |       | (px)    | (px)    | (images) |
----------------------------------------------
| 0   | 72000 | 0.18294 | 0.18208 | 0.219    |
----------------------------------------------

Refined crystal models:
model 1 (414837 reflections):
Crystal:
    Unit cell: (92.342, 92.341, 127.709, 89.994, 90.001, 59.995)
    Space group: P 1
    U matrix:  {{-0.1568, -0.0838, -0.9841},
                { 0.9586, -0.2529, -0.1312},
                {-0.2379, -0.9639,  0.1200}}
    B matrix:  {{ 0.0108,  0.0000,  0.0000},
                {-0.0063,  0.0125,  0.0000},
                { 0.0000, -0.0000,  0.0078}}
    A = UB:    {{-0.0012, -0.0010, -0.0077},
                { 0.0120, -0.0032, -0.0010},
                { 0.0035, -0.0121,  0.0009}}

model 2 (0 reflections):
Crystal:
    Unit cell: (92.342, 92.341, 127.709, 89.994, 90.001, 59.995)
    Space group: P 1
    U matrix:  {{-0.1568, -0.0838, -0.9841},
                { 0.9586, -0.2529, -0.1312},
                {-0.2379, -0.9639,  0.1200}}
    B matrix:  {{ 0.0108,  0.0000,  0.0000},
                {-0.0063,  0.0125,  0.0000},
                { 0.0000, -0.0000,  0.0078}}
    A = UB:    {{-0.0012, -0.0010, -0.0077},
                { 0.0120, -0.0032, -0.0010},
                { 0.0035, -0.0121,  0.0009}}

13809 unindexed reflections
Saving refined experiments to experiments.json
Saving refined reflections to indexed.pickle
</pre>

Probably just a "feature" but if we plan to split up processing like this into chunks would be a good idea to clean this up

**Comment by rjgildea** [comment]
I have tried to reproduce the problem but ran into the following error:

```
$ dials.import template=$(libtbx.find_under_build xia2_regression/test_data/i04_bag_training)/th_8_2_####.cbf image_range=1,270 output.datablock=datablock_1_270.json
$ dials.import template=$(libtbx.find_under_build xia2_regression/test_data/i04_bag_training)/th_8_2_####.cbf image_range=271,540 output.datablock=datablock_271_540.json
$ dials.find_spots datablock_1_270.json output.reflections=strong_1_270.pickle nproc=8
$ dials.find_spots datablock_271_540.json output.reflections=strong_271_540.pickle nproc=8
$ dials.combine_found_spots datablock_1_270.json datablock_271_540.json strong_1_270.pickle strong_271_540.pickle 
DIALS 1.dev.378-g6a3e174
The following parameters have been modified:

input {
  datablock = datablock_1_270.json
  datablock = datablock_271_540.json
  reflections = strong_1_270.pickle
  reflections = strong_271_540.pickle
}

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/combine_found_spots.py", line 316, in <module>
    halraiser(e)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/combine_found_spots.py", line 314, in <module>
    script.run()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/combine_found_spots.py", line 290, in run
    params)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/combine_found_spots.py", line 181, in combine
    raise RuntimeError('Scans do not match')
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Scans do not match
```

**Comment by rjgildea** [comment]
dials.combine_found_spots is not more, so guess this is no longer an issue?
