### ISSUE TITLE
flex.reflection_table.match doesn't 

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1397]
[integrated.zip](https://github.com/dials/dials/files/5194008/integrated.zip)

Data in zip file are from processing a 360° small molecule data set while looking at some ongoing pull requests. Trying to match up reflections between processing route A and B I found that the reflection matching works in a highly non-obvious way (or does not work for me) 

To be precise: matching a reflection table with itself should give as many matches as there are reflections, and it does not viz:

```
from dials.array_family import flex

data = flex.reflection_table.from_file("integrated.refl")
integrated = data.select(data.get_flags(data.flags.integrated))
matches = integrated.match(integrated)

print(f"{matches[0].size()} should equal {integrated.size()}")
```

proclaims 

```
26131 should equal 26882
```

which I think breaks the principle of least surprise 🙂

**Comment by dagewa** [comment]
Digging down, this uses this class
https://github.com/dials/dials/blob/81ec77c2b8b588307424330a2c7ef22dfd81341d/algorithms/spot_finding/spot_matcher.py#L6
which apparently is there to match observed reflections with predicted. That is, `predicted["xyzcal.px"]` is compared with `observed["xyzobs.px.value"]`.

I think this could be made more general purpose. That is, `table_a` can be compared with `table_b` where the columns being used for comparison could be specified during the call. That would allow this to match preds to obs, obs to obs, preds to preds and possibly other things.

**Comment by graeme-winter** [comment]
OK, I think I am misunderstanding something. Here I have written a script which does the same thing as `spot_matcher` above with a teeny bit more control:

```
from dials.array_family import flex
from annlib_ext import AnnAdaptor

def match(a, b, max_separation=2, key="xyzobs.px.value"):
    """Match reflections from list a and list b, returning tuple of 
    flex.size_t indices, optionally specifying the maximum distance and 
    key to search on (which is assumed to be a 3-vector column)."""

    xyz_a = a[key]
    xyz_b = b[key]

    a = xyz_a.as_double().as_1d()
    b = xyz_b.as_double().as_1d()

    ann = AnnAdaptor(a, 3)
    ann.query(b)

    mm = flex.size_t(range(xyz_b.size()))
    nn, distance = ann.nn, flex.sqrt(ann.distances)
    
    sel = distance <= max_separation
    
    mm = mm.select(sel)
    nn = nn.select(sel)
    distance = distance.select(sel)
    return nn, mm, distance
    
data = flex.reflection_table.from_file("integrated.refl")
integrated = data.select(data.get_flags(data.flags.integrated))

nn, mm, distance = match(integrated, integrated)

print(nn.size(), integrated.size())
```

and guess what? _There are no matches_ - 

```
Grey-Area regular :) $ dials.python ann.py 
0 26882
```

i.e. when comparing a set of vectors with itself I find no close positions. 

I suspect I have something wrong here but I cannot see it (uses data above)

**Comment by graeme-winter** [comment]
Computerised soft toy: adding 0.001 to the vector b matches every reflection. They won't match if they are in precisely the same place. Awesome

**Comment by graeme-winter** [comment]
@dagewa points out `AnnAdaptorSelfInclude` is a thing which works, but does not make the `refl.match()` method do what one may expect. But means we could add a new match function to `ReflectionTable`

**Comment by graeme-winter** [comment]
Wrote a script using this

https://github.com/dials/dials_scratch/commit/b578b69febb182143aec184ed4c1a9be43d1352f

which works for my use case - I will look at merging this into `flex.reflection_table`
