### ISSUE TITLE
dials.discover_better_experimental_model should give beam centre in pixels and at 2theta=0

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#140]
example data

```
$ dials.import /dls/i19-2/data/2016/cm14477-2/mwarren/offset_tests/3_centered/offset_tests01_00*cbf
$ dials.find_spots nproc=4 datablock.json sigma_strong=15
$ dials.discover_better_experimental_model datablock.json strong.pickle
(..)
Old beam centre: 39.12 mm, 105.57 mm
New beam centre: 40.47 mm, 104.74 mm
Shift: -1.35 mm, 0.83 mm
```

It would be useful when updating the image headers (`# Beam_xy (227.47, 310.68) pixels`) to have the beam centre also expressed in pixels.

This dataset was collected at 2theta=30°, and I assume that the stated beam centre does not take this into account?

**Comment by rjgildea** [comment]
@Anthchirp is this still an issue?
