### ISSUE TITLE
nproc=auto as default for find_spots and integrate

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1408]
Setting `nproc` > 1 is standard behaviour for `dials.find_spots` and `dials.integrate`. There is no real reason for all that extra keyboard bashing at the command line in most cases, because we could accept `nproc=Auto` as default and let the program decide what is appropriate. #1019 suggests there was some attempt to do this with `dials.find_spots` (now broken). For `dials.integrate`, this gets as far as **`Modelling reflection profiles`** and then fails.

**Comment by graeme-winter** [comment]
👍  sounds like an excellent idea 🙂

**Comment by dagewa** [comment]
Is there any reason not to set this to the equivalent of `libtbx.show_number_of_processors`?

**Comment by dagewa** [comment]
maybe something something `psutils`?

**Comment by Anthchirp** [comment]
yes, the libtbx function is not the correct number to use.

**Comment by Anthchirp** [comment]
Correct solution as far as I can tell is to use the following:
* [`len(os.sched_getaffinity(0))`](https://docs.python.org/3.6/library/os.html#os.sched_getaffinity)
* [`len(psutil.Process().cpu_affinity())`](https://psutil.readthedocs.io/en/latest/#psutil.Process.cpu_affinity) as primary fallback
* [`os.cpu_count()`](https://docs.python.org/3/library/os.html#os.cpu_count) as secondary fallback
* [`psutil.cpu_count()`](https://psutil.readthedocs.io/en/latest/#psutil.cpu_count) as tertiary fallback
* `1` as last resort

**Comment by Anthchirp** [comment]
and step 0: if the environment variable `NSLOTS` is set to an integer >=1 then use that instead

**Comment by graeme-winter** [comment]
So we need a `dials.util.how_many_cores` type helper function yes?
