### ISSUE TITLE
Save statistics output from dials programs in machine-readable format

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1438]
If I look at e.g. indexing output I see

```
RMSDs by experiment:
+-------+--------+----------+----------+------------+
|   Exp |   Nref |   RMSD_X |   RMSD_Y |     RMSD_Z |
|    id |        |     (px) |     (px) |   (images) |
|-------+--------+----------+----------+------------|
|     0 |   1499 |  0.25081 |  0.19309 |    0.18995 |
+-------+--------+----------+----------+------------+
```

and

```
+------------+-------------+---------------+-------------+
|   Imageset |   # indexed |   # unindexed | % indexed   |
|------------+-------------+---------------+-------------|
|          0 |       48270 |         12357 | 79.6%       |
+------------+-------------+---------------+-------------+
```

- spot finding etc. saves similar information. If we could cache the numbers for these in the output experiment it would mean a calling process could access the data without file scraping.

Propose: programs save key statistics of program output with output experiments

**Comment by graeme-winter** [comment]
Obviously scaling on my list too 🙂


```
Recommendation is use all data
                                             Overall    Low     High
High resolution limit                           1.37    3.71    1.37
Low resolution limit                           55.54   55.59    1.39
Completeness                                   92.2    99.9    19.8
Multiplicity                                  100.2   128.9     4.5
I/sigma                                        49.0   205.2     0.4
Rmerge(I)                                     0.066   0.038   1.797
Rmerge(I+/-)                                  0.065   0.037   1.793
Rmeas(I)                                      0.066   0.038   2.036
Rmeas(I+/-)                                   0.066   0.037   2.051
Rpim(I)                                       0.006   0.003   0.944
Rpim(I+/-)                                    0.008   0.004   0.986
CC half                                       1.000   1.000   0.348
Anomalous completeness                         88.2    99.9     1.5
Anomalous multiplicity                         53.2    71.2     4.2
Anomalous correlation                         0.573   0.727  -0.926
Anomalous slope                               0.837
dF/F                                          0.025
dI/s(dI)                                      1.111
Total observations                          1586799  118609     777
Total unique                                  15830     920     172
```

**Comment by jbeilstenedmands** [comment]
For scaling, if you give the option output.json= then it will save all of the data from the html report as a JSON file, so perhaps this is an alternative approach that might work well for some programs that make their own reports.

**Comment by dagewa** [comment]
I prefer the idea of a separate .json file rather than including this with the experiments. The statistics are typically to do with the reflections rather than the experimental models.

**Comment by graeme-winter** [comment]
@jbeilstenedmands @dagewa these are both true, however I was thinking of trying to do this without adding too much clutter and also with an eye to the future where e.g. reflections and models live together in some other container.

I don't think it is too far off base (particularly if we are recording data and models) to also save the metadata for further inspection. For example I can see it being very useful for e.g. CCP4i or whatever after processing with xia2 to be able to pick up the scaled data and see all of the processing statistics for each step, not having to recalculate anything.

I'll take a look at the `output.json` option however I would imagine adding this to `find_spots`, `index`, `refine`, `integrate` and `symmetry` as well could be tedious... though I guess that work is necessary no matter what file the metadata ends up in. It just seemed neat to me to save the salient metadata with the resulting model. 

Re: statistics to do with the reflections _not_ the model - I would say that the statistics are equally dependent on the model and reflections in most cases.

**Comment by dagewa** [comment]
My feeling is that it is worth being strict here. Until we have a combined `reflex` format, `.expt` should be for experimental models and `.refl` for reflections only. Mission creep rarely ends well. I'm reasonably happy* with the idea that derived data can have a third other standardised output format, even if starting this seems tedious. Refinement already has an optional `history.json`. I'd be happy if this were co-opted into a standard stats output.

*I see the value of this file, but another problem is that it is all too easy for derived data to go stale. Having the means wherever possible to recalculate stats on the fly is preferable and it is worth us doing more to enable this.

**Comment by graeme-winter** [comment]
Hostility to suggestion clear; will scrape `stdout` as needed then; closing

**Comment by Anthchirp** [comment]
I agree that retaining the output in the result file probably isn't helpful. However, to reduce scraping headaches any dials command could produce machine-readable output similarly to
```
git status
```
vs
```
git status --porcelain
```
This could go then to stdout or to a separate file.

**Comment by graeme-winter** [comment]
Suspect that this would face same objections (goes stale etc.) - however recalculating stats kinda messy as means reloading data etc. so 🤷‍♂️

**Comment by dagewa** [comment]
It is less bad if a separate file goes stale because treating those files together is a decision taken by the user. Having statistics embedded in the experiments is bad because this can go stale perniciously, simply by another external file (the reflections) being updated.

**Comment by dagewa** [comment]
Reopening because I think saving the statistics in a machine-readable format is better than scraping the log files. My only objection is about it being packaged within the experiments `.expt` file.
