### ISSUE TITLE
dials.reciprocal_lattice_viewer: non-obvious behaviour with grid scans

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1445]
[rlv-fail.zip](https://github.com/dials/dials/files/5340703/rlv-fail.zip)

Looking at some grid scan data, which I would expect to maybe work, turns out it does not - I am assuming because the experiment id's take up way too much horizontal space...

![Screenshot 2020-10-07 at 13 48 01](https://user-images.githubusercontent.com/1241716/95332726-bbe57280-08a3-11eb-8ef5-f64968cc3f79.png)

I would expect to see a couple of slices through the space - probably we should have some sanity checking on the experiment id's widget to work more gracefully for large N?

**Comment by jbeilstenedmands** [comment]
This now works, thanks to https://github.com/dials/dials/pull/2248
![image](https://github.com/dials/dials/assets/30625594/79c1d0a3-f680-4415-89ed-b9568b067bc1)
