### ISSUE TITLE
gaussianrs test failures

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1456]
Tests
```
test.algorithms.integration.test_parallel_integrator.test_gaussianrs_detector_space_intensity_calculator 
test.algorithms.integration.test_parallel_integrator.test_gaussianrs_detector_space_with_deconvolution_intensity_calculator
test.algorithms.integration.test_parallel_integrator.test_gaussianrs_detector_space_with_deconvolution_intensity_calculator2
```
have been failing for a while on Jenkins with output such as
```python
    def test_gaussianrs_detector_space_intensity_calculator(data):
        algorithm = IntensityCalculatorFactory.create(
            data, detector_space=True, deconvolution=False
        )
    
        reflections = flex.reflection_table_to_list_of_reflections(data.reflections)
    
        errors = 0
        for r in reflections:
            try:
>               algorithm(r, [])
E               RuntimeError: dials Internal Error: /scratch/jenkins_agent/workspace/dials_test_linux_python3/build_dials/modules/dials/algorithms/profile_model/gaussian_rs/transform/transform.h(950): DIALS_ASSERT(fraction <= 1.0) failure.
```

Tests can be run with
```bash
$ pytest test/algorithms/integration/test_parallel_integrator.py::test_gaussianrs_detector_space_{intensity_calculator,with_deconvolution_intensity_calculator{,2}}
```

Since these tests rely on dials_regression they are not run on Azure, which is why the Azure build appears to be happy.

It looks like this was triggered by environment changes. My existing developer build works, but a newly created one fails.

**Comment by ndevenish** [comment]
From the Jenkins log, the base "3 Linux installer Conda3" log for the environment changes October 14th → October 15th
https://gist.github.com/ndevenish/5078fbac6fc31c8e33ee77180606d452/revisions.

Looks like a GCC version changed?

**Comment by ndevenish** [comment]
Ah yes, https://conda-forge.org/docs/user/announcements.html

> 2020-10-08
> Compiler Upgrade to GCC 9.3.0
> 
> We will be upgrading all GCC-based compilers to version 9.3.0 on all platforms. This upgrade will not affect C or C++ code, but will require a rebuild of all feedstocks that use FORTRAN due to a change in the SONAME. During this rebuild, we will keep the old compiler versions in production, temporarily doubling the build matrix. Once the migration is deemed complete, these old compiler versions will be removed.

**Comment by ndevenish** [comment]
Error coming from https://github.com/dials/dials/blob/7417272c0a119adf098fd2003277cfe62563036e/algorithms/profile_model/gaussian_rs/transform/transform.h#L949-L950

I added a
```C++
std::cout << "Fraction: " << fraction << ", " << fraction-1.0 << std::endl;
```
and are getting for the tests
```
FFraction: 1, 1.40332e-13
FFraction: 1, 1.05027e-13
```
So something something float handling is as far as I've gotten for now.
