### ISSUE TITLE
Reading Eiger data: are we casting twice?

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#148]
from format/nexus.py:

```
  def __getitem__(self, index):
    from scitbx.array_family import flex
    import numpy as np
    d = self.lookup[index]
    i = index - self.offset[d]
    data = self.datasets[d][i,:,:]
    if data.dtype == np.uint16:
      data = data.astype(np.uint32)
    return flex.int(data)
```

are we casting from uint16 to uint32 to int32? May be expensive for 16 Mpix images - better to have a constructor for flex.int which can take uint16?

**Comment by graeme-winter** [comment]
Looks like flex.int could take ushort as input anyways? could be more efficient....

**Comment by graeme-winter** [comment]
Turns out no... confused.

**Comment by graeme-winter** [comment]
only if BOOST_ADAPTBX_TYPE_ID_SIZE_T_EQ_UNSIGNED_SHORT is defiined?

**Comment by graeme-winter** [comment]
OK, short version - we should probably avoid going through numpy / h5py here & go directly to the HDF5 file to avoid so much casting. This casting can take 30s in total for 1800 9M images...

**Comment by graeme-winter** [comment]
[citation needed]

```
Mon Jun  6 10:03:29 2016    dials_find_spots_profile.out

         1616924 function calls (1614805 primitive calls) in 897.166 seconds

   Ordered by: internal time
   List reduced from 2416 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1800  519.349    0.289  519.354    0.289 /dials/algorithms/spot_finding/threshold.py:106(__call__)
     1800  195.363    0.109  307.773    0.171 /cctbx_project/dxtbx/imageset.py:513(get_corrected_data)
     1879   41.746    0.022   42.166    0.022 /python2.7/site-packages/h5py/_hl/dataset.py:337(__getitem__)
     1801   31.777    0.018   31.777    0.018 {method 'astype' of 'numpy.ndarray' objects}
     1801   29.994    0.017  103.881    0.058 /cctbx_project/dxtbx/format/nexus.py:1105(__getitem__)
     1800   21.698    0.012  541.082    0.301 /dials/extensions/kabsch_spotfinder_threshold_ext.py:85(compute_threshold)
     1800   19.849    0.011  881.150    0.490 /dials/algorithms/spot_finding/finder.py:65(__call__)
     3600   11.929    0.003   11.929    0.003 /dials/algorithms/spot_finding/finder.py:106(<genexpr>)
        1    9.714    9.714  890.879  890.879 /dials/algorithms/spot_finding/finder.py:223(__call__)
     1801    3.894    0.002  107.775    0.060 /cctbx_project/dxtbx/format/FormatHDFEigerNearlyNexus.py:341(get_raw_data)
```

**Comment by graeme-winter** [comment]
This was the top 10 bad boys from 1800 image spot finding with one thread.

**Comment by biochem-fan** [comment]
Hi Graeme,

I agree that we should read directly into a flex array in the long term, but did you try h5py's `read_direct` method? It sounds promising.

http://docs.h5py.org/en/latest/high/dataset.html
> Read from an HDF5 dataset directly into a NumPy array, which can avoid making an intermediate copy as happens with slicing. The destination array must be C-contiguous and writable, and must have a datatype to which the source data may be cast. Data type conversion will be carried out on the fly by HDF5.

**Comment by graeme-winter** [comment]
Looking into this now thank you for the pointer

**Comment by graeme-winter** [comment]
OK, tried this but in my hands it did not seem to make a lot of difference with the data coming off disk - I will keep on this track though as it is almost certainly a better route to take in the longer term.

**Comment by phyy-nx** [comment]
Hi folks for what it's worth, this line in nexus.py, where data is a numpy
array, incurs a copy:
  data_as_flex = flex.int(data)

The relevant code is scitbx/array_family/boost_python/numpy_bridge.cpp

  template <typename SourceType, typename TargetType>
  void
  copy_data_with_cast(
    std::size_t n,
    SourceType const* s,
    TargetType* t)
  {
    for(std::size_t i=0;i<n;i++) {
      t[i] = static_cast<TargetType>(s[i]);
    }
  }

which is invoked by versa_flex_from_numpy_array in the same file.

Instantiating flex arrays from numpy arrays happens a lot in xfel land so
this affects serial crystallography too.  Wouldn't surprise me if there
were other dxtbx/iotbx format/detectorbase classes that do this as well.

-Aaron

On Jun 27, 2016, at 7:54 AM, Graeme Winter <notifications@github.com> wrote:

OK, tried this but in my hands it did not seem to make a lot of difference
with the data coming off disk - I will keep on this track though as it is
almost certainly a better route to take in the longer term.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dials/dials/issues/148#issuecomment-228770198>, or mute
the thread
<https://github.com/notifications/unsubscribe/AM2OypojY4yuFz5zBLJIDrDjjVc1GQiTks5qP-RBgaJpZM4IuxvG>
.

**Comment by graeme-winter** [comment]
Very likely that we cannot actually avoid this however if we can limit the # of transmogrifications of the data to exactly one that would be a winner...

**Comment by graeme-winter** [comment]
(in other news, a tool to track what we actually do to the image data would be damn useful)

**Comment by jmp1985** [comment]
We now extract data from HDF5 dataset directly into a flex array.

**Comment by graeme-winter** [comment]
This is a good thing to do for future proofing the DIALS code however it sadly does not seem to make much of a performance improvement...

```
[gw56@cs04r-sc-com99-03 dials]$ grep Time\ Taken dials.find_spots.{sav,par,log}
dials.find_spots.sav:Time Taken: 52.699111
dials.find_spots.par:Time Taken: 43.469710
dials.find_spots.log:Time Taken: 44.626107
```

best speedup came from the shoebox work...

**Comment by graeme-winter** [comment]
Looking at the same data as CBF files for comparison, looks like that may still be faster... though also benefitted from the work described above:

```
[gw56@cs04r-sc-com99-03 dials-cbf]$ grep Time\ Taken dials.find_spots.{sav,log}
dials.find_spots.sav:Time Taken: 43.736441
dials.find_spots.log:Time Taken: 37.022480
```

Looks like we can average 20 frames/s on a 20 core node => need to check how this scales now.
