### ISSUE TITLE
Remove fluff from installers

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#149]
> just downloaded the dials-v1-2-4 installer. Inside matplotlib is about 74MB on Linux, 45MB of which is in a directory called "tests"

investigate.

**Comment by dagewa** [comment]
Graeme suggested modules/dials/test/data/sim_mx could be trashed too - or moved to e.g. dials_regression if a test depends on it

**Comment by dagewa** [comment]
25 MB in modules/cbflib/doc

**Comment by graeme-winter** [comment]
that can go :)

**Comment by dagewa** [comment]
base/share/gtk-doc is also 25 MB

**Comment by Anthchirp** [comment]
result:
dials-linux-x86_64.tar.gz:	 284.88 MB -> 239.85 MB (-15.8%)
dials-linux-x86_64.tar.xz: 176.67 MB -> 142.19 MB (-19.5%)

**Comment by Anthchirp** [comment]
..unfortunately this effort was more than offset by recent dependency updates.
Current 1.3 release candidate:
dials-v1-dev-538-linux-x86_64.tar.xz: 192.57 MB (+35%)
