### ISSUE TITLE
dials.export format=mtz: don't throw away summation integrated values if profile fitting failed

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#15]

**Comment by jmp1985** [comment]
I've added a potential fix to a new branch "fix_export"

**Comment by graeme-winter** [comment]
Thanks James, some instructions on best practice for branch usage for
oldsters would be ++ welcome ;o)

**Comment by jmp1985** [comment]
Hi Graeme,

To use the fix you would do the following:

git checkout fix_export

Then, any changes you make to dials will be within the “fix_export” branch. If you do “git push” from here you will only push changes from this branch back to github. Doing “git push –all” will push changes from all branches.

To go back to the master branch do the following:

git checkout master

If you want to “rebase” the fix_export branch back to master then do the following:

git checkout fix_export
git rebase master

James

**Comment by jmp1985** [comment]
OK, I've added a parameter "ignore_profile_fitting=True/False" so we can keep summation results in the case that profile fitting fails for all reflections. Not very elegant. We need to revisit what we should keep/throw away in export.

**Comment by jbeilstenedmands** [comment]
With the updated code, if no reflections have profile fitted intensities, the following Sorry exception is raised:
"Sorry: No reflections found with both prf and sum intensities, try selecting a different filtering option - sum perhaps?"
I might improve the message, but I believe this behaviour is sufficient to close this issue? Or do we want dials.export to go ahead automatically and only export sum in this case without the user having to run another export job with intensity=sum?
