### ISSUE TITLE
dials.find_spots should use a chunksize commensurate with #cores and #images

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#150]
i.e. chunksize=auto by default such that nframes / (ncores*chunksize) is integer (i.e. no remainder)

**Comment by graeme-winter** [comment]
Agree with RG that this should be fixed in DIALS principally, will copy results in but it can make a big difference to the time taken to find spots....

**Comment by graeme-winter** [comment]
```
10 Time Taken: 80.592925
20 Time Taken: 77.165398
30 Time Taken: 68.305521
40 Time Taken: 82.535501
50 Time Taken: 70.923461
60 Time Taken: 82.675676
70 Time Taken: 91.532685
80 Time Taken: 100.463441
90 Time Taken: 65.609781
```

chunk size for 1800 frames / 20 cores

**Comment by graeme-winter** [comment]
```
10 Time Taken: 67.411552
20 Time Taken: 67.646297
30 Time Taken: 61.639138
40 Time Taken: 76.718679
50 Time Taken: 66.580639
60 Time Taken: 78.578976
70 Time Taken: 87.189984
80 Time Taken: 95.329265
90 Time Taken: 60.818384
```

same for CBF files - some scope for usefulness here

**Comment by graeme-winter** [comment]
![cs](https://cloud.githubusercontent.com/assets/1241716/15863673/d9d5ce42-2ccb-11e6-8407-95bced8ccaba.png)

**Comment by graeme-winter** [comment]
30, 90 chunk size up to 30% faster than suboptimal combinations.

**Comment by rjgildea** [comment]
The current solution has the side effect of removing the intermediate printing of progress:

```
Found 788 strong pixels on image 1
Found 731 strong pixels on image 2
Found 712 strong pixels on image 3
Found 716 strong pixels on image 4
Found 743 strong pixels on image 5
Found 885 strong pixels on image 6
Found 871 strong pixels on image 7
Found 862 strong pixels on image 8
Found 862 strong pixels on image 9
etc...
```

E.g. spotfinding on 4000 image sweep with nproc=8, chunksize=auto sets chunksize=500 -> no output for a very long time!

```
$ dials.find_spots datablock.json nproc=8
DIALS 1.dev.343-g71311a5
The following parameters have been modified:

spotfinder {
  mp {
    nproc = 8
  }
}
input {
  datablock = datablock.json
}

Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------


Finding spots in image 1 to 4000...
Setting chunksize=500
Extracting strong pixels from images
 Using multiprocessing with 8 parallel job(s)
```

**Comment by graeme-winter** [comment]
Acknowledged. Suggest what then - using a chunksize which is factor of N smaller such that it comes out around (say) 50, or no less than 50?

**Comment by graeme-winter** [comment]
Is this really such a problem? Could warn() if chunksize > 50 say?

**Comment by rjgildea** [comment]
I believe it was you that requested this intermediate output ;-)

**Comment by graeme-winter** [comment]
Indeed... could still output something perhaps in a file read perhaps ... ?

**Comment by rjgildea** [comment]
From your plot not much difference in speed as long as `nimg%(chunksize*nproc) == 0`? Therefore set chunksize = smallest integer > (say) 20 where `nimg%(chunksize*nproc) == 0`?

**Comment by jmp1985** [comment]
Just an additional comment. Increasing the chunk size also has the effect of increasing the amount of data returned by each process. I'm in favour of keeping intermediate output if possible. @rjgildea's suggestion seems reasonable.

**Comment by graeme-winter** [comment]
OK, please feel free to make the commits :)

**Comment by jmp1985** [comment]
Algorithm used as follows

```
  def _compute_chunksize(self, nimg, nproc, min_chunksize):
    from math import ceil
    chunksize = int(ceil(nimg / nproc))
    remainder = nimg % (chunksize * nproc)
    test_chunksize = chunksize-1
    while test_chunksize >= min_chunksize:
      test_remainder = nimg % (test_chunksize * nproc)
      if test_remainder <= remainder:
        chunksize = test_chunksize
        remainder = test_remainder
      test_chunksize -= 1
    return chunksize

```
