### ISSUE TITLE
dials.image_viewer show mask does not work with stacked images

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1512]
Just makes a mess
![Screenshot from 2020-12-04 15-10-30](https://user-images.githubusercontent.com/11502083/101180118-13555400-3643-11eb-832b-f30c20799e9f.png)

**Comment by graeme-winter** [comment]
Verified

Since I added the `stack` option (I _think_) I will see if I can fix it

**Comment by graeme-winter** [comment]
Behaviour question: should the mask be _and_ or _or_ i.e. if showing mask across `N` images should the mask show pixels which are masked in _any_ of the images or only pixels which are masked in _all_ images.

**Comment by rjgildea** [comment]
I would say the former, i.e. pixels which are masked in _any_ of the images, since the summed counts include the contribution of some counts that were marked as questionable (i.e. masked).

**Comment by biochem-fan** [comment]
I investigated this issue.

`dials.image_viewer` replaces masked pixels with `MAX_VAL` in `mask_image_data`, which is "[minimum value for an int](https://github.com/dials/dials/blob/main/src/dials/util/image_viewer/slip_viewer/frame.py#L26)".
On top of this, more frames are added in `stack_images`.

As the first step, calling `mask_image_data` again shows the mask for the first frame.

```diff
diff --git a/src/dials/util/image_viewer/spotfinder_frame.py b/src/dials/util/image_viewer/spotfinder_frame.py
index 56e7304e1..a6aef04b6 100644
--- a/src/dials/util/image_viewer/spotfinder_frame.py
+++ b/src/dials/util/image_viewer/spotfinder_frame.py
@@ -1109,6 +1111,8 @@ def stack_images(self):
             if mode == "mean":
                 image_data = tuple(i / self.params.stack_images for i in image_data)
 
+            if self.params.show_mask:
+                self.mask_image_data(image_data)
             # Don't show summed images with overloads
             self.pyslip.tiles.set_image_data(image_data, show_saturated=False)
```

I haven't figured out how to implement mask merging. After that, I will make a PR.
