### ISSUE TITLE
Speeding up multi-lattice indexing

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1518]
Multi-lattice indexing is cumulative, so that each time new lattices are found the whole set of lattices are refined. When there are many lattices, this leads to long refinement jobs because of the growing number of parameters. For example, the first refinement job for a C2 lattice has 14 parameters. Each additional lattice adds 7 parameters to refinement, but the NLLS runtime scales with the square of the number of parameters (in fact it is worse than that, because the number of reflections in refinement increases too).

It seems unnecessary to refine the previously-found crystal models every time a new crystal is added. Perhaps this should only be done if the set of reflections assigned to that crystal changes (significantly?).

It is also probably unnecessary to refine the detector and beam models in every single refinement job. A final refinement job could be performed once all models are found that refines every available parameter against every available reflection.

**Comment by rjgildea** [comment]
All crystal models are re-indexed at each iteration, because they potentially previously indexed reflections that were actually better modelled by another lattice. Therefore I think that it probably is necessary to re-refine all crystal models at each step.

**Comment by rjgildea** [comment]
I suspect that the reflections assigned to each crystal will almost always vary between rounds of indexing - for example, each round of indexing will presumably start at a lower resolution and gradually increase the resolution of reflections included as it progresses through the macrocycles.

Could you use a reference detector/beam from another dataset (or single indexing job) and then fix the detector/beam model for multi-lattice indexing? How much of a performance benefit does this actually have in practice?

**Comment by dagewa** [comment]
Much to my surprise, the current runtime of `dials.index` scales almost linearly with `max_lattices=`, for the case I was looking at.
![index_times](https://user-images.githubusercontent.com/11502083/101900274-1f8f6300-3ba7-11eb-9fa6-13a3d3aedb90.png)
The N^2 dependence on parameters does not appear to be the dominant factor, so it seems this is not worth pursuing.
