### ISSUE TITLE
index restricted by part of images

### ISSUE THREAD

**Issue by lijunliuks** [dials/dials#1529]
Only a part of images may be used in the INDEX step, knowing multiple lattices exist.  For example, having one swipe of  images 1-720.  Using image_range=1,320 worked.  However, the rest of images were sure to be useful.  Any way to expand the matrices indexed  from 1-320 to the whole range of 1-720 to get the whole dataset indexed then integrated?  Since the presence of multiple lattices, try to avoid dividing datasets into several subsets/sun-swipes.  Thanks.

**Comment by graeme-winter** [comment]
What you can do is this:

```
dials.index imported.expt strong.refl image_range=1,320
dials.index indexed.expt strong.refl
```

The former will determine the orientation matrix etc. then the latter will use this matrix to index all of the reflections in the input list.

Does this do what you wanted?

**Comment by dagewa** [comment]
Closing on the assumption that the reply did indeed do what the OP wanted
