### ISSUE TITLE
Allow dials.import to generate a mask using dials.util.masking PHIL parameters

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#1544]
At present,
- the PHIL scope of `dials.find_spots` exposes the `dials.util.masking.phil_scope`,
- the PHIL scope of `dials.integrate` exposes the `dials.util.masking.phil_scope`,
- the PHIL scope of `dials.import` does not expose the `dials.util.masking.phil_scope`, though it includes an option `mask` so that you can supply a mask that you've created with `dials.generate_mask`, which uses the `dials.util.masking` PHIL scope.

It would be nice if `dials.import` could make a mask itself from valid `dials.masking.phil_scope` parameters.

**Comment by benjaminhwilliams** [comment]
Hmm... on consideration, maybe I'm misinterpreting how masking in DIALS is supposed to work.  I think it's sufficient to follow `dials.import` with `dials.generate_mask` for cases where a user-defined mask should apply throughout.

**Comment by graeme-winter** [comment]
@benjaminhwilliams though you have closed this PR I am certain that you have learned something in the process which should probably be documented somewhere. I don't know if we have a place where a few words on the topic of masking could go, but it seems like the newly gained insight you have should go there 🙂

Am pretty sure if you have questions others will
