### ISSUE TITLE
dials.image_viewer coordinate offset

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1545]
I'm pretty sure we've been here before, but I'm also fairly sure this was fixed at some point. Currently, the mouse pointer has an offset of about half a pixel (maybe exactly half) when displaying the intensity read out in the bottom status bar. Here's an example using `X4_wide_M1S4_2_0001.cbf`. The cursor is inside the masked region and should show intensity = -1, but instead the intensity of the pixel to the left is displayed.

![image_viewer_offset](https://user-images.githubusercontent.com/11502083/104594737-7e923d00-5669-11eb-8aa1-47f520ff707d.png)

This is really annoying when you notice, and plainly misleading when you don't.

**Comment by dagewa** [comment]
Yes, I was right, it _did_ work in the past. It still works in CCP4's version (`DIALS 2.2.10-g6dafd9427-release`). So this is a relatively recent regression, or a difference between the 2 and 3 series.

Note here the cursor is right up at the border inside the mask, and the intensity correctly still shows -1
![image_viewer_ccp4](https://user-images.githubusercontent.com/11502083/104597917-d468e400-566d-11eb-87ef-03ea174fbe12.png)

**Comment by phyy-nx** [comment]
IIRC this is a difference between single and multipanel images.  In other words, i think if you load a single panel image it still looks right.

**Comment by phyy-nx** [comment]
Nope, wrong on single panel images too.  EG dials_regression/ALS_831/q315r_lyso_001.img

**Comment by graeme-winter** [comment]
Would guess that this came back when the laboratory frame changes went in (e.g. image viewed at small offset etc.)

**Comment by dagewa** [comment]
Ah, does this refer to an implicit "snap to orthogonal" feature for small rotations? It wasn't clear to me that had gone in. I must say I find that behaviour confusingly opaque. I would much rather have this under the control of an explicit checkbox (with snapping switched on by default). But that's a topic for a different ticket (if only I could find it).

**Comment by dagewa** [comment]
Had a go at fixing this the other day. Failed.

**Comment by phyy-nx** [comment]
Commenting to remove the stale label and tagging @voklejas2 who may have looked at this recently

**Comment by elena-pascal** [comment]
For documentation purposes, removing the `-0.5` from [this line](https://github.com/dials/dials/blob/main/src/dials/util/image_viewer/slip_viewer/frame.py#L450-L452) fixes the offset between the cursor position and the read cursor position. It also fixes #2190. But I don't know why because I don't know what the line is trying to achieve in the first place.
