### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1546]
GitHub has now rolled out their mechanism for seamlessly renaming the branch, and migrating issues and pull requests: https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories-

Therefore, we can now do this. This repository and pull requests will be automatically migrated. Any developer installs will have to be manually migrated. GitHub's instructions for the branch rename propose:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
which will apparently show as a notification to users of the repository. We could put in something more complicated but I think although the target developers for dials is larger than xia2 that it's not worth doing for a once-off change and in a worst case re-bootstrapping is acceptable. Bootstrapping files will have to change, but should transparently work after a rename anyway.

In DIALS Core [Meeting 2020-10-01](https://dials.github.io/kb/core/20201001#renaming-master-branch--main) it was apparently decided that DIALS/dxtbx should be migrated two weeks after xia2: https://github.com/xia2/xia2/issues/557. If my proposed schedule is accepted, this will mean we make this change on 1st February.

**Comment by dagewa** [comment]
> 1st February

Do I need to do anything yet to my developer installs?

**Comment by Anthchirp** [comment]
No.
When we reach the point where you need to so something it will be very obvious and instructions will be provided.

**Comment by ndevenish** [comment]
I think the xia2 transfer raised a couple of issues that we'd need to deal with in order to make the transition smooth

**Comment by phyy-nx** [comment]
Could the Jenkins emails that track commits in dials and dxtbx be updated to track commits on main instead of master?  Or has this been done already?  Thanks!

**Comment by phyy-nx** [comment]
And by that I mean the jiscmail emails :)

**Comment by Anthchirp** [comment]
Well spotted. Emails (plus backlog) should be coming through again shortly.
