### ISSUE TITLE
dials.image_viewer threshold map should not respond to brightness

### ISSUE THREAD

**Issue by dagewa** [dials/dials#156]
At some point viewing the threshold map in dials.image_viewer became more difficult because the brightness of strong pixels is controlled by the brightness slider. As I understand it, the threshold map is binary and therefore should always be displayed in black/white if the 'grayscale' or 'invert' colour schemes are selected for maximum contrast.

With the default grayscale and brightness of 100 the strong pixels are very hard to pick out. This was flagged as a bug by users during the DESY workshop.

![light_spots](https://cloud.githubusercontent.com/assets/11502083/16114623/22a56f20-33ba-11e6-97f8-62f98f577864.png)

**Comment by Anthchirp** [comment]
Probably caused by fix to #55, https://sourceforge.net/p/cctbx/code/24040/ then.

**Comment by dagewa** [comment]
Hmm yes. The fix seems appropriate for diffraction images, but less so for viewing a truly binary image like the threshold map

**Comment by Anthchirp** [comment]
looks fixed to me

**Comment by dagewa** [comment]
yes, looks good now, thanks

-- David
