### ISSUE TITLE
Strange logic in FormatHDFEigerNearlyNexus.py

### ISSUE THREAD

**Issue by dagewa** [dials/dials#157]
At the moment this format erroneously recognises the [X-Spectrum LAMBDA](http://www.x-spectrum.de/) detector at PETRA III's P14 beamline. The logic for understanding an image appears to be

1) It is HDF5, containing entry
2) entry has attribute 'NX_class', which is equal to 'NXentry'
3) entry does *not* contain the key 'definition'
4) entry contains the key 'instrument'

The .nxs example file in dials_regression/image_examples/putative_imgCIF_HDF5_mapping has 'definition' in entry, so is correctly not recognised here. But any other nexus file that does satisfy (1)-(4) will be loaded by FormatEigerNearlyNexus, which is what happens with the LAMBDA dataset.

**Comment by jmp1985** [comment]
Hi David,

So this is a problem; however, it wasn't obvious to me how to otherwise determine that the file was a non-conforming Eiger Nexus file.

James

________________________________

**Comment by biochem-fan** [comment]
Hi James,

What about looking at /entry/instrument/detector/description?
It should contain "Dectris Eiger 16M" (or 9M or 4M).

**Comment by dagewa** [comment]
>>> 'Dectris Eiger' in entry['instrument']['detector']['description'].value
True

works for the two datasets I have my hands on. Thanks! I will add the relevant condition to the format.
