### ISSUE TITLE
phenix dispatchers in dials release

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1576]
e.g.
```
$ wget https://github.com/dials/dials/releases/download/v3.3.2/dials-v3-3-2-linux-x86_64.tar.xz
$ tar xf dials-v3-3-2-linux-x86_64.tar.xz
$ cd dials-installer/
$ ./install --prefix=..
$ . ../dials-v3-3-2/dials_env.sh
$ phenix.<tab>
Display all 105 possibilities? (y or n)
```
(reported by Aaron)

**Comment by graeme-winter** [comment]
Pretty sure we _used_ to strip them out right?

**Comment by dagewa** [comment]
They are not supposed to be created in the first place
https://github.com/dials/dials/blob/master/installer/bootstrap.py#L1015

**Comment by ndevenish** [comment]
They aren't supposed to be generated at all with `--skip_phenix_dispatchers`, which apparently we are passing (and don't show on my development install)

**Comment by graeme-winter** [comment]
I'll wager side-effect of upstream change 🤔

**Comment by ndevenish** [comment]
It's apparently unset rather than ignored:
```
$ libtbx.show_env build/libtbx_env | grep skip
                   'skip_phenix_dispatchers': False,
```

**Comment by dagewa** [comment]
Billy suggested that `--skip-phenix-dispatchers` would need adding to [`reconfigure`](https://github.com/dials/dials/blob/7cfb6ec791614a68fb5b129f5f039fe398bce39d/installer/dials_installer.py#L63)
