### ISSUE TITLE
sequence_to_stills.py unable to expand scan-static files

### ISSUE THREAD

**Issue by PrinceWalnut** [dials/dials#1610]
`sequence_to_stills.py` should be able to generate stills from scan-static files. Presently, because of the use of `experiment.crystal.get_A_at_scan_point(SCAN_POINT)`, scan-static experiments cannot be expanded into stills. 

The traceback from attempting to do this:

`Traceback (most recent call last):
  File "/home/rahewitt/dials/build/../modules/dials/command_line/sequence_to_stills.py", line 233, in <module>
    run()
  File "/home/rahewitt/dials/conda_base/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/rahewitt/dials/build/../modules/dials/command_line/sequence_to_stills.py", line 224, in run
    (new_experiments, new_reflections) = sequence_to_stills(
  File "/home/rahewitt/dials/build/../modules/dials/command_line/sequence_to_stills.py", line 118, in sequence_to_stills
    * matrix.sqr(experiment.crystal.get_A_at_scan_point(i_scan_point))
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /home/rahewitt/dials/modules/dxtbx/model/crystal.h(547): DXTBX_ASSERT(index < A_at_scan_p
oints_.size()) failure.`
                                                              
`

**Comment by dagewa** [comment]
This seems to work now:
```
$ dials.sequence_to_stills indexed.expt indexed.refl 
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Converting experiment 0 images 0 to 45 to stills
Re-predicting reflection centroids
Generating experiment identifiers
Saving stills experiments to stills.expt
Saving stills reflections to stills.refl
```
