### ISSUE TITLE
Option parser thinks reflection pickles are experiments

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1618]
They are not, they are reflections - see #1616 as a manifestation of the problem

**Comment by graeme-winter** [comment]
Is this to do with "image pickles" I wonder 🤔

**Comment by phyy-nx** [comment]
Dunno, but possible!  For testing, there is an old image pickle in dials_regression that still works: image_examples/LCLS_CXI/shot-s04-20111204004533388.pickle

**Comment by graeme-winter** [comment]
If we have "reflection data are pickle" and "image data are pickle" but we are no longer exporting reflection data as pickle then we are _probably_ OK -> closing
