### ISSUE TITLE
Refine: interval_width_degrees=Auto would be useful

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#162]
i.e. to avoid 

```
Sorry: Too few reflections to parameterise Crystal1 unit cell
Try modifying refinement.parameterisation.auto_reduction options
```

for data with small unit cell

this case setting = 60 worked

alt: explain #parameters used so we can estimate externally right #intervals to use

**Comment by dagewa** [comment]
My intention is to solve this and #158 at the same time by performing an analysis of the input residuals. With a measure of what frequency of change is required to sufficiently model real changes, then the degree of smoothing can be set appropriately, as well as the block width over which reflections can be assumed to come from the same model for outlier rejection.

**Comment by graeme-winter** [comment]
Sounds like a nice solution :+1:

**Comment by rjgildea** [comment]
@dagewa issue #158 appears to have been resolved, but this is still open - is there now an interval_width_degrees=Auto option?

**Comment by dagewa** [comment]
almost... the code is there to do the calculation, but I have not been able to test it on lots of datasets to make sure it gives sensible results

**Comment by dagewa** [comment]
Example starting from data created by xia2_regression test `xia2_regression.X4_wide.dials`:

```
dials.refine  '9_refined_experiments.json' '9_refined.pickle' 'scan_varying=True' 'close_to_spindle_cutoff=0.020000' 'outlier.algorithm=auto' 'output.experiments=junk.json' 'output.reflections=junk.pickle' 'reflections_per_degree=100' 'unit_cell.smoother.interval_width_degrees=Auto' 'orientation.smoother.interval_width_degrees=Auto' debug_centroid_analysis=True
dev.dials.plot_centroid_analysis centroid_analysis_reflections.pickle
```
**x-residual analysis**
![x-residual-analysis](https://user-images.githubusercontent.com/11502083/27386357-7a761050-568d-11e7-8ee5-2424c2c73fd6.png)
**y-residual analysis**
![y-residual-analysis](https://user-images.githubusercontent.com/11502083/27386361-7fa9ef60-568d-11e7-8d69-3a8cb1d65802.png)
**phi-residual analysis**
![phi-residual-analysis](https://user-images.githubusercontent.com/11502083/27386368-83c323a0-568d-11e7-9d84-f85577569f88.png)

In this case, the narrowest interval width is determined for the x-residual analysis, so this is the value that will be set for scan-varying refinement. Red lines are at frequencies corresponding to 54, 36 and 18 degrees.

**Comment by dagewa** [comment]
Note that `tst_centroid_analysis.py` is now moved to [dials_scratch](https://github.com/dials/dials_scratch/blob/master/dgw/centroid_analysis/tst_centroid_analysis.py)

**Comment by rjgildea** [comment]
I believe interval_width_degrees=auto is an option (but not default). @dagewa can this issue now be closed?

**Comment by rjgildea** [comment]
I believe interval_width_degrees=auto is an option (but not default). @dagewa can this issue now be closed?

**Comment by dagewa** [comment]
Yes, the option now exists (but isn't yet as useful as hoped).
