### ISSUE TITLE
Profile fitting issues for reflections in panel gaps.

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#1638]
Following on from #1297, we now integrate reflections that have part of their intensity in the panel gaps, however I have found that the profile fitting seems to be not working well in this case. This has become apparent in some datasets I've been processing, where I am seeing many profile fitted intensities being given zero or near zero intensities, but being marked as successfully profile fitted with the `integrated_prf` flag.

I tried to simulate this using some ideas from the `test_profile_fitting.py` code. To simulate a reflection moving into a panel gap, I simulated a `13x13x13` pixel box, with a gaussian centred at `6,6,6` with width `2,2,2`, progressively masking a region of the pixel box to simulate an edge (code example below). Plotted below is the ratio of the fitted to true intensity for a number of rows of the box that are masked, repeated 1000 times over random seed values for the poisson noise.

![Intensity_variation](https://user-images.githubusercontent.com/30625594/112855209-82e5c800-90a6-11eb-90e9-1f417d59540b.png)

And here are a few histograms of the same data.
One row masked (vast majority within 1% so good):
![histogram_1](https://user-images.githubusercontent.com/30625594/112855640-ecfe6d00-90a6-11eb-9678-5ab5a146dc5d.png)

Three rows masked (starting to see larger variability):
![histogram_3](https://user-images.githubusercontent.com/30625594/112855703-f982c580-90a6-11eb-8384-d65354e8e7c2.png)

Six rows masked (significant variability):
![histogram_6](https://user-images.githubusercontent.com/30625594/112855744-02739700-90a7-11eb-8ffc-9ddb4abec9f8.png)

Eleven rows masked, highly unreliable, here you can see that some fits are given zero intensity:
![histogram_11](https://user-images.githubusercontent.com/30625594/112855772-0bfcff00-90a7-11eb-8375-1231c8ad4806.png)

Picture of a real reflection where this occurs:
![Screenshot_panelgap](https://user-images.githubusercontent.com/30625594/112857292-9bef7880-90a8-11eb-912a-57defa2f86c2.png)

FWIW I'm not suggesting reverting #1297 as I think we should be integrating cases where there are only a few masked pixels and the tests from that PR show that there is only small bias for a low number of masked pixels. However maybe we should be setting limits on how far into a panel gap a reflection can go before the fit is unreliable, and assigning a higher uncertainty for these cases.

Code:
```
from dials.test.algorithms.integration.profile.test_profile_fitting import add_poisson_noise, gaussian

import numpy as np
import matplotlib.pyplot as plt

from dials.algorithms.integration.fit import ProfileFitter
from dials.array_family import flex


def test_fit():
    intensities = flex.double()
    edge_values = flex.int()
    p = gaussian((13, 13, 13), 1, (6, 6, 6), (2, 2, 2))
    s = flex.sum(p)
    p = p / s
    initial = 1.0
    for x in range(0, 1000):
        np.random.seed(x)

        c = add_poisson_noise(100 * p)

        for n in range(0, 12):
            edge_values.append(n)

            b = flex.double(flex.grid(13, 13, 13), 0)
            m = flex.bool(flex.grid(13, 13, 13), True)
            for i in range(0, n):
                for j in range(0, 13):
                    for k in range(0, 13):
                        m[i, j, k] = False

            # Fit
            fit = ProfileFitter(c, b, m, p)
            intensity = fit.intensity()
            if n == 0:
                initial = intensity[0]
            V = fit.variance()
            assert fit.niter() < fit.maxiter()
            intensities.append(intensity[0] / initial)

    for n in range(1, 12):
        sel = (edge_values == n)
        y = intensities.select(sel)
        plt.figure()
        plt.hist(y, bins=20)
        plt.savefig(f"histogram_{n}.png")

    plt.figure()
    plt.scatter(edge_values, intensities)
    plt.xlabel("Rows masked")
    plt.ylabel("I(fit) / I(True)")
    plt.savefig("Intensity_variation.png")

if __name__ == "__main__":
    test_fit()
```

**Comment by graeme-winter** [comment]
Interesting - I have seen several cases in recent history where summation integration gives far fewer reflections but those reflections are substantially "better" -> I can't help but think these ideas are related. They were also unsurprisingly on multi-panel detectors, in this case with rather small pixels.

**Comment by dagewa** [comment]
Profile fitting is like a weighted sum, where the strong pixels are given greatest weight. I would think profile fitting would be very unreliable in any situation in which the strongest pixels are masked. I think we should ensure at least that the predicted centroid pixel is inside the non-masked region.

**Comment by jbeilstenedmands** [comment]
Further observations. I believe the expected intensity for the reflection above is 100. If the expected intensity is changed to 10000, then the fit variability is reduced as expected:
![Intensity_variation](https://user-images.githubusercontent.com/30625594/112862432-a82a0480-90ad-11eb-85f0-ca4fb2190653.png)
Interestingly you can also see an effect in the correlation to the 'reference' profile (which is the noiseless case here):
For I = 10000:
![correlation](https://user-images.githubusercontent.com/30625594/112862570-d1e32b80-90ad-11eb-9866-2a88a4edea81.png)
For I = 100:
![correlation](https://user-images.githubusercontent.com/30625594/112862732-f808cb80-90ad-11eb-8b8b-d95843d3c9f2.png)

So the correlation could act as another handle on identifying this issue.

**Comment by biochem-fan** [comment]
> I think we should ensure at least that the predicted centroid pixel is inside the non-masked region.

Don't we have something equivalent to [`MINPK`](https://xds.mr.mpg.de/html_doc/xds_parameters.html#MINPK=) in another program?

**Comment by jbeilstenedmands** [comment]
This should have been largely addressed by the linked PR, so closing this issue now.
