### ISSUE TITLE
eltbx.attenuation_coefficient treats composite materials as "elements"

### ISSUE THREAD

**Issue by dagewa** [dials/dials#164]
A cctbx issue really, but probably exists because of DIALS. The nist_elements class has been extended to handle composite materials, but method names are no longer really appropriate. This code might make chemists feel a bit queasy:

```
>>> from cctbx.eltbx.attenuation_coefficient import nist_elements
>>> elts = nist_elements()
>>> elts.atomic_number('CdTe')
93
>>> elts.atomic_number('GaAs')
94
```

**Comment by graeme-winter** [comment]
So this is logically correct in the *structure* of the method, just has a bad name, please find a better name for this method (which should probably be an alias in first instance) which somehow characterises the idea of “chemical stuff” in place of element which CdTe clearly is not…

Flag on cctbxbb for discussion?

**Comment by rjgildea** [comment]
As far as I can tell the attenuation coefficients were added to cctbx by jmp, so we are privably

**Comment by jmp1985** [comment]
svn blame indicates that I may not be entirely culpable for the CdTe entry

I guess we could have a separate table for compounds and then a higher-leve interface which accesses both from the same class etc.

________________________________

**Comment by graeme-winter** [comment]
Does can blame me? For information. I'd believe yes...

**Comment by dagewa** [comment]
Simple solution, just call them all "materials". Doesn't really matter that some are elements, some are composites, right?

**Comment by rjgildea** [comment]
The X-rays certainly don't care about the distinction ;)

**Comment by graeme-winter** [comment]
Works for me :-)

**Comment by dagewa** [comment]
Closing as this is really an eltbx issue and it seems unlikely that we'll do anything about it
