### ISSUE TITLE
dials.combine_experiments requires reflections

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1658]
At some point in the past, I remember `dials.combine_experiments` being able to work without providing reflections. This is no longer the case (or I imagined it). I think it should be possible to run without providing reflections as it is useful for shuttling models about between experiments. Alternatively, a separate `dials.copy_model` (or something) might be useful.

**Comment by jbeilstenedmands** [comment]
This issue has annoyed me for a while, also related is #1741 . Following yesterday's core meeting, I'll take ownership of this alongside refactoring dials.combine_experiments into library code plus a command line interface.
