### ISSUE TITLE
Image path is not in dials.import.log

### ISSUE THREAD

**Issue by jonathanrd** [dials/dials#1662]
Hi,

I recently wanted to see which images were used to generate a particular integrated.mtz file. I had the the dials logs but nothing else. I checked the dials.import.log but it wasn't particularly helpful:

```
input {
  experiments = <image files>
}
```

I'm sure this line used to show the full path to the images? 

I ran a quick test with the latest dials and it has the same behaviour. The path can be found in the imported.expt file but I think it would be really useful to have the path in the import log too.

Cheers

**Comment by dagewa** [comment]
Agree this would be useful, but I wanted to add that for a more robust mapping between images and MTZ file it would also be useful if this is written to the `dials.export.log`, or whenever else an MTZ file was created (could be `dials.merge.log` too)

**Comment by graeme-winter** [comment]
> Agree this would be useful, but I wanted to add that for a more robust mapping between images and MTZ file it would also be useful if this is written to the `dials.export.log`, or whenever else an MTZ file was created (could be `dials.merge.log` too)

Note in `dials.export` (and indeed, `dials.import`) there can be several sets of images here.

I agree with the premise - particularly in `dials.import` just saying `<image files>` is aggressively unhelpful. 

I suppose something along the lines of:

```
/data1/user/2021-04-19/foobar/foo_bar_1_####.cbf (1...18000)
```

or 

```
/data1/user/2021-04-19/foobar/foo_bar_1.nxs (1...18000)
```

would be easiest way to express...?

**Comment by rjgildea** [comment]
> I suppose something along the lines of:
> 
> ```
> /data1/user/2021-04-19/foobar/foo_bar_1_####.cbf (1...18000)
> ```
> 
> or
> 
> ```
> /data1/user/2021-04-19/foobar/foo_bar_1.nxs (1...18000)
> ```
> 
> would be easiest way to express...?
Or just borrow the xia2 `/foo/bar.nxs:start:end` syntax?

**Comment by graeme-winter** [comment]
> > I suppose something along the lines of:
> > ```
> > /data1/user/2021-04-19/foobar/foo_bar_1_####.cbf (1...18000)
> > ```
> > 
> > 
> > or
> > ```
> > /data1/user/2021-04-19/foobar/foo_bar_1.nxs (1...18000)
> > ```
> > 
> > 
> > would be easiest way to express...?
> > Or just borrow the xia2 `/foo/bar.nxs:start:end` syntax?

Yeh that would work for me. I guess the _best_ way for this to work would be to add an operation to `ExperimentList` which can return these as strings, then use this wherever we want? Could see the same being useful e.g. in `dials.integrate` too if integrating multiplex experiments...

**Comment by rjgildea** [comment]
And given that `dials.export` has already been mentioned, this could perhaps be added to the mtz "history"?

**Comment by graeme-winter** [comment]
<nudge> this one is probably worth doing something with, seems to have fallen off the radar (though could also be more tricky than we would like)

**Comment by graeme-winter** [comment]
@dagewa good point

**Comment by phyy-nx** [comment]
The indices field would be important, especially for HDF5 files where the
experiments represent hits cherry-picked from the whole dataset.
