### ISSUE TITLE
Build directory on Windows is enormous

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1667]
With a DIALS bootstrap on Windows, the resulting `build` directory is enormous. For comparison, the contents of `build/dials` on Linux is 43 M, whereas on Windows it is 701 MB!

Under that directory, the largest single file on Linux is 
```
4.1M	./algorithms/integration/boost_python/parallel_integrator_ext.o
```
on Windows the equivalent object file is `algorithms\integration\boost_python\parallel_integrator_ext.obj`, which is the wrong side of 82 MB.

I suspect this is due to the inclusion of the `/Z7` switch in the builds. Do we have any control over this?

**Comment by Anthchirp** [comment]
Try removing this line:
https://github.com/cctbx/cctbx_project/blob/0b1af689c6a4e8bc5bc85a1b20e741cba1d7adf8/libtbx/SConscript#L392-L393
and see if it makes a difference in size and/or performance

**Comment by dagewa** [comment]
This partly addresses the build size: `build\dials` on Windows is then 247 MB not 701 MB, but still a lot larger than on Linux. I'll look at any performance differences next.

**Comment by dagewa** [comment]
No significant difference in performance on the tests.

**Ten longest tests with `/Z7`:**
```
105.96s call     test/algorithms/refinement/test_multi_experiment_refinement.py::test
51.75s call     test/command_line/test_refine.py::test_scan_varying_multi_scan_one_crystal
49.84s call     algorithms/indexing/test_index.py::test_index_4rotation
47.02s call     test/test_scan_varying_integration_bug.py::test
43.64s call     test/command_line/test_preservation_of_experiment_identifiers.py::test_preservation_of_identifiers
29.28s call     algorithms/indexing/test_index.py::test_all_expt_ids_have_expts
26.49s call     algorithms/indexing/test_index.py::test_index_small_molecule_multi_sequence_3
26.04s call     test/command_line/test_export_best.py::test_export_best
25.52s call     algorithms/scaling/test_scale.py::test_scale_and_filter_image_group_mode
25.12s call     algorithms/scaling/test_scale.py::test_incremental_scale_workflow
```

**Without `/Z7`:**
```
106.17s call     test/algorithms/refinement/test_multi_experiment_refinement.py::test
51.53s call     test/command_line/test_refine.py::test_scan_varying_multi_scan_one_crystal
50.32s call     algorithms/indexing/test_index.py::test_index_4rotation
47.06s call     test/test_scan_varying_integration_bug.py::test
41.15s call     test/command_line/test_preservation_of_experiment_identifiers.py::test_preservation_of_identifiers
29.21s call     algorithms/indexing/test_index.py::test_all_expt_ids_have_expts
26.10s call     algorithms/indexing/test_index.py::test_index_small_molecule_multi_sequence_3
25.89s call     test/command_line/test_export_best.py::test_export_best
25.82s call     algorithms/scaling/test_scale.py::test_scale_and_filter_image_group_mode
25.33s call     algorithms/scaling/test_scale.py::test_incremental_scale_workflow
```

**Comment by dagewa** [comment]
Still true, and relevant to Windows builds in the CI.

The `build\` directory on my Windows machine is 7.94 GB.

**Comment by dagewa** [comment]
It's still fairly big. The top level directory is 6.9 GB. The `micromamba\` and `conda_base\` sub-directories are the largest with 2.9 GB and 2.5 GB respectively. Not much we can do about that, probably, and these directories are actually somewhat larger on my Linux build (though I may have other packages installed). However, the `build\` directory is 1.0 GB on Windows compared to 156 MB on Linux.

A lot of space seems to be taken up by subdirectories named `RelWithDebInfo\`, for example my build has 49 MB in a directory called `C:\Users\fcx32934\sw\dials\build\dials\src\dials\algorithms\integration\dials_algorithms_integration_parallel_integrator_ext.dir`. Google told me that

> `RelWithDebInfo` is a build configuration type in CMake and other build systems, such as Visual Studio, that provides a release build with debug information included.

**Comment by dagewa** [comment]
Yes, sounds reasonable. I will try to find out how they are including DIALS with their system.
