### ISSUE TITLE
discover_better_experimental_model assumes beam intersects with detector

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#167]
```
$ dials.discover_better_experimental_model datablock.json strong.pickle 
The following parameters have been modified:

input {
  datablock = datablock.json
  reflections = strong.pickle
}

Running DPS using 2460 reflections
Found 23 solutions with max unit cell 470.62 Angstroms.
Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/discover_better_experimental_model.py", line 465, in <module>
    run(sys.argv[1:])
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/discover_better_experimental_model.py", line 455, in run
    wide_search_binning=params.wide_search_binning)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/discover_better_experimental_model.py", line 392, in discover_better_experimental_model
    old_beam_centre = detector.get_ray_intersection(beam.get_s0())[1]
RuntimeError: dxtbx Internal Error: /scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/model/detector.h(330): DXTBX_ASSERT(w_max > 0) failure.
```

This was originally called from within xia2 processing chemical crystallography data.
[Example datablock.json & strong.pickle](https://github.com/dials/dials/files/340977/input.zip)

**Comment by graeme-winter** [comment]
This probably does not work for lots of reasons - are we sure discover better experimental models is designed to work for 2theta != 0?

**Comment by graeme-winter** [comment]
For example depends on essentially indexing the data with DPS algorithm which will obviously fail here:

```
Running DPS using 2460 reflections
Found 23 solutions with max unit cell 470.62 Angstroms.
```

=> maybe add something at the start which makes sure that the two-theta angle is about 0?

**Comment by graeme-winter** [comment]
@nksauter is there anything in there which would make us think that this should work? Certainly when we put this together back in the day it was just tested where the beam was about orthogonal to the detector surface.

**Comment by graeme-winter** [comment]
Update - #140 suggests it works for 2-theta != 0

**Comment by Anthchirp** [comment]
Changed title probably better reflects the issue at hand. Don't know if the underlying algorithms are supposed to work or not.

**Comment by graeme-winter** [comment]
I am looking at this right now

**Comment by graeme-winter** [comment]
Option 1

```
[gw56@ws133 dials-167]$ dials.discover_better_experimental_model datablock.json strong.pickle max_cell=40
The following parameters have been modified:

max_cell = 40
input {
  datablock = datablock.json
  reflections = strong.pickle
}

Sorry: input beam does not intersect detector
```

**Comment by graeme-winter** [comment]
@Anthchirp would a cleaner error be an improvement over a stack trace i.e. what answer are you looking for here

**Comment by Anthchirp** [comment]
@graeme-winter I found this error in xia2 processing logs of high-angle I19 CD data. xia2 already ignores the error. In that sense, a cleaner error message would be an improvement.

**Comment by nksauter** [comment]
Hi Graeme,

Can you supply a sequence of commands that would allow me to reproduce the
problem?  In most general terms the discover_better_experimental_model
algorithm from Sauter (2004) works in reciprocal space, so it shouldn't
care anything about two theta.  But I would have to confirm this in detail.

Nick

Nicholas K. Sauter, Ph. D.
Computer Staff Scientist, Molecular Biophysics and Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Hi Nick

If you look I think there is an attachment to the ticket from Markus which shows the problem

Best wishes Graeme

**Comment by nksauter** [comment]
Graeme,

OK, agreed I can reproduce the problem based on these inputs.  However, I'm
off to the July 4 celebration now and will have to get back to this later.

Nick

Nicholas K. Sauter, Ph. D.
Computer Staff Scientist, Molecular Biophysics and Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by dagewa** [comment]
Confirmed this is still an issue 3 years later, but at least it fails with a sensible error message now:
```
dials.search_beam_position datablock.json strong.pickle 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = datablock.json
  reflections = strong.pickle
}

Sorry: input beam does not intersect detector
```
I am going to close this.
