### ISSUE TITLE
dials profile models not deterministic

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#168]
It was noticed recently that the DIALS profile models are not deterministic as they are calculated using a simplex optimisation. At the very least this code should probably set a random seed so that results would be reproducible.

**Comment by graeme-winter** [comment]
Running a few tests looks like non-random values work OK

```
      # Set the starting values to try
      # start = random.random() * pi / 180
      # stop = random.random() * pi / 180
      start = 1 * pi / 180
      stop = 3 * pi / 180
      starting_simplex = [flex.double([start]), flex.double([stop])]
```

also random values in the range 0 to 180 degrees seems wild for mosaic spread...

**Comment by graeme-winter** [comment]
Tests still pass...
