### ISSUE TITLE
flatten_reflections doesn't flatten anything

### ISSUE THREAD

**Issue by dwpaley** [dials/dials#1681]
This is `dials.util.options.flatten_reflections`:

```
def flatten_reflections(filename_object_list):
    """
    Flatten a list of reflections tables

    A check is also made for the 'id' values in the reflection tables, which are
    renumbered from 0..n-1 to avoid clashes. The experiment_identifiers dict is
    also updated if present in the input tables.

    :param filename_object_list: The parameter item
    :return: The flattened reflection table
    """
    tables = [o.data for o in filename_object_list]
    if len(tables) > 1:
        tables = renumber_table_id_columns(tables)
    return tables
```

This code does n refl files in-->n refl tables out. Is this as intended? It's easy to make a reflection table in the calling code and extend it with each item in the "flattened" reflections list, but the name seems misleading...

**Comment by graeme-winter** [comment]
I am very sympathetic to this viewpoint - I had always _understood_ (evidently incorrectly) that this would take N reflection tables and give you back a single one. However now you raise this I think that I may have stumbled across this before but assumed that I had misunderstood something. 

Simply chnaging the behaviour is a non-trivial change as this is used in several places, though I would waget a KitKat that every time this is used there is some code to join the reflection tables immediately afterwards, for example from `dials.index`

```
            tables_list = renumber_table_id_columns(tables_list)
            for table in tables_list:
                indexed_reflections.extend(table)
```

In `missing_reflecions`

```
    reflections = flatten_reflections(params.input.reflections)

    if not experiments or not reflections:
        parser.print_help()
        return
    if len(reflections) != 1 and len(experiments) != len(reflections):
        sys.exit("Number of experiments must equal the number of reflection tables")
```

which gets me wondering why `flatten_reflections` was used at all except for cargo culting... 

🤔

**Comment by dwpaley** [comment]
A trial balloon: If this were called `unwrap_renumber_reflections(filename_object_list, flatten=False)`, the existing functionality would be preserved and the name would not be confusing. `flatten_reflections` could be a wrapper for the `flatten=True` case. What do you think?
