### ISSUE TITLE
`dev.dials.thing`

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1703]
I was just using `dev.dials.sort_reflections`, thinking that it was useful and wondering why it was behind a `dev.dials.` dispatcher. There are 7 `dev.dials.` from DIALS (and many others from `dials_scratch`). The ones from DIALS are:

### Reflection wrangling utilities
- `dev.dials.sort_reflections`
- `dev.dials.merge_reflection_lists`

### Other data processing analysis jiffies
- `dev.dials.find_bad_pixels`
- `dev.dials.csv`

### Tutorial build scripts
- `dev.dials.generate_tutorial_text`
- `dev.dials.make_sphinx_html`

### Introspection
- `dev.dials.show_extensions`

I believe the first two classes should graduate from `dev.dials.thing` to just `dials.thing`. That is, if it is in DIALS and does something with diffraction data it should be `dials.`.

**Comment by rjgildea** [comment]
I think historically `dev.dials.*` has been used to signal "not tested or actively supported". If any are graduated to `dials.*` I would suggest we should at a minimum add a test (if none exists).

`dev.dials.csv` can probably be removed - we (Diamond) now use `dials.export format=json` in its place.

**Comment by dagewa** [comment]
`sort_reflections` and `merge_reflection_lists` both have tests. I don't think `find_bad_pixels` has one. Is this script useful?

**Comment by dagewa** [comment]
This was supposed to have been closed when #1708 was merged
