### ISSUE TITLE
`dev.dials.find_bad_pixels` is untested

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1709]
`sort_reflections` and `merge_reflection_lists` both have tests. I don't think `find_bad_pixels` has one. Is this script useful?

_Originally posted by @dagewa in https://github.com/dials/dials/issues/1703#issuecomment-841267793_

**Comment by graeme-winter** [comment]
👍

I accept ownership of this

**Comment by dagewa** [comment]
Thanks. Two items here, I think:

- [ ] Add test
- [ ] Promote from `dev.dials.` to `dials.`
