### ISSUE TITLE
dials.find_spots fast mode for grid scans

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#171]
As discussed, reminder :-)

finder.py:SpotFinder:_find_in_imageset looks like a great place to make use of params.fast_grid_mode

**Comment by graeme-winter** [comment]
N.B. also made a branch to start on this:

```
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 867 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
To git@github.com:dials/dials.git
 * [new branch]      dials-171 -> dials-171
Branch dials-171 set up to track remote branch dials-171 from origin.
```

**Comment by graeme-winter** [comment]
(seemed like a good idea...)

**Comment by jmp1985** [comment]
Hi Graeme,

This is now implemented. If the shoeboxes=False parameter is set then, if the input is either a set of stills or force_2d=True is set, the spot finding will be done in 2D with all the calculations happening in the process rather than the labelling being done afterwards.
