### ISSUE TITLE
dials.image_viewer fundamentally broken if two theta != 0

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1715]
Following the change sets discussed in https://github.com/dials/dials/discussions/1358 from https://github.com/dials/dials/pull/1182 etc. the image viewer is basically broken if you have a two-theta offset. If you have a small 2-theta offset then the image is weirdly stretched:

![Screenshot 2021-05-19 at 09 47 34](https://user-images.githubusercontent.com/1241716/118785799-1d81ac80-b889-11eb-9ab5-f7ac41480cc4.png)

becomes

![Screenshot 2021-05-19 at 09 47 14](https://user-images.githubusercontent.com/1241716/118785814-207c9d00-b889-11eb-93de-949d945e4d8b.png)

Then if you have a more substantial offset the viewer simply _refuses_ to show an image:

![Screenshot 2021-05-19 at 10 01 39](https://user-images.githubusercontent.com/1241716/118785913-39854e00-b889-11eb-92ff-7ba7f8ece8f3.png)

this was reported by @benjaminhwilliams  a long time ago and essentially the outcome was that we could not revert the changes but were invited to investigate the underlying issues:

https://github.com/dials/dials/issues/1385#issuecomment-685907993

however we are in a position where we now _cannot_ use this for operational beamlines for their day-to-day needs. 

The changes have now been built on top of so there is no easy revert to address the operational issues. Users have been using DIALS 2.2 version of the viewer which was made before this change was merged but that is unsustainable.

**Comment by graeme-winter** [comment]
See also 

https://github.com/dials/dials/issues/1385
https://github.com/dials/dials/issues/1358

**Comment by dagewa** [comment]
It might be worth noting that https://github.com/cctbx/dxtbx/pull/224 shows how to do this properly for detectors on 2θ arms. If there is will, that code could be brought into `dials.image_viewer`

**Comment by graeme-winter** [comment]
> It might be worth noting that [cctbx/dxtbx#224](https://github.com/cctbx/dxtbx/pull/224) shows how to do this properly for detectors on 2θ arms. If there is will, that code could be brought into `dials.image_viewer`

Thanks @dagewa  I will be honest that _any_ fix which turns this into a working thing would be super welcome right now - the limiting factor to me is the amount of calendar time such a splice would take.

**Comment by dagewa** [comment]
Yes, this is unclear. I'll have a look in the image viewer code to see if I can work out _where_ this would go. If I can figure it out in finite time I'll try making a PR. I'll enter this with a fairly low threshold for giving up though.

**Comment by graeme-winter** [comment]
[mjh73_01.zip](https://github.com/dials/dials/files/6508844/mjh73_01.zip)
[mjh73_02.zip](https://github.com/dials/dials/files/6508845/mjh73_02.zip)
[mjh73_03.zip](https://github.com/dials/dials/files/6508846/mjh73_03.zip)
[mjh73_04.zip](https://github.com/dials/dials/files/6508847/mjh73_04.zip)
[mjh73_05.zip](https://github.com/dials/dials/files/6508848/mjh73_05.zip)
[mjh73_06.zip](https://github.com/dials/dials/files/6508850/mjh73_06.zip)
[mjh73_07.zip](https://github.com/dials/dials/files/6508851/mjh73_07.zip)
[mjh73_08.zip](https://github.com/dials/dials/files/6508852/mjh73_08.zip)
[mjh73_09.zip](https://github.com/dials/dials/files/6508854/mjh73_09.zip)
[mjh73_10.zip](https://github.com/dials/dials/files/6508855/mjh73_10.zip)
[mjh73_11.zip](https://github.com/dials/dials/files/6508857/mjh73_11.zip)
[mjh73_12.zip](https://github.com/dials/dials/files/6508858/mjh73_12.zip)
[mjh73_13.zip](https://github.com/dials/dials/files/6508860/mjh73_13.zip)

First 9 frames each of 13 scans, with increasing two-theta angles - nicely demonstrate the issues as showed above

**Comment by graeme-winter** [comment]
I believe that this was fixed by @dagewa
