### ISSUE TITLE
investigate using powder information for indexing

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#172]
With CX data we sometimes get many lattices and the indexing algorithm falls over. See if we can find a way to more reliably approximate a unit cell by treating the data as powder data.

**Comment by dagewa** [comment]
Is there still work to do on this?

**Comment by Anthchirp** [comment]
Unless someone wants to follow up on this or thinks it is still a priority (@benjaminhwilliams ?), then we may as well close this ticket.
