### ISSUE TITLE
Enable parallel processing on windows

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1721]
Currently we rely on `easy_mp` which works only on UNIX-like systems - propose -

- [ ] assess desired usage patterns
- [ ] simplify content of `dials.util.mp`
- [ ] unify all multiprocessing to use `dials.util.mp` interface
- [ ] remove use of easy_mp
- [ ] replace with `concurrent.futures`

#discuss

**Comment by graeme-winter** [comment]
Assess desired usage patterns - currently `dials.util.mp` allows you to:

- run on multiple cores
- run on cluster
- run using drmaa
- run mp jobs with some qsub command
- not use Windows

We only (as far as I am aware) use the first of these and our users would prefer the last, to no's 2-4, I believe.

**Comment by graeme-winter** [comment]
`dials.util.mp` contains

- `parallel_map`
- `MultiNodeClusterFunction` which is I think a helper to allow others?
- `batch_multi_node_parallel_map`
- `multi_node_parallel_map`

How much are these _actually executed_? They are all available in the code, but are they ever used?

**Comment by graeme-winter** [comment]
As pointed out by @Anthchirp  see also #39

**Comment by graeme-winter** [comment]
Turns out that this is a little more complicated than anticipated - we have a lot of conflation between the `nproc` and `njob` options. In particular, if you are running something which is not "threaded" then `njob` takes the place of `nproc`  - or may be that `nproc * njob` remains constant while the relative values of one and the other are adjusted according to a mystery parameter `len(manager)`

**Comment by graeme-winter** [comment]
Coming back to the main topic of _why_ this does not work -> something something multiprocessing something fork something spawn pickle something _but_ all the inputs here can be pickled:

```
            batch_multi_node_parallel_map(
                func=ExtractSpotsParallelTask(function),
                iterable=indices,
                nproc=mp_nproc,
                njobs=mp_njobs,
                cluster_method=mp_method,
                chunksize=mp_chunksize,
                callback=process_output,
            )
```

yet the end product can't be

**Comment by dagewa** [comment]
My (very limited) understanding of this issue is that for spawn to work, it is not just the inputs here that must be pickleable, but because a fresh interpreter process is started, everything required to get up to this point must also be pickleable.

**Comment by graeme-winter** [comment]
> My (very limited) understanding of this issue is that for spawn to work, it is not just the inputs here that must be pickleable, but because a fresh interpreter process is started, everything required to get up to this point must also be pickleable.

I am not 100% sure this is correct, but I get the gist of your point - you have to be able to recreate the process state from that which you can pickle, which means local scope function definitions are bad news. I think this is what is happening here.
