### ISSUE TITLE
`dials.image_viewer` does not update results of bottom buttons for series of '.expt'

### ISSUE THREAD

**Issue by elena-pascal** [dials/dials#1734]
When loading a series of _.expt_ in `dials.image_viewer` the buttons at the bottom (mean... threshold) don't seem to update results when moving through the images. 

If I use instead the raw files (`dials.image_viewer image_*.cbf`), the results of buttons at the bottom update as expected.

**Comment by graeme-winter** [comment]
OK interesting it worked OK for me there - what platform was this?

**Comment by graeme-winter** [comment]
Also: what was the command-line used to start `dials.image_viewer`?

**Comment by elena-pascal** [comment]
hmm. I am on Ubuntu 20.04. 
I used `dials.image_viewer imported_*.expt` where `imported_###.expt` is a list of imported experiments as imported by `dials.stills_process`. Is it not meant to be used like this?
Adding the reflections doesn't change the observed effect.

**Comment by graeme-winter** [comment]
Verified & reproduced thank you

This appears to be a bug in the implementation of the buttons - if you load an image which is not the first one, then select one of the buttons, you end up with the processed version of the 1st image. 

This would explain why it does not update when you move from one to the next.

**Comment by graeme-winter** [comment]
> Verified & reproduced thank you
> 
> This appears to be a bug in the implementation of the buttons - if you load an image which is not the first one, then select one of the buttons, you end up with the processed version of the 1st image.
> 
> This would explain why it does not update when you move from one to the next.

Correction

It shows the _first_ image you selected not image-view with over and over again, not the first image. 

To reproduce: 

```
dials.stills_process unit_cell=97,97,97,90,90,90 space_group=p23 ./*cbf
dials.image_viewer idx-merlin0047_1748*imported.expt
```

**Comment by graeme-winter** [comment]
OK, I found it 🙂
