### ISSUE TITLE
DIALS Integrate failed

### ISSUE THREAD

**Issue by arif9485** [dials/dials#1736]
Hi everyone,

I had tried to process a data from Diamond Light Source using Xia2 DIALS and I get this error.

Error: dials.integrate subprocess failed with exitcode 1

The data could be processed by an older version of DIALS during data collection back in 2019. I have attached the log files here.

Any help would be appreciated

Thanks

Arif

[12_dials.integrate_INTEGRATE.log](https://github.com/dials/dials/files/6622942/12_dials.integrate_INTEGRATE.log)
[xia2.txt](https://github.com/dials/dials/files/6622943/xia2.txt)
[xia2-debug.txt](https://github.com/dials/dials/files/6622944/xia2-debug.txt)
[xia2-error.txt](https://github.com/dials/dials/files/6622945/xia2-error.txt)

**Comment by ndevenish** [comment]
Hi @arif9485, it looks like it's failing because it's running out of memory. Integration tries to estimate the memory usage and is scaling down the number of parallel operations from 8 to 6:
```
...INTEGRATE.log:

  Available system memory (excluding swap)          : 10.5 GB
  Memory required per process                       :  1.4 GB
Reducing number of processes from 8 to 6 due to memory constraints.
```

but it looks like that was still too high. We've been working on trying to get this scaling better, but it keeps being tricky.

Does it work if you specify a lower count directly when running xia2 e.g. `xia2 nproc=4 ....`?

**Comment by arif9485** [comment]
Dear Nicholas,

Thanks for your suggestion. It however failed again. I had executed the following command: xia2_dials nproc=4 pipeline=dials /home/arif/windows_share/DapD_Paper/data_final/5-DapD_JML_50mM_1_18548_47/raw_data/DapD_JML_50mM_1, where xia2_dials calls the latest version of DIALS.

I have attached here the integrate log file. Please have a look.

Thanks

Arif

[12_dials.integrate_INTEGRATE.log](https://github.com/dials/dials/files/6626272/12_dials.integrate_INTEGRATE.log)

**Comment by arif9485** [comment]
Please see the other log files. I have changed the file extensions to .log as .txt was not uploading here for some unknown reason. 

Thanks

Arif

[xia2-error.log](https://github.com/dials/dials/files/6626296/xia2-error.log)
[xia2-debug.log](https://github.com/dials/dials/files/6626297/xia2-debug.log)
[xia2.log](https://github.com/dials/dials/files/6626298/xia2.log)

**Comment by ndevenish** [comment]
Hi, can you try `nproc=1`? It'll be slower, but If that fails then we have a bigger problem

**Comment by arif9485** [comment]
Hi, I tried nproc=1. It failed again. Please see the log file attached.


[12_dials.integrate_INTEGRATE.log](https://github.com/dials/dials/files/6628500/12_dials.integrate_INTEGRATE.log)

**Comment by dagewa** [comment]
Hi Arif, integration appears to have succeeded this time. Your xia2 job may have failed for other reasons

**Comment by arif9485** [comment]
Hi David,

Thanks for noticing. Can you suggest a fix for failure of xia2?

Arif

**Comment by arif9485** [comment]
Here are the log files.

Thanks
[xia2-error.log](https://github.com/dials/dials/files/6630622/xia2-error.log)
[xia2-debug.log](https://github.com/dials/dials/files/6630623/xia2-debug.log)
[xia2.log](https://github.com/dials/dials/files/6630624/xia2.log)

**Comment by arif9485** [comment]
Hi, I would like to run all of the DIALS script one by one after integration. I could run dials.scale and dials.merge. Could you please guide me which ones are next to get the final data processing file?

Thanks
Arif

**Comment by dagewa** [comment]
Looks a bit like it bombed during the `dials.report` stage.

If you can run `dials.scale` and `dials.merge` then you have a merged MTZ, right? Isn't that what you want?

**Comment by arif9485** [comment]
Sorry I missed running dials.symmetry before dials.scale and dials.merge. When I run that it fails.

**Comment by arif9485** [comment]
I am a bit confused if merged.mtz is the file which we use for all furher crystalloraphic operations. Should it contain Rfree? I want something similar to 75944883_AUTOMATIC_DEFAULT_free.mtz file. Can you guide me how to get there step by step?

**Comment by dagewa** [comment]
You can add a free R flag when you load the dataset into CCP4 (other crystallographic software suites are available)

**Comment by dagewa** [comment]
However, I think we'd want to work out why `dials.report` failed here. It should not, and if we can stop that happening then you can get everything you want from a completed xia2 run

**Comment by arif9485** [comment]
Ok thanks. For me dials.symmetry is not runing. It is getting killed.

**Comment by arif9485** [comment]
Is there a step by step tutorials to run all of the dials scripts? I found one but that goes only until the integration step. It is here. https://dials.diamond.ac.uk/documentation/getting_started.html. I would prefer to run further scripts of dials rather than going to pointless and aimless.

Thanks

**Comment by dagewa** [comment]
Running `dials.symmetry` is not essential, it just gives you more information to determine the space group, which remains a hypothesis until the structure is solved. If you have run `dials.merge` then you have produced a merged MTZ file. You can import this into CCP4 using the "Import merged reflection data" task in ccp4i2. This allows a FreeR set to be defined.

As regards tutorials, this one is fairly recent: https://dials.github.io/documentation/tutorials/mpro_x0692.html. The steps are all there, just skip the `dials.symmetry` step if that does not work. It is a bit surprising that this fails though.
