### ISSUE TITLE
Add "small molecule" mode to dials.symmetry

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1798]
Right now `dials.symmetry` will give you one of 65 space groups in output by default. `xia2.small_molecule` runs (I discovered) a separate reindex step to assign e.g. `C 1 2/m 1` as the space group - but this should be possible as part of `dials.symmetry` I feel.

**Comment by graeme-winter** [comment]
[integrated.zip](https://github.com/dials/dials/files/6787515/integrated.zip)

Suitable example data

**Comment by graeme-winter** [comment]
[symmetrized.zip](https://github.com/dials/dials/files/6788664/symmetrized.zip)

Annoying counterexample where solution comes out with `xia2.small_molecule` as `P 1 2/m 1` when correct solution is `P 1 21 1` (sucrose)

Though Flack parameter pretty lousy either way:

```
 Flack x =    0.737(372) by classical fit to all intensities
 Flack x =    0.690(189) from 2848 selected quotients (Parsons' method)
```

🤔  I suspect there is no solution here

**Comment by dagewa** [comment]
I think this is a duplication of #1118
