### ISSUE TITLE
Please can we have an easy tool for filtering a reflection pickle file on resolution

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#180]
i.e. dev.dials.filter_reflections d_min=x d_max=y

**Comment by graeme-winter** [comment]
this turns out to be impossible as there is no geometric information in the reflection table which will allow the exclusion of reflections based on resolution - cannot compute the resolution. 

In principle can filter the indexed pickle based on the reciprocal space location of the reflection i.e. we have length of this is equal to 1/d. Still thinking about this...

**Comment by rjgildea** [comment]
After indexing the pickle file should have 'rlp' or 's1' vectors, should be possible to filter by resolution based on these. Or just pass datablock.json file and map to reciprocal space?

**Comment by jmp1985** [comment]
If the reflection table has predictions it should have a column "d" in it that can be used for filtering. I'll add this today.

james

________________________________
