### ISSUE TITLE
Scan-varying refinement with the SparseLevMar engine is unhelpful

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1800]
Following the question in https://github.com/dials/dials/discussions/1521#discussioncomment-905551, I took a 3600 image, 360° test dataset and tried scan-varying refinement leaving the refinement engine as default (`LevMar`) or setting it to `SparseLevMar`.

In either case,
```
There are 115 parameters to refine against 153095 reflections in 3 dimensions
```

1. Dense case
```
/usr/bin/time -v dials.refine -vv indexed.{expt,refl} scan_varying=True
...
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:23.84
Maximum resident set size (kbytes): 3568632
```

2. Sparse case
```
/usr/bin/time -v dials.refine -vv indexed.{expt,refl} scan_varying=True engine=SparseLevMar
...
Elapsed (wall clock) time (h:mm:ss or m:ss): 2:03.69
Maximum resident set size (kbytes): 10605640
```

Surprisingly, the "sparse" job took considerably longer and used nearly 3 times as much memory. Both jobs took 11 steps with identical RMSDs at each step. The final models are equivalent, except that the `SparseLevMar` job does not calculate unit cell errors, whereas the default job does.

**Comment by dagewa** [comment]
Trying to figure out what is going on. An image helps. This is the Jacobian matrix at some step of refinement:

<img src="https://user-images.githubusercontent.com/11502083/125090189-fdbb7780-e0c6-11eb-8c8a-62180956e600.png" width="400">
The gradients of X make the upper block, then of Y and then the block of ϕ gradients. The parameters are in order so that the first block of columns contains the detector parameters, then the beam, then the crystal orientation and finally the crystal unit cell.


For this refinement job, the Jacobian is a sparse matrix with 52817775 elements, of which only 918570 are structural zeroes. It turns out that all of these are in the block coloured white at the bottom left. These are the derivatives of the ϕ residuals with respect to detector parameters (153095 rows × 6 detector parameters). As the position and orientation of the detector has no effect on the calculated ϕ value, these gradients are all zero. Indeed, they have been recognised as such and made _structural zeroes_, not taking up space in memory.

However, counting the elements of the matrix that are _actually equal to zero_, whether structural or explicit, shows there are 38307848 zero elements, or 73% of the whole matrix is zero. This makes sense because the scan varying crystal orientation and cell parameters are localised and as such are non-zero only for reflections local in ϕ.

The problem here is that the scan-varying gradient calculation is returning explicit zeroes for reflections that should be identified as structurally zero.

**Comment by dagewa** [comment]
Looking at this further, I'm starting to remember the issue. Calculation of the scan-varying derivatives requires arrays of derivatives of the **U** and **B** matrices wrt each parameter. These are `mat3_double` arrays and we don't currently have a sparse array type for `mat3_double` or `vec3_double`. One approach would be to add those sparse array types with their associated matrix and vector operations so that they can be used alongside flex arrays. Another would be to store the gradients only for the subset of reflections affected by each parameter, along with their indices. Then calculations could use dense vector methods on this subset, ultimately writing back to sparse arrays once the calculation is in terms of scalars dX/dp, dY/dp and dϕ/dp.

**Comment by graeme-winter** [comment]
Guessing a side effect of this slimming back could also be to reduce the memory footprint?

Corrent `dials.refine` job taking ~16GB ram, down from ~21 just now....

**Comment by dagewa** [comment]
Yes, that's the aim. Most of the RAM for scan-varying jobs is currently taken up storing floating point `0.0` values.

**Comment by dagewa** [comment]
I've been working on this in a branch (https://github.com/dials/dials/tree/sparse-scan-varying), without a huge amount of success yet.

**Comment by dagewa** [comment]
https://pypi.org/project/memory-profiler/ pointed out by @elena-pascal looks useful. On the sparse-scan-varying branch I now have the Jacobian properly constructed with 72% structural zeroes for the example case, for a reasonable memory saving:

**sparse-scan-varying**
![mprof](https://user-images.githubusercontent.com/11502083/127197763-527549b8-045e-479b-b2a7-4c5d5a09b5dc.png)

**main**
![mprof_main](https://user-images.githubusercontent.com/11502083/127197837-32220e75-d351-40ef-878b-b9d782eacf55.png)

At the moment, the code on the branch takes much longer though, due to an expensive Python function call. I expect to be able to speed this up.

**Comment by dagewa** [comment]
Ok, it's not going that well. My C++ code replacing two Python loops over arrays with C++ loops is actually 2 times slower than the Python version :thinking:

The demonstration of this is here https://github.com/dials/dials/blob/bd1914deb13d41026448352b1f4c3844b09e0a6b/tests/algorithms/refinement/test_scan_varying_prediction_parameters.py#L424-L471

**Comment by dagewa** [comment]
@rjgildea's suggestion to use `np.intersect1d` here certainly helps. We're still a long way off the `main` branch performance in terms of wallclock time, but around half the peak memory usage.
![mprof_numpy](https://user-images.githubusercontent.com/11502083/127699975-650cce60-8045-479c-85a7-e9dda7cda470.png)

**Comment by dagewa** [comment]
83% of the runtime is spent inside `SparseFlex.extend`, so this approach will have to be changed.

**Comment by dagewa** [comment]
Returning to this. Adding a couple of C++ functions and classes removed the need for `SparseFlex.extend` entirely. The main issue was an expensive consistency check though. This is not necessary, as the gradients are all tested vs finite derivatives anyway. Now the branch is both faster than main and has a smaller memory footprint.

![mprof-latest-branch](https://user-images.githubusercontent.com/11502083/156555356-c50cde60-aa69-4850-840d-38661371cf55.png)
