### ISSUE TITLE
dials.index with > 1 sweep and > 1 lattice

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1821]
dials.index with multple sweeps and multiple lattices - if you say max_lattices=2 will not try for more lattices (presumably it is counting _experiments_ in the code) 

Had to set max_lattices=8 to get 

```
+------------+-------------+---------------+-------------+
|   Imageset |   # indexed |   # unindexed | % indexed   |
|------------+-------------+---------------+-------------|
|          0 |       22175 |           895 | 96.1%       |
|          1 |       10894 |           548 | 95.2%       |
|          2 |        9108 |           622 | 93.6%       |
|          3 |        7260 |           443 | 94.2%       |
+------------+-------------+---------------+-------------+
```

Probably annoying small book keep error

**Comment by biochem-fan** [comment]
This *seems* to work, but I'm not sure if this breaks the stills indexer.
Can somebody check?

```diff
diff --git a/src/dials/algorithms/indexing/indexer.py b/src/dials/algorithms/indexing/indexer.py
index 1a42c7e37..6fc3fb8b0 100644
--- a/src/dials/algorithms/indexing/indexer.py
+++ b/src/dials/algorithms/indexing/indexer.py
@@ -518,7 +518,7 @@ def index(self):
             if had_refinement_error or have_similar_crystal_models:
                 break
             max_lattices = self.params.multiple_lattice_search.max_lattices
-            if max_lattices is not None and len(experiments) >= max_lattices:
+            if max_lattices is not None and len(experiments) >= max_lattices * len(self.experiments):
                 break
             if len(experiments) > 0:
                 cutoff_fraction = (
```

**Comment by graeme-winter** [comment]
> This _seems_ to work, but I'm not sure if this breaks the stills indexer. Can somebody check?
> 
> ```diff
> diff --git a/src/dials/algorithms/indexing/indexer.py b/src/dials/algorithms/indexing/indexer.py
> index 1a42c7e37..6fc3fb8b0 100644
> --- a/src/dials/algorithms/indexing/indexer.py
> +++ b/src/dials/algorithms/indexing/indexer.py
> @@ -518,7 +518,7 @@ def index(self):
>              if had_refinement_error or have_similar_crystal_models:
>                  break
>              max_lattices = self.params.multiple_lattice_search.max_lattices
> -            if max_lattices is not None and len(experiments) >= max_lattices:
> +            if max_lattices is not None and len(experiments) >= max_lattices * len(self.experiments):
>                  break
>              if len(experiments) > 0:
>                  cutoff_fraction = (
> ```

I am fairly sure I tried this kind of logic before, and it did not quite do what I had intended. Will revisit though, thank you for picking it up.
