### ISSUE TITLE
`dials.image_viewer`: improvements to masking UI

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1824]
The masking UI could do with some improvements. One is that it is possible to save a mask before the polygon mode has finalised, which can end up with an empty mask. Perhaps clicking "save" should deselect/complete the polygon mode.

**Comment by biochem-fan** [comment]
Also: #539

**Comment by biochem-fan** [comment]
Another issue is that when one accidentally double-clicks on the image while drawing a polygon mask, the zoom level changes and the polygon becomes a mess.

**Comment by biochem-fan** [comment]
Also #1964: I made a separate issue for this one because there is no user-side workaround.

**Comment by biochem-fan** [comment]
For completeness: other issues include https://github.com/dials/dials/issues/1512 and https://github.com/dials/dials/issues/2712.

**Comment by biochem-fan** [comment]
> Another issue is that when one accidentally double-clicks on the image while drawing a polygon mask, the zoom level changes and the polygon becomes a mess.

This issue can be resolved by storing vertices (`self._mode_polygon_points`) in the PySlip Geo coordinate system, not in the View coordinate system. I will send a PR together with other masking fixes.
