### ISSUE TITLE
Tutorial updates

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1828]
The text of some of our introductory tutorials is getting out of date.

- [x] `dials.find_spots` and `dials.integrate` are presented with an explicit `nproc=4` in the command-line tutorials. This should no longer be necessary.
- [ ] rbs changes (#1825) mean that the [Mpro tutorial](https://dials.github.io/documentation/tutorials/mpro_x0692.html) steps now result in a reported mI lattice, not mC
- [ ] The CCP4 pipeline of `pointless`, `aimless` and `ctruncate` is still mentioned at the end of the tutorials. I question whether this is useful here.

**Comment by rjgildea** [comment]
The Mpro tutorial output _should_ be https://github.com/dials/dials/blob/fa58b57493feddf4b2bae50d6347f32466e6034d/command_line/generate_tutorial_text.py#L331-L337 via `dials.generate_tutorial_text`, but it appears that the `--mpro_x0692` option was never added to the `dials.generate_tutorial_text` in the relevant Jenkins job. I've now added this and retriggered the update job.

**Comment by rjgildea** [comment]
It turns out the relevant Mpro data are no longer on disk at DLS, so automatically generating the text for this tutorial depends on adding the data to `dials.data` (https://github.com/dials/data/pull/290 and https://github.com/dials/data/pull/291)
