### ISSUE TITLE
Try multiple indexing methods

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#183]
It would be nice to have an option to try the second indexing method when the first method failed. For example, first try `fft3d` and then fall back to `fft1d`. This is similar to the behaviour of CrystFEL's `indexamajig`. Or, should I do this by a shell script?

**Comment by phyy-nx** [comment]
I've been considering this for stills too. I have one example where real space grid search is better than fft1d (20% increase in number of integration results), and another example where I see the opposite by a large margin. 

-Aaron

**Comment by graeme-winter** [comment]
Folks

I would say this kind of behaviour should be implemented at the next level up I.e. In xia2 or cctbx.xfel for example. Dials should provide the tools to do this but I would not like this to be the behaviour of dials.index. 

I can see the benefit of a mechanism to run the basis determination in isolation then take the results forward. Aaron I think this would better meet your needs. 

Python scripts based on the index command line tool should be pretty easy to put together 

Best wishes Graeme

**Comment by phyy-nx** [comment]
Sounds reasonable.  Making a note to get this set up in
dials.stills_process.

**Comment by rjgildea** [comment]
This is/was (it may or may not still work) already implemented in xia2 as the option dials.index.method=None, which will try both and choose the one with the lowest rmsds. What the best/most effective way to do this is open to question - whether to 1) do basis search for each method, then combine the basis vector lists before looking for suitable orientation matrices, or 2) consider each separate list of basis vectors independently at this stage, and then combine all possible orientation matrices before refinement to decide the best one, or 3) do this at a higher level still.

**Comment by biochem-fan** [comment]
I see. I did it by shell:
```bash
dials.index datablock.json strong.pickle indexing.method=fft1d || \
 dials.index datablock.json strong.pickle indexing.method=fft3d || \
 echo "FAILED!"
```

I think Richard's idea (1) is promising, because I sometimes observe that each method finds different two from three basis vectors.

**Comment by dagewa** [comment]
Closing this particular issue as the consensus was to attempt multiple runs by scripting.

**Comment by phyy-nx** [comment]
Also, I did actually add indexing.stills.method_list = None, but never
closed the issue.

Help string: "List of indexing methods. If indexing fails with first
method, indexing will be attempted with the next, and so forth"

Use like this
indexing.stills.method_list =fft1d,fft3d
