### ISSUE TITLE
Cannot get the expected cell with rbs

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1832]
I have some confusion regarding monoclinic cells again, for a tutorial dataset for the upcoming IUCr school on electron crystallography. The structure has been [solved previously](https://www.nature.com/articles/s41467-021-22590-6/tables/1) by MicroED, with the cell reported to be 99.06, 31.01, 54.30, 90.00, 107.70, 90.00, in space group C2.

Inside [iucr_tutorial.zip](https://github.com/dials/dials/files/6925169/iucr_tutorial.zip) are the `imported.expt` and `strong.refl`. Indexing with 
```
dials.index imported.expt strong.refl detector.fix=distance
```
gives the cell `29.798(7), 49.57(3), 51.81(6), 72.83(7), 89.19(6), 73.43(4)`. If I then run
```
dials.refine_bravais_settings indexed.expt indexed.refl
```
there are two solutions, one of which is an `mI` lattice with cell `133.10  62.19 239.87  90.00 104.23  90.00`.

If instead I run
```
dials.refine_bravais_settings indexed.expt indexed.refl best_monoclinic_beta=False
```
then the non-triclinic solution has an `mC` lattice with cell `243.20  62.07 132.65  90.00 107.69  90.00`.

This second version has the right cell angles, but b is double the expected cell, while a and c are not integer multiples of the expected values.

However, I *can* get the expected cell if I run indexing asking for C2:

```
dials.index imported.expt strong.refl detector.fix=distance space_group=C2
```
gives
```
Crystal:
    Unit cell: 94.87(13), 29.748(18), 51.72(11), 90.0, 107.68(14), 90.0
```
which is exactly what is wanted.

How can I get the expected cell going from the P1  indexing solution and using `dials.refine_bravais_settings`? For tutorial purposes I don't want to have to "know" the space group in advance

**Comment by dagewa** [comment]
This is how the cells compare. Orange is the expected cell. Blue is the one from `dials.refine_bravais_settings` with `best_monoclinic_beta=False`. The view is down the b* axis, which is doubled in the orange cell. a* and c* are not integer multiples between the cells, which seems weird.
![Screenshot from 2021-08-03 16-37-09](https://user-images.githubusercontent.com/11502083/128044378-7a625f48-3963-46d0-af47-fd22a507198a.png)

**Comment by rjgildea** [comment]
I think it is just that you're fixing the detector distance in indexing, but not in RBS. If I set `detector.fix=distance` here as well, then it gives the unit cell you are looking for:
```
$ dials.refine_bravais_settings indexed.{expt,refl} best_monoclinic_beta=False detector.fix=distance
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.dev.534-gfa58b5749
The following parameters have been modified:

best_monoclinic_beta = False
refinement {
  parameterisation {
    detector {
      fix = all position orientation *distance
    }
  }
}
input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Chiral space groups corresponding to each Bravais lattice:
aP: P1
mC: C2
+------------+--------------+--------+--------------+----------+-----------+------------------------------------------+----------+-----------+
|   Solution |   Metric fit |   rmsd | min/max cc   |   #spots | lattice   | unit_cell                                |   volume | cb_op     |
|------------+--------------+--------+--------------+----------+-----------+------------------------------------------+----------+-----------|
|   *      2 |       1.4691 |  0.116 | 0.843/0.843  |      541 | mC        | 94.78  29.76  51.75  90.00 107.59  90.00 |   139119 | a-2*b,a,c |
|   *      1 |       0      |  0.046 | -/-          |      541 | aP        | 29.80  49.57  51.82  72.82  89.19  73.43 |    69879 | a,b,c     |
+------------+--------------+--------+--------------+----------+-----------+------------------------------------------+----------+-----------+
* = recommended solution
```
