### ISSUE TITLE
in dials.report: do not create empty sections

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1873]
e.g. just there I was trying to work out why there was a scaling box but no scaling result plots -> it was integrated input. But, should probably just not show the section.

**Comment by rjgildea** [comment]
I think we probably need similar logic to this:
https://github.com/dials/dials/blob/9aede7c354eb5cd749ebd0ba3ca3d8d86813619b/templates/scaling_report.html#L23-L25
in the `report.html` template:
https://github.com/dials/dials/blob/main/templates/report.html
