### ISSUE TITLE
Memory leak in stills indexing

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#193]
This leak should not be the same leak as in issue #189.  I found this leak after adding memory tracking to cctbx.xfel.xtc_process, which uses the same code as dials.stills_process for indexing and integration.  Results from processing a 4 minute run from a recent experiment at CXI, using 2 nodes with 16 cores each, ~938 events per node:

Data read (import) only (includes hierarchical detector creation): 155 Kb leaked per core
Add spotfinding: 399.25 Kb leaked per core
Add indexing: 73.1 Mb leaked per core
Add integration: 82.1 Mb leaked per core

I then repeated indexing, using indexing.stills.refine_all_candidates=False: 786.9 Kb.  This narrows the memory leak down to algorithms.indexing.stills_indexer.stills_indexer.choose_best_orientation_matrix()

**Comment by nksauter** [comment]
Could you provide a single-process unit test that isolates the
first-occurring leak and let's focus on that first?  Or provide separate
unit tests that isolate different memory leaks.

It should *not* be necessary to have an XTC stream.  All needed input could
be provided by pickled objects, with the memory leak manifested by an outer
for...loop.

Nick

Nicholas K. Sauter, Ph. D.
Computer Staff Scientist, Molecular Biophysics and Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by dagewa** [comment]
Is this still relevant? Thanks.

**Comment by Anthchirp** [comment]
If it is still relevant please reopen.
