### ISSUE TITLE
dials.check_indexing_symmetry needs both d_min and d_max

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#1956]
The default value of `d_max` in `dials.check_indexing_symmetry` is 0. https://github.com/dials/dials/blob/main/command_line/check_indexing_symmetry.py#L41

Thus, if I specify only `d_min`, no reflections are accepted. I suggest changing the default to infinity (or 9999).

**Comment by graeme-winter** [comment]
It's a bug, thank you for reporting.

**Comment by biochem-fan** [comment]
Great! Thank you very much for your quick fix.
