### ISSUE TITLE
rlv fails on WSL

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1979]
A user reports that `dials.reciprocal_lattice_viewer imported.expt strong.refl` failed with

```
reciprocal_lattice_viewer.py: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```
when run on a Windows 10 PC under WSL (Ubuntu), with an Xming display server. `dials.image_viewer` works okay, so this might be related to Open GL

**Comment by graeme-winter** [comment]
I don't have a system to test on, but could be that you need to also install some `xming-mesa` package or similar to get openGL support?

**Comment by graeme-winter** [comment]
> I don't have a system to test on, but could be that you need to also install some `xming-mesa` package or similar to get openGL support?

Though the web pages says "OpenGL support is now provided by all Xming installers" - however it is not obvious if that is true for the free versions? 🤔

**Comment by dagewa** [comment]
I'm trying this out now. Have installed `Xming-mesa` from http://www.straightrunning.com/XmingNotes/, and `glxgears` works when started from the WSL Ubuntu terminal, but _after_ I close the `glxgears` window I see this message:
```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 88625 requests (39 known processed) with 0 events remaining.
```
I'll install DIALS next.

**Comment by dagewa** [comment]
Ok, rlv works for me this way, but it is horribly slow, to the point of being unusable
![image](https://user-images.githubusercontent.com/11502083/150321264-478cb47d-514a-4a1d-9373-f0c2bddbbcc6.png)

**Comment by dagewa** [comment]
Ok, it also works with MobaXterm from https://mobaxterm.mobatek.net/, but is also fairly slow

**Comment by dagewa** [comment]
That bug was noted previously https://github.com/dials/dials/issues/1233

**Comment by dagewa** [comment]
Using MobaXterm works for the original user too. Leaving this open with a question: should we provide some instructions on the main website about installing DIALS under WSL, with a preferred X server?
