### ISSUE TITLE
Warning message something not found something HDF5 something

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#198]
Graemes-MacBook-Pro-4:dxtbx graeme$ svn diff
# Index: format/nexus.py

--- format/nexus.py (revision 25350)
+++ format/nexus.py (working copy)
@@ -14,9 +14,8 @@
 try:
   from dxtbx_format_nexus_ext import *
 except ImportError:
-  print "Warning, HDF5 libraries not found" # stop gap for LCLS until linking is worked out
-  pass
## 

 class check_dtype(object):
   '''
   A class to check whether the dataset data type matches the expected
Graemes-MacBook-Pro-4:dxtbx graeme$ svn commit -m "Sorry, I don't think that this warning should occur on every occasion this is loaded but not used"
Sending        format/nexus.py
Transmitting file data .
Committed revision 25351.

**Comment by nksauter** [comment]
Graeme,

I'm worried that you obliterated a useful message that we need to debug the
build.  The more useful thing would be to simply take away the try---except
altogether.  Import of the dxtbx_import_nexus library should never appear
at the top of the module, instead it should be dynamically loaded only when
needed.  So as to avoid generating an ImportError unless getting one
prevents you from processing data anyway.

Nick

Nicholas K. Sauter, Ph. D.
Computer Staff Scientist, Molecular Biophysics and Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by dagewa** [comment]
What is the status of this issue? Thanks

**Comment by phyy-nx** [comment]
Still an issue, but I think can be fixed while I work on cctbx/cctbx_project#126

**Comment by rjgildea** [comment]
Is this now fixed?

**Comment by phyy-nx** [comment]
Ok, so for the last month or so I've been using psana installed using conda via the xfel_dependencies channel.  This has been working well.  I think the workarounds can be removed, but I'd like to test it first.

See
https://github.com/cctbx/dxtbx/blob/master/SConscript#L65-L88
https://github.com/cctbx/dxtbx/blob/master/format/nexus.py#L9-L11

**Comment by dagewa** [comment]
It is not clear what this issue is about, so I am closing. Please re-open (with a more useful description) if it is still a concern.
