### ISSUE TITLE
Better extend for reflection tables

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#1983]
A very common use case of experiment lists and reflection tables is concatenation.  Here's an example:

```
experiments1.extend(experiments2)
reflections1.extend(reflections2)
```

That snippet however will usually crash with an [exception](https://github.com/dials/dials/blob/main/array_family/boost_python/flex_table_suite.h#L576) that indicates duplicate values in the `id` column.  Therefore the user needs to hand curate the `id` column and identifier map:

```
experiments1.extend(experiments2)
reflections2 = flex.reflection_table()
next_id = flex.max(reflections1['id']) + 1
for expt_id, expt in enumerate(experiments2):
  subset = reflections2.select(reflections2['id'] == expt_id)
  del subset.experiment_identifiers()[expt_id]
  subset.experiment_identifiers()[next_id] = expt.identifier
  subset['id'] = flex.size_t(len(subset), next_id)
  reflections2.extend(subset)
  next_id += 1
```

If instead the extend method did the above micromanagement, then the first snippet would be sufficient.

[Example of this coding pattern](https://github.com/cctbx/cctbx_project/blob/master/xfel/util/sublattice_helper.py#L110-L118) that could be simplified.

I've put in a new branch (`extend_test`) a test the demonstrates the [desired behavior](https://github.com/dials/dials/blob/extend_test/tests/array_family/test_flex_shoebox.py#L142-L163).

**Comment by rjgildea** [comment]
It might be better to leave the existing `reflection_table.extend()` method as a relatively dumb method, and then add an explicit function e.g. `combine_reflection_tables()` that can contain more complex logic. I suspect most of the time

C.f. [`pd.DataFrame.append`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html) vs. [`pd.concat`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html).

Some of this functionality kind of already exists but is spread across multiple functions that often need to be chained, e.g. the numerous functions in [`dials.util.multi_dataset_handling`](https://github.com/dials/dials/blob/main/util/multi_dataset_handling.py):

https://github.com/dials/dials/blob/7df0b0d85b49b0387d179523f2d9f969e1f63f71/command_line/cosym.py#L344-L356

Whether it's possible to come up with a single function that can cover all possible use cases I don't know - but it does seem that as soon as you try and put more complex logic into `reflection_table.extend()` then someone will find another use case that isn't covered by the initial added logic.

**Comment by phyy-nx** [comment]
Good points, and I'm supportive a custom method with a custom name that does the kind of concatenation I described above.

**Comment by jbeilstenedmands** [comment]
I'm looking through the code to find some current usage.
Example 1, for example after indexing, when you might have a list of reflection tables (each of which may contain data from multiple experiments):
```
tables_list = renumber_table_id_columns(tables_list)
for table in tables_list:
    indexed_reflections.extend(table)
```
The `renumber_table_id_columns` function is this, and perhaps could be made more elegant:
```
def renumber_table_id_columns(reflection_tables):
    """Renumber the id columns in the tables from 0..n-1
    If set, the experiment identifiers mapping is updated.

    Args:
        reflection_tables (list): A list of reflection tables

    Returns:
        (list): A list of reflection tables.
    """

    new_id_ = 0
    for table in reflection_tables:
        table_id_values = sorted(set(table["id"]).difference({-1}), reverse=True)
        highest_new_id = new_id_ + len(table_id_values) - 1
        expt_ids_dict = table.experiment_identifiers()
        new_ids_dict = {}
        new_id_ = highest_new_id
        orig_id = copy.deepcopy(table["id"])
        for val in table_id_values:
            sel = orig_id == val
            if val in expt_ids_dict:
                # only delete here, add new at end to avoid clashes of new/old ids
                new_ids_dict[new_id_] = expt_ids_dict[val]
                del expt_ids_dict[val]
            table["id"].set_selected(sel.iselection(), new_id_)
            new_id_ -= 1
        new_id_ = highest_new_id + 1
        if new_ids_dict:
            for i, v in new_ids_dict.items():
                expt_ids_dict[i] = v
    return reflection_tables
```

**Comment by jbeilstenedmands** [comment]
As a test, taking inspiration from Richard's mention of `pd.concat`, I tried to wrap the above code in a simple `flex.reflection_table.concat` function, which passes your test. I've pushed this to the `extend_test` branch, (and renamed the test to `test_concat`), as a starting point for this work.

**Comment by jbeilstenedmands** [comment]
A slightly different issue that we might need to take into account is the `imageset_id` column. I found that I had to also use the `dials.util.multi_dataset_handling.update_imageset_ids` function, else scaled data would not show properly in the image viewer. After integration, I don't think we (dials-east) use the `imageset_id` for anything processing related, as everything can be handled by the identifiers and properly tracking back to imagesets. Do you find you need to specially handle the `imageset_id` too?

**Comment by phyy-nx** [comment]
Your changes look like exactly what I'm looking for.  Thanks!

No need to micro-manage the `imageset_id` column in xfel land.  We don't use it.
