### ISSUE TITLE
Adding seaborn library

### ISSUE THREAD

**Issue by mevol** [dials/dials#1985]
Can you please add "seaborn" to dials-python?
I would like to use dials-python, scikit-learn and seaborn within it to train the metrix-ml models. This would make it easier for Irakli to deploy the models at Diamond.

Currently, my scripts fail as there is no seaborn available and I don't have permission to add it.

Also, seaborn may have some nice plotting features for you anyway.

**Comment by ndevenish** [comment]
Hi @mevol, DIALS doesn't actually use seaborn for anything so it isn't a dependency of this package. I suspect that you are asking for it to be added to internal DIALS installations at Diamond, which which I shall follow up with you internally.
