### ISSUE TITLE
Eiger imageset slicing

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#199]
# Background
The bugs listed below are preventing users from running dials.combine_experiments on the experiment.json files created from processing Eiger data as stills using dials.stills_process.  Therefore, these users cannot refine metrology using joint refinement.

These tests were performed at dials.lbl.gov using the eiger16MNov2015 nearly nexus dataset.

# Problem 1: Slice a datablock.json's imageset
$ cd /net/dials/raid1/aaron/dectris/eiger16MNov2015/2015_11_10/test
$ dials.import ../insu6_1_master.h5
$ cat show_bug_1.py
```
from dxtbx.datablock import DataBlockFactory
from dxtbx.imageset import ImageSet
import sys
datablocks = DataBlockFactory.from_json_file(sys.argv[1], check_format=False)
imageset = datablocks[0].extract_imagesets()[0]
print imageset._indices
subset = imageset[100:101]
print subset._indices
```

$ libtbx.python show_bug_1.py datablock.json
[0]
[0]

Expected result: a list of available images numbers in the imageset

# Problem 2: slice an imageset created by DataBlockFactory.from_filenames
$ cd /net/dials/raid1/aaron/dectris/eiger16MNov2015/2015_11_10/test
$ cat show_bug_2.py
```
from dxtbx.datablock import DataBlockFactory
from dxtbx.imageset import ImageSet
import sys
datablocks = DataBlockFactory.from_filenames([sys.argv[1]])
imageset = datablocks[0].extract_imagesets()[0]
print imageset._indices
subset = imageset[100:101]
print subset._indices

sliced_datablock = DataBlockFactory.from_imageset(subset)[0]

from dxtbx.datablock import DataBlockDumper
dump = DataBlockDumper(sliced_datablock)
dump.as_json("sliced_datablock.json")

roundtrip_datablock = DataBlockFactory.from_json_file("sliced_datablock.json")[0]
print roundtrip_datablock.extract_imagesets()[0]._indices
dump = DataBlockDumper(roundtrip_datablock)
dump.as_json("roundtrip_datablock.json")
```
$ libtbx.python show_bug_2.py ../insu6_1_master.h5
[0, \<snip\>, 899]
[100]
[0]

Expected result:
[0, \<snip\>, 899]
[100]
[100]

$ diff sliced_datablock.json roundtrip_datablock.json
Files are identical, as expected

# Problem 3: remove scan and gonio from datablock
$ cd /net/dials/raid1/aaron/dectris/eiger16MNov2015/2015_11_10/test
$ cat show_bug_3.py
```
from dxtbx.datablock import DataBlockFactory
from dxtbx.imageset import ImageSet
import sys
datablocks = DataBlockFactory.from_filenames([sys.argv[1]])
imageset = datablocks[0].extract_imagesets()[0]
print imageset._indices
subset = imageset[100:101]
print subset._indices
subset = ImageSet(subset.reader(), subset.indices())
subset.set_scan(None)
subset.set_goniometer(None)
print subset._indices

sliced_datablock = DataBlockFactory.from_imageset(subset)[0]

from dxtbx.datablock import DataBlockDumper
dump = DataBlockDumper(sliced_datablock)
dump.as_json("sliced_datablock.json")

roundtrip_datablock = DataBlockFactory.from_json_file("sliced_datablock.json")[0]
print roundtrip_datablock.extract_imagesets()[0]._indices
dump = DataBlockDumper(roundtrip_datablock)
dump.as_json("roundtrip_datablock.json")
```
$ libtbx.python show_bug_3.py ../insu6_1_master.h5
[0, \<snip\>, 899]
[100]
[100]
[0, \<snip\>, 899]

Expected result:
[0, \<snip\>, 899]
[100]
[100]
[100]

$ diff sliced_datablock.json roundtrip_datablock.json
Files are very different. Expected result: files are identical

# Problem 4: sliced experiment list
$ cd /net/dials/raid1/aaron/dectris/eiger16MNov2015/2015_11_10/test
$ cat show_bug_4.py
```
from dxtbx.datablock import DataBlockFactory
from dxtbx.model.experiment.experiment_list import ExperimentListFactory
from dxtbx.imageset import ImageSet

import sys
datablocks = DataBlockFactory.from_filenames([sys.argv[1]])
imageset = datablocks[0].extract_imagesets()[0]
print imageset._indices
subset = imageset[100:101]
print subset._indices

from dxtbx.model.crystal import crystal_model
crystal = crystal_model((1,0,0),(0,1,0),(0,0,1),'P1')
experiments = ExperimentListFactory.from_imageset_and_crystal(subset, crystal)
print experiments[0].imageset._indices

from dxtbx.model.experiment.experiment_list import ExperimentListDumper
dump = ExperimentListDumper(experiments)
dump.as_json("sliced_experiments.json")

experiments = ExperimentListFactory.from_json_file("sliced_experiments.json")
print experiments[0].imageset._indices
dump = ExperimentListDumper(experiments)
dump.as_json("roundtrip_experiments.json")
```
$ libtbx.python show_bug_4.py ../insu6_1_master.h5
[0, \<snip\>, 899]
[100]
[100]
[0]

Expected result:
[0, \<snip\>, 899]
[100]
[100]
[100]

$ diff sliced_experiments.json roundtrip_experiments.json
```
17c17
<       "template": "../insu6_1_master.h5",
---
>       "template": "/net/dials/raid1/aaron/dectris/eiger16MNov2015/2015_11_10/insu6_1_master.h5",
```
Expected result: files are identical

# Problem 5: remove scan and gonio from experiment list with sliced imageset
$ cd /net/dials/raid1/aaron/dectris/eiger16MNov2015/2015_11_10/test
$ cat show_bug_5.py
```
from dxtbx.datablock import DataBlockFactory
from dxtbx.model.experiment.experiment_list import ExperimentListFactory
from dxtbx.imageset import ImageSet

import sys
datablocks = DataBlockFactory.from_filenames([sys.argv[1]])
imageset = datablocks[0].extract_imagesets()[0]
print imageset._indices
subset = imageset[100:101]
print subset._indices
subset = ImageSet(subset.reader(), subset.indices())
subset.set_scan(None)
subset.set_goniometer(None)
print subset._indices

from dxtbx.model.crystal import crystal_model
crystal = crystal_model((1,0,0),(0,1,0),(0,0,1),'P1')
experiments = ExperimentListFactory.from_imageset_and_crystal(subset, crystal)
print experiments[0].imageset._indices

from dxtbx.model.experiment.experiment_list import ExperimentListDumper
dump = ExperimentListDumper(experiments)
dump.as_json("sliced_experiments.json")

experiments = ExperimentListFactory.from_json_file("sliced_experiments.json")
print experiments[0].imageset._indices
dump = ExperimentListDumper(experiments)
dump.as_json("roundtrip_experiments.json")
```
$ libtbx.python show_bug_5.py ../insu6_1_master.h5
[0, \<snip\>, 899]
[100]
[100]
[100]
Traceback (most recent call last):
  File "show_bug_5.py", line 25, in <module>
    experiments = ExperimentListFactory.from_json_file("sliced_experiments.json")
  File "/net/cci-filer2/raid1/home/aaron/projects/phenix-src/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 979, in from_json_file
    return ExperimentListFactory.from_json(infile.read(), check_format)
  File "/net/cci-filer2/raid1/home/aaron/projects/phenix-src/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 969, in from_json
    check_format)
  File "/net/cci-filer2/raid1/home/aaron/projects/phenix-src/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 954, in from_dict
    experiments = ExperimentListDict(obj, check_format).decode()
  File "/net/cci-filer2/raid1/home/aaron/projects/phenix-src/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 439, in decode
    self._ilist = self._extract_imagesets()
  File "/net/cci-filer2/raid1/home/aaron/projects/phenix-src/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 502, in _extract_imagesets
    raise TypeError('expected int or str, got %s' % type(value))
TypeError: expected int or str, got <type 'list'>

Expected result: no crash.  Cannot test if the roundtrip json is identical to the sliced json.

**Comment by phyy-nx** [comment]
Hi James, these tests are not fixed for me.  Further, the original bug from dials.combine_experiments seems to still be present.  I'm happy to work on this too when I get back into the lab.

Details:

Problem # 1 is unchanged for me (still broken)
Problem # 2 is also still broken, it gives me this output:
[0, <snip>, 899]
[100]
[0]
and this diff:

$ diff sliced_datablock.json roundtrip_datablock.json
16c16
<           100
---
>           0

Problem # 3, the output is now correct, but the diff still shows the roundtripped files are not identical
Problem # 4, I still get this output:
[0, <snip>, 899]
[100]
[100]
[0]
The diffs are not identical (file name is changed)
Problem # 5 no longer crashes and I get the expected output. However, the diff shows the roundtripped files are not identical.

**Comment by jmp1985** [comment]
# Problem 1

Output:

[0...899]
[100]
[0]

# Problem 2

Output:

[0...899]
[100]
[100]

sliced_datablock.json and roundtrip_datablock.json are now the same.

# Problem 3

Output:

[0...899]
[100]
[100]
[100]

sliced_datablock.json and roundtrip_datablock.json are now the same.

# Problem 4

Output:

[0...899]
[100]
[100]
[100]

sliced_experiments.json and roundtrip_experiments.json are now the same.

# Problem 5

Output:

[0...899]
[100]
[100]
[100]
[100]

sliced_experiments.json and roundtrip_experiments.json are now the same.
