### ISSUE TITLE
MPI crashes/hangs after importing uuid (!)

### ISSUE THREAD

**Issue by dwpaley** [dials/dials#1998]
This week we had some very weird headaches on large (1600 process) `cctbx.xfel.merge` jobs. We learned the following:

* NERSC systems generally use MPICH, which does not guarantee safety when `fork`ing processes. 
* The `uuid` module checks the platform on import by calling `platform.system()`, which ultimately forks off a call to the system `uname`.
* When 1600 ranks all import `uuid` it's often enough to kill MPI communication. It's a very nasty bug because it's inconsistent and scale-dependent.
* We fixed this by adding the following lines at the top of `merge.py`:
```
def monkeypatch(): return sys.platform.capitalize()
import platform
platform.system = monkeypatch
```
This gives the correct results for OSX and Linux (`Darwin` and `Linux` respectively) although basically by coincidence. Other meaningful return values for `platform.system()` include `AIX` and `Windows` although I'm sure there are others; in these cases `sys.platform.capitalize()` doesn't give the right answer.

If MPI-safety is of general interest, then all instances of `import uuid` should have something like this monkeypatch (or a nicer version) to prevent forking a subprocess. Otherwise it will be needed in client code and it will be a land mine if not present. I'm not aware of any similar failures in `dials.stills_process`, but it could become relevant if kHz data collection requires bigger MPI indexing runs.

Credit to @nksauter @phyy-nx @JBlaschke @bkpoon for a team effort on identifying this issue.

**Comment by dwpaley** [comment]
Should have mentioned that these are the two places dials imports uuid:

https://github.com/dials/dials/blob/ed5cefad33024763da360eea615debd1277a4452/util/multi_dataset_handling.py#L11
https://github.com/dials/dials/blob/ed5cefad33024763da360eea615debd1277a4452/algorithms/scaling/scaling_library.py#L15

and one more in dxtbx:

https://github.com/cctbx/dxtbx/blob/e65d01176cf6ddbc9b44e957ee66d52b843dfc54/src/dxtbx/format/FormatHDF5EigerNearlyNexus.py#L4

**Comment by graeme-winter** [comment]
I think we can safely ignore the `dxtbx` instance as this is not actually "useful" 

```
        temp_file = "tmp_master_%s.nxs" % uuid.uuid1().hex
```

For the multi-data-set handling I suspect we can encapsulate this import / monkeypatch combination _into_ `generate_experiment_identifiers` so then at least we don't pepper the code with weirdness. 

`./algorithms/scaling/scaling_library.py` could probably use `generate_experiment_identifiers` in place of "raw" `uuid` call. 

Looking at the docs - 

"Get the hardware address as a 48-bit positive integer. The first time this runs, it may launch a separate program, which could be quite slow. If all attempts to obtain the hardware address fail, we choose a random 48-bit number with the multicast bit (least significant bit of the first octet) set to 1 as recommended in [RFC 4122](https://tools.ietf.org/html/rfc4122.html). “Hardware address” means the MAC address of a network interface. On a machine with multiple network interfaces, universally administered MAC addresses (i.e. where the second least significant bit of the first octet is unset) will be preferred over locally administered MAC addresses, but with no other ordering guarantees."

It looks like if we want to do this "right" we will need to do something more than "macOS" here -> the monkeypatch idea could be OK but the detail of the patch is a discussion topic. 

However - in MPI is _every_ rank having to execute every import function on one machine? Then sending jobs across? Or is every rank in its own address space, and executes until you get to a "hold up, this is where we do MPI things" line?

**Comment by graeme-winter** [comment]
Additional:

```
uuid.uuid4()
  Generate a random UUID.
```

maybe we don't care _that_ much about correctness, but the other thing could be useful to know.

**Comment by Anthchirp** [comment]
Yes, we only use uuid4, where we can copy over the implementation as needed.

Fixing uuid itself is a feature request on cpython, imho.

**Comment by graeme-winter** [comment]
```
def uuid4():
    """Generate a random UUID."""
    return UUID(bytes=os.urandom(16), version=4)
```

Looks like a very reasonable suggestion 👍

**Comment by graeme-winter** [comment]
```
        if bytes is not None:
            if len(bytes) != 16:
                raise ValueError('bytes is not a 16-char string')
            assert isinstance(bytes, bytes_), repr(bytes)
            int = int_.from_bytes(bytes)  # big endian
```

and 

```
    def __str__(self):
        hex = '%032x' % self.int
        return '%s-%s-%s-%s-%s' % (
            hex[:8], hex[8:12], hex[12:16], hex[16:20], hex[20:])
```

probably enough to add to `dials/util/uuid.py` (say) - if I get a chance tomorrow will have a go

**Comment by dwpaley** [comment]
Unfortunately there's a second one just like this but more widespread. When importing `pandas`, `numexpr` gets imported as an optional dependency. `numexpr` calls `platform.machine()` on import, which also makes a subprocess. This is also enough to kill MPI on the new machine at NERSC.

I know two fixes, both pretty unappealing. One is just deleting `numexpr`. The other is adding another monkeypatch before any import of `pandas`:

```
def mp_machine():
  return 'x86_64'
import platform
platform.machine = mp_machine
```

Haven't checked whether any other packages also depend (optionally or otherwise) on `numexpr`.

**Comment by Anthchirp** [comment]
Can't you do all necessary monkeypatching in cctbx.xfel? Or patch cpython platform on your install?

**Comment by graeme-winter** [comment]
> Unfortunately there's a second one just like this but more widespread. When importing `pandas`, `numexpr` gets imported as an optional dependency. `numexpr` calls `platform.machine()` on import, which also makes a subprocess. This is also enough to kill MPI on the new machine at NERSC.
> 
> I know two fixes, both pretty unappealing. One is just deleting `numexpr`. The other is adding another monkeypatch before any import of `pandas`:
> 
> ```
> def mp_machine():
>   return 'x86_64'
> import platform
> platform.machine = mp_machine
> ```
> 
> Haven't checked whether any other packages also depend (optionally or otherwise) on `numexpr`.

OK, on this one you'll need to monkeypatch `cctbx.xfel` as @Anthchirp  suggetss as we support multiple processor architectures and this is likely to have very unpredictable results. PR incoming for the `uuid` related issues.

**Comment by graeme-winter** [comment]
> Unfortunately there's a second one just like this but more widespread. When importing `pandas`, `numexpr` gets imported as an optional dependency. `numexpr` calls `platform.machine()` on import, which also makes a subprocess. This is also enough to kill MPI on the new machine at NERSC.
> 
> I know two fixes, both pretty unappealing. One is just deleting `numexpr`. The other is adding another monkeypatch before any import of `pandas`:
> 
> ```
> def mp_machine():
>   return 'x86_64'
> import platform
> platform.machine = mp_machine
> ```
> 
> Haven't checked whether any other packages also depend (optionally or otherwise) on `numexpr`.

Thinking some more about this one, it does feel like something which someone else has probably dealt with upstream 🤔

UUID + large MPI ranks _could_ be unusual behaviour but I would think `pandas` and large MPI ranks strikes me as something which is done by more people & there is probably a better idiomatic solution than monkey patching around `platform.machine` (which really feels like a _bad_ monkey patch) 

I return to a set of questions mentioned above in https://github.com/dials/dials/issues/1998#issuecomment-1030540033 - are you sure this is right @dwpaley ?

**Comment by dwpaley** [comment]
> which really feels like a _bad_ monkey patch

Right, that wasn't a suggestion, more of an illustration :)

> However - in MPI is every rank having to execute every import function on one machine? Then sending jobs across? Or is every rank in its own address space, and executes until you get to a "hold up, this is where we do MPI things" line?

The second one is correct. You fully execute `-n` copies of the program and at certain points they might do different things based on their rank number (I'm rank 0, I will do server stuff/I'm rank !=0, I will do client stuff). On global operations the execution pauses until everybody syncs up.

I'm also surprised that this seems to be the first anyone is hearing of this. `numexpr` has been calling `platform.machine()` on import for at least several years. MPICH claims to handle forks safely if you set some environment variables, so the fact that doesn't work maybe implies that something is misconfigured in our installation. No idea how widespread this problem might be.

It's true that we can fix the immediate problem (`cctbx.xfel.merge` doesn't work) by applying monkeypatches from inside our own application. However. What would you think about moving `import pandas` inside function bodies when possible? That would give a bit of insurance against the future case where we try to run `stills_process` on 500 nodes and everything mysteriously breaks.

I might open an issue in numexpr after reflecting on this for the rest of the weekend.

Thank you @graeme-winter for your quick work on the local implementation of `uuid4`!

**Comment by dwpaley** [comment]
Hi Nick, I identified it by putting `assert False` in the `subprocess.Popen` constructor:

```
>>> import uuid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pscratch/sd/d/dwpaley/dials/20221126/alcc-recipes/cctbx/opt/mamba/envs/psana_env/lib/python3.8/uuid.py", line 57, in <module>
    _AIX     = platform.system() == 'AIX'
  File "/pscratch/sd/d/dwpaley/dials/20221126/alcc-recipes/cctbx/opt/mamba/envs/psana_env/lib/python3.8/platform.py", line 891, in system
    return uname().system
  File "/pscratch/sd/d/dwpaley/dials/20221126/alcc-recipes/cctbx/opt/mamba/envs/psana_env/lib/python3.8/platform.py", line 857, in uname
    processor = _syscmd_uname('-p', '')
  File "/pscratch/sd/d/dwpaley/dials/20221126/alcc-recipes/cctbx/opt/mamba/envs/psana_env/lib/python3.8/platform.py", line 613, in _syscmd_uname
    output = subprocess.check_output(('uname', option),
  File "/pscratch/sd/d/dwpaley/dials/20221126/alcc-recipes/cctbx/opt/mamba/envs/psana_env/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/pscratch/sd/d/dwpaley/dials/20221126/alcc-recipes/cctbx/opt/mamba/envs/psana_env/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/pscratch/sd/d/dwpaley/dials/20221126/alcc-recipes/cctbx/opt/mamba/envs/psana_env/lib/python3.8/subprocess.py", line 740, in __init__
    assert False
```

This is a little more clear:
```
$ strace -e fork,vfork,clone python3 -c 'import platform; print("<<<<<"); print(platform.system()); print(">>>>>>")'
<<<<<
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5457fdca10) = 6662
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=6662, si_uid=1526, si_status=0, si_utime=0, si_stime=0} ---
Linux
>>>>>>
+++ exited with 0 +++
```

**Comment by ndevenish** [comment]
Ahah, that explains the difference. The early-subprocess call was removed so only the `processor` part would use it, and it wasn't called unless specifically requested, in https://github.com/python/cpython/commit/518835f3354d6672e61c9f52348c1e4a2533ea00

**Comment by ndevenish** [comment]
Is this specifically an MPI problem that this happens in the middle of running otherwise fully-connected analysis? Wondering if e.g. adding an `import uuid`/`import platform; platform.uname()` in the `dxtbx/__init__.py` or, say, `cctbx/xfel/__init__.py`, before the MPI connection is set up, do the job?

**Comment by dwpaley** [comment]
If I understand it correctly, the MPI environment is configured at job
startup by `srun` or `mpirun`. The `mpi_helper` checks and stores some
information like rank number and total job size, but all that stuff has
already been set up. So I don't believe Python has any opportunity to do
anything before configuring MPI. Maybe @jblaschke can see if this sounds
right...

**Comment by JBlaschke** [comment]
Hi Folks,

just catching up on my messages. This issue is one of those "How did this even work in the first place?" -- basically `system`, `fork`, `popen` can result in undefined behaviour in the underlying transport used by MPI (the MPI standard does not require `fork`ing to work, so naturally different MPI implementations will support is to varying degress). This has lead to `uuid` working just fine until now:

1. https://docs.nersc.gov/development/languages/python/using-python-perlmutter/#python-issues
2. also: https://www.open-mpi.org/faq/?category=openfabrics#ofa-fork

@dwpaley is right: the MPI fabric is not meant to be reconfigured after `srun`/`mpirun` -- i.e. `srun` begins by configuring the transport layer and configuring all of the resources, and then it launches MPI program. So by the time that Python runs its first line of code, the resources that MPI relies on are already configured.

Depending on where the bug is there might be hope: 
1. If the issue is in MPI then calling `fork` _before_ `MPI.Init` might actually work
2. If the issue is in `libverbs` (i.e. the transport layer) then we would have to call `fork` _before_ srun configures the transport layer: that might be possible with some advanced use of `PMI2` https://wiki.mpich.org/mpich/index.php/PMI_v2_API

One last tangent: Before trying either of these, you could try:
```python
from mpi4py import 

if MPI.COMM_WORLD.Get_rank() == 0:
    x=uuid()

MPI.COMM_WORLD.Barrier()

# communicate the value of x the the other ranks
```
This is likely not going to work -- as `MPI.COMM_WORLD.Barrier()` does need to do _some_ communication. I bring this up because I didn't see any crashes occur on `Barrier` (just the other collectives)
