### ISSUE TITLE
dials.reciprocal_lattice_viewer: Drawing area not updated on window resize

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#2]
Steps to reproduce:
dials.import $files
dials.find_spots datablock.json
dials.reciprocal_lattice_viewer datablock.json strong.pickle
(window opens, resize window to full screen)
click with middle mouse button on reciprocal lattice, dragging it to all corners of the window

Expected behaviour:
Lattice moves around

Actual behaviour:
Lattice is not visible when moved outside a box described by the original window size

**Comment by rjgildea** [comment]
I don't see this in my local builds (mac or linux), only in module load
dials/nightly. What is different about the nightly builds? I see this error
message in dials/nightly, which may be related:

(reciprocal_lattice_viewer.py:23407): Gtk-CRITICAL **:
gtk_widget_set_size_request: assertion `width >= -1' failed

(reciprocal_lattice_viewer.py:23407): Gtk-CRITICAL **:
gtk_widget_set_size_request: assertion `width >= -1' failed

(reciprocal_lattice_viewer.py:23407): Gtk-CRITICAL **:
gtk_widget_set_size_request: assertion `width >= -1' failed

(reciprocal_lattice_viewer.py:23407): Gtk-CRITICAL **:
gtk_widget_set_size_request: assertion `width >= -1' failed

Any ideas?

**Comment by Anthchirp** [comment]
Oh. Confirmed here, too.

(However, my local build does not do fonts for some unrelated reason :( )

**Comment by dagewa** [comment]
I think I have seen this too, possibly at the Okinawa workshop. It will be
worth keeping this in mind when we check the CCP4 build of DIALS.

-- David

**Comment by Anthchirp** [comment]
This is not a relocation problem, and can be reproduced with a freshly bootstrapped copy.

@rjgildea Am I correct in assuming that when you run
```bash
ls $(libtbx.show_build_path)/../base/lib/libwx_baseu-*so
```
on your working linux copy, you get a 2.8 version?

**Comment by rjgildea** [comment]
Should be fixed as of cctbx r:23569
http://sourceforge.net/p/cctbx/code/23569/

**Comment by Anthchirp** [comment]
Confirmed fixed deployed version. Many thanks for this.
