### ISSUE TITLE
Use partial reflections

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#200]
Currently, partial reflections (some pixels out of the rotation range, in a detector gap, masked, etc) are completely rejected. Can we keep them and scale-up by the partiality calculated from the empirical profile (c.f. MINPK keyword and PEAK column in XDS). 

I found the multiplicity is slightly less than other programs, which is not very serious in most cases but does matter for small-wedge datasets with high mosaicity (e.g. LCP microcrystals).

**Comment by graeme-winter** [comment]
They are only excluded in the export stage by default - you can include them by using:

  include_partials = False
  keep_partials = False

*yes* this is confusing... include_partials allows adjacent reflections to be summed to make a full, then scales them up to a "full" based on the partiality. keep_partials is about them going into the MTZ file. I for one acknowledge that this is confusing and is also my fault as I think I wrote the original code in here...

Will investigate more fully & get back to you - thank you for asking this.

**Comment by biochem-fan** [comment]
Hi Graeme,

Thank you very much, but I am still confused. What do you mean by "adjacent reflections to be summed to make a full"? In 3D profile fitting, unlike 2D profile fitting in MOSFLM, we have only one entry in `integrated.pickle` regardless of the number of the frames where the reflection was observed, don't we?

Suppose a reflection is located in phi = -0.3 deg to 0.7 deg and we collected data from phi = 0.0 to 0.7 deg at 0.1 deg / frame. Thus, we are missing reflections from -0.3 deg to 0.0 deg. What happens to this reflection? And what if part of the reflection fall upon masked pixels?

**Comment by graeme-winter** [comment]
Your case you describe below would come out with a partiality < 1 & would by default be rejected - however if you elect to keep these then it would remain.

Adjacent reflections summing means if we have a reflection which was not contained within one integration block, the two parts of it are added - these are very few & are unlikely to be well measured anyway. If you look at some of the slides from @jmp1985 this will be clearer.

**Comment by biochem-fan** [comment]
Aha! I got it.

> some of the slides from @jmp1985

Where is it?

**Comment by graeme-winter** [comment]
http://cci.lbl.gov/dials/6/James_Parkhurst.pdf I expect contains the material you seek - if not will dig out (am in location with limited network right now)

**Comment by biochem-fan** [comment]
Thanks.
