### ISSUE TITLE
Selecting minor cluster in dials.cosym

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#2005]
I am working on a multi-crystal small-molecule MicroED dataset. Indexing and integrating in P1, I realized that this dataset contained two crystal forms.

`dials.cosym` separated these two populations when I lowered the `threshold` to 100.
However, I could not get information about the minor population (hexagonal) because `dials.cosym` proceeded with the largest cluster. `xia2.multiplex` also didn't help, because xia2's own clustering was performed after `dials.cosym` selected the largest cluster.

`unit_cell_clustering.log=True` made cosym more verbose but the list of experiment identifiers is cryptic and the list is only for the largest cluster.

It would be nice if the program could:
- analyze the Patterson group of the minor cluster (P6/mmm or something lower?)
- show the lists of crystals belonging to each cluster, so that I can re-process them in the right Patterson group

```
    2 clusters:

    Cluster_id       N_xtals  Med_a         Med_b         Med_c         Med_alpha    Med_beta     Med_gamma   Delta(deg)

i
    2 in P1.
    cluster_3        2        9.76  (0.01 ) 9.81  (0.00 ) 12.36 (0.08 ) 89.55 (0.11) 89.73 (0.24) 60.56 (0.13)
         P 6/m m m (No. 191)  9.81          9.81          12.36         90.00        90.00        120.00        0.85

    26 in P1.
    cluster_4        26       8.10  (0.08 ) 8.76  (0.12 ) 8.89  (0.18 ) 89.95 (0.84) 89.88 (0.74) 89.85 (0.62)
         P 4/m m m (No. 123)  8.82          8.82          8.10          90.00        90.00        90.00         0.91


    Standard deviations are in brackets.
    Each cluster:
    Input lattice count, with integration Bravais setting space group.
    Cluster median with Niggli cell parameters (std dev in brackets).
    Highest possible metric symmetry and unit cell using LePage (J Appl Cryst 1982, 15:255) method, maximum delta 3deg.
    Selecting subset of 26 datasets for cosym analysis: ['f7b0c1c0-cf4e-4504-b6f5-0ef94657dfef', 'c2751d3a-9346-494f-9c35-b60f574a486f', '15dbc4bd-70f8-45be-9eae-41cae5341532', '29a3c1d8-9afc-404c-baa1-129973925ba7', 'f79fe3d3-340a-49d9-b100-4ba3dfb88e0e', '182c0a3c-5c6e-41b0-9615-a683ff3eba75', '6ebb6773-538e-4e34-86c8-e5b5bfedf37d', 'ce21ad1d-f578-45a3-8f81-bff3b34056ab', '337c6e79-7f29-41b7-adce-fd850f521241', 'ad402e5c-ee0e-44b9-8561-a0aa398e5f49', '32cc5bdf-a1ac-4076-9318-ed659cb5b769', '5809eb57-9083-4611-bbc4-2301a48b935a', 'ce04e1ee-cbe5-4f18-8741-919372a401ad', '08f815e7-3f8b-46d6-a697-866e894d7a29', '77bf95e4-26ec-4f39-a313-e5501eb0e544', '28167da0-45c7-4a80-bd07-28a0d465843c', '8923b430-7ed7-4fd5-b365-04d526081491', 'c35f2e0f-ac94-4ea6-99ae-5db239c19414', 'dfd2450c-c715-498c-b272-b6dd49ee793f', 'df32ceb8-1052-424b-87c3-a5a3748e74e9', '47de088e-8168-4fc5-ba54-03997485343d', '7a24557c-c955-4920-a955-f28d00f84d22', 'd931456a-1d1d-493a-93f1-fc87c363035e', '5afc921e-3e0d-4f43-904b-2c268d2c16a2', '626a3eb1-d896-4d4c-bd8d-3ea0d234d3c7', '5f3dde00-5124-4ce0-8ae8-3a8aba448f67']
```

**Comment by jbeilstenedmands** [comment]
Hi @biochem-fan 
I recently added a new feature to `dials.cluster_unit_cell` which I think can help for your use case. If you set `output.clusters=True`, then a file pair for each cluster is created, which could then be processed individually with `dials.cosym`

**Comment by biochem-fan** [comment]
Wonderful! This command did what I wanted to do.

I also managed to get the list of images in a cluster by
```
dials.show cluster_1.expt |grep template| cut -f3 -d" "
```
