### ISSUE TITLE
dials.import needlessly pedantic & rather annoying

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#202]
Trying to import 11,000 images, this works fine for a while then I get:

```
[gw56@cs04r-sc-com99-01 import]$ dials.import /dls/i24/data/2016/nt14493-9/processing/DIALS/spotfinding/zurich/CORRECT_BEAMXY/images
DIALS 1.dev.677-g0e81abc
Sorry: Unable to handle the following arguments:
  /dls/i24/data/2016/nt14493-9/processing/DIALS/spotfinding/zurich/CORRECT_BEAMXY/images/.adxv_beam_center
```

after like *10 minutes* then have to work out how to ignore this file...

Surely we should be able to ignore some files in a directory which are clearly not images?? I did not even add this as a command-line argument, it "discovered" it.

**Comment by graeme-winter** [comment]
Slightly less grumpy suggestion - if input passed is a directory interpret this as directory=

**Comment by jmp1985** [comment]
I've added a parameter ignore_unhandled=True/False that can be used to ignore unhandled arguments. The reason why we throw an exception by default is that when people use dials on their datasets where images are corrupt or missing (seems to happen a lot at workshops) it becomes less obvious when they complain about indexing failures etc. In the past it's been useful to flag this during import; however the flip side of this is that in the current implementation passing a directory with other stuff in by default will fail if there is weird stuff in there.
