### ISSUE TITLE
test_dials_cluster_unit_cell_command_line_output_files fails on Windows

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2027]
Captured stdout shows
```
No reflection data found in the input
```

**Comment by dagewa** [comment]
Ok, I think this might be because the `dials_regression` I have on Windows is a minimal `dials_regression` that includes only files that were touched by tests. Does that mean a720ccd5e added a new dependency to data in `dials_regression`?

**Comment by dagewa** [comment]
It looks like that is the case, because the other tests that look in `dials_regression/refinement_test_data/multi_narrow_wedges` (`test_refine_multi_wedges.py` and `test_combine_experiments.py`) use files called `reflections.pickle`, not `indexed.pickle`

**Comment by dagewa** [comment]
Unfortunately, changing the test to use `reflections.pickle` rather than `indexed.pickle` fails on Windows anyway because

```
E       AssertionError: assert not 1
E        +  where 1 = ReturnObject(args=('C:\\Users\\fcx32934\\sw\\cctbx\\build\\bin\\dials.combine_experiments.BAT', 'C:\\Users\\fcx32934\\...w_wedges\\data\\sweep_048\\reflections.pickle'), returncode=1, stdout=b'', stderr=b'The command line is too long.\r\n').returncode
```
i.e. `The command line is too long.`

**Comment by jbeilstenedmands** [comment]
I don't think that commit specifically introduced a dependency on new test data, as it uses the same input as the test above ``test_dials_cluster_unit_cell_command_line``

**Comment by jbeilstenedmands** [comment]
Sorry please ignore the above comment, this new test does rely on new data (it uses experiment and reflection data, rather than just experiment data like the test abve)

**Comment by jbeilstenedmands** [comment]
I wonder if this will work if you add the extra line below the reflections list:
```
reflections = list(data_dir.glob("data/sweep_*/indexed.pickle"))
reflections = [f"input.reflections={i}" for i in reflections]

**Comment by jbeilstenedmands** [comment]
This should have been fixed in https://github.com/dials/dials/pull/2028 ?
