### ISSUE TITLE
[Feature Request] dials.symmetry Should Use a Fourier Analysis to Detect Screw Axes

### ISSUE THREAD

**Issue by kmdalton** [dials/dials#2042]
As discussed in  #1742, Fourier analysis is an effective strategy to detect screw axes which is robust to systematic errors in background estimates. [Pointless](http://scripts.iucr.org/cgi-bin/paper?S090744491003982X), appears to use such a strategy to detect screw axes. Currently, `dials.symmetry` finds screw axes by testing whether systematic absences are significantly different from zero. It would be better if `dials.symmetry` _also_ implemented a Fourier approach. There is some example numpy code in #1742 which might be helpful.

**Comment by dagewa** [comment]
Here is a link to a dataset from a user, for which `dials.symmetry` returns P2, but `pointless` (correctly) chooses P21. https://drive.google.com/file/d/1F-Epkowjmo9CMJ_ltqticgERs-sV6GNZ/view?usp=sharing

**Comment by kmdalton** [comment]
I had a look into these data, @dagewa. Indexing actually fails for a different reason. Namely, these are not indexed in the appropriate convention when `dials.symmetry` passes them to `dials.algorithms.symmetry.absences.run_absences_checks.run_systematic_absences_checks`. This leads to the program searching the wrong axis for systematic absences. I'll try to look into this more this week, but I am afraid I am juggling a lot right now. It feels like it might be a bug.

**Comment by kmdalton** [comment]
I _think_ [this](https://github.com/dials/dials/compare/main...kmdalton:dials:main) is a fix for the P21 data set. Although I'm a little bleary eyed.

**Comment by dagewa** [comment]
Ah I see, sorry @kmdalton I didn't realise this was a different underlying issue. Thanks for the suggested fix. Perhaps it is easiest to set this up as a PR. I think @rjgildea and/or @jbeilstenedmands are probably best placed to look at it

**Comment by kmdalton** [comment]
Yes, agreed. I'll try to submit a PR this afternoon.

**Comment by kmdalton** [comment]
And thanks for that data set, it was helpful. Perhaps we can add it to the tests.

**Comment by kmdalton** [comment]
resolved by #2184
