### ISSUE TITLE
DIALS has a cyclic dependency on the xfel module

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#2076]
At some point we developed a circular dependency on the "optional" xfel module. This takes the form of usage of`xfel.clustering.cluster.Cluster` and ` xfel.clustering.cluster_groups.unit_cell_info`. Since the conda-forge/cctbx[-base] conda packages don't include xfel, this is a blocker to `conda install dials` - at the very least, we should make it an optional dependency again.

The places that appear to use unqualified imports are:
- [ ] [`dials.cosym`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/command_line/cosym.py#L11) uses `unit_cell_info` for output.
- [ ] [`dials.combine_experiments`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/command_line/combine_experiments.py#L20) uses `unit_cell_info` for output, and imports `.cluster` for `Cluster`.
- [ ] [`dials.cluster_unit_cell`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/command_line/cluster_unit_cell.py#L13-L14) uses both,
- [ ] and so does [`algorithms/indexing/analysis.py`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/algorithms/indexing/ssx/analysis.py#L12-L13).
- [ ] Finally, [`algorithms/clustering/unit_cell.py`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/algorithms/clustering/unit_cell.py#L6) uses `Cluster` only.

The `unit_cell_info`-only cases like cosym look reasonably easy to deal with - it's just parts of the output, so could pretty easily be moved to import-dependent output, in case the `xfel` modules is missing. The usage of `Cluster` is a little more complex - I don't have a good understanding of how easy/hard it'd be to replace these, either moving some of the code into dials or using something in scipy/scikit-learn for replacing it.

**Comment by ndevenish** [comment]
Other, embedded uses (e.g. doesn't get pulled in by simply importing, so less problematic):

- [ ] `dials.still_process` uses [`xfel.cxi.cspad_ana`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/command_line/stills_process.py#L905) in debug-write mode, [`xfel.util.sublattice_helper`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/command_line/stills_process.py#L1226) in integration when `dispatch.coset=` is set, and [`xfel.command_line.frame_extractor `](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/command_line/stills_process.py#L1417) when `integration_pickle=` output is requested.
- [ ] `algorithms/indexing/nave_parameters.py` uses [`xfel.mono_simulation.max_like.minimizer`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/algorithms/indexing/nave_parameters.py#L98) and [`xfel.mono_simulation.util.green_curve_area`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/algorithms/indexing/nave_parameters.py#L155).
- [ ] [`tests/algorithms/indexing/ssx/test_analysis.py`](https://github.com/dials/dials/blob/cafaf4df9454b1a63cac2940322784d0ca020fc7/tests/algorithms/indexing/ssx/test_analysis.py#L140) uses `Cluster` in a unit test. This is reasonably easy to skip if not present.

**Comment by phyy-nx** [comment]
The issues listed here are in the dials-->xfel direction.  The xfel-->dials direction is also worth considering.  Specifically, code like `cctbx.xfel.merge` [has compile time dependencies on](https://github.com/cctbx/cctbx_project/blob/master/xfel/merging/ext.cpp#L17) the dials reflection table. So the cctbx-base conda package, which includes the xfel python files, can't be extended to compile the xfel c++ libraries as that would add a dials dependency.

A similar issue is the reliance of simtbx (including nanoBragg and diffBragg) on dxtbx, [where](https://github.com/cctbx/cctbx_project/blob/master/simtbx/kokkos/detector.h#L14-L15) [three](https://github.com/cctbx/cctbx_project/blob/master/simtbx/gpu/detector.h#L15-L16) [locations](https://github.com/cctbx/cctbx_project/blob/master/simtbx/nanoBragg/nanoBragg.h#L18-L19) use dxtbx's detector and beam models.

Simply stated, how will a user use conda to get a working build of cctbx.xfel?  I think we'll need to build separate conda packages for cctbx.xfel and simtbx, that installs putative cctbx-base, dials, and dxtbx conda packages, and then can compile against the headers those packages include.

**Comment by phyy-nx** [comment]
Hi, some updates after some conversations on the xfel stuff.  I see this being resolved in 3 stages:

1. Move any dials.stills_process and nave_parameters import statements that use xfel to try/except statements that notify the user if the xfel module is available. Also continue the current process I see going on about breaking the xfel cluster dependency in dials.  With these tasks done, the cctbx_project/xfel module is no longer a dials dependency (in the libtbx.configure sense).
2. When the dials conda package is built, dials.stills_process won't work.  If users need it they can still get dials binaries from dials.github.io or build it custom for psana.  This is an intermediate state.  It would be nice if the user runs dials.stills_process that an under construction message be printed out.
3. Once the dials conda package is available, we'll create a cctbx.xfel conda package which configures xfel and includes any xfel compiled libraries.  This package will bring in cctbx-base, dxtbx, and dials conda packages.  Likewise we'll make a simtbx package which depends on dxtbx.

How does this sound?  I think this handles the dependencies nicely.

**Comment by Anthchirp** [comment]
I think overall this sounds reasonable. I think an obvious suggestion at this point would be to move the `dials.stills_process` entrypoint into the `xfel` package.

Also, just for information, the pypi package name `xfel` is as of yet unclaimed :wink:

**Comment by phyy-nx** [comment]
Progress update.  At this point the circular dependency is broken on these `serial_tbx` branches of dials, cctbx, and dxtbx.  All the xfel imports in dials and dxtbx now point to code in serialtbx, or have been directly ported in to dials and dxtbx.

Next week I'll run all the tests on my local system, and when I get those passing I'll put in draft PRs.

BTW there are 4 other repos affected by this.  So the simultaneous merge of 7 repos will be interesting.  @ndevenish how do you want to approach this from a release perspective?
