### ISSUE TITLE
Hardcoded inequality inconsistent with error message

### ISSUE THREAD

**Issue by PrinceWalnut** [dials/dials#2084]
In https://github.com/dials/dials/blob/0cda7353e6c8a5facb5705399f3cfbabd83eee3a/algorithms/integration/integrator.py#L559-L563 there is a `<=0` check on a reflection column, but the error message suggests it should be simply a `<0` check. This can break certain reflection tables where this column is set with hypothetically 0 variance (e.g. overridden values).

**Comment by dagewa** [comment]
Sorry it took so long for anyone to look at this! I agree the error message did not match. Rather than changing the message I thought let's try changing the equality, to support the overridden values use case you hinted at. The tests all seem to pass, so it seems like that was a safe change.
