### ISSUE TITLE
Overly Restrictive KeyError compares lengths instead of one list being a subset of another

### ISSUE THREAD

**Issue by PrinceWalnut** [dials/dials#2085]
Per Slack discussions with @jbeilstenedmands the following error was agreed to be overly restrictive, since there may be more `id_values` than requested in `list_of_identifiers`.
https://github.com/dials/dials/blob/0cda7353e6c8a5facb5705399f3cfbabd83eee3a/array_family/flex_ext.py#L1164-L1171

**Comment by graeme-winter** [comment]
@jbeilstenedmands can we assign this one to you to have a look at?
