### ISSUE TITLE
Add params dictionary to dxtbx format class and propagate from dials.import

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#209]

**Comment by rjgildea** [comment]
Initial parameters that need supporting include:

dynamic_shadowing(=False)

and something along the lines of supporting selection of single-panel vs multi-panel detectors (e.g. P6M or P12M - although the latter is between 24 and 120 panel version rather than single panel)

**Comment by jmp1985** [comment]
This is now in place. Parameters are now propagated; however, they are not used at the moment. Each format class now has a **kwargs thing in its constructor. Parameters are handled during import and are serialised in json and pickle etc.
