### ISSUE TITLE
Centroids and viewer

### ISSUE THREAD

**Issue by DrTheMick** [dials/dials#211]
Starting a few days ago I have been unable to index or look at the threshold map on any of my data sets. When clicking on the threshold tab in dials.image_viewer datablock.json, I get this error in the terminal:

 File "/Users/############/Desktop/dials/modules/dials/util/spotfinder_frame.py", line 599, in get_raw_data
    goniometer_shadow_mask=self.params.goniometer_shadow_mask)
TypeError: get_mask() got an unexpected keyword argument 'goniometer_shadow_mask'

Additionally, if I go through with spot finding and use dials.index I am getting autotype error for the max cell. Putting in a reasonable max cell, it then attempts to index using 0 centroids. Resulting in:

Setting d_min: 2.34
FFT gridding: (256,256,256)
Number of centroids used: 0
Sorry: Indexing failed: fft3d peak search failed to find sufficient number of peaks.

Things had been working well until recently. Thank you for your help.

**Comment by Anthchirp** [comment]
Which version of DIALS are you running? (try ``` dials.version```)

**Comment by DrTheMick** [comment]
DIALS 1.dev.745-g2390ee9

**Comment by rjgildea** [comment]
Sorry, missed commit in recent changes, now fixed: https://sourceforge.net/p/cctbx/code/25413

**Comment by Anthchirp** [comment]
Since you are using a development version you'll have to update the svn repository in modules/cctbx_project (ie. ```cd modules/cctbx_project; svn up```)
That should solve the problem

**Comment by Anthchirp** [comment]
relevant patch is https://github.com/cctbx/cctbx/commit/e1b60a8abd4d2855ef9b2bb908923c701022d671

**Comment by DrTheMick** [comment]
Thank you. This has fixed the image viewer issue, but the indexing using 0 centroids and inevitably failing. Dials version DIALS 1.dev.745-g2390ee9
cctbx At revision 25416.

**Comment by Anthchirp** [comment]
@DrTheMick I have moved that issue to its own ticket in #213.
