### ISSUE TITLE
Make scan slicing sane

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2111]
Though this rapidly becomes a yak shaving expedition - should we refactor `slice_sequence` to be a thing wrapper around an API, then use this API everywhere? 🤔

_Originally posted by @graeme-winter in https://github.com/dials/dials/issues/1227#issuecomment-613402516_

This :arrow_up: seems a good idea that was never acted upon. Correctly doing this would fix the latest issue on helpdesk, plus probably also latent open issues such as #2098, #1227, #587...

**Comment by ndevenish** [comment]
I think some work/investigation has happened on this, but I don't think leaving this ticket open is going to be the driving factor.

**Comment by dagewa** [comment]
This is somewhat better these days, even if we are not using the same code in all places.
