### ISSUE TITLE
dials.index: autotype error for max cell

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#213]
Reported by @DrTheMick in #211:
```
if I go through with spot finding and use dials.index I am getting autotype error
for the max cell. Putting in a reasonable max cell, it then attempts to index
using 0 centroids. Resulting in:

Setting d_min: 2.34
FFT gridding: (256,256,256)
Number of centroids used: 0
Sorry: Indexing failed: fft3d peak search failed to find sufficient number of peaks.

Things had been working well until recently. Thank you for your help. 
```
Dials version DIALS 1.dev.745-g2390ee9
cctbx At revision 25416.

**Comment by rjgildea** [comment]
It's not exactly clear what you mean by autotype error? What is the exact command line you are using?

**Comment by DrTheMick** [comment]
Here is the error I get when attempting to index and the entire process:

**dials.estimate_gain datablock.json** 
The following parameters have been modified:

input {
  datablock = datablock.json
}

q1, q2, q3: 4.68, 5.22, 6.11
Estimated gain: 5.11

**dials.find_spots datablock.json spotfinder.threshold.xds.gain=5.11 spotfinder.mp.nproc=64**

Extracted 150043 spots
Removed 133215 spots with size < 6 pixels
Removed 2557 spots with size > 100 pixels
Calculated 14271 spot centroids
Calculated 14271 spot intensities
Filtered 11984 of 14271 spots by peak-centroid distance

Histogram of per-image spot count for imageset 0:
11984 spots found on 227 images (max 371 / bin)

**dials.index datablock.json strong.pickle indexing.nproc=64**
DIALS 1.dev.755-gd7c7905
The following parameters have been modified:

indexing {
  nproc = 64
}
input {
  datablock = datablock.json
  reflections = strong.pickle
}

/.../dials/base/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/.../dials/build/../modules/dials/command_line/index.py", line 176, in <module>
    run(sys.argv[1:])
  File "/.../dials/build/../modules/dials/command_line/index.py", line 153, in run
    params=params)
  File "/.../dials/modules/dials/algorithms/indexing/indexer.py", line 533, in from_parameters
    idxr = indexer_fft3d(reflections, imagesets, params=params)
  File "/.../dials/modules/dials/algorithms/indexing/fft3d.py", line 33, in __init__
    super(indexer_fft3d, self).__init__(reflections, imagesets, params)
  File "/.../dials/modules/dials/algorithms/indexing/indexer.py", line 473, in __init__
    self.index()
  File "/.../dials/modules/dials/algorithms/indexing/indexer.py", line 721, in index
    experiments.extend(self.find_lattices())
  File "/.../dials/modules/dials/algorithms/indexing/fft3d.py", line 49, in find_lattices
    5 * max_cell / self.params.fft3d.reciprocal_space_grid.n_points)
TypeError: unsupported operand type(s) for *: 'int' and 'AutoType'

**dials.index datablock.json strong.pickle indexing.nproc=64 max_cell=80**

The following parameters have been modified:

indexing {
  nproc = 64
  max_cell = 80
}
input {
  datablock = datablock.json
  reflections = strong.pickle
}

Setting d_min: 1.56
FFT gridding: (256,256,256)
**Number of centroids used: 0**
Sorry: Indexing failed: fft3d peak search failed to find sufficient number of peaks.

Apologies for the delay. I was out of town for a few days.

**Comment by rjgildea** [comment]
Do the results of spotfinding look sensible? e.g.
`dials.reciprocal_lattice_viewer datablock.json strong.pickle`
Could you send the datablock.json and strong.pickle to dials-support@lists.sourceforge.net ?

**Comment by hattne** [comment]
This turned out to be an issue completely unrelated to DIALS--the data conversion pipelines from the microscopes had inadvertently gotten out-of-sync.  Unless @DrTheMick objects, I think the issue can be closed as invalid.
