### ISSUE TITLE
Image viewer: if low resolution screen user cannot see all of "controls"

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2142]
Found during workshop, apparently impossible to resolve.

**Comment by graeme-winter** [comment]
e.g. was < HD it is pretty much unusable. Some element of display scaling would be useful.

**Comment by dwpaley** [comment]
While this is far from a *fix*, on XFCE I can alt-click on the body of a
dialog and drag it around the screen. I believe MacOS has a similar trick.
This could be a band-aid for the situation where you can't reach the bottom
of a dialog that is too tall for the screen. (h/t @phyy-nx)

**Comment by dagewa** [comment]
The settings window was made more compact in #2753. I suspect screens with such low resolution that controls are not visible are now rare enough that this can be closed.
