### ISSUE TITLE
dials.check_indexing_symmetry needs sanity checks

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#215]
Needs sanity checks if nref is too small to give any sensible answer:

```
nproc=`libtbx.show_number_of_processors`
dials.import $(libtbx.find_under_build xia2_regression)/test_data/i04_bag_training/th_8_2_*.cbf
dials.find_spots datablock.json nproc=$nproc scan_range=1,5 scan_range=268,272 scan_range=536,540
dials.index datablock.json strong.pickle
dials.check_indexing_symmetry experiments.json indexed.pickle grid_search_scope=1 symop_threshold=0.7
```

output:

```
Checking HKL origin:

dH dK dL   Nref    CC
-1  0 -1     20 0.769
-1  1  0     20 0.863
 0  0  0     41 -0.052
 0  1 -1     14 0.719
 1  0  0     20 0.898
 1  0  1     18 0.765
```

**Comment by dagewa** [comment]
With the merge of #825, the SE is printed alongside the CCs if the SE is significant at the level of the number of digits reported. This makes it possible for the user to assess the relevance of results from the grid search in `test_P1_crystal_indexing`

In addition, within `test_crystal_pointgroup_symmetry`, the acceptable element indicator `***` is only added to rows where the CC is greater than the `symop_threshold` at the 95% confidence level.

**Comment by rjgildea** [comment]
@dagewa perhaps I'm missing something, but it isn't clear to me how this helps for the specific case above. This output still suggests that a reindexing of +0,-1,+1 or +0,+1,-1 is ok, even though the initial indexing (i.e. 0,0,0) is correct in this case? I.e. a CC of 0.903 +/- 0.012 and 0.901 +/- 0.010?
```
Checking HKL origin:

dH dK dL   Nref    CC
-1 -1 -1     28 0.07(4)
-1 -1  0     18 0.01(6)
-1  0 -1     12 0.04(10)
-1  0  0     18 0.77(3)
-1  0  1     28 0.17(4)
-1  1 -1     24 0.14(4)
-1  1  1     20 0.14(5)
 0 -1 -1     18 0.25(6)
 0 -1  0     20 0.80(2)
 0 -1  1     18 0.903(12)
 0  0  0     20 0.28(5)
 0  1 -1     20 0.901(10)
 0  1  1     28 0.05(4)
 1 -1 -1     24 0.57(3)
 1  0 -1     14 0.50(6)
 1  0  0     10 0.83(4)
 1  0  1     18 0.39(5)
 1  1  0     20 0.79(2)
 1  1  1     14 0.27(8)
```

**Comment by dagewa** [comment]
That does indeed seem to be what the correlation coefficients suggest.
