### ISSUE TITLE
Error when opening Reciprocal lattice viewer on windows

### ISSUE THREAD

**Issue by WilliamLewis-X-ray** [dials/dials#2153]
When I try to open the reciprocal lattice viewer I get the error below in the command line console, and the viewer does not open. Otherwise DIALS and DUI seems to be running ok, as I have fully processed a dataset.

Traceback (most recent call last):
  File "C:\dials\modules\cctbx_project\boost_adaptbx\boost\python.py", line 22, in import_ext
    try: mod = __import__(name)
ImportError: DLL load failed while importing gltbx_glu_ext: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dials\modules\dials\src\dials\command_line\reciprocal_lattice_viewer.py", line 16, in <module>
    from dials.util.reciprocal_lattice.viewer import ReciprocalLatticeViewer, phil_scope
  File "C:\dials\modules\dials\src\dials\util\reciprocal_lattice\viewer.py", line 22, in <module>
    from dials.util import wx_viewer
  File "C:\dials\modules\dials\src\dials\util\wx_viewer.py", line 14, in <module>
    import gltbx.glu as glu
  File "C:\dials\modules\cctbx_project\gltbx\glu.py", line 3, in <module>
    ext = bp.import_ext("gltbx_glu_ext")
  File "C:\dials\modules\cctbx_project\boost_adaptbx\boost\python.py", line 31, in import_ext
    raise ImportError(
ImportError: __import__("gltbx_glu_ext"): DLL load failed while importing gltbx_glu_ext: A dynamic link library (DLL) initialization routine failed.
  sys.path:
    C:\dials\modules\dials\src\dials\command_line
    C:\dials\modules\xia2\src
    C:\dials\modules\dials\src
    C:\dials\modules\dxtbx\src
    C:\dials\modules\cctbx_project
    C:\dials\modules
    C:\dials\modules\cctbx_project\boost_adaptbx
    C:\dials\build\lib
    C:\dials\conda_base\lib\site-packages
    C:\dials\conda_base
    C:\dials\dui_files
    C:\dials\conda_base\python39.zip
    C:\dials\conda_base\DLLs
    C:\dials\conda_base\lib
    c:\dials\dui-2021.11.1\dui-2021.11.1\src
    C:\dials\conda_base\lib\site-packages\win32
    C:\dials\conda_base\lib\site-packages\win32\lib
    C:\dials\conda_base\lib\site-packages\Pythonwin

**Comment by dagewa** [comment]
Hi, how did you install DIALS on Windows? There are various ways, which might produce different results. If you let me know exactly what you did I'll try to reproduce the issue. Thanks

**Comment by WilliamLewis-X-ray** [comment]
Hi, apologies, I meant to write back earlier, but time got away with me. I installed dials by downloading following https://github.com/dials/dials/wiki/DIALS-on-Windows. I ran bootstrap. 

I have run bootstrap again, and sent the output to a file, which is attached:
[output.txt](https://github.com/dials/dials/files/9128784/output.txt)

**Comment by dagewa** [comment]
@WilliamLewis-X-ray sorry for the delay. Can you try this again? My latest build worked successfully. You can also try `python.exe bootstrap.py --cmake` as another way to build now

**Comment by ndevenish** [comment]
This should be solved in the next release, 3.19.
