### ISSUE TITLE
In reciprocal lattice viewer please can we have smarter colouring

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#217]
i.e. if we have background_rgb=a,b,c then point colours are derived to be contrasting to this - for printing could be very helpful - we already have rotating colour schemes for different experiments, maybe just need to take complement of these if rgb=1,1,1 in first instance.

**Comment by rjgildea** [comment]
Is this resolved?

**Comment by graeme-winter** [comment]
No not really as it only currently works if background_rgb=0,0,0 or 1,1,1, what if background=0.5,0.5,0.5 or something silly?
