### ISSUE TITLE
Simple 2D integration

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2170]
@ronandrevon needs frame-by-frame intensity measurements, similar to the software PETS, for use in dynamic-diffraction based refinement procedures for electron diffraction.

It seems to me that this might actually be rather simple to do, especially with @toastisme's simple integration script. We could do everything up to background subtraction, and then just do a frame-by-frame summation integration of pixels inside the peak mask. We would not have 2D profile fitting like MOSFLM, but it would at least be a start.

**Comment by ndevenish** [comment]
@dagewa, is this something you are still interested in?

**Comment by dagewa** [comment]
Yes, but a little less now that Tarik has left. No sense in keeping this around indefinitely.
