### ISSUE TITLE
expose serial number from detector object

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#219]
Can we have a feature to expose information identifying the image source, in particular the detector serial number. Something along the lines of
```
print detector.get_serial_number()
print detector.identify()
print detector.serial_number
```

**Comment by graeme-winter** [comment]
Suggest we just use "identity" here i.e. serial number implies it is a ... number

What we want is for the dxtbx object to have a unique string which can be used to identify it i.e. P6M-100 is fine. Adding a test somewhere that they are unique would be even better...

**Comment by Anthchirp** [comment]
Would use the information in the image headers, for example for I19 this would be ```PILATUS 2M, S/N 24-0107 Diamond```. Keeping it too concise just means collisions.

**Comment by jmp1985** [comment]
I've added a get/set_identifier method to the panel class. This should be set in the format classes

**Comment by Anthchirp** [comment]
Thank you. Is panel (and not detector) the right place for this though?

**Comment by Anthchirp** [comment]
Relevant commit is cctbx/cctbx@4c8305a961886cae22bebb892f5a274a1bdc2914

**Comment by jmp1985** [comment]
I don't mind too much. I added the info to the panel class because other info resides there rather than in the detector class. Also, I think the original design was that we would be able to support multiple detectors in principle which may have different identifiers I guess.
________________________________
