### ISSUE TITLE
DIALS cheatsheet is chronically out of date

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#2193]
The [DIALS "cheatsheet"](https://drive.google.com/file/d/0B0yDAeP5vfI7aW5ORWdORHVmOGs/preview?resourcekey=0-0QJL2EeUv6nv0UB4d0tPIg) is rather out of date and could do with updating (e.g. it still refers to .json and .pickle extensions rather than .expt and .refl respectively).

**Comment by murpholinox** [comment]
Also... is there a way to get the documentation into a single pdf ...?
instead of a lot of html files?
https://dials.github.io/documentation/programs/dials_*.html

**Comment by dagewa** [comment]
I had a go at updating this now. Nice to see the website automatically shows the document updated on Google Drive https://dials.github.io/documentation/programs/index.html
