### ISSUE TITLE
Get the xfel_regression tests running

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#2214]
As noticed in #2209, the xfel_regression tests do not appear to be running.

[Recent log](https://dev.azure.com/azure-dials/8f9a0b14-1c65-4a82-9c06-1ec7513061ae/_apis/build/builds/9339/logs/68)

**Comment by ndevenish** [comment]
I think it did run on that job - https://dev.azure.com/azure-dials/dials/_build/results?buildId=9339&view=logs&j=728b758c-216d-5daa-c333-7c882b66b365&t=85fcb9b8-652b-5a8e-53be-fa3ac0301275

I think it's just the reporting step that something has broken, and that it doesn't run the tests if everything else failed?

**Comment by phyy-nx** [comment]
Ah ok, so it's just that report that isn't working.  That's good to see.

I also see what you mean that if the "Run tests" step fails, the "Run xfel_regression tests" step isn't run.  That's ok with me, as look as when xfel_regression is ran and it fails, that the whole job is marked as failed.

Thanks fo rlooking into this :)
