### ISSUE TITLE
Remove dependency on wxPython?

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2217]
See #2216  for some background but generally the wxPython tools are increasingly hard to maintain. Moving to e.g. PyQt / PySide or similar would be a useful discussion topic. Should we finally accept that the image viewer and reciprocal lattice viewer (and other wxPython GUI tools) need replacing?

**Comment by graeme-winter** [comment]
Hard bit will be finding the effort to make this happen though 😞

**Comment by luisodls** [comment]
If you ask me: what is better between WxPython and PySide: I would say: For certain PySide, I have worked with both and I prefer PySide.

However, to change now is going to be a very big endeavour, if we find resources / developer(s) to do that it will take a while and it should be done incrementally.

It worth commenting that part of the job for the image viewer is already done, I made reusable the code for the embedded image viewer in DUI2, and it uses PySide2, it's a t least a starting point.

**Comment by graeme-winter** [comment]
> If you ask me: what is better between WxPython and PySide: I would say: For certain PySide, I have worked with both and I prefer PySide.
> 
> However, to change now is going to be a very big endeavour, if we find resources / developer(s) to do that it will take a while and it should be done incrementally.
> 
> It worth commenting that part of the job for the image viewer is already done, I made reusable the code for the embedded image viewer in DUI2, and it uses PySide2, it's a t least a starting point.

Thinking some more about this I think I mis-posed the question - the question should not (I think) be about GUI toolkit more about adopting something which already exists - and it is noteworthy that @dagewa has the RLV already prototyped in [napari](https://github.com/napari/napari) and I was somewhat successful in putting together a functional if basic image viewer in the same. 

An audit of which tools we have that would need porting could be useful - image, reciprocal lattice and geometry viewers jump to mind...

**Comment by graeme-winter** [comment]
For reference [this](https://gist.github.com/graeme-winter/0f6f4ba32d1b9c468047c87bf20868dd) was my previous attempt (not recently re-tested)

**Comment by biochem-fan** [comment]
One consideration when choosing a library is whether it is happy with X11 forwarding. Some libraries require advanced OpenGL and are not compatible with `ssh -X`. Others work but are very sluggish; compare scrolling log files in the CCP4 old viewer (Tk) and GUI 2 (Qt).

Although there are advanced solutions like VirtualGL, NoMachine, x2go etc but they are not necessarily available on users' side.

**Comment by graeme-winter** [comment]
> One consideration when choosing a library is whether it is happy with X11 forwarding. Some recent libraries require advanced OpenGL and are not compatible with `ssh -X`. Others work but are very sluggish; compare scrolling log files in the CCP4 old viewer (Tk) and GUI 2 (Qt).
> 
> Although there are advanced solutions like VirtualGL, NoMachine, x2go etc but they are not necessarily available on users' side.

Testing `napari` over an ssh connection: very useful suggestion thank you

**Comment by ndevenish** [comment]
> One consideration when choosing a library is whether it is happy with X11 forwarding. Some recent libraries require advanced OpenGL and are not compatible with `ssh -X`. Others work but are very sluggish; compare scrolling log files in the CCP4 old viewer (Tk) and GUI 2 (Qt).

yes, this direction has troubled me for a while; I attempted to bring this problem up in one of the "Modern image viewer" community meetings but there didn't seem much interest in discussion.

It seems to be getting harder and harder to actually get this to work - and when it does it's almost always on server-side rendering and just sending the bitmaps (e.g. I think QT has an environment setting for this). Conversely, we have also however had reports with issues getting the X DIALS viewers running on more modern distributions with only Wayland.

I wonder if at some point we are going to have to decide as a community whether we can afford to either continue supporting or abandoning this support case.

**Comment by graeme-winter** [comment]
"I wonder if at some point we are going to have to decide as a community whether we can afford to either continue supporting or abandoning this support case."

That's an interesting question. Wondering: polling ccp4bb -> some kind of survey online thing

**Comment by dwpaley** [comment]
At a couple important facilities here (LCLS and NERSC) there are multiple clusters controlled via a single NX server. In those cases there is an `ssh -X` connection between the NX server and the cluster. Of course those connections are within the facility, so it's probably ok if the application uses heavy bandwidth when forwarded over ssh; but without significant sysadmin effort at (each of!) these facilities, we'll still need X forwarding.

**Comment by graeme-winter** [comment]
Balance is probably leave things as is until pushed
