### ISSUE TITLE
dials.import override detector distance workaround

### ISSUE THREAD

**Issue by dagewa** [dials/dials#222]
@jmp1985 This is the simplest workaround I could think of. Could we at import have a translate_detector=x,y,z parameter, which will move everything by the specified vector (i.e. including the root frame)? Therefore, to get my distance changed from 100 to 409.47 mm for the case I'm looking at I would import with translate_detector=0,0,-309.47.

Then, to make this clearer I will set the dummy detector's distance in the format to 0, and my translate vector will be 0,0,-409.47

**Comment by dagewa** [comment]
...but more generally the existing mechanism for overriding the detector geometry at dials.import presents a problem. We can override the panels, but not the panel groups higher up in the hierarchy. This means you can end up 'peeling' the panels off the root frame, so that a hierarchical detector that should have all levels in the hierarchy coplanar is no longer coplanar. That affects how the detector is parameterised for refinement.

**Comment by jmp1985** [comment]
Fixed in commit b3ba0b543be34f1285d2c225f8b149583de5badc

**Comment by dagewa** [comment]
I'm not sure `translate_detector` really does what it should, or I don't understand it. For example, a simple single-panel detector:

```
dials.import $(libtbx.find_in_repositories dials_regression)/data/i04-BAG-training/th_8_2_0*cbf
```
gives me a datablock in which

```
        "hierarchy": {
          "origin": [
            0.0, 
            0.0, 
            0.0
...
```

and the position is entirely determined within the panel:

```
        "panels": [
          {
            "origin": [
              -210.7602, 
              205.27684000000002, 
              -265.27
            ], 
...
```

Later refinement may move the panel around, but the hierarchy origin stays at 0,0,0.

However, if I import with `translate_detector`:

```
dials.import $(libtbx.find_in_repositories dials_regression)/data/i04-BAG-training/th_8_2_0*cbf \
  translate_detector=1,1,-100 output.datablock=translated_datablock.json
```

then the change is applied to the root:

```
        "hierarchy": {
          "origin": [
            1.0, 
            1.0, 
            -100.0
...
```

and the panel is the same as before
```
            "origin": [
              -210.7602, 
              205.27684000000002, 
              -265.27
...
```

I suppose for a single panel detector where the hierarchy is not normally relevant this is equivalent to putting the translation into the panel directly and leaving the hierarchy alone. But the result is confusing. Perhaps `translate_detector` should operate on the panel origin when there is only one panel and therefore the hierarchy is irrelevant?

I realise I did originally ask for this to move the root frame, but I think that is appropriate only for real multi-panel detectors, where the hierarchy has meaning.

**Comment by jmp1985** [comment]
Hi David,

I can't remember why it behaves the way it does, but I'm happy to modify it if it's confusing.

So am I right in saying:

1. In the case of a single panel detector, you'd like the translation to be applied directly to the panel.
2. In the case of a multi panel detector, you'd like it applied to the hierarchy.

James

________________________________

**Comment by dagewa** [comment]
Hi James, yes, I think exactly that, for now. 

Thinking back though, the whole thing was to get around the problem that you can't override a detector root frame in `dials.import`, you can only override the panels. For this case, probably I shouldn't have been using `translate_detector`, because I could have just overridden the panel (although that is annoying too, because you can't set the `origin` without also setting `fast` and `slow`, even when they shouldn't change).

Maybe ultimately we need a better way to override the detector geometry at `dials.import` that works for both real hierarchical detectors and single panel detectors.

**Comment by jmp1985** [comment]
You can now specify the complete detector hierarchy, so you can offset the whole detector by setting the origin in the root node (and also groups if present)

**Comment by dagewa** [comment]
Great, I'll try to figure it out, though if I get stuck an example would be useful.

**Comment by jmp1985** [comment]
You can see the phil scope usage in dxtbx/model/{beam,detector,goniometer,scan}.py There is also a test is tst_import.py. Let me know if you need more/better examples!
