### ISSUE TITLE
Xia2/DIals requisites?

### ISSUE THREAD

**Issue by murpholinox** [dials/dials#2226]
What is the software needed to run `xia2 pipeline=$VAR blahblahblah`; where $VAR is: 3d 3dii dials dials-aimless?

Do I need to install the full ccp4 suite? to run dials-aimless? 

Thanks a lot... and sorry to make this an issue.

**Comment by murpholinox** [comment]
Thanks. 
And if $VAR = 3d, then I only need XDS programs... right?

**Comment by graeme-winter** [comment]
No, you still need CCP4 as well because of the above jiffies etc. 

If people _really_ wanted a CCP4-free xia2, we could investigatie it, but hard to justify
