### ISSUE TITLE
dials.refine: possible to block-diagonalise the matrix?

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2235]
If we have 

```
dials.refine indexed.expt indexed.refl
```

Where the input experiments are completely decoupled i.e. there are no common experiment models would it be possible / sensible to block-diagnonalise the problem and then iterate over the blocks which are then "dense"

N.B. here I am talking strictly about zero / non-zero overlap but with ensemble processing it is _very_ easy to end up with a massive block diagonal matrix e.g. 

```
Detecting centroid outliers using the MCD algorithm
14283 reflections have been flagged as outliers
103640 reflections remain in the manager

Summary statistics for 103640 observations matched to predictions:
+-------------------+---------+----------+------------+---------+--------+
|                   |     Min |       Q1 |        Med |      Q3 |    Max |
|-------------------+---------+----------+------------+---------+--------|
| Xc - Xo (mm)      | -0.5099 | -0.01803 |  0.0004293 | 0.01852 | 0.4753 |
| Yc - Yo (mm)      |  -0.245 | -0.01287 |  0.0005945 | 0.01348 | 0.2513 |
| Phic - Phio (deg) |  -1.852 | -0.01099 | -5.917e-05 | 0.01096 |  1.687 |
| X weights         |    1236 |     1929 |       2011 |    2068 |   2133 |
| Y weights         |    1308 |     2034 |       2085 |    2112 |   2133 |
| Phi weights       |   931.7 |     1188 |       1200 |    1200 |   1200 |
+-------------------+---------+----------+------------+---------+--------+

There are 2625 parameters to refine against 103640 reflections in 3 dimensions
Performing refinement of 105 Experiments...
```

which probably has zero cross-talk between experiments (it could perhaps have non-zero in this case but the models are not coupled here.)

**Comment by graeme-winter** [comment]
For record: yes I know I can `dials.split_experiment` and `dials.combine_experiments` to achieve this but seems like it would be neat to decompose the problem inside the refinement program.

**Comment by dagewa** [comment]
This is an interesting idea and I'll think about how best to approach it. There is similar analysis done when the experiments are parameterised. We could figure out which blocks of experiments are independent then, and possibly return a list of Refiners rather than a single one. This list could then be iterated over to run refinement - possibly even in parallel.
