### ISSUE TITLE
new (sort of) dependency on `packaging`

### ISSUE THREAD

**Issue by dwpaley** [dials/dials#2242]
This cctbx_project PR: https://github.com/cctbx/cctbx_project/pull/797 will remove the `setuptools<60` version pin. It also eliminates a "backup" import of `packaging` from the vendored copy provided by pip. This is because with setuptools>=60 it's no longer safe to import anything from pip, doing so breaks setuptools as discussed here: https://github.com/pypa/setuptools/issues/3297 and other linked issues.

`packaging` does not get installed in a plain Python conda env, although there are many packages that pull it in as a dependency. I'm just flagging this in case you wish to add `packaging` as an explicit dependency, since the backup copy from pip is going away.

**Comment by ndevenish** [comment]
Ah, I think I know actually - it's the issue from https://github.com/cctbx/cctbx_project/commit/b80db8830a2f043908cd7fd5a077dfaeb6013be2, which hasn't made it through to our CI because it only uses builds that pass your testing, which none have yet.

**Comment by dwpaley** [comment]
Sorry about the `python` vs `sys.executable` bug.

The cctbx_project CI runs are failing from a second (different!) setuptools update that is discussed here: https://github.com/cctbx/cctbx_project/pull/802. It should be fixed today and the green checks will resume. In the meanwhile if you get a working cctbx_project build then you should be unaffected by the setuptools issue because you have your own conda envs with setuptools still pinned. (I do see a green check on the most recent cctbx_project commit with `[skip ci]` in the message, I wonder if that is sufficient for your CI to pull it in.)

About importing pip, the immediate problem is that setuptools uses a vendored, modified copy of distutils, and pip needs the unmodified version, so they end up stepping on each other's imports. That part of the problem is fixed by quarantining `import pip` inside a subprocess. I do understand that `import pip; print(pip.__version__)` is not promised to be supported forever, but if we did `pip --version` then we would have to parse that output in some way that also isn't certain to be future-proof.
