### ISSUE TITLE
reflection_table.sort('miller_index') doesn't work

### ISSUE THREAD

**Issue by dagewa** [dials/dials#225]
sort says

```
    Sort the reflection table by a key.

    :param name: The name of the column
    :param reverse: Reverse the sort order
```
but this uses flex.sort_permutation, which doesn't work for types such as miller_index or vec3_double. From 50cae9a dev.dials.sort_reflections is using Python's sorted instead to get around this. Prior to 3ad45d4 sort_reflections used to allow sorting on sub-elements e.g.  "miller_index:1,0,2" to sort by k,h then l, but this feature disappeared with the transition to using reflection_tables.

**Comment by jmp1985** [comment]
Should now work
