### ISSUE TITLE
python quits unexpectedly when closing image viewer on some macs

### ISSUE THREAD

**Issue by toastisme** [dials/dials#2250]
When manually closing the image viewer (i.e clicking the red x) on an M1 mac a python quit unexpectedly error appears. Does not seem to happen on ~~non M1 macs~~ my 2015 Intel MacBook running Catalina.

**Comment by graeme-winter** [comment]
Respectfully point out that this _does_ happen on my Intel MacBook -> is not M1 special. I have to Ctrl-C if I don't want the OS to complain.

**Comment by toastisme** [comment]
Respectfully noted.
