### ISSUE TITLE
Image viewer reports internal error when viewing non-consecutive images

### ISSUE THREAD

**Issue by nksauter** [dials/dials#2253]
When viewing two SMV-format images with non-consecutive sequence numbers, the image viewer reports a DXTBX_ASSERT error. 

/global/cfs/cdirs/lcls/sauter/test3> dials.image_viewer test_full_001.img test_full_100.img
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
dxtbx Internal Error: /global/cfs/cdirs/lcls/sauter/ly99/alcc-recipes/cctbx/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.

This code appears to be from a 2019 commit:
b4ef6a89b model/scan.h           (Nicholas Devenish               2019-10-17 10:55:51 +0100 314)       DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]);

**Comment by graeme-winter** [comment]
To be clear:

This is reporting an internal error but _does not fail_ 

```
Grey-Area thau-grid :) $ dials.image_viewer Thaumatin_1_00*1.cbf.gz
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(314): DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]) failure.
The following parameters have been modified:

input {
  experiments = <image files>
}
```

I share the view that this is not desirable behaviour, but I would tread carefully in assigning the "git blame" as I suspect that this is working around a different issue. 

https://github.com/cctbx/dxtbx/commit/b4ef6a89b

Is the link to the commit in question

Will have a proper look shortly (I have had this error crop up in other contexts as well)

**Comment by graeme-winter** [comment]
@nksauter thank you for reporting this. It was a long standing annoyance and the prod to fix it was appreciated.

**Comment by graeme-winter** [comment]
Oh, for documentation: the caught exception is `RuntimeError` which really _really_ should not be used to control program flow - see cctbx/dxtbx/#566
