### ISSUE TITLE
Migrate platform toward more modern C++

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2295]
See #2291 for motivation though more generally we have control over the compilers via conda so should give thought to moving to more up to date C++ standard. Seems pretty universally supported in the "usual" (i.e. non-prehistoric) compiler suites.

**Comment by graeme-winter** [comment]
Ah, looking at commentary for #2299 it is more a matter of updating the build system to _allow_ the compilers to work with modern C++. 

I wonder if "migrate the platform" is best achieved by adopting `cmake` for the builds. This would also align with most of the rest of the universe in terms of software compilation and smooth future transitions to e.g. other compilers (ohai oneAPI etc.)

**Comment by graeme-winter** [comment]
OK, this is looking more and more like a case for _removing deliberate incompatibility_ than adding anything e.g. 

```
./cctbx_project/libtbx/SConscript:        libtbx.env.build_options.env_cxxflags.replace('c++14', 'c++11').replace('c++17', 'c++11')
./cctbx_project/libtbx/SConscript:        libtbx.env.build_options.env_cppflags.replace('c++14', 'c++11').replace('c++17', 'c++11')
```

**Comment by dagewa** [comment]
I know there has been work on this recently, so can this be closed yet?

**Comment by ndevenish** [comment]
Yes, we now run on C++14. C++17 doesn't work yet because of, IIRC, usage of auto_ptr elsewhere in the system, but 14 probably qualifies.
