### ISSUE TITLE
Improve spot finder parameters for CCD/Image plate

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#23]

**Comment by jmp1985** [comment]
Implement David's suggestion of a script to perform a grid search of parameters on JCSG CCD data

**Comment by rjgildea** [comment]
Please can we try and collectively sort something out here - bad spotfinding with default parameters are one of the most common causes of problems at workshops and bug reports

**Comment by graeme-winter** [comment]
+1

**Comment by jmp1985** [comment]
I had a look at this a while back. I think best practice is to estimate the gain for the detector prior to spot finding and then set the gain in spot finding. It was difficult to find better default values for the parameters.



________________________________

**Comment by dagewa** [comment]
...With the caveat that the value you get from `dials.estimate_gain` is very often not an appropriate gain value for spot finding. With significant PSF, `dials.estimate_gain` underestimates severely. This was always true of e.g. MOSFLM, where the gain of ADSC modules is [set to 0.25](http://www.mrc-lmb.cam.ac.uk/harry/cgi-bin/keyword2.cgi?GAIN) to approximate Poisson statistics. A better gain for ADSC modules is 2.4 ADU/photon (came from the datasheet, now can't find it). James Holton estimates a gain of 1.8 for ADSC, but I think he was talking about the _real_ gain, which includes photons that are lost due to imperfect DQE. The gain we care about is that between the ADUs and the _detected_ photons.

**Comment by rjgildea** [comment]
Can we add this value of the gain to the relevant format classes?

**Comment by dagewa** [comment]
James Holton lists some gains for his [crystal size calculator](http://bl831.als.lbl.gov/xtalsize.html), but I think these might be real gains (including DQE). Not totally sure (perhaps we should check with him). From the source code:

```
    if( det == "ADSC Q210/315r (hwbin)")   { gain = 1.8 ; rn = 3   ; bg0 = 40; }
    if( det == "ADSC Q210/315r (swbin)")   { gain = 0.6 ; rn = 3   ; bg0 = 40; }
    if( det == "ADSC Q210/315r (unbin)")   { gain = 2.4 ; rn = 3   ; bg0 = 40; }
    if( det == "ADSC Q210/315 (hwbin)")    { gain = 2.4 ; rn = 4   ; bg0 = 40; }
    if( det == "ADSC Q210/315 (swbin)")    { gain = 0.6 ; rn = 2.3 ; bg0 = 40; }
    if( det == "ADSC Q210/315 (unbin)")    { gain = 2.4 ; rn = 4   ; bg0 = 40; }
    if( det == "ADSC Q270")                { gain = 2.8 ; rn = 1.5 ; bg0 = 40; }
    if( det == "Mar/Rayonix 165 CCD")      { gain = 1.0 ; rn = 3   ; bg0 = 10; }
    if( det == "Mar/Rayonix 325HE (slow)") { gain = 2.4 ; rn = 0.9 ; bg0 = 10; }
    if( det == "Mar/Rayonix 325HE")        { gain = 2.4 ; rn = 2   ; bg0 = 10; }
    if( det == "Mar/Rayonix 300HE (slow)") { gain = 2.8 ; rn = 0.9 ; bg0 = 10; }
    if( det == "Mar/Rayonix 300HE")        { gain = 2.8 ; rn = 2   ; bg0 = 10; }
    if( det == "Mar/Rayonix 325 (slow)")   { gain = 1.3 ; rn = 1.5 ; bg0 = 10; }
    if( det == "Mar/Rayonix 325")          { gain = 1.3 ; rn = 2.5 ; bg0 = 10; }
    if( det == "Mar/Rayonix 300 (slow)")   { gain = 1.5 ; rn = 1.5 ; bg0 = 10; }
    if( det == "Mar/Rayonix 300")          { gain = 1.5 ; rn = 2.5 ; bg0 = 10; }
    if( det == "Pilatus")                  { gain = 1.0 ; rn = 0   ; bg0 =  0; }
    if( det == "Rigaku Saturn (slow)")     { gain = 15  ; rn = 5   ; bg0 = 20; }
    if( det == "Rigaku Saturn")            { gain = 15  ; rn = 18  ; bg0 = 20; }
    if( det == "Rigaku S944")              { gain = 17  ; rn = 13  ; bg0 = 20; }
    if( det == "Rigaku IP")                { gain = 2   ; rn = 1   ; bg0 =  5; }
    if( det == "Rigaku A200")              { gain = 14  ; rn = 12  ; bg0 = 20; }
```

**Comment by rjgildea** [comment]
There is a optional parameter global_threshold=auto to dials.find_spots that tries to estimate a suitable value for global_threshold to avoid problems such as finding "spots" behind the beamstop shadow. It is now available as a standalone command (if you have dials_scratch configured) `dev.dials.estimate_global_threshold`:
`dev.dials.estimate_global_threshold datablock.json plot=True`
![global_threshold](https://user-images.githubusercontent.com/2810624/27682821-d742a56c-5cbb-11e7-934f-af5231bde58b.png)
It essentially plots the number of pixels above various threshold values, and then identifies the "elbow" of the plot (and then conservatively chooses a couple of points lower than the elbow).

global threshold map with global_threshold=0:
![screenshot-54](https://user-images.githubusercontent.com/2810624/27682939-4c397116-5cbc-11e7-9ef5-b591b4704a33.png)

global threshold map with global_threshold=25 (as determined by above routine):
![screenshot-55](https://user-images.githubusercontent.com/2810624/27682947-50152da2-5cbc-11e7-9acd-1c269194cd0d.png)

Any objections if I set global_threshold=auto to be the default for ccd images?

**Comment by rjgildea** [comment]
Makes this difference to the strong pixels found:
![screenshot-57](https://user-images.githubusercontent.com/2810624/27683150-f0deace0-5cbc-11e7-8eb6-15ae4cdba644.png)
vs:
![screenshot-56](https://user-images.githubusercontent.com/2810624/27683158-f80abfea-5cbc-11e7-982c-33962d957741.png)

**Comment by phyy-nx** [comment]
This seems like a great idea.  dxtbx/model/detector.py's DetectorFactory
has a static sensor function that takes a string and asserts it is a member
of an enumeration of known panel types, so you could check a panel's
get_type method against that enumeration?  In fact, it seem like the
reflection table's from_observations function should be checking this
enumeration too when params.spotfinder.filter.min_spot_size is Auto.

It's worth noting that FormatCBFFull has a panel type of unknown.  Not all
format classes may be returning CCD when it's appropriate.

-Aaron

**Comment by dagewa** [comment]
:+1: @phyy-nx I like that approach, I also think that 'CCD' is set in a few places where it doesn't really mean phosphor-taper-CCD area detector. There are detectors where neither 'CCD' nor 'PAD' is correct.

**Comment by phyy-nx** [comment]
Right.  IMAGE_PLATE and unknown are the other values of that enumeration,
but there's no reason we can't expand it to be more precise.

On a related note, Nick and I were chatting that it would be cool if
FormatCBF (Full and Mini) would auto determine its parallax strategy based
on sensor type in the image header.  That will require a bit of digging
into specifications but it could be done.

**Comment by dagewa** [comment]
Closing this as https://github.com/cctbx/cctbx_project/issues/51 is intended to address the issue. If it ultimately does not, this could be reopened
