### ISSUE TITLE
dials.index refinement mode=None only works for stills indexer

### ISSUE THREAD

**Issue by PrinceWalnut** [dials/dials#2305]
When using the flag `indexing.refinement_protocol.mode=None` while calling `dials.index` on a scan, no error or warning is thrown, and refinement simply proceeds with defaults. From the documentation online, it appears that `indexing.refinement_protocol.mode=None` only works with the stills indexer. This functionality should be expanded to the other indexers.

**Comment by dagewa** [comment]
Seems reasonable
