### ISSUE TITLE
AssertionErrors in testsuite on arm64 and ppc64e

### ISSUE THREAD

**Issue by rolandmas** [dials/dials#2315]
Hello,
I'm Roland Mas, Debian maintainer for the dials package. The Debian CI infrastructure detects testsuite errors on the arm64 and ppc64el architectures, and I'd like some help in fixing them.
The full logs are available at https://ci.debian.net/data/autopkgtest/testing/arm64/d/dials/29450078/log.gz and https://ci.debian.net/data/autopkgtest/testing/ppc64el/d/dials/29455641/log.gz respectively, but in both cases the testsuite ends with this:

```
        # now try the Reeke method to generate indices
        r = ReekeIndexGenerator(ub_beg, ub_end, sg.type(), axis, s0, dmin, margin=1)
        reeke_indices = r.to_array()
    
        for oi in obs_indices:
>           assert tuple(map(int, oi)) in reeke_indices
E           assert (-30, 0, -10) in <cctbx_array_family_flex_ext.miller_index object at 0xffff441d5460>
E            +  where (-30, 0, -10) = tuple(<map object at 0xffff5be42830>)
E            +    where <map object at 0xffff5be42830> = map(int, (-30.0, 0.0, -10.0))

tests/algorithms/spot_prediction/test_reeke_index_generator.py:134: AssertionError
=========================== short test summary info ============================
FAILED tests/algorithms/spot_prediction/test_reeke_index_generator.py::test_versus_brute_force
====== 1 failed, 820 passed, 531 skipped, 1 xfailed in 1477.78s (0:24:37) ======
```

The testsuite runs fine on the amd64 architecture, so there's not much I can do to debug by myself, and any help will be most welcome. This issue prevents the migration of Dials to the "testing" distribution of Debian, which will be frozen in a few weeks on its way to becoming the next stable version (Debian 12 "bookworm").

Thanks for any help!

**Comment by graeme-winter** [comment]
@rolandmas is there any way to get access to computers where this is run? To allow some interactive debugging to work out what is going on here. If I were doing this for myself I would pepper the test code with `print()` to work out what is going on. I don't have the platforms you list above at all.

**Comment by ndevenish** [comment]
Hi Roland, we aren't involved in the debian packaging for dials at all (despite our requests for engagement beyond tickets in the past) don't actually support linux-arm64 or ppc64el platforms, and don't have any way of testing them internally - so I'm not sure how we can really help.

The cctbx arrays do indeed have slightly unhelpful default `__repr__` instances, in case it's helpful I've used https://github.com/ndevenish/tbxtools/blob/main/src/tbxtools/repr.py to monkeypatch diagnostic output onto them for when I've needed diagnostics in the past.
