### ISSUE TITLE
dials.rs_mapper does not work for multi-panel detectors

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2333]
This was raised by I23 beamline scientists

```
$ dials.rs_mapper AUTOMATIC_DEFAULT_SAD_SWEEP1.expt
The following parameters have been modified:

input {
  experiments = AUTOMATIC_DEFAULT_SAD_SWEEP1.expt
}

DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Setting nproc=4
Sorry: This program does not support multi-panel detectors.
```

This will also be relevant for the plan to use `rs_mapper` for the neutron diffraction data processing GUI.

**Comment by co2e14** [comment]
Following for Dr Duman

**Comment by dagewa** [comment]
@co2e14 could you point me to an I23 dataset to try this out? I just had a go with a single image that we use for tests, but for whatever reason in that case the output map file ends up only containing zeroes. So, I need a full rotation dataset.

**Comment by luisodls** [comment]
This is the one I will use to test/fix Dui2 image viewer, there are 4 datasets there:

/dls/i23/data/2023/cm33851-1/TestLysozyme/20230220/lys_1

**Comment by dagewa** [comment]
`Permission denied` for me. I'll wait to be pointed towards one :)

**Comment by co2e14** [comment]
@dagewa **/dls/mx-scratch/i23_fordwg/lys_1**

apologies for not supplying anything more exciting than lysozyme...

**Comment by dagewa** [comment]
Thanks, it's a good one actually because there are four sweeps and this highlighted another artificial limitation of `dials.rs_mapper`, which is that it only worked on a single scan. I'm still struggling to do the test though. It keeps getting killed on the cluster. Not sure why memory usage is so high.
