### ISSUE TITLE
Data processing with missing images

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2339]
The cRED electron diffraction data collection methodology ([10.1107/S1600576718015145](https://doi.org/10.1107%2FS1600576718015145)) uses a crystal tracking technique in which every nth image comes from  defocused beam, providing a real space image of the crystal rather than a diffraction pattern. This is not well handled by DIALS. Currently practitioners of this method are treating each block of diffraction images as a separate scan through all steps of processing.

A possible improvement might be to join reflection lists together and create a single scan after spot-finding, so that indexing and refinement can use a global model. This model can then be split again at the point of integration to avoid any attempt to read from missing images. It is possible that this is already available through some combination of `dials.merge_reflection_lists`, `dials.modify_geometry`, and `dials.split_experiments`. If not, a reasonably simple script should be able to do the job. This may also apply to other circumstances where one or a few images are missing from a dataset.

I'm keeping track of this topic with this issue.

**Comment by dagewa** [comment]
There are actually two distinct cases here:

1. Datasets where images are not missing, but do not contain diffraction data (blank images, crystal positioning images, or whatever)
2. Datasets where some image files are actually missing from what would otherwise be a complete scan.

The cRED use case is more like (1), but is being treated like (2) in processing, which is a lot of extra hassle. I think the only thing not allowing it to be treated more simply like (1) is that it isn't currently possible to exclude individual images from spotfinding, unlike integration.

**Comment by dagewa** [comment]
There's some related issues here. I suspect the confusion noted in #1992 would actually be cleared up if images had been excluded from spot-finding, because in that case shoeboxes should never extend onto the excluded images.

#2285 notes that `exclude_images` syntax is not consistent between programs. The `dials.scale` approach is better because that allows including an experimental identifier. In fact, in #1996, @jbeilstenedmands added this as a general `exclude_images` module to `util/`.

**Comment by jbeilstenedmands** [comment]
@dagewa is this issue solved by https://github.com/dials/dials/pull/2511 ?

**Comment by dagewa** [comment]
Yes, happy to call this solved.
