### ISSUE TITLE
get_beam() returns wrong wavelength from sliced imagesets

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#235]
dials.stills_process handles multi-image files by creating an array of sliced imagesets:
split_datablocks = []
for imageset in datablock.extract_imagesets():
  for i in xrange(len(imageset)):
    subset = imageset[i:i+1]
    split_datablocks.append(DataBlockFactory.from_imageset(subset)[0])

This allows the program to easily do multiprocessing without needing to load the imageset many times.  Relevant for NeXus or SACLA data.  However, if the dataset has get_beam(index) implemented, meaning the dataset has a different energy for every shot, the sliced dataset returns the wrong energy.

Demonstrate using this: libtbx.python dials_regression/command_line/show_slicing_bug_235.py

Reason: format classes like FormatHDF5SaclaMPCCD.py have to implement get_beam(index=None)  by returning the first beam avaiable.

**Comment by biochem-fan** [comment]
The `dxtbx` needs modifications to keep track of original indices in an (multi-event) image file even after an imageset was sliced. For `get_raw_data()`, this is done in the `ImageSet` class as
```python
image = self.reader().read(self._indices[index])
```
https://github.com/cctbx/cctbx/blob/master/dxtbx/imageset.py#L520.

However, `get_beam()`, `get_detector()`, `get_path()` etc are called without such conversion, thus causing this bug and also #227. For example, we can store `_indices` in `SingleFileReader` as well as in `ImageSet` to implement this conversion.

**Comment by jmp1985** [comment]
This should now be fixed. libtbx.python dials_regression/command_line/show_slicing_bug_235.py now works.

**Comment by biochem-fan** [comment]
Confirmed. Thanks.
