### ISSUE TITLE
Pixel masking in DIALS

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#236]
Could someone please summarize how pixel masking is done in DIALS (spot finding and integration)?
1.  Is panel's `trusted_range` set in a dxtbx class automatically respected? What if `get_mask` is defined? Do I have to implement `get_mask()` in the format class, where the mask is generated by panel's `get_trusted_range_mask` and (possibly) merged with other pixel masks?
   
   In my MPCCD class, setting `trusted_range` alone seems sufficient; but some dxtbx classes like `FormatPYunspecified` and `FormatCBFMiniPilatus` implement `get_mask`. So I wanted to make sure.
2.  When `mask=mask.pickle` is supplied to `dials.spot_find` or `dials.integrate`, does it replace the mask from the dxtbx class, or is it merged?
3. It seems that I have to specify `mask=mask.pickle` to `dials.spot_find` and `dials.integrate`, not only to `dials.import`. Is this intended behaviour?

**Comment by jmp1985** [comment]
So pixel masking is done in the following way:

1. Imageset has a function get_mask; this function will call the format class get_mask function. The default return value for this is "None"; however it can be overriden to provide more sophisticated masking (e.g. dynamic masking etc). If the format get_mask function returns a value that is not "None", then this is used. Otherwise, if "None" is returned then a mask is created on the fly from the trusted_range values given by the panel class. So to summarize, if you implement get_mask then you are responsible for making sure that it masks things correctly; if you don't implement get_mask then the trusted_range is used.

2. Is mask is set then this is merged with the mask from the format get_mask function or the trusted range mask.

3. I may have to look into this. But I think that you can serialize a mask into the JSON file through dials.import and this will be used during spot finding and integration but there is also the option of specifying a mask in spot finding and integration that will not be serialized into the imageset itself. This sounds a bit complicated so maybe we need to tidying up the way this is done.

I hope that answers your questions?

**Comment by biochem-fan** [comment]
Hi James,

Thank you very much for clarification. (1) and (2) are very clear.

(3) Specifying a mask to `dials.import` does not seem to be sufficient. I have an EIGER serial (still) dataset with ice rings. So I created `mask.pickle` by `dials.generate_mask`.

> But I think that you can serialize a mask into the JSON file through dials.import

Yes. `dials.import dataset_master.h5 mask=mask.pickle` creates `datablock.json`, where `mask` is correctly specified. 

However, `dials.image_viewer datablock.json` does not show the provided mask even after `show mask` is checked. `dials.image_viewer datablock.json mask=mask.pickle` does show the provided mask in red as expected.

> this will be used during spot finding and integration

I am not sure.

`dials.find_spots datablock.json` finds lots of false spots on ice rings as confirmed by `dials.image_viewer datablock.json strong.pickle`. `dials.find_spots datablock.json mask=mask.pickle` works fine, excluding spots on the ice rings.

> but there is also the option of specifying a mask in spot finding and integration that will not be serialized into the imageset itself. 

Judging from the behaviour above,  `spotfinder.lookup.mask` and `mask` in an imageset have different effects on spot finding. Is this intended?

**Comment by jmp1985** [comment]
I guess the dials.image_viewer issue is one for @rjgildea.

I've just had a look at the spot finding code and line 106 of dials/algorithms/spot_finding/finder.py is

    mask = self.imageset.get_mask(
      index, goniometer_shadow_mask=self.goniometer_shadow_mask)

    # Set the mask
    if self.mask is not None:
      assert(len(self.mask) == len(mask))
      mask = tuple(m1 & m2 for m1, m2 in zip(mask, self.mask))

The masks should be applied together. If this is not happening then someone funny is going on! If you have a test case where the mask is not being applied could you send it and I'll have a closer look.

**Comment by rjgildea** [comment]
I'm not sure this is an issue with dials.image_viewer, the following works for me:
```
$ dials.import dials_regression/centroid_test_data/centroid_000*.cbf
$ dials.generate_mask ice_rings.filter=True datablock.json ice_rings.d_min=2
$ dials.import dials_regression/centroid_test_data/centroid_000*.cbf mask=mask.pickle
$ dials.image_viewer datablock.json show_mask=True 
```
![screen shot 2016-10-20 at 15 03 24](https://cloud.githubusercontent.com/assets/2810624/19563064/9a912fe0-96d6-11e6-9ab5-3075a8b7cd14.png)

**Comment by rjgildea** [comment]
However the following does not work in the same way:
```
$ dials.import dials_regression/image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5 
$ dials.generate_mask ice_rings.filter=True datablock.json ice_rings.d_min=2
$ dials.import dials_regression/image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5 mask=mask.pickle 
$ dials.image_viewer datablock.json show_mask=True
```
The mask created in mask.pickle isn't being returned in the call to imageset.get_mask(index) made by the image viewer. Therefore I think the issue lies somewhere in dxtbx/format class and not the image viewer.

**Comment by biochem-fan** [comment]
Hi James,

`DataBlockDictImporter.load_models` expects `mask` as a direct child of the `imageset` object in the JSON dictionary. However, the reference to the mask is stored for each element of the `images` array.

```javascript
 "imageset": [
      {
        "__id__": "ImageSet",
        "images": [
          {
            "filename": "/path/to/run266702-0-subset.h5",
            "mask": "/path/to/mask.pickle",
            "gain": null,
            "pedestal": null,
            "image": 0,
            "beam": 0,
            "detector": 0
          },
          {
            "filename": "/path/to/run266702-0-subset.h5",
            "mask": "/path/to/mask.pickle",
            "gain": null,
            "pedestal": null,
            "image": 1,
            "beam": 1,
            "detector": 0
          }
      ],
     # ... other elements BUT no "mask" here
}
```

My proposed fix to `Datablock.to_dict` is:
```python
for i in xrange(len(iset)):
          image_dict = OrderedDict()
          image_dict['filename'] = abspath(iset.get_path(i))
#          image_dict["mask"] = abspath_or_none(iset.external_lookup.mask.filename)
          image_dict["gain"] = abspath_or_none(iset.external_lookup.gain.filename)
          image_dict["pedestal"] = abspath_or_none(iset.external_lookup.pedestal.filename)
          if iset.reader().is_single_file_reader():
            image_dict['image'] = iset.indices()[i]
          try:
            image_dict['beam'] = b.index(iset.get_beam(i))
          except Exception:
            pass
          try:
            image_dict['detector'] = d[iset.get_detector()]
          except Exception:
            pass
          try:
            image_dict['goniometer'] = g.index(iset.get_goniometer())
          except Exception:
            pass
          try:
            image_dict['scan'] = s.index(iset.get_scan(i))
          except Exception:
            pass
          image_list.append(image_dict)
imageset["mask"] = abspath_or_none(iset.external_lookup.mask.filename) # ADDED
imageset['images'] = image_list
```
https://github.com/cctbx/cctbx/blob/master/dxtbx/datablock.py#L230

We do not allow per-image external masks for an image set, do we?

**Comment by jmp1985** [comment]
Hi Takanori,

So we don't allow per-image external masks so I guess this fix looks ok. If it doesn't break anything then feel free to commit; will this break old datablock.json files? I'm off this afternoon so I'm planning to address this and the other DIALS issues you've raised when I'm back in on Monday.

James

________________________________

**Comment by biochem-fan** [comment]
Hi James,

It should not break anything, because the `mask` field under `images` was not read by anything before.
As I don't have developer access to cctbx svn, could you please commit my patch?

**Comment by rjgildea** [comment]
Hi Takanori, I'm sure if you contact @nksauter he can grant you commit access to cctbx sourceforge svn (although given we are hoping to move cctbx to github in the near future this won't be a problem for long).

**Comment by biochem-fan** [comment]
Hi Richard, yes, I am waiting the migration to GitHub, as I am not as familiar with svn as git.

**Comment by biochem-fan** [comment]
Fixed by cctbx r25765.
