### ISSUE TITLE
Feature request: would be cute to compute a DQE map of the detector to include in the output of dials.report integrated.pickle

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#237]
May give a lot of insight, particularly to small molecule users.

**Comment by dagewa** [comment]
Does this just mean adding a plot a bit like this one https://github.com/dials/dials/blob/89e7d1e36d6019c07045d4b44d658e288349069c/command_line/report.py#L798 but using the `QE` column of the integrated reflections? If so, that should be trivial to add
