### ISSUE TITLE
Document various different ways of excluding parts of datasets from processing

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2376]
We have various different ways of excluding parts of datasets, including (but perhaps not limited to):

- Setting `scan.image_range` in `dials.import`
- Using `exclude_images` in various programs. The interface is consistent across the programs, but their effects are subtly different
- Using `scan_range` in various programs. This is more piecemeal as it is not defined in one place, and might not be consistent.
- Running `dials.slice_sequence` to select a subset

We need documentation explaining the various use cases for these and their differing effects. We might also need to improve the interfaces further. See e.g. #2111, #1227 and #1992

**Comment by graeme-winter** [comment]
Life is probably too short, but a nice idea
