### ISSUE TITLE
`dials.export` does not add `HKL_base` to MTZ

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2379]
According to 

```
gemmi mtz integrated.mtz
```

integrated MTZs from DIALS do not have the `HKL_base` dataset with id 0, which is [standard](https://www.ccp4.ac.uk/html/mtzformat.html#the-base-dataset). This often does not actually _matter_ because if the MTZ is touched by the CMTZ library, the base dataset will be added (this is also why it appears to be there on the output of `mtzdmp integrated.mtz` or `iotbx.mtz.dump integrated.mtz`).

However, this could be problematic if the MTZs are used without the CMTZ library (for example by software using gemmi).

**Comment by jbeilstenedmands** [comment]
This should be straightforward, Richard did a similar thing for https://github.com/dials/dials/pull/23780, but only for merged MTZ I think:
```
mtz_writer.add_crystal(crystal_name="HKL_base", project_name="HKL_base")
mtz_writer.add_empty_dataset(wavelength=0, name="HKL_base")
mtz_writer.add_dataset(
    r_free_array=r_free_array,
)
 ```

**Comment by dagewa** [comment]
Thanks. It was a difference I noticed compared to the MTZ files I was writing with gemmi, where the base dataset is set. If we decide to switch to gemmi output then this issue will be fixed (along with some others). I haven't got the PR quite ready for gemmi-fied MTZs yet though.
