### ISSUE TITLE
New dev import broken

### ISSUE THREAD

**Issue by DrTheMick** [dials/dials#238]
dials.import template=1_###.img, etc  returns usage spiel
dials.import *.img splits data into 18 sweeps

Started doing this between today and yesterday afternoon.

DIALS 1.dev.840-gbf10060

**Comment by rjgildea** [comment]
Likely culprit this commit: https://github.com/dials/dials/commit/bf10060057181e651a599dbab8b4790d73c10ed5

Presumably template= parameter does not have a test?

**Comment by graeme-winter** [comment]
Following modes now work:
- passing images on command line
- template=
- passing directory
- passing datablock.json file
better test needed...

**Comment by graeme-winter** [comment]
Added test for template=; now should be properly exercised
