### ISSUE TITLE
Remove cctbx.xfel dependency in dials.ssx_index

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#2389]
`dials.ssx_index` has a dependency on `cctbx.xfel` ([via nave_parameters.py](https://github.com/dials/dials/blob/18146d1d65d55d974e94ec837369359ce58cf838/src/dials/algorithms/indexing/nave_parameters.py#L98)). This means it won't work on conda builds where `cctbx.xfel` isn't available.

**Comment by phyy-nx** [comment]
Duplicate of #2076 or do you want this as a separate issue?  Either is fine with me :)

**Comment by jbeilstenedmands** [comment]
Resolved by #2404
