### ISSUE TITLE
dials.stills_process applies the reference geometry to only the first image of a multi-event file

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#240]
To reproduce: run `dials.stills_process` on `run266702-0-subset.h5` in dials_regression with some geometry JSON file supplied as `input.reference_geometry`. By inspecting `idx-run266702-0-subset_0000N_datablock.json`, you can see the geometry is not applied except for the first frame.

cctbx r25607 to fix #235 caused this problem.

For `dials.stills_process`, the following change to replace the detector **after** slicing solves the problem. However, we might want to make sure other commands are not affected as well.

stills_process.py:
```python
#      if self.reference_detector is not None:
#        from dxtbx.model import Detector
#        for datablock in datablocks:
#          for imageset in datablock.extract_imagesets():
#            print imageset
#            imageset.set_detector(Detector.from_dict(self.reference_detector.to_dict()))
#
#      for datablock in datablocks:
#        for imageset in datablock.extract_imagesets():
#          update_geometry(imageset)

      indices = []
      basenames = []
      split_datablocks = []
      for datablock in datablocks:
        for imageset in datablock.extract_imagesets():
          for i in xrange(len(imageset)):
            subset = imageset[i:i+1]
# ADDITION START
            if self.reference_detector is not None:
              from dxtbx.model import Detector
              subset.set_detector(Detector.from_dict(self.reference_detector.to_dict()))
            update_geometry(subset)
# ADDITION END
            split_datablocks.append(DataBlockFactory.from_imageset(subset)[0])
            indices.append(i)
            basenames.append(os.path.splitext(os.path.basename(subset.paths()[0]))[0])
```

**Comment by jmp1985** [comment]
I'm not sure why this should have worked in the past. ImageSet.set_detector(detector, index=None) should be called with index=${EACH_IMAGE_NUMBER} otherwise it just sets it for the first image - I know this is confusing but this was a feature that was requested a long time ago. I've added a fix to dials.stills_process.
