### ISSUE TITLE
Remove as_grid_scan from dials.import

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2452]
As seen in #2447 this does nothing useful and is misleading - either

 - remove `as_grid_scan`
 - modify it to be an alias which sets `scan.oscillation=0,0`

I think the second is superior, will look

**Comment by JunAishima** [comment]
having the name grid_scan in there implies that it could enable processing the data in a way that the images may be related to each other. this might be useful for real grid scans, but simply changing it to stills would make sense for us (with these datasets).

**Comment by graeme-winter** [comment]
> having the name grid_scan in there implies that it could enable processing the data in a way that the images may be related to each other. this might be useful for real grid scans, but simply changing it to stills would make sense for us (with these datasets).

Conceptually I completely agree, however we don't do that _right now_ and you would think we do. That's an answer in favour of simply eliminating the option, and we can put it back one day when we do "something special" with grid scans over simply importing as stills.

**Comment by JunAishima** [comment]
> > having the name grid_scan in there implies that it could enable processing the data in a way that the images may be related to each other. this might be useful for real grid scans, but simply changing it to stills would make sense for us (with these datasets).
> 
> Conceptually I completely agree, however we don't do that _right now_ and you would think we do. That's an answer in favour of simply eliminating the option, and we can put it back one day when we do "something special" with grid scans over simply importing as stills.

Sounds reasonable!

**Comment by graeme-winter** [comment]
(by way of a narrative annotation, I am getting crazy déjà vu doing this)
