### ISSUE TITLE
dials.import invert_rotation_axis=true fails for even numbers of imagesets

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2467]
Importing a single imageset is okay:
```
dials.import $(dials.data get -q x4wide)/*.cbf invert_rotation_axis=true
dials.show imported.expt | grep "Rotation"
```
gives
```
    Rotation axis:   {-1,-0,-0}
```
but for multiple imagesets this fails silently:
```
dials.import $(dials.data get -q x4wide)/X4_wide_M1S4_2_00{01,46}.cbf invert_rotation_axis=true
dials.show imported.expt | grep "Rotation"
```
gives
```
    Rotation axis:   {1,0,0}
    Rotation axis:   {1,0,0}
```

**Comment by graeme-winter** [comment]
I've been watching these threads with a sense of familiarity. I am sure I fixed this or touched it at least a while back? 🤔

**Comment by graeme-winter** [comment]
OK, this was what I was thinking of, close but unrelated

https://github.com/dials/dials/issues/2398

**Comment by dagewa** [comment]
I know what this is now, and it is dumb. There are two imagesets, but each of these point to the same goniometer model. The manual geometry updater is called twice. The first call inverts the axis, but the second call then inverts it right back again :roll_eyes:

**Comment by dagewa** [comment]
```
dials.import $(dials.data get -q x4wide)/X4_wide_M1S4_2_00{01,23,46}.cbf invert_rotation_axis=true
dials.show imported.expt | grep "Rotation"
```
-->
```
    Rotation axis:   {-1,-0,-0}
    Rotation axis:   {-1,-0,-0}
    Rotation axis:   {-1,-0,-0}
```
:scream:
