### ISSUE TITLE
dials.index with multiple sweeps

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#247]
If I dials.index sweep1...N then I end up with experiment ID's -1...(N-1) - this is fine however I therefore don't know in RLV which sweep reflections with expt ID -1 came from, and can't see unindexed reflections from sweep M as I could if it were a single run.

Is there a workaround for this? For case like

```
RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 2204 | 0.4496  | 0.69659 | 0.6174   |
| 1   | 574  | 1.2966  | 4.8668  | 2.5778   |
| 2   | 2134 | 0.53168 | 0.45897 | 0.41136  |
| 3   | 2274 | 0.57035 | 0.33231 | 0.45538  |
| 4   | 1946 | 0.39325 | 0.48061 | 0.37536  |
---------------------------------------------
```

I would want to look at unindexed reflections from sweep 1, say - only 672 reflections in split pickle file... also dials.split could use this as well to keep reflections from a sweep together

**Comment by rjgildea** [comment]
I'm not quite sure what you're asking for, but I think it might be resolved by https://github.com/dials/dials/issues/273 ?

**Comment by graeme-winter** [comment]
I will check

**Comment by graeme-winter** [comment]
This now does exactly what I wanted since we have imageset id's option
