### ISSUE TITLE
local indexing crashes when local.nearest_neighbours = number of reflections

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#248]
When `index_assignment.local.nearest_neighbours` < the number of accepted reflections, we get an unhandled C++ exception from ANNlib saying "Requesting more near neighbors than data points". Since this not only fails for the particular image but kills the entire `dials.stills_process`, I trapped this condition by 066c90f.

The case where `index_assignment.local.nearest_neighbours` == the number of accepted reflections should be OK. Actually, it results in segmentation fault. This is because `ann.nn[i_k_plus_i_ann]` in `algorithms/indexing/index.h` https://github.com/dials/dials/blob/master/algorithms/indexing/index.h#L229 becomes `-1` when `i_ann` == `len(rlps)` == `nearest_neighbours`. I don't know why this happens because the ANN library allows such queries. 

```
/home/packages/dials/build/lib/dials_algorithms_indexing_ext.so(boost::python::detail::caller_arity<8u>::impl<void (*)(_object*, scitbx::af::const_ref<scitbx::vec3<double>, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<double, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<scitbx::mat3<double>, scitbx::af::trivial_accessor> const&, double, double, double, int), boost::python::default_call_policies, boost::mpl::vector9<void, _object*, scitbx::af::const_ref<scitbx::vec3<double>, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<double, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<scitbx::mat3<double>, scitbx::af::trivial_accessor> const&, double, double, double, int> >::operator()(_object*, _object*)+0x3dc) [0x7f4e998ed8fc]
/home/packages/dials/build/lib/dials_algorithms_indexing_ext.so(boost::python::objects::make_holder<7>::apply<boost::python::objects::value_holder<dials::algorithms::AssignIndicesLocal>, boost::mpl::vector7<scitbx::af::const_ref<scitbx::vec3<double>, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<double, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<scitbx::mat3<double>, scitbx::af::trivial_accessor> const&, double const, double const, double const, int const> >::execute(_object*, scitbx::af::const_ref<scitbx::vec3<double>, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<double, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<scitbx::mat3<double>, scitbx::af::trivial_accessor> const&, double, double, double, int)+0x97) [0x7f4e998fd587]
/home/packages/dials/build/lib/dials_algorithms_indexing_ext.so(dials::algorithms::AssignIndicesLocal::AssignIndicesLocal(scitbx::af::const_ref<scitbx::vec3<double>, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<double, scitbx::af::trivial_accessor> const&, scitbx::af::const_ref<scitbx::mat3<double>, scitbx::af::trivial_accessor> const&, double, double, double, int)+0x1f8c) [0x7f4e998fc5fc]
/lib64/libc.so.6() [0x3b434326a0]
Segmentation fault (Python and libc call stacks above)
```

Currently, my commit 066c90f rejects this corner case as well to prevent crashes.

**Comment by nksauter** [comment]
Dear Takanori,

The annlib_adaptbx package provides for two specializations of the ANN
code:  AnnAdaptor and AnnAdaptorSelfInclude.  DIALS imports the AnnAdaptor
specialization, which does not permit the self point to be a nearest
neighbor.  I believe this may explain your observed behavior.

Nick

Nicholas K. Sauter, Ph. D.
Senior Staff Scientist, Molecular Biophysics & Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by biochem-fan** [comment]
Dear Nick, 

Thank you very much for explanation. Then my current patch is OK as is.
