### ISSUE TITLE
`dials.image_viewer` basis vector display is problematic

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2480]
For detectors with > 90° swing, the basis vectors being centred at the calculated beam centre looks strange. Also, they do not appear to be of the expected length in this case: https://github.com/dials/dials/pull/2479#issuecomment-1658229088

There are other problems with this feature. A particular bugbear of mine is that we scale them 10 times (by default) and then label them as `a*`, `b*`, `c*` ignoring the scaling factor. This is misleading. I would prefer the basis vector scale to by 1× by default and above that for the scale factor to be included on the label.

Sometimes only one or two of the 3 axes is displayed. This is because the end point of the vectors is calculated as an intersection on the detector, and if that intersection is off the panel then that vector is not displayed.

Biggest question is, **_does anybody actually find this feature useful?_** While preparing a figure I found the basis vector display confusing and unhelpful. It was far easier to simply use the `Show hkl` checkbox to label indexed spots. If no one uses the basis vector display then a simple and easy solution to its issues may be to just remove it.

**Comment by nksauter** [comment]
I vote for "Leave", err..."Remove basis vectors".

**Comment by graeme-winter** [comment]
> I vote for "Leave", err..."Remove basis vectors".

@nksauter still too soon! I know, I need to get over it.

However I share the view that these _have never been useful_
