### ISSUE TITLE
Dials installer skips over destination folder on Mac

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#250]
From Paul Emsley

Hi,

I downloaded the 1.3.5 Mac Installer for OS X 10.6.  When I run it, I am unable to activate
the "Destination Select" so that I can install it to my directory (the GUI skips over this
item). This seems to be a bug.

Paul.

From Graeme

Paul

I reproduce your error in the GUI installer - sadly I have no idea where this comes from (it's derived from the phenix one) so I will follow up with colleagues at LBL to see if we can get this debugged

I think the behaviour I experienced is slightly different - when I select "change install location" it skips back to "installation type" however it only allows installation for "all users of this computer" which is probably not what we want...

That said, looks like it is behaving as intended:

welcome.write("""\
This package contains %(package)s version %(version)s compiled for %(arch)s. \
It will install the full command-line suite and graphical launcher(s) \
to %(dest_name)s.  If you need to install %(package)s to a different \
location, you must use the command-line installer (also available from \
our website).""" % { "package" : options.package_name,
                     "version" : options.version,
                     "arch"    : system_type,
                     "dest_name" : dest_name })

@LBL folks:
I've been poking around in cctbx/modules/cctbx_project/libtbx/auto_build/create_mac_pkg.py 
but not found any inspiration...

From Aaron
Hi all, just looked at the Dials installer compared to the Phenix installer and they have different behaviors, but in neither case can you select a location other than /Applications.  Regardless, the Dials installer is non-intuitive as it skips the Destination step completely.

**Comment by Anthchirp** [comment]
Any development on this? Do people still use macs? Or can this be closed?

**Comment by Anthchirp** [comment]
If there is more information please reopen.
