### ISSUE TITLE
dials.import error for h5 image files

### ISSUE THREAD

**Issue by DHekstra** [dials/dials#2502]
hi, 
I'm trying to process h5 images collected at CHESS by Steve Meisburger (FWIW: to see if we can improve on processing by taking the spectral properties of the beam into account). Upon the call

`dials.import input.template="/n/hekstra_lab/data/20221204_CHESS_ID7B2/lys2_sweep1_1_data_0000##.h5"`

I get the following error:

`Traceback (most recent call last):
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/bin/dials.import", line 11, in <module>
    sys.exit(run())
             ^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dials/command_line/dials_import.py", line 965, in run
    do_import(args, phil=phil, configure_logging=True)
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dials/command_line/dials_import.py", line 874, in do_import
    imagesets = _extract_or_read_imagesets(params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dials/command_line/dials_import.py", line 228, in _extract_or_read_imagesets
    experiments = ExperimentListFactory.from_templates(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dxtbx/model/experiment_list.py", line 840, in from_templates
    raise ValueError(
ValueError: Please report this error to dials-support@lists.sourceforge.net: Image file /n/hekstra_lab/data/20221204_CHESS_ID7B2/lys2_sweep1_1_data_000001.h5 appears to be a 'type', but this is an abstract Format

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
File <timed eval>:1

File /n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2493, in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
   2491 with self.builtin_trap:
   2492     args = (magic_arg_s, cell)
-> 2493     result = fn(*args, **kwargs)
   2495 # The code below prevents the output from being displayed
   2496 # when using magics with decorator @output_can_be_silenced
   2497 # when the last Python token in the expression is a ';'.
   2498 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File /n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/IPython/core/magics/script.py:154, in ScriptMagics._make_script_magic.<locals>.named_script_magic(line, cell)
    152 else:
    153     line = script
--> 154 return self.shebang(line, cell)

File /n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/IPython/core/magics/script.py:314, in ScriptMagics.shebang(self, line, cell)
    309 if args.raise_error and p.returncode != 0:
    310     # If we get here and p.returncode is still None, we must have
    311     # killed it but not yet seen its return code. We don't wait for it,
    312     # in case it's stuck in uninterruptible sleep. -9 = SIGKILL
    313     rc = p.returncode or -9
--> 314     raise CalledProcessError(rc, cell)

CalledProcessError: Command 'b'\n# Import data\n# You may need to change some of these values to match your data set\ndials.import input.template="/n/hekstra_lab/data/20221204_CHESS_ID7B2/lys2_sweep1_1_data_0000##.h5"  #"PATH/TO/DATA/e080_###.mccd" # Replace with the path to your raw data\n'' returned non-zero exit status 1.`

[LOGFILE.txt](https://github.com/dials/dials/files/12675733/LOGFILE.txt)

**Comment by graeme-winter** [comment]
I have had headaches with similar data before, if you could make some available (or ask Steve to) I will have a look - I had to do some hoop jumping couple years back for a user at a workshop

**Comment by DHekstra** [comment]
thanks. please see your Diamond email

**Comment by DHekstra** [comment]
For the record, I should have done `dials.import "/n/hekstra_lab/data/20221204_CHESS_ID7B2/lys2_sweep1_1_master.h5"`
the "master" h5 contains the metadata and pointers to individual frames

**Comment by graeme-winter** [comment]
In fairness the dials import step could be more helpful here as this is quite a likely failure mode. I can't remember if we tried to fix that already... 🤔

**Comment by DHekstra** [comment]
sorry to reopen this. just a note to self and others `-- geometry.scan.image_range=` comes in handy here, since we cannot restrict the image range to a subset using `input.template`.
