### ISSUE TITLE
goniometer.get_rotation_axis() does not return the rotation axis in the laboratory frame

### ISSUE THREAD

**Issue by dagewa** [dials/dials#251]
What is `goniometer.get_setting_rotation()`?

In refinement we don't currently parameterize the rotation axis. So the only thing we need to know from the goniometer is actual axis about which the crystal turns in the laboratory frame. I thought that this is what `goniometer.get_rotation_axis()` returned, with all other details of the goniometer encapsulated within the goniometer object.

As cf251f6 shows, this is apparently not true, and to get the actual axis of rotation every call to `goniometer.get_rotation_axis()` has to be accompanied by a call to `goniometer.get_setting_rotation()` and a matrix product done.

So what is `goniometer.get_rotation_axis()`?

If it is not actually a way to get the laboratory frame axis about which the crystal rotates then what is it for? Is it returning what is conventionally called the omega axis, or the primary rotation axis of the goniometer system?

I am confused and I think the code is confusing. For the purposes of simplicity, and avoiding additional matrix products in Python, I think `goniometer.get_rotation_axis()` should return the actual rotation axis in the laboratory frame.

**Comment by rjgildea** [comment]
@graeme-winter made it so: https://sourceforge.net/p/cctbx/code/25143/

**Comment by dagewa** [comment]
I think it breaks a principle of encapsulation. I should only know about the setting matrix if I _need_ to know about the setting matrix. At least, it means the original method name is inappropriate, and should be `get_primary_rotation_axis` / `get_omega_rotation_axis` with a suitable convention for omega or similar.

**Comment by rjgildea** [comment]
What it is currently returning is the rotation axis at goniometer zero position (which in the case of a phi-scan on a kappa goniometer happens to be aligned with omega).

**Comment by graeme-winter** [comment]
issue was getting consistent mapping from lab frame to RS which requires the torque rotation implied by rotation of the rotation axis i.e. if they are not orthogonal I need to know the rotation of the full U matrix not just the axis that the U matrix is scanning around ...

**Comment by graeme-winter** [comment]
Fundamentally I agree though that we could have get_rotation_axis gives you setting x axis; get_datum_rotation_axis would do (say) current behavior for those of us who care... #discuss

**Comment by dagewa** [comment]
`get_rotation_axis_datum()`? Does that make sense?

@graeme-winter sorry don't understand that sentence! Encapsulation is great because then I don't have to understand that sentence today. I will only have to unpack it sometime in future when parameterizing the goniometer axis. That'll be a quadruple espresso day.

**Comment by dagewa** [comment]
Yes, agree use of `datum` in there somewhere :)

**Comment by rjgildea** [comment]
So in the constructor for Gonimeter, what makes sense, to accept rotation_axis at datum or true rotation axis?

```
    /**
     * Initialise the goniometer.
     * @param rotation_axis The goniometer rotation axis
     * @param fixed_rotation The additional fixed rotation of the sample
     * @param setting_rotation The additional setting rotation of the axis
     */
    Goniometer(vec3 <double> rotation_axis,
               mat3 <double> fixed_rotation,
               mat3 <double> setting_rotation)
      : fixed_rotation_(fixed_rotation),
        setting_rotation_(setting_rotation) {
      DXTBX_ASSERT(rotation_axis.length() > 0);
      rotation_axis_ = rotation_axis.normalize();
    }
```

**Comment by dagewa** [comment]
In this constructor you have to know the `fixed_rotation` and the `setting_rotation` anyway. So it makes sense that you know the `rotation_axis_at_datum`. If you don't know these, then a simple constructor (I guess not needed in C++ if handled by the Python factory anyway) would only need the true axis and the other matrices will be identity.

**Comment by graeme-winter** [comment]
Playing catch up, not been at desk much today is more discussion needed on what we need to do to get the effective goniometer axis out (i.e. setting x datum axis) ?

**Comment by graeme-winter** [comment]
7f2e0004690532becd3565fc0c7572b9450d51c5 looks like problem went away

**Comment by rjgildea** [comment]
Fixed by:
https://sourceforge.net/p/cctbx/code/25705/
https://github.com/dials/dials/commit/7f2e0004690532becd3565fc0c7572b9450d51c5

These fixes appears to resolve the problems with processing Mark Warren's I19-2 phi-scan data in recent versions of DIALS.
