### ISSUE TITLE
Rmeas, Rmerge and Rpim bigger when using dials vs dials-aimless?

### ISSUE THREAD

**Issue by murpholinox** [dials/dials#2512]
Same dataset... on the right using `pipeline=dials-aimless` and on the left using `pipeline=dials`.

![Screenshot from 2023-10-05 14-07-19](https://github.com/dials/dials/assets/732802/4005e9dc-026a-4a7f-b707-a6d988d14a71)

**Comment by graeme-winter** [comment]
The one on the left suggests that the resolution limit estimation for this pipeline is somewhat off - despite the data on the right indcating that maybe it is OK (though at 6% completeness all bets are off anyway)

Any chance you could upload a `.zip` of rhe `LogFiles` directories so we can have a poke about? If the data are confidential, we can get in touch off-github to figure out how to transmit.

**Comment by murpholinox** [comment]
I was thinking dropbox... but I can probably upload to zenodo or proteindiffraction... (never done it, but it can't be too difficult...right?) any preferences?

**Comment by dagewa** [comment]
I'm going to close this for now, but please re-open if the files are made available.
