### ISSUE TITLE
Overriding geometry on import resets beam Probe

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2515]
Discovered while processing ED data, demonstrated with this file: [00001.img.zip](https://github.com/dials/dials/files/12868581/00001.img.zip)

```
dials.import 00001.img
dials.show imported.expt | grep probe
```
produces
```
    probe: electron
```
as expected. However, 

```
dials.import 00001.img geometry.goniometer.axis=-0.6204,-0.7843,0.0000
dials.show imported.expt | grep probe
```
produces
```
    probe: x-ray
```

**Comment by biochem-fan** [comment]
I am curious what this flag affects. Isn't a wavelength sufficient for processing (within DIALS)?

**Comment by dagewa** [comment]
It currently does not affect anything. The idea is that we can use this to affect the behaviour of specific algorithms in an explicit way. Such algorithms may include the QE and parallax corrections (as noted here https://github.com/cctbx/dxtbx/pull/647), which do not use a suitable model for ED.

**Comment by dagewa** [comment]
Currently this is done in places by setting the simple parallax correction and an extreme value for $\mu$ in the detector model. See comment here https://github.com/cctbx/dxtbx/blob/cd0366339440a04f40e496876721d44c125a654c/src/dxtbx/format/FormatNXmxED.py#L34-L54. It would be nicer to have this behaviour switch explicit on the probe type in the beam model.
