### ISSUE TITLE
Build fail with bootstrap.py for Mac OSX Ventura 13.6

### ISSUE THREAD

**Issue by toastisme** [dials/dials#2522]
User reported build fail with `bootstrap.py build` using an M1 mac with Ventura 13.6.

Steps they took:
```
wget https://raw.githubusercontent.com/dials/dials/main/installer/bootstrap.py 
python bootstrap.py update
python bootstrap.py base 
python boostrap.py build
```
Unable to reproduce because my Macbook is too old.
[bootstrap_ventura_13_6_M1.log](https://github.com/dials/dials/files/12930364/bootstrap_ventura_13_6_M1.log)
[config_ventura_13_6_M1.log](https://github.com/dials/dials/files/12930370/config_ventura_13_6_M1.log)
[bootstrap_ventura_13_6_M1_err.log](https://github.com/dials/dials/files/12930376/bootstrap_ventura_13_6_M1_err.log)

**Comment by toastisme** [comment]
This looks to have been fixed along with [#2546 ](https://github.com/dials/dials/pull/2546)

**Comment by Justin-Bergmann** [comment]
With the updated version it worked once to install DIALS where I could see that arm64-apple-darwin20.0.0-clang++ was used.
When I try to reinstall it it always falls back to some default   CXX: /usr/bin/g++ compiler even when I set 
CC=arm64-apple-darwin20.0.0-clang
CXX=arm64-apple-darwin20.0.0-clang++
before  python bootstrap.py build

Which results in:
Running ./indirection.sh bin/libtbx.scons -j 10 (in build)
scons: Reading SConscript files ...
Compiler settings:
  CC:  /usr/bin/gcc
  CXX: /usr/bin/g++

and ends in 
14 warnings and 1 error generated.
1 warning generated.
scons: *** [ccp4io_adaptbx/cmtzlib_f.o] Error 1
scons: building terminated because of errors.
usr+sys time: 3.37 seconds
wall clock time: 6.69 seconds
Process failed with return code 2

**Comment by ndevenish** [comment]
sigh. Yes, this is obviously somewhat broken.

I have a couple of ideas about what be going on here (taking environment every time instead of just on configuration), but when running the build through bootstrap that should be handled.

**Comment by ndevenish** [comment]
I'm having trouble replicating this. To be clear, this is the sequence of commands that fails in a fresh folder:
```bash
wget https://raw.githubusercontent.com/dials/dials/main/installer/bootstrap.py 
python3 bootstrap.py update
python3 bootstrap.py base 
python3 bootstrap.py build # This had a typo in the original post
python3 bootstrap.py build
```
I can somewhat replicate weirdness if I manually `cd build && make` without activating the environment (it fails to find the right compiler and uses `g++`), but cannot seem to replicate this through `python3 bootstrap.py build`.

This is a fresh folder and a fresh bootstrap.py, right?

**Comment by Justin-Bergmann** [comment]
I have repeated it and recorded all output. please find the exact sequence in history.txt and the output in the related *txt files
 
```
wget https://raw.githubusercontent.com/dials/dials/main/installer/bootstrap.py
python bootstrap.py update > update.txt
python bootstrap.py base > base.txt
 micromamba activate /Users/usrname/DIALS_test/conda_base
 python bootstrap.py build > build.txt
```

[base.txt](https://github.com/dials/dials/files/13278929/base.txt)
[build_terminal.txt](https://github.com/dials/dials/files/13278930/build_terminal.txt)
[build.txt](https://github.com/dials/dials/files/13278931/build.txt)
[update.txt](https://github.com/dials/dials/files/13278932/update.txt)
[history.txt](https://github.com/dials/dials/files/13278964/history.txt)

**Comment by graeme-winter** [comment]
Looking at `build.txt` I see

```
libtbx.scons: OpenMP is disabled.
BOOST_VERSION: 108200
  Ignored: [Errno 2] No such file or directory: '/Users/usrname/DIALS_test/build/exe_dev/cctbx.getting_started'
  Ignored: [Errno 2] No such file or directory: '/Users/usrname/DIALS_test/build/exe_dev/cctbx.sym_equiv_sites'
  Ignored: [Errno 2] No such file or directory: '/Users/usrname/DIALS_test/build/exe_dev/cctbx.convert_ccp4_symop_lib'
  Ignored: [Errno 2] No such file or directory: '/Users/usrname/DIALS_test/build/exe_dev/cctbx.lattice_symmetry'
  Ignored: [Errno 2] No such file or directory: '/Users/usrname/DIALS_test/build/exe_dev/cctbx.find_distances'
  Ignored: [Errno 2] No such file or directory: '/Users/usrname/DIALS_test/build/exe_dev/cctbx.sys_abs_equiv_space_groups'
  Ignored: [Errno 2] No such file or directory: '/Users/usrname/DIALS_test/build/exe_dev/cbflib.tst_memory'
```

That's odd... what do you get if just `python bootstrap.py`?

**Comment by ndevenish** [comment]
Two issues identified:
- `CC` and `CXX` were set in the user `.bash_profile`. This confused the configuration which then ended up with a mix of system and conda compilations which failed the first build and failed to configure on subsequent runs.
- Errors in `ccp4io_adaptbx` fortran conversions. We should monitor these elsewherel
