### ISSUE TITLE
Need to apply setting matrix in export_mtz

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#253]
See https://github.com/dials/dials/commit/db8ac70791ad4cc7b27897a4732f930220440e81

Do we need to apply the setting rotation here somehow? i.e. we have the U.B. matrix assuming that the axis is equal to S * axis_datum but here we are just giving the effective axis so at scan angle 0 this will not be correct... not even sure we can express the stack of matrices S * R * F * U * B in MTZ format?...

**Comment by dagewa** [comment]
The original `FIXME` in the referenced commit has now gone. In its place is a comment that we do not try to represent a multi-axis goniometer in MTZ format; we assume a single axis in the laboratory frame and calculate frame-by-frame orientations from this.
https://github.com/dials/dials/blob/6ec457a50ce1f7ffabe473190e6a53f322c2b1bd/src/dials/util/export_mtz.py#L276-L279
