### ISSUE TITLE
Online documentation out of date re: default for scan_varying refinement

### ISSUE THREAD

**Issue by maggie-klureza** [dials/dials#2542]
https://dials.github.io/documentation/programs/dials_refine.html shows that the default setting for scan_varying is False. However, my local dials installation (dials-dev20230907) has the default setting as Auto. 

Assuming that this setting hasn't been changed to default to False in the last 6 weeks, it looks like the online documentation is out of date and needs updating.

**Comment by dagewa** [comment]
Hi @maggie-klureza, you are right. I thought this documentation was auto-generated and would have picked up the changed default (`Auto` since 2019: #751). I'll figure out how the documentation is supposed to be updated and do it.

**Comment by dagewa** [comment]
This _should_ get fixed overnight when the website is next built, but I'll reopen now as a reminder to check that.

**Comment by dagewa** [comment]
It did not update overnight because the documentation build is currently broken, so keeping this open for now

**Comment by dagewa** [comment]
It seems this is resolved.
