### ISSUE TITLE
image_viewer open in background by default?

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#2559]
Is there any compelling reason not to do this?

Raised by @jbeilstenedmands

**Comment by graeme-winter** [comment]
i.e. when you type `dials.image_viewer` it releases the terminal? Or we put in the tutorials

```
dials.image_viewer <stuff> &
```

I understand why this was raised, the terminal being busy is a frequently raised workshop problem

**Comment by jbeilstenedmands** [comment]
Yes I raised this as we often see people stumbling on this in tutorials. In my opinion I think it would be better if this happened automatically, rather than having to explain another linux feature to new learners.

**Comment by ndevenish** [comment]
> i.e. when you type `dials.image_viewer` it releases the terminal?

Yes, explicitly this. I don't think the output is ever really useful except for crashes, which we can probably pass through if it happens on launch.

**Comment by dagewa** [comment]
Agree. See also `dials.rlv`
