### ISSUE TITLE
Pyside2 and DUI

### ISSUE THREAD

**Issue by double00six** [dials/dials#2562]
Hi there 

I was wondering if you could help

I have been trying to install the DUI for a user as per website instructions with the latest version of Dials. However there are conflicts when trying install Pyside2, specifically on command, (I include some of the conflicts in attached doc)
libtbx.conda install -c conda-forge pyside2
from
https://github.com/dials/dials/wiki/Installing-DUI

I was wondering if there was a stable version to or other recommend way of installing a DUI

Many thanks for all your help 

[Dials DUI conflicts.odt](https://github.com/dials/dials/files/13565003/Dials.DUI.conflicts.odt)

**Comment by dagewa** [comment]
paging @luisodls

**Comment by dagewa** [comment]
You might like to try to install DUI2 as an alternative? There are some instructions for that here: https://github.com/ccp4/dui2

**Comment by dagewa** [comment]
DUI2 is released, closing this
