### ISSUE TITLE
dials.export is broken with "Error: can't set attribute"

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#2569]
I realized that `dials.export` is broken at the moment:
```
$ dials.version
DIALS 3.dev.1076-g2e18ef586
Python 3.10.12
```

Using 5AUI as in https://github.com/dials/dials/issues/2486#issue-1843165349,
```
dials.import template=images/collect_1_#####.cbf
dials.find_spots nproc=24 imported.expt 
dials.index imported.expt strong.refl 
dials.refine indexed.{expt,refl} scan_varying=True
dials.integrate refined.{expt,refl} nproc=24
dials.symmetry integrated.{expt,refl}
dials.scale symmetrized.{expt,refl} # OK up to here
dials.export scaled.{expt,refl}
```

The final line dies with:
```
Data appears to be scaled, setting intensity = scale
Data appears to be scaled, setting mtz.hklout = 'scaled.mtz'
Read 62609 predicted reflections
Selected 57741 scaled reflections
Combined 1 partial reflections with other partial reflections
Removed 9 intensity.scale.value reflections with I/Sig(I) < -5.0
Error: can't set attribute
```

This problem happens on other datasets as well. Actually I cannot export anything at the moment.

I suspected that my "base" might be outdated. So I reran `python bootstrap.py base`.
This also died with:
```
Out of memory allocating 18446744071562068032*24 bytes!
Process failed with return code -6
```
I don't know if the export problem is caused by old `conda_base` or something else.
I will try clean install.

**Comment by dagewa** [comment]
Hi, I suspect this is due to https://github.com/dials/dials/pull/2549 being merged recently. It requires gemmi to be updated to version 0.6.3, which you should get with a bootstrap or fresh install. I'm not sure why your `python bootstrap.py base` did not work

**Comment by biochem-fan** [comment]
You are right. I did `conda install gemmi` and export is working again. I am sorry for my false alarm.

I don't know why but `bootstrap.py base` isn't working for me. I am trying an alternative
`conda install --file modules/dials/.conda-envs/linux.txt` as written in https://github.com/dials/dials/wiki/Updating-a-development-environment. If this fails, I will delete everything and start from scratch.

**Comment by biochem-fan** [comment]
`conda install --file modules/dials/.conda-envs/linux.txt` worked.
