### ISSUE TITLE
Reduce number of imports, make things more lazy

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#257]
```
$ module load dials/latest
$ time dials.version
8.2 seconds (first run after clearing caches)
$ libtbx.python -v $(libtbx.find_in_repositories dials/command_line/version.py) 2>&1 | grep "^import" | wc -l
300
$ strace -c dials.version
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 71.43    0.095629           8     11812     11226 open
 18.95    0.025371           8      3353      3065 stat
```

Removing imports from [```dials/util/__init__.py```](https://github.com/dials/dials/blob/master/util/__init__.py#L13) and last 4 lines from [```dials/extensions/__init__.py```](https://github.com/dials/dials/blob/master/extensions/__init__.py#L70):
```
$ time dials.version
3.5 seconds (first run after clearing caches)
$ libtbx.python -v $(libtbx.find_in_repositories dials/command_line/version.py) 2>&1 | grep "^import" | wc -l
54
$ strace -c dials.version
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 90.16    0.002886           1      2874      2746 open
  4.75    0.000152           0       899       731 stat
```

Still not good, but better.

**Comment by jmp1985** [comment]
@Anthchirp Is this still open? Also, what about #288 ?

**Comment by Anthchirp** [comment]
Yep, nothing has changed in the mentioned files, so ```dials.version``` still clocks in at 327 imports vs 67 imports with the mentioned lines disabled.

This is independent of the attempt of making importing more efficient. This issue here is about avoiding the imports at all unless actually required.

**Comment by jmp1985** [comment]
Maybe the extension mechanism should be retired anyway. We started with an idea about being able to dynamically add algorithms to dials but I think this may have been more idealistic than practical - only spot finding and integration make use of it anyway.

**Comment by jmp1985** [comment]
The original idea behind the extension mechanism was that a postdoc on a beamline could write an algorithm and it would slot straight into dials with minimal effort just by placing a file in a location on the filesystem similar to how the format system works. 

In over 4 years this has never happened and I suspect will never happen. Therefore, after discussing with @Anthchirp and @ndevenish we have decided that unless there are compelling reasons not to, the extension mechanism will be removed. @graeme-winter  and @dagewa do you have any opinions. The alternative would be to re-write the extension mechanism using package utils which provides a more efficient way of doing things. However, an "if" statement would probably be simpler and more efficient and do the job!

**Comment by Anthchirp** [comment]
Raised at DIALS 9 meeting, and the consensus is that the mechanism can be removed.

**Comment by Anthchirp** [comment]
```
$ time dials.version
```
from 5.4-6.5 seconds down to 0.8-1.7 seconds.

```
$ libtbx.python -v $(libtbx.find_in_repositories dials/command_line/version.py) 2>&1 | grep "^import" | wc -l
```
from 331 down to 55 imports.

```
$ strace -c dials.version
```
from 4162 open() calls with 3531 errors
down to 1149 open() calls with 1019 errors

from 1156 stat() calls with 1190 errors
down to 547 stat() calls with 320 errors.

Closing.
