### ISSUE TITLE
Unexpected behavior of `d_min_start` in `dials.stills_process`

### ISSUE THREAD

**Issue by Baharis** [dials/dials#2584]
I am trying to index simulated XFEL data. Each of my images features more than 1000 strong spots, some well visible up to the corner resolution of 2.5Å. In these conditions, the default orientation refinement protocol fails to refine the initial orientation matrix ~20% of the times. After some suggestions from @phyy-nx, I figured that the refinery must struggle with starting from a large amount of high-resolution data, and thus decided to set `indexing.refinement_protocol.d_min_start = 8.0`. In this resolution range I still have > 200 spots per image. After this change the indexing rate increased from 79% to 99%.

According to the `dials.stills_process` phil string, the desired behavior controlled by `indexing.refinement_protocol` for `mode=refine_shells` is to "refine in increasing resolution cutoffs after indexing". In other words, start from `d_min = d_min_start` and linearly subtract from `d_min`, either `n_macro_cycles` times or in `d_min_step` steps, until all reflections are included or `d_min_final` is reached. In this way, the orientation can be gradually improved by including more and more reflections. The final experimental geometry should still rely on all found spots:

```
  refinement_protocol {
    mode = *refine_shells repredict_only None
      .help = "refine_shells: refine in increasing resolution cutoffs after"
              "indexing. repredict_only: do not refine after indexing, just"
              "update spot predictions. None: do not refine and do not update"
              "spot predictions."
      .type = choice
      .expert_level = 1
    n_macro_cycles = 5
      .help = "Maximum number of macro cycles of refinement, reindexing all"
              "reflections using updated geometry at the beginning of each"
              "cycle. Does not apply to stills.indexer=stills."
      .type = int(value_min=1, allow_none=True)
    d_min_step = Auto
      .help = "Reduction per step in d_min for reflections to include in"
              "refinement."
      .type = float(value_min=0, allow_none=True)
    d_min_start = None
      .type = float(value_min=0, allow_none=True)
    d_min_final = None
      .help = "Do not ever include reflections below this value in refinement."
      .type = float(value_min=0, allow_none=True)
    disable_unit_cell_volume_sanity_check = False
      .help = "Disable sanity check on unrealistic increases in unit cell"
              "volume during refinement."
      .type = bool
      .expert_level = 1
  }
```

I am fairly sure that this isn't what happens at all when using `dials.stills_process`. In fact, most of mentioned parameters are completely unused. The only parameter affecting refinement is `d_min_start`, and its meaning is different than described. It is simply treated as a lower limit of d-spacing ([link](https://github.com/dials/dials/blob/7b19b5f69eb12270e3e3e3569b5dc3e5beb94d56/src/dials/algorithms/indexing/stills_indexer.py#L110)). Consequently, the output files `*indexed.refl` and `*refined.expt` rely only on the information up to `d_min_start`:

```
from dials.array_family import flex
from dxtbx.model import ExperimentList
expt = ExperimentList.from_file('idx-0000_refined.expt', check_format=False)
refl = flex.reflection_table.from_file('idx-0000_refined.expt')
ds = expt[0].crystal.get_unit_cell().d(refl['miller_index']))
print(min(ds), max(ds))
7.986007295763752 127.12173710745984
```

Given these circumstances, I believe that the `indexing.refinement_protocol` for `dials.still_process` needs to be revised. The parameters should at least raise warnings when set, though it would be best if the `refine_shells` mode actually worked. I don't feel competent enough to offer rewriting the code myself, but I would like to start a discussion and help with finding solutions.

**Comment by phyy-nx** [comment]
Hi, the behavior is here is by design but the documentation could be improved.  Further, the source of the issue is not dials.stills_process, but rather the stills indexer, which can be used by dials.index.  The sequences indexer (indexer.py) uses n_macro_cycles but the stills indexer does not.  It does only one round of refinement.  The original rationale was that there are not enough reflections to warrant increasing shells of refinement for stills, so just refine it all at once one time.

If I were to do this again, I'd likely revise the phil block something like this:

```
refinement_protocol {
    sequences {
      mode = *refine_shells repredict_only None
        .help = "refine_shells: refine in increasing resolution cutoffs after"
                "indexing. repredict_only: do not refine after indexing, just"
                "update spot predictions. None: do not refine and do not update"
                "spot predictions."
        .type = choice
        .expert_level = 1
      n_macro_cycles = 5
        .help = "Maximum number of macro cycles of refinement, reindexing all"
                "reflections using updated geometry at the beginning of each"
                "cycle. Does not apply to stills.indexer=stills."
        .type = int(value_min=1, allow_none=True)
      d_min_step = Auto
        .help = "Reduction per step in d_min for reflections to include in"
              "refinement."
        .type = float(value_min=0, allow_none=True)
      d_min_start = None
        .type = float(value_min=0, allow_none=True)
      d_min_final = None
        .help = "Do not ever include reflections below this value in refinement."
        .type = float(value_min=0, allow_none=True)
      disable_unit_cell_volume_sanity_check = False
        .help = "Disable sanity check on unrealistic increases in unit cell"
                "volume during refinement."
        .type = bool
        .expert_level = 1
    }
    stills {
      mode = *refine repredict_only None
        .help = "refine: refine once using reflections up to the d_min cutoff"
                "repredict_only: do not refine after indexing, just"
                "update spot predictions. None: do not refine and do not update"
                "spot predictions."
        .type = choice
        .expert_level = 1
      d_min = Auto
        .help = "Resolution cutoff for reflections to include in refinement."
        .type = float(value_min=0, allow_none=True)
    }
  }
```

This would break a bunch of documentation and even cxi.db depositions with phil files.  Might still be worth it, but it's likely too much.  Instead, adding sentences like "ignored for stills" to a bunch of the existing parameters might be enough.

**Comment by Baharis** [comment]
Thank you; this answers my question. If that is the case, I can think of a way to incorporate your suggestions into the code in the least destructive way. In the meantime, however, let me ask some follow-up questions:

- Given I have a counterexample for the "number of spots" argument, is there any other scientific reason for not implementing shell refinement for stills?
- Is there an alternative way to obtain a refl with "indexed" spots up to max resolution? For example, re-refine with known orientations from expts?
- Alternatively, can one maybe modify `strong.refl` to yield all said spots?

**Comment by phyy-nx** [comment]
> Given I have a counterexample for the "number of spots" argument, is there any other scientific reason for not implementing shell refinement for stills?

Nope, seems like it's worth trying

> Is there an alternative way to obtain a refl with "indexed" spots up to max resolution? For example, re-index and re-refine with a priori known orientations from expts?

`dials.index known.expt strong.refl d_min=X` should use the crystal model from known.expt to index strong.refl

> Alternatively, can one maybe modify phil parameters for strong.refl to yield all said spots?

I don't think so in existing code, but I think the above should work.  If not `known_orientations` will work in `dials.stills_process`

**Comment by Baharis** [comment]
@phyy-nx Thank you for the comments; When investigating #2587 I was surprised to learn that my data can be processed by the `sequences` indexer. It does not allow for multiple crystals per frame, but implements macro-cycles, which – to my dismay – still do not improve my indexing rate. Consequently, this implementation lost some priority; nevertheless, I compared the indexers yesterday: introducing macro-cycles into stills_indexers seems doable, so I will think about it as soon as I have a decent test example.

**Comment by graeme-winter** [comment]
> @phyy-nx Thank you for the comments; When investigating #2587 I was surprised to learn that my data can be processed by the `sequences` indexer. It does not allow for multiple crystals per frame, but implements macro-cycles, which – to my dismay – still do not improve my indexing rate. Consequently, this implementation lost some priority; nevertheless, I compared the indexers yesterday: introducing macro-cycles into stills_indexers seems doable, so I will think about it as soon as I have a decent test example.

Multiple crystals per frame is typically supported through the max lattices keyword which defaults to 1. That said making it work _well_ is a different matter.
