### ISSUE TITLE
`dials.image_viewer` locale failure on WSL Ubuntu 22.04

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2595]
I'm trying out DIALS 3.17.0 installed under WSL for a workshop. The image viewer does not open because of a locale error:
```
$ dials.image_viewer imported.expt strong.refl
Traceback (most recent call last):
  File "/home/fcx32934/sw/dials-v3-17-0/build/../modules/dials/src/dials/command_line/image_viewer.py", line 12, in <module>
    from dials.util.image_viewer.spotfinder_wrap import spot_wrapper
  File "/home/fcx32934/sw/dials-v3-17-0/modules/dials/src/dials/util/image_viewer/spotfinder_wrap.py", line 8, in <module>
    from .slip_viewer.frame import chooser_wrapper as _chooser_wrapper
  File "/home/fcx32934/sw/dials-v3-17-0/modules/dials/src/dials/util/image_viewer/slip_viewer/frame.py", line 19, in <module>
    from ..rstbx_frame import EVT_EXTERNAL_UPDATE
  File "/home/fcx32934/sw/dials-v3-17-0/modules/dials/src/dials/util/image_viewer/rstbx_frame.py", line 10, in <module>
    import wxtbx.plots
  File "/home/fcx32934/sw/dials-v3-17-0/modules/cctbx_project/wxtbx/plots/__init__.py", line 18, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/home/fcx32934/sw/dials-v3-17-0/conda_base/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
The output of `locale` is this:
```
$ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```
Not sure what is wrong because this output is the same as my Ubuntu 22.04 native laptop, except that in that case `LANGUAGE=en_GB.UTF-8` is also set. But I have tried setting that too for WSL and it made no difference.

Any ideas?

**Comment by ndevenish** [comment]
Setting `LC_ALL=`? Either to `en_GB.UTF-8` or apparently `LC_ALL=C` is a basic sanity check?

**Comment by ndevenish** [comment]
.. . there does seem to be several places this is overridden in cctbx so I don't know if that is causing interference inside python, for some reason

**Comment by dagewa** [comment]
Thanks, I hit some other issues so am currently going through a complete purge and reinstall of WSL. If I get back here I'll try the above

**Comment by dagewa** [comment]
Ok, `LC_ALL=C dials.image_viewer imported.expt` did not work, but editing the line where it failed to 
```
  locale.setlocale(locale.LC_ALL, 'C')
```
_does_ work.

**Comment by dagewa** [comment]
Sigh. It simply did not work with `en_GB.UTF-8`. I had to use `sudo dpkg-reconfigure locales` to generate the `en_US.UTF-8` locale and set _that_ as the system default. Now `dials.image_viewer` (unmodified) and `dials.python` both work fine

**Comment by dagewa** [comment]
I think I can close this now. I don't know _why_ it was necessary to install the `en_US.UTF-8` locale, and why the behaviour under WSL seemed different to native Ubuntu 22.04, but at least we know what the solution is.
