### ISSUE TITLE
rs_mapper - scale of the output

### ISSUE THREAD

**Issue by wojdyr** [dials/dials#261]
We've been playing with a [viewer][1] that could show both reciprocal lattice spots and a map generated by rs_mapper. So I get spots generated by @rjgildea 's [script](https://github.com/dials/dials_scratch/blob/master/rjg/rl_json.py)
and a map generated by @biochem-fan 's rs_mapper. The first one is in units 1/A, but the latter is not in any particular units?
I was advised to rescale the map by factor 2 / (grid_size * max_resolution), and it seems to work, i.e. it matches the spots found by dials:

![rlp_and_map_2](https://cloud.githubusercontent.com/assets/491873/20888324/443ac70c-baf6-11e6-9a02-4daa2872149c.png)

but the max_resolution is not written in the map file.

Any thoughts? Ideally the "unit cell" of the map would be in 1/A and no re-scaling would be necessary, but I don't know if other programs (pymol etc) could handle it.

[1]: http://uglymol.github.io/reciprocal.html

**Comment by biochem-fan** [comment]
Hi,

I have a SACLA beamtime until next Monday. I will look into this after that. I am sorry for delay.

**Comment by wojdyr** [comment]
Hi Takanori, no need to hurry. If there is anything to discuss or test - I'll get to it after New Year, as I'll be on holidays for the rest of December.

**Comment by wojdyr** [comment]
Hi, could we get back to it?

**Comment by biochem-fan** [comment]
Hi, 

I am sorry for delay.

Yes, we can change the scale when writing the map.
https://github.com/dials/dials/blob/master/command_line/rs_mapper.py#L115
I think PyMOL can handle arbitrary map scale.

**Comment by wojdyr** [comment]
Thanks Takanori. I'm testing now my viewer, it seems to work:
![screenshot_2017-01-20_18-47-49](https://cloud.githubusercontent.com/assets/491873/22161573/de04c566-df42-11e6-8f38-2703cb1f8fc3.png)

I'll soon open a pull request and write more about it.
