### ISSUE TITLE
dials.image_viewer - Format error takes two clicks to clear

### ISSUE THREAD

**Issue by dagewa** [dials/dials#262]
![imageviewer](https://cloud.githubusercontent.com/assets/11502083/20922227/4d9a548a-bb9f-11e6-944c-2b53e89a0dd4.png)

I attempted to jump to an image beyond the end of the dataset. I get a sensible error pop-up, but I am unable to clear that error. If I click 'OK' it just comes back again.

**Comment by dagewa** [comment]
Actually after clicking 3 times the box does clear, for the version at the head of the master branch (DIALS 1.dev.990-g85a786e). For the version in CCP4 (DIALS 1.3.5-g214df5b-release) it takes many more clicks than this, or never clears ;-)

**Comment by rjgildea** [comment]
You should only have to click on it 2 times now! For some reason OnJumpToImage() gets called twice, once via OnEnter() and once via OnFocusLost(). Not sure why this is...

**Comment by dagewa** [comment]
Interestingly, if I'm stupid enough to do it again, it takes 3 clicks to clear.

There seems to be a new problem too. The first time I attempt to jump outside the scan the box does not appear, and there is a traceback:

```
Traceback (most recent call last):
  File "/home/david/bsx/cctbx-svn/sources/dials/util/spotfinder_frame.py", line 168, in OnJumpToImage
    self.load_image(self.image_chooser.GetClientData(phil_value - 1))
  File "/home/david/bsx/cctbx-svn/sources/dials/util/spotfinder_frame.py", line 352, in load_image
    show_untrusted=show_untrusted)
  File "/home/david/bsx/cctbx-svn/sources/cctbx_project/rstbx/slip_viewer/frame.py", line 324, in load_image
    img = rv_image(os.path.abspath(file_name_or_data))
  File "/usr/lib/python2.7/posixpath.py", line 367, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

```

**Comment by dagewa** [comment]
The other issues seem to be fine now. All that's left is that the message box takes two clicks to clear.
