### ISSUE TITLE
radiation damage series?

### ISSUE THREAD

**Issue by mysecondnameisdanger** [dials/dials#2629]
How to treat radiation damage series?
Let's say I collected the same dataset from the same crystal many times...(each time with 2 sweeps, defined in the `master.h5` file).

I am doing a simple for loop in `bash` like this ..

```
#!/bin/bash
# First crystal
for i in `seq -w 49 72`
do
  mkdir ${i}
  # run xia2 in the folder with the datasets
  xia2 pipeline=dials space_group=X /home/msnid/NSLS2/${i} image=/home/msnid/NSLS2/Test-msnid-3-15_122${i}_master.h5
done

```

Is this the correct way to do it?

**Comment by graeme-winter** [comment]
You have two sweeps in _each_ `master` file?

TBH for this use case I would use "raw" DIALS

```
dials.import /home/msnid/NSLS2/Test-msnid-3-15_122??_master.h5
dials.find_spots imported.expt
dials.index imported.expt strong.refl [space_group=X if you think it would help]
dials.refine indexed.expt indexed.refl
dials.integrate refined.expt refined.refl
dials.symmetry integrated.expt integrated.refl
dials.scale symmetrized.expt symmetrized.refl \
  anomalous=true absorption_level=medium
```

or something similar, then look at the output from the scaling to see how the sample evolved over time. This does depend on the two sweeps being correctly understood geometry wise, as it only indexes all `N` sweeps with a single orientation matrix to start with, but ensures in scaling that these all have the same unique Miller index

I'll keep this issue open and close the one in `xia2`

**Comment by mysecondnameisdanger** [comment]
uhmmm 
... sorry...for the confusion... 
 I have two masters (one for each sweep). Each master with two data (`*_data_00000?.h5`) files.

I was asking because, I believe (I am right?) I need to specify the first dataset as a reference for all later datasets? (I am planning to run [ridl](https://github.com/GarmanGroup/RIDL) later)

**Comment by graeme-winter** [comment]
If each `master.h5` has > 1 data file that's no problem at all

You have many `master.h5` files taken one after the other on the same crystal? Then the spell above will work fine

**Comment by dagewa** [comment]
I believe @graeme-winter refers to his spell (dials/raw), and that this is answered.
