### ISSUE TITLE
phil parameter disambiguation

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#265]
I assert we can do better than
```
Sorry: Ambiguous parameter definition: global_threshold = 20.0
Best matches:
  spotfinder.threshold.xds.global_threshold
  spotfinder.threshold.helen.global_threshold
```

Step 1: Suggest distinguishing two levels of ambiguity.
* If one of the matches has a minimum expert_level, ie which is lower than that of all alternative matches, then print a warning: ```You said xx. I think you meant 'banana' and I will proceed under this assumption.```.
* If two or more matches have the same minimum expert_levels, fail. Potentially list the more likely options first.

Step 2: Change expert_level of all extension stuff to positive infinity.

**Comment by dagewa** [comment]
Interesting... Also currently affects scan-varying refinement with parameters like `interval_width_degrees`. This probably means changes to libtbx/phil, so perhaps is a cctbx issue?

**Comment by Anthchirp** [comment]
Yes, this is definitely a cctbx/libtbx issue, but cctbx does not have a github issue tracker for $reasons.

**Comment by Anthchirp** [comment]
libtbx part in cctbx/cctbx_project#8. This issue to track setting expert_level priority settings in dials.
