### ISSUE TITLE
Unit cell tool doesn't work in dials.image_viewer

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#267]
Note, this works for cctbx.image_viewer.  Run dials.image_viewer, select Actions->Show unit cell tool. Exception: 
  File "<snip>/cctbx_project/rstbx/slip_viewer/uc_frame.py", line 45, in __init__
    if self.phil_params.calibrate_unitcell.unitcell is not None:
AttributeError: 'scope_extract' object has no attribute 'calibrate_unitcell'

**Comment by rjgildea** [comment]
Presumably these phil parameters (wherever they are defined?) need adding to the dials.image_viewer phil parameters if this is to work.
