### ISSUE TITLE
Setting refinement_protocol.mode=None for dials.index can result in failure

### ISSUE THREAD

**Issue by PrinceWalnut** [dials/dials#2686]
In [this line](https://github.com/dials/dials/blob/97e2b7327236666bd025bbbbc98eb383683fce17/src/dials/algorithms/indexing/indexer.py#L658) we have the code block for `refinement_protocol.mode=None`. We have that `refined_reflections` becomes `reflections_for_refinement`, which are the indexed reflections. There does not seem to be any column of the variety `xyzcal.XX`, so when this set of reflections proceeds to [this line](https://github.com/dials/dials/blob/97e2b7327236666bd025bbbbc98eb383683fce17/src/dials/algorithms/indexing/indexer.py#L786) then DIALS is unable to find the column to convert mm to pixels. I'm not certain, but I would guess that the refinement engine is assumed to have supplied the `xyzcal.mm` column, but since no refinement was run there is no such column.

**Comment by dagewa** [comment]
Looks like I was responsible for adding this feature to scans refinement, in https://github.com/dials/dials/pull/2456, so I'll try to pick this up.
