### ISSUE TITLE
Mask generation for multi-panel detectors

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#2712]
How should masks for multi-panel detectors be generated?

Our new XFEL detector (CITIUS) has 72 panels. My pipeline masks module borders and stores it in the NXmx file but users need to add masks for the beam stopper, the injector nozzle etc. Because they vary from experiment to experiment,  they cannot be hard-coded in the preprocessing pipeline.

`dials.image_viewer`'s masking tool complains "Point must be within a panel" (circle tool), "All points must be contained within a single panel" (polygon tool).

`dials.generate_mask imported.expt circle=-23,5,100` (coordinates were read from the image viewer's toolbar) made a mask on the first panel (the top left panel in the image), not on the image center.

(The beam stopper for our previous detector, MPCCD, was glued to the capton window and lacked the "arm". Thus, we could use the `d_max` option for masking. This does not apply to CITIUS.)

@phyy-nx do you have any experiences with CSPAD?

<img width="566" alt="image" src="https://github.com/user-attachments/assets/18b588a8-4cac-4157-9802-239d285bf141">

**Comment by graeme-winter** [comment]
For reference: is some data available? The errors you report feel like unnecessarily tight constraints

**Comment by biochem-fan** [comment]
The CITIUS image above is not available yet because I haven't finalized my NXmx writer but the same issue can be observed in any multi-panel detectors. For example, an MPCCD example is in [dials-data/image_examples/SACLA-MPCCD-Phase3-21528-5images.h5](https://github.com/dials/data-files/blob/master/image_examples/SACLA-MPCCD-Phase3-21528-5images.h5).

> The errors you report feel like unnecessarily tight constraints

Having a global 2D coordinate system is non-trivial for segmented detectors with non-parallel sensors (e.g. PILATUS 12M-DLS). But for the rest, removing this constraint is very useful.

**Comment by phyy-nx** [comment]
For this kind of thing (like on the cspad, jungfrau, or mpccd detectors), I either mask each panel by hand using the polygon tool or I use a threshold.  For thresholding, I use dxtbx.image_average with a water only run and hopefully the beamstop is the lowest counts on the average, standard deviation, or max image.  Then I run a script like this one:

```
import dxtbx 
from libtbx import easy_pickle 
image=dxtbx.load('avg.cbf') 
m=tuple([d>=3 for d in image.get_raw_data()]) # keep all pixels with at least 3 counts on the average
easy_pickle.dump('threshold_3.mask', m)
```

Then I'd inspect the new mask to be sure it wasn't masking out any dead or weak pixels.  Thresholding average/stddev/max images in different ways works pretty well in a lot of cases, and was the basis of the original (now long since deprecated) [cspad masking code](http://viper.lbl.gov:8080/cctbx.xfel/index.php/Preparatory_steps_pyana_version#Creating_a_mask_image) for pyana.

**Comment by phyy-nx** [comment]
Of course, realistically it is not outside of the realm of programming to fix the masking tool in the image viewer such that I can drag a box across multiple panels and have it mask out all the pixels it crosses without raising any exceptions.  Someone's just gotta sit down and do that math, converting from image to pixel space as appropriate.

**Comment by biochem-fan** [comment]
@phyy-nx
I see. Supporting multi-panel masking would be very useful as more and more segmented detectors are introduced, but I understand it is not trivial.

For the meanwhile, your approach seems a practical compromise.

FYI: XDS generates shadow masks by comparing the average pixel value with the radial average.
https://xds.mr.mpg.de/html_doc/xds_program.html#DEFPIX
https://xds.mr.mpg.de/html_doc/xds_files.html#ABS.cbf

**Comment by biochem-fan** [comment]
Apparently `dxtbx.image_average` (or `FullCBFWriter`) has a bug.
Even though the original NXmx file is properly displayed (see the first post), the panels are shuffled in the resulting average/max/sd images written in CBF.

![image](https://github.com/user-attachments/assets/d4f9989a-a8f3-4698-bc32-9182aac5e40f)

I will investigate further and make a new issue in the dxtbx repo.

**Comment by phyy-nx** [comment]
Whoa!  Yup that's a bug.

**Comment by biochem-fan** [comment]
@phyy-nx I submitted a bug report with test files to cctbx/dxtbx#745.

**Comment by biochem-fan** [comment]
Probably we can extend the rectangle mask tool in `dials.image_viewer` for multiple panels. We can intersect a polygon with each panel in the image viewer's projected (Geo) coordinate system using functions in `algorithms/polygon/clip`. We cannot support the circle tool because a circle in the projected, image viewer coordinate system does not necessarily becomes a circle on a panel. Similarly we cannot support the rectangle tool because an edge-aligned rectangle in the viewer is not necessarily edge-aligned (e.g. when the panel is rotated by non-multiples of 90 degrees).

**Comment by biochem-fan** [comment]
@phyy-nx @graeme-winter 

> Of course, realistically it is not outside of the realm of programming to fix the masking tool in the image viewer such that I can drag a box across multiple panels and have it mask out all the pixels it crosses without raising any exceptions. Someone's just gotta sit down and do that math, converting from image to pixel space as appropriate.

My polygon clipping idea seems working :)

<img width="72" alt="image" src="https://github.com/user-attachments/assets/520e0da2-c6a1-4855-b142-ae7e8b94bd1a">

**Comment by dagewa** [comment]
Nice! Looks possibly offset by ~1 pixel between the polygon and the mask, but I have a feeling that might be another longstanding mask tool bug

**Comment by biochem-fan** [comment]
Indeed the cyan line is slightly off. This is probably related to #2190. Fortunately, the resulting mask is correct (i.e. touching panel edges).
