### ISSUE TITLE
Add input parameters to xia2/dials?

### ISSUE THREAD

**Issue by mysecondnameisdanger** [dials/dials#2716]
In autoproc/xds I have this macro file,

```
autoPROC_XdsKeyword_UNTRUSTED_QUADRILATERAL=" 0 1337 0 1253 764 1274 764 1319"
autoPROC_XdsKeyword_UNTRUSTED_QUADRILATERAL="  764 1279 764 1310 1190 1307 1190 1282"
autoPROC_XdsKeyword_UNTRUSTED_QUADRILATERAL=" 1190 1282 1196 1289 1196 1300 1190 1307"
autoPROC_Img2Xds_DamagedPixels="1232,1297 1179,1297 1224,1302 1229,1278 1237,1295 1228,1278 1237,1295 1238,1295 1235,1296 1236,1296 1237,1296 1233,1297 1230,1298 1231,1298 1232,1298 1224,1302"
autoPROC_XdsKeyword_OVERLOAD=1048575
```

and that can be fed into `process` with something like this `process -M macro ...`

Now, I want to process the datasets with xia2/dials...using the same parameters in the `macro` file ... but... How is that done?

Thanks

**Comment by graeme-winter** [comment]
Sorry, been away for some time, will see what we can do here

**Comment by dagewa** [comment]
This seems like a xia2 issue. I would transfer the issue, but it isn't letting me. Please re-open there if this is still a problem.
