### ISSUE TITLE
tst_scan_varying_prediction_parameters.py platform differences

### ISSUE THREAD

**Issue by dagewa** [dials/dials#272]
Why do comparisons between analytical derivatives and finite difference approximations exhibit platform differences at the level of 1e-6? Tolerances are now increased, which is probably reasonable, but it would be good to understand why the results are this different. Is it the analytical or finite difference calculation that causes the greatest discrepancy?

**Comment by Anthchirp** [comment]
unlikely to be investigated any time soon.
