### ISSUE TITLE
Cannot process Eiger data with DIALS

### ISSUE THREAD

**Issue by markArmstrong989** [dials/dials#2720]
It should be a rotational dataset but is being interpreted by dials as stills. Similar problem to this issue: https://github.com/dials/dials/issues/126. The conclusion of that issue was that the metadata was the problem. In this case the metadata seems to be correct for a phi scan.

<img width="703" alt="thumbnail_screenshot" src="https://github.com/user-attachments/assets/533fdcc8-935b-4d22-bb21-35d32e933d90">

The logging from the import is below:
```
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.20
The following parameters have been modified:

input {
  experiments = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNXmxEigerFilewriter.FormatNXmxEigerFilewriter'>
  template: C:\Users\marka\Documents\data\Ylid\series_2\series_2_master.h5:1:360
  num images: 360
  sequences:
    still:    1
    sweep:    0
  num stills: 0
--------------------------------------------------------------------------------
Writing experiments to imported.expt
```
dials.show imported.expt is really long because there's 360 stills but here is the last one
```
Experiment 359:
Experiment identifier: 4e7db1c8-f5ed-5a08-8788-0017103ebcb1
Image template: C:\Users\marka\Documents\data\Ylid\series_2\series_2_master.h5
Detector:
Panel:
  name: /entry/instrument/detector/module
  type: SENSOR_PAD
  identifier:
  pixel_size:{0.075,0.075}
  image_size: {2068,2162}
  trusted_range: {0,382559}
  thickness: 0.45
  material: Si
  mu: 9.92318
  gain: 1
  pedestal: 0
  fast_axis: {1,0,0}
  slow_axis: {0,-1,0}
  origin: {-83.775,88.35,-50}
  distance: 50
  pixel to millimeter strategy: ParallaxCorrectedPxMmStrategy
    mu: 9.92318
    t0: 0.45


Max resolution (at corners): 1.204917
Max resolution (inscribed):  1.454253

Beam:
    probe: x-ray
    wavelength: 1.3416
    sample to source direction : {0,0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999
    flux: 0
    transmission: 1
    sample to source distance: 0

Beam centre:
    mm: (83.77,88.35)
    px: (1117.00,1178.00)

Scan:
    number of images:   1
    image range:   {360,360}
    epoch:    35.9
    exposure time:    0.1
    oscillation:   {20,0}

Goniometer:
    Rotation axis:   {1,0,0}
    Fixed rotation:  {1,0,0,0,1,0,0,0,1}
    Setting rotation:{1,0,0,0,1,0,0,0,1}
```

I've tried a few versions of dials including 3.20 used above and the dev version. The version of Simplon is 1.8.0. Maybe also useful is that if I configure the detector for an omega scan instead it is loaded as a sweep (still with a single axis goniometer though). A link to the data in dropbox: https://www.dropbox.com/scl/fo/cki5qwexbqvbaz8bhs1p0/APlSWoKQYjf1z_Pma3WeU1E?rlkey=ltzefowmowgyvrhaatz4cj9ma&st=6lhbmxrd&dl=0

**Comment by markArmstrong989** [comment]
Looked into it a bit more and it seems that the depends_on metadata stuff was setup wrong. entry/sample/depends_on was going to entry/sample/transformations/omega which had an attribute depends on going to entry/sample/transformations/translation and that was the end of the dependency chain. So even though it had the other angle data it was getting ignored. After fixing that it loaded as a sweep.

**Comment by graeme-winter** [comment]
Thanks for documenting the fix, I have been out of the office

I would take from this that some tools to show the chain would be useful but possible more in the scope of NXmx than dials per se - your issue is helpful for others who will stub their toes on this in future
