### ISSUE TITLE
Is the polarization correction relevant for electrons and neutrons?

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#2734]
The `lp` column in the reflection table contains contributions from both the Lorentz correction and the polarization correction. When we process electron diffraction datasets **kinematically**, we need to apply the Lorentz correction $\zeta \sin(2\theta)$. But I am not sure if the polarization correction is relevant for electrons; the electric field $E$ for X-ray is a vector field but electron's wave function is a scalar field (we ignore spins).

In the code below, `L` corresponds to the Lorentz correction while `P` is the polarization correction. Although "a value of 0.5 implies an unpolarized beam", only `P2` vanishes and `P4` remains non-zero as $(1+\cos^2 2\theta)/2$.

https://github.com/dials/dials/blob/1747513625b726af062658048dfb57db593539f8/src/dials/algorithms/integration/corrections.h#L30-L60

Admittedly, this is merely an resolution dependent scale factor, which can be partially absorbed into atomic B factors. Because $2\theta$ is very small in electron diffraction, the effect is not large, but if the right physics is without the polarization corection, we should disable it using the new probe type field in dxtbx (https://github.com/cctbx/dxtbx/issues/575).

I am not an expert on the physics. Does anyone know if the polarization correction is necessary or not?

**Comment by dagewa** [comment]
I am sure the polarization correction is not correct for electrons. However, in most format classes for electron diffraction I try to set `polarization_fraction=0.5` in the beam model (which means unpolarized). Even in cases where this is not set, the fact that scattered beams are all very low angle means that the polarization correction is very small. Eventually it would be useful to switch this off according to the `Probe` type of the beam (noting that it is also not correct for neutrons @toastisme)

**Comment by biochem-fan** [comment]
@dagewa

> I am sure the polarization correction is not correct for electrons.

Thank you very much for confirmation.

As I pointed out above, "set polarization_fraction=0.5 in the beam model" does not completely turn it off, since $(1+\cos^2 2\theta)/2$ remains.

> Eventually it would be useful to switch this off according to the Probe type of the beam

This sounds the right direction.

**Comment by dagewa** [comment]
Ah yes, I did not read your comment properly. I had not realised before that `polarization_fraction=0.5` does not in fact "switch off" the correction. Interesting. What does this mean for X-ray home sources?

Meanwhile, I agree we should disable this based on `Probe`.

**Comment by biochem-fan** [comment]
> I had not realised before that `polarization_fraction=0.5` does not in fact "switch off" the correction. Interesting. 
 What does this mean for X-ray home sources?

This means that there is a resolution dependent intensity scaling even with an unpolarized beam. @keitaroyam pointed this out to me and referred me to [Thomson scattering](https://en.wikipedia.org/wiki/Thomson_scattering#Description_of_the_phenomenon). See the figure there. The same factor applies regardless of the polarization direction. Thus, the factor survives after averaging over all oscillation directions in unpolarized light.

That being said, a quick calculation for a reflection at d = 0.5 Å for 200 kV (0.0251 Å) electrons resulted in $2\theta$ ~ 0.05 rad. Thus, $(1+\cos^2 2\theta)/2$ ~ 0.998. The error is tiny and the priority of this issue is low.

**Comment by dagewa** [comment]
Ok, for X-ray `P4` is correct as it is the isotropic reduction in intensity due to scattering at some angle no matter the polarization

**Comment by biochem-fan** [comment]
Yes.

**Comment by dagewa** [comment]
Although, we are not currently using `dials.scale` for neutron diffraction, so the corrections are not applied.
