### ISSUE TITLE
Reading Eiger data on Apple Silicon computers "feels slow"

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2775]
I appreciate that this is on the face of it an unhelpful issue to report however

It really does feel very slow processing Eiger data on my M2 Pro, and I suspect a chunk of that is that the decompression is using the basic C implementation of bitshuffle whilst on x86-64 the code uses a lot of SIMD instructions via Intel intrinsics

We should explore optimising bitshuffle on ARM architecture using e.g. SVE2 intrinsics which are _probably_ comparable. I appreciate that this will involve upstreaming the change sets to the `bitshuffle` library and plugin so is not a trivial commitment. I need to do this for other reasons anyway so self-assigning.

**Comment by biochem-fan** [comment]
Are you sure the bottleneck is really in bitshuffle, not lz4 decompression or other routines? You can benchmark it by `h5repack`-ing the data without any compression, with lz4 alone or with bitshuffle alone. The latter needs trivial codes with `h5py`.

**Comment by biochem-fan** [comment]
> using e.g. SVE2 intrinsics

As far as I know, SVE/SVE2 is not supported by Apple M series. They support NEON, which [bitshuffle already uses](https://github.com/kiyo-masui/bitshuffle/blob/master/src/bitshuffle_core.c#L61).

**Comment by graeme-winter** [comment]
> > using e.g. SVE2 intrinsics
> 
> As far as I know, SVE/SVE2 is not supported by Apple M series. They support NEON, which [bitshuffle already uses](https://github.com/kiyo-masui/bitshuffle/blob/master/src/bitshuffle_core.c#L61).

Ah, thank you - I was probably becoming confused between multiple implementations of `bitshuffle` I had looked at recently

I had not realised SVE2 is not supported by M series: I thought this was a standard part of the ARMv8 specification. Will explore.

**Comment by graeme-winter** [comment]
> Are you sure the bottleneck is really in bitshuffle, not lz4 decompression or other routines? You can benchmark it by `h5repack`-ing the data without any compression, with lz4 alone or with bitshuffle alone. The latter needs trivial codes with `h5py`.

Hard to measure, but you are right I should

**Comment by graeme-winter** [comment]
I'll close this now, with a view to doing some benchmarking before opening another
