### ISSUE TITLE
Running Dials on Apple Silicon?

### ISSUE THREAD

**Issue by AZangiabadi** [dials/dials#2789]
It seems Dials installation doesn't recognize apple silicon (M2) and after installation, running the dials_env.sh doesn't do anything. 

Is there any solution for this?

Thank you,
Amir

```shell
    ==========================================================================
                          DIALS Installation

                          version: dev20241031
                     machine type: mac-intel-osx-x86_64
                       OS version: 15.0
                      destination: /usr/local/dials-dev20241031
                  # of processors: 8
    =========================================================================

Configuring DIALS components...
**********************************
* Finalizing DIALS installation*
*********************************
Log file: /Users/amir/dials-installer-dev/base_tmp/install_finalize.log
Generating DIALS environment setup scripts...
Generating DIALS environment additions for dispatchers...
Calling write_gui_dispatcher_include
  args ['--build_dir=/usr/local/dials-dev20241031/build', '--base_dir=/usr/local/dials-dev20241031/conda_base', '--suffix=dials', '--gtk_version=2.10.0', '--quiet', '--use_conda', '--ignore_missing_dirs']
  prologue export DIALS="/usr/local/dials-dev20241031"
export DIALS_VERSION=dev20241031
export DIALS_ENVIRONMENT=1
export DIALS_MTYPE=mac-intel-osx-x86_64
  epilogue 
Configuring DIALS components...
Precompiling .py files...
**************************
* Installation complete! *
**************************
(base) amir@Amir-MacBook-Air dials-installer-dev % cd /usr/local/dials-dev20241031 
(base) amir@Amir-MacBook-Air dials-dev20241031 % source dials_env.sh     
(base) amir@Amir-MacBook-Air dials-dev20241031 % source dials_env.sh
(base) amir@Amir-MacBook-Air dials-dev20241031 % 
```

**Comment by graeme-winter** [comment]
This is correct, it does not do anything _visible_

Instead when you source `dials_env.sh` you will then find the dials executables in the PATH so that you can e.g. follow the tutorial at 

https://github.com/graeme-winter/dials_tutorials/blob/main/ccp4-aps-2024/WORKFLOW.md

Now, I also note that you appear to have installed the x86-64 version rather than the apple silicon version, which I _think_ we do produce

**Comment by graeme-winter** [comment]
Though the x86-64 version will work because there are tools in the OS to translate the code on-the-fly

**Comment by AZangiabadi** [comment]
Thanks @graeme-winter for your quick reply!
I made it to work. Sorry for my silly question. 

Best,
Amir

**Comment by ndevenish** [comment]
Hi @AZangiabadi -

Yes, we don't distribute directly a DIALS installer for macOS arm; some issues with the legacy installer producer that we use (which a solution is being worked on).

What Graeme suggests works, but in the meantime the easiest way (if you are familiar with conda) is probably getting it from conda-forge, e.g. something like `conda install -c conda-forge dials`. 

Nick

**Comment by AZangiabadi** [comment]
Thanks very much @ndevenish.
This would be helpful.
