### ISSUE TITLE
In dials.reciprocal_lattice_viewer if data are indexed please can we align on a*, b*, c* as option

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#279]
i.e. have button a* / b* / c* which will allow you to align lattice accordingly; will then set b*; c* as close as possible to alignment with cardinal axes on image (i.e. x, y)

**Comment by dagewa** [comment]
I'm going to say that now we have the option to view the reciprocal cell, manual alignment is not too tedious. This feature would still be a nice-to-have, but it may be better to add it to a `dials.rlv` replacement, possibly based on https://github.com/toastisme/dials_browser_rlv

Please feel free to re-open if you disagree.
