### ISSUE TITLE
Output mmCIF with unmerged data from DIALS

### ISSUE THREAD

**Issue by dagewa** [dials/dials#281]
The mmCIF working group has a data proposal for mmCIF files that contain unmerged (and merged) intensity data, plus other items useful for archive, allowing investigation of e.g. space group assignment in deposited data.

The group requests that DIALS allows export in this format, which is currently still in a draft state, for testing. In future, extend this to include scaled and merged data. I do not know if the draft proposal should be distributed outside of the working group, so it is not copied here, but I can provide on request.

**Comment by jmp1985** [comment]
Hi David,

Sounds interesting. I would like to see the proposal - last time I looked at mmCIF the format lacked a lot of the required information. Ideally, it would have columns for all the things in the NXreflections specification that Aaron recently got through in the Nexus committee meeting.

James

________________________________

**Comment by dagewa** [comment]
Hi James, fowarded on. You will find that mmCIF still lacks a lot of information. The goal, as far as I understand it, is a lean archive format with just enough information to allow certain things like space group assignment to be tested at a later date. It is not to be considered a working data format. But it is quite possible that some information from NXreflections could be useful.

**Comment by jmp1985** [comment]
I have added this functionality based on the document you sent me. However, I have zero experience with CIF files so if you could look over what I'm outputting and let me know if I've interpreted the document correctly, that would be awesome!

**Comment by rjgildea** [comment]
Hi James, is there any particular reason you haven't made use of iotbx.cif in your CIF output? See e.g. https://github.com/cctbx/cctbx_project/blob/master/iotbx/cif/__init__.py#L218

**Comment by dagewa** [comment]
Thanks James! I will take a look through. I'm happy to look at using iotbx.cif too.

**Comment by Anthchirp** [comment]
I think we should use ```format=mmcif``` instead of ```format=cif``` to avoid confusing those two

**Comment by Anthchirp** [comment]
No idea if useful, but we generate CIF/mmCIF files in xia2 with iotbx.cif:
https://github.com/xia2/xia2/blob/master/Handlers/CIF.py

**Comment by jmp1985** [comment]
Hi Markus,

I'll have a look at this in a bit

James
________________________________

**Comment by jmp1985** [comment]
I've updated the definitions to match those in the example file. And now you do format=mmcif. I think we're getting closer!

**Comment by jmp1985** [comment]
Output seems to validate using iotbx.cif.validate so I'm closing this issue.

[mmcif_pdbx_v5_rc_with_draft-diffrn-data-set-extension.dic.zip](https://github.com/dials/dials/files/716323/mmcif_pdbx_v5_rc_with_draft-diffrn-data-set-extension.dic.zip)

**Comment by dagewa** [comment]
@jbeilstenedmands we're now nearly in a position to write out mmCIF including scaled, unmerged, intensities. This is the original issue, and there is now a repository at https://github.com/pdbxmmcifwg/diffrn-data-set-extension detailing the format required

**Comment by jbeilstenedmands** [comment]
I have now implemented this in the refactor-export-mtz branch, as it relies on my new filtering for export code, but this issue is ready to be closed once the changes are merged in.
However we may need to get further clarification on the mmCIF standard in future, as there is some ambiguity in how exactly we should be reporting scaled data, which is not addressed in the files in the pdbxmmcifwig repo.

**Comment by dagewa** [comment]
Hi @jbeilstenedmands , sounds good and the timing is just right... the mmCIF working group has awoken from hibernation and want to organise a meeting soon. It will be really useful if I can send round a scaled example file for comment. I'll generate this using the `refactor-export-mtz` branch for now.

**Comment by dagewa** [comment]
I just tried `dials.export scaled.pickle scaled_experiments.json format=mmcif` using the refactor-export-mtz branch, but I see
```
pdbx_diffrn_data_section.type_scaled false
```
in the output. Have I done something wrong?

**Comment by dagewa** [comment]
Oh, I see, it is not automatic. I need to add something like `intensity="*prf *sum *scale"` to the command. Hmmm.

**Comment by jbeilstenedmands** [comment]
Hi David, did you get this to work in the end?  (To get this to parse try intensity='prf'+'sum'+'scale' ). Scale is not automatic as this is my attempt at a unified interface for all export types and keeping the defaults to match current behaviour at this point in time.

**Comment by dagewa** [comment]
Hi James, yes, once I found the option it worked fine. I'm not sure what the best default behaviour should be, but that can be discussed later.

**Comment by dagewa** [comment]
It seems that the PDB would ideally like the scaling statistics written into mmCIF as well as the unmerged intensities. The relevant categories are [reflns](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/reflns.html) and [reflns_shell](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/reflns_shell.html). The examples look reasonably straightforward.

**Comment by dagewa** [comment]
Closing this as the feature now exists. Future requests as the format develops may get their own issues
