### ISSUE TITLE
dials.import: add simple mechanism to import data set as 3 chunks

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2815]
![Screenshot 2024-11-22 at 06 51 10](https://github.com/user-attachments/assets/aba5652b-306e-4fc5-81b1-266e5ab09a89)

Vector data collection at 3 points, 3600 at each => 10800 in total

```
dials.import (data) image_range=1,3600 image_range=3601,7200 image_range=7201,10800
```

only imports the last range, I ended up with

```
export DATA=/dls/i04/data/2024/mx39148-1/TestThermolysin/Thermolysin_12/Thermolysin_12_3_master.h5

dials.import $DATA image_range=1,3600 output.experiments=imp0.expt
dials.import $DATA image_range=3601,7200 output.experiments=imp1.expt
dials.import $DATA image_range=7201,10800 output.experiments=imp2.expt

dials.combine_experiments imp0.expt imp1.expt imp2.expt
dials.find_spots combined.expt
```

which is _horrible_ 🤣

**Comment by biochem-fan** [comment]
+1 for this.

Small wedge datasets from SPring-8 (e.g. https://xrda.pdbj.org/entry/277/path/cpv1deg/PH1deg-CPS0296-04/data) also benefit from this.

> Diffraction images from multiple crystal locations are stored in a single set of HDF5 files. The number of frames per location (crystal) is stored in `/entry/instrument/detector/detectorSpecific/nimages`, while the number of locations (crystals) is in `/entry/instrument/detector/detectorSpecific/ntriggers`.

https://github.com/GKLabIPR/MicroED/tree/main/scripts#small-wedge-x-ray-datasets-from-spring-8-beam-lines

**Comment by graeme-winter** [comment]
OK, if I get a few quiet moments today I will have a look at this

I am aware of the small wedge data set use case, it is already supported in `xia2` with `image=foo.h5:1:9000:100` (say) for 90x100 image sets - I imagine (because I am lazy) I will adopt the same syntax

**Comment by graeme-winter** [comment]
OK, this is likely to be a pain to fix

```
Grey-Area tmp :) $ dials.import /Users/graeme/.cache/dials_data/centroid_test_data/centroid_000?.cbf image_range=1,9,3
usage: dials.import [options] /path/to/image/files
dials_import.py: error: Invalid phil parameter: Too many values for geometry.scan.image_range: 3 given, exactly 2 required (command line argument, line 1)
```

It's already into `dxtbx` PHIL parameters 😭

**Comment by graeme-winter** [comment]
```
scan_phil_scope = libtbx.phil.parse(
    """
  scan
    .expert_level = 1
    .short_caption = "Scan overrides"
  {

    image_range = None
      .type = ints(size=2)
      .help = "Override the image range"
      .short_caption = "Image range"

    extrapolate_scan = False
      .type = bool
      .help = "When overriding the image range, extrapolate exposure and epoch information from existing images"
      .short_caption = "Extrapolate scan"

    oscillation = None
      .type = floats(size=2)
      .help = "Override the image oscillation"
      .short_caption = "Oscillation"

    batch_offset = None
      .type = int(value_min=0)
      .help = "Override the batch offset"
      .short_caption = "Batch offset"
  }
"""
)
```

in `dxtbx/src/dxtbx/model/scan.py` =>
- need to make length 2, 3
- need to add logic to "unroll" into scans
- need to allow multiple as alternative, if multiple then unroll

Alternative:
- add `chunks=0,900,300` or whatever as an alias which unrolls the scans inside the logic of `dials.import`

This alternative I am in two minds about: it is both horrible but also maybe saner in the medium game?

**Comment by graeme-winter** [comment]
> +1 for this.
> 
> Small wedge datasets from SPring-8 (e.g. https://xrda.pdbj.org/entry/277/path/cpv1deg/PH1deg-CPS0296-04/data) also benefit from this.
> 
> > Diffraction images from multiple crystal locations are stored in a single set of HDF5 files. The number of frames per location (crystal) is stored in `/entry/instrument/detector/detectorSpecific/nimages`, while the number of locations (crystals) is in `/entry/instrument/detector/detectorSpecific/ntriggers`.
> 
> https://github.com/GKLabIPR/MicroED/tree/main/scripts#small-wedge-x-ray-datasets-from-spring-8-beam-lines

Apropos to these data, which are quite substantial: is there an efficient way to download some of them e.g. with `wget`?

**Comment by biochem-fan** [comment]
1 deg data is smaller and some pins have fewer crystals:
https://data.pdbjpw1.pdbj.org/xrda/277/cpv1deg/PH1deg-CPS0296-16/data/

```
curl -k -O https://data.pdbjpw1.pdbj.org/xrda/277/cpv1deg/PH1deg-CPS0296-16/data/CPS0296-16-multi_data_00000[1-7].h5
curl -k -O https://data.pdbjpw1.pdbj.org/xrda/277/cpv1deg/PH1deg-CPS0296-16/data/CPS0296-16-multi_master.h5
```
Apparently something is wrong with the SSL certificate and we need to add `-k`. I reported this to the server administrator.

I am not the depositor of this dataset and I myself have never processed this one. I will test your patch on my own data from another SPring-8 beamline next Monday.

**Comment by biochem-fan** [comment]
I will comment my test results on https://github.com/dials/dials/pull/2816.
