### ISSUE TITLE
What are strictly necessary files after processing datasets?

### ISSUE THREAD

**Issue by mysecondnameisdanger** [dials/dials#2829]
I am processing datasets at different resolution cutoffs, but my computer has a small disk. What are the strictly necessary files after data processing? I guess the mtz merged and unmerged, the report and the summary file??

**Comment by graeme-winter** [comment]
Probably, yes

Reducing the footprint of intermediate files is on our hit list

**Comment by graeme-winter** [comment]
On a more useful note:

- `scaled.refl` and `scaled.expt` contain all the information from the processing i.e. all integration results, `bbox` etc. for interrogation
- `indexed.refl` and `indexed.expt` contain all the information from spot finding and indexing for e.g. diagnostics of earlier stages

so, data files _not_ in this list don't really contain new unique information unless you want to change the space group... but then you can probably go back and re-index / re-scale the data with ~no loss of fidelity

**Comment by frmupe** [comment]
Thanks

**Comment by dagewa** [comment]
Seems this question is answered
