### ISSUE TITLE
dials.image_viewer 2theta output misleading

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#284]
eg.
```dials.image_viewer /dls/i19-1/data/2017/cm16760-1/fructose_collect/fructose_01_00001.cbf```

which was collected at 2theta = 30°
``` 
$ grep -a DET_2THETA /dls/i19-1/data/2017/cm16760-1/fructose_collect/fructose_01_00001.cbf 
(..)
SCAN1 DET_2THETA 30.0000 0.0 0.0 0.0 0.0 0.0
FRAME1 DET_2THETA 30.0000 0.0
(..)
```

prints:
```
$ dials.image_viewer fructose_01_00001.cbf
The following parameters have been modified:

input {
  datablock = <image files>
}

File: /dls/i19-1/data/2017/cm16760-1/fructose_collect/fructose_01_00001.cbf
Number of pixels: slow=1679 fast=1475
Pixel size: 0.172000 mm
Saturation: 791927
Detector distance: 160.00 mm
Detector 2theta swing: 0.00 deg.
Rotation start: -145.00 deg.
Rotation width: 0.20 deg.
Beam center: x=148.78 mm  y=33.18 mm
Wavelength: 0.688900 Ang.
```

**Comment by rjgildea** [comment]
This is printed somewhere deep by the iotbx detector_base object:
https://github.com/cctbx/cctbx_project/blob/b0460954eac07a3a3639dbe7efd942c21e12ebc1/iotbx/detectors/detectorbase.py#L239

**Comment by rjgildea** [comment]
We can 'fix' this by overriding the show_header method of the image viewer chooser_wrapper object:
https://github.com/cctbx/cctbx_project/blob/b0460954eac07a3a3639dbe7efd942c21e12ebc1/rstbx/slip_viewer/frame.py#L47

Options:
1) Print dxtbx objects (similar to dials.show datablock.json), could be quite verbose
2) Don't print anything here - do we really need any output on the command line for a graphical tool?

Opinions?

**Comment by dagewa** [comment]
I like (2), restricting the scope of image_viewer to viewing images, the information can be obtained anyway via dials.show

**Comment by Anthchirp** [comment]
Sounds good to me. Not showing info is better than showing wrong info.

**Comment by graeme-winter** [comment]
+1 Markus

**Comment by Anthchirp** [comment]
Thank you
