### ISSUE TITLE
dials.check_indexing_symmetry gave a clearly wrong solution

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#287]
Check indexing symmetry gave a result which indicated a higher correlation on P-1 but which was clearly wrong in refinement...

/dls/i04/data/2017/cm16781-1/processing/rotation_calibrationB/DEFAULT/NATIVE/SWEEP1/index/6_dials.check_indexing_symmetry.log 

@rjgildea will add this one to the regression set; we should work out why it went wrong; good spot.

```
Range on h: -29 to 24
Range on k: -30 to 35
Range on l: -106 to 93
Checking HKL origin:

dH dK dL   Nref    CC
 0 -1 -1  23576 0.747
 0  0  0  32922 0.531
```

**Comment by dagewa** [comment]
The behaviour of the correlation coefficients may be improved by calculating them on E^2 not I (or at least some approximation of E^2 given the fairly rough 'integration' done by summing strong pixels). Otherwise you get artificially high correlation everywhere because of the fall off with angle. This may mask the right solution in a marginal case. Correlation of sets of E^2 is what Pointless does.

**Comment by dagewa** [comment]
Of course, this might not be relevant in this case, but it does seem like it should be noted...

**Comment by graeme-winter** [comment]
Almost certainly is relevant have seen this before 

Only issue is scaling rather depends on correct indexing 

Have wondered about a local scaling i.e. divide through by mean of local observations in a sliding window...

**Comment by rjgildea** [comment]
I did experiment a while back with normalisation for CIS/RBS, but results were inconclusive, hence default is not to do it:

https://github.com/dials/dials/blob/master/command_line/check_indexing_symmetry.py#L117

**Comment by rjgildea** [comment]
See also https://github.com/dials/dials/issues/421

**Comment by rjgildea** [comment]
Perhaps dials.check_indexing_symmetry should also perform refinement (a la dials.refine_bravais_settings) as an improvement in rmsds is the ultimate measure of whether or not there is an indexing offset.

**Comment by rjgildea** [comment]
Another example:
xia2 image=/dls/mx-scratch/gw56/i24-vera/data/KpDyP/Data/little/KpDyP_97/KpDyP_97_1_0001.cbf.gz read_all_image_headers=False atom=s integrate_p1=True reintegrate_correct_lattice=False nproc=1

Initial indexing is fine, however after dials.check_indexing_symmetry refinement blows up:
```
Removing 43 unindexed reflections
Range on h: -19 to 8
Range on k: -40 to 26
Range on l: -33 to 28
Checking HKL origin:

dH dK dL   Nref    CC
 0  0  0      0 0.000
 1  0  0     14 0.823

Check symmetry operations on 731 reflections:

               Symop   Nref    CC
               x,y,z    731 1.000 ***
```

**Comment by graeme-winter** [comment]
That would be lovely

This will never happen

Closing with prejudice

Again we could revisit one day
