### ISSUE TITLE
Reciprocal lattice viewer behaving strangely

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#291]
Steps to reproduce:
* ```dials.reciprocal_lattice_viewer /dls/i19-1/data/2017/cm16760-1/processed/fructose120117_collect/4/DEFAULT/scale/80_{e,r}*```
* Click on beam fast text field (showing "32.80")
* Don't change anything. Hit enter.
* What just happened?

Doesn't readily happen on other files, maybe 2theta?

**Comment by Anthchirp** [comment]
underlying data collected at 2theta=30

**Comment by Anthchirp** [comment]
```
Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 573, in OnChangeSettings
    self.parent.update_settings()
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 347, in update_settings
    panel_id, beam_centre = detector.get_ray_intersection(beam.get_s0())
RuntimeError: dxtbx Internal Error: /scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/model/detector.h(757): DXTBX_ASSERT(w_max > 0) failure.
```

**Comment by jmp1985** [comment]
This would imply that the beam centre does not intersect the detector.

James

________________________________

**Comment by dagewa** [comment]
Seems rather probable for a 2theta=30 data collection
