### ISSUE TITLE
DIALS 1.4.3->1.4.4 cherry-picking

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#298]
Of the picked commits I un-picked the following to avoid test breakages. Order is oldest on top.

* [x] @3b8c40d add help for dials.goniometer_calibration; add test
* [x] @c1350a9 dials.export: add option format=json for exporting rlp in json format (for uglymol reciprocal lattice viewer)
* [x] @94ce883 dials.export format=json: support multiple datablock/reflection files
* [x] @d7c7fe6 cleanup
* [x] @52be1e0 fix test
* [ ] @949f934 new option for max cell estimation NN analysis: histogram_binning - choose between linear and logarithmic binning
* [ ] @2dd27e6 add another small molecule indexing test case
* [ ] @f1c2a92 dials.index: change default histogram_binning=log
* [ ] @a8f1630 nearest neighbour analysis: use relative frequency, i.e. bin_count/bin_width to account for varying bin width if histogram_binning==log
* [ ] @16b9b30 refactor indexing code to allow fft1d and fft3d basis vector search to re-used outside of full indexing
* [ ] @120712a fix entering_flags logic in nearest neighbour analysis
* [ ] @860aebc more logic fixes in nearest neighbour analysis
* [ ] @49c041d eliminate nonsensical direct space distances in nearest neighbour analysis

**Comment by Anthchirp** [comment]
picked
@c1350a9
@94ce883 
@d7c7fe6a90c03a9b49bc9be12759ac4eeee0168d
@52be1e003b83f868a6916051a7d8eea46c5d7997
@3727f8526c38dc25ee1d710f94ab2b47dc9888df
@bddd3963d76b21e2ae157356e99d9f0376d850a4
and @wojdyr s 4 commits for the json RLP stuff.

test still failing:
```
Traceback (most recent call last):
  File "/scratch/jenkins_slave/workspace/dials_next_tests/build_dials/modules/dials/test/command_line/tst_export.py", line 190, in <module>
    test.run()
  File "/scratch/jenkins_slave/workspace/dials_next_tests/build_dials/modules/dials/test/command_line/tst_export.py", line 34, in run
    self.test_json()
  File "/scratch/jenkins_slave/workspace/dials_next_tests/build_dials/modules/dials/test/command_line/tst_export.py", line 180, in test_json
    assert d['rlp'][:3] == [-0.5975, -0.6141, 0.4702], d['rlp'][0]
AssertionError: -0.7098
```

**Comment by Anthchirp** [comment]
With correct assert output:
```
$ libtbx.python ~/local/dials/modules/dials/test/command_line/tst_export.py 
OK
OK
OK
OK
Traceback (most recent call last):
  File "/home/wra62962/local/dials/modules/dials/test/command_line/tst_export.py", line 190, in <module>
    test.run()
  File "/home/wra62962/local/dials/modules/dials/test/command_line/tst_export.py", line 34, in run
    self.test_json()
  File "/home/wra62962/local/dials/modules/dials/test/command_line/tst_export.py", line 180, in test_json
    assert d['rlp'][:3] == [-0.5975, -0.6141, 0.4702], d['rlp'][:3]
AssertionError: [-0.7098, 0.2576, 0.3196]
```

**Comment by rjgildea** [comment]
Suspected culprit:
$ svn log -v -r 1575
------------------------------------------------------------------------
r1575 | rjgildea | 2016-12-05 14:31:42 +0000 (Mon, 05 Dec 2016) | 1 line
Changed paths:
   M /trunk/centroid_test_data/integrated.pickle

updated integrated.pickle file
------------------------------------------------------------------------

**Comment by Anthchirp** [comment]
Dials 1.4 runs off dials_regression r1573. Because dials_regression is svn we can't fork it.

Given that 1574 is:
´´´
------------------------------------------------------------------------
r1574 | rjgildea | 2016-11-29 12:29:09 +0000 (Tue, 29 Nov 2016) | 1 line

add files for dials.goniometer_calibration test
------------------------------------------------------------------------
´´´
I will check whether we can move it forward to 1575. Alternatively disable test. ¯\_(ツ)_/¯

**Comment by Anthchirp** [comment]
dials_regression 1575 worked.

**Comment by Anthchirp** [comment]
picked @3b8c40d. Remaining ones cause test failures. Is it ok to leave those for 1.5?

**Comment by wojdyr** [comment]
could you pick also this little commit? 2f093d7ae0a95f1c5bfe93164032e0485bf280a4

**Comment by Anthchirp** [comment]
Picked. Tests are running now, see topmost commit at https://github.com/dials/dials/commits/dials-next

**Comment by wojdyr** [comment]
thanks!

**Comment by Anthchirp** [comment]
1.4.4 done for now. If anything else should go into 1.4 in the future see https://github.com/dials/dials/wiki/How-do-I-get-my-commit-into-the-next-point-release%3F
