### ISSUE TITLE
fonts in dials GUI replaced by [][][] boxes

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#3]
**Running GUI commands result in these or similar errors, all characters (possibly with the exception of button labels) are replaced by boxes ([][][])**

Fontconfig error: Cannot load default config file

(python2.7:11976): Pango-WARNING **: No builtin or dynamically
loaded modules were found. Pango will not work correctly.
This probably means there was an error in the creation of:
  '(..)/base/etc/pango/pango.modules'
You should create this file by running pango-querymodules.

(python2.7:11976): Pango-WARNING **: pango_shape called with bad font, expect ugly output

(python2.7:11976): Pango-WARNING **: pango_font_get_glyph_extents called with null font argument, expect ugly output

(python2.7:11976): Pango-WARNING **: _pango_cairo_font_install called with bad font, expect ugly output

**Comment by Anthchirp** [comment]
This is caused by the use of (unrelocatable) absolute paths in pango and fontconfig and a subsequent move of the dials installation.

Temporary fix:
base/etc

cat >pangorc <<eof
[Pango]
ModulesPath = $(pwd)/../lib/pango/1.6.0/modules/
ModuleFiles = $(pwd)/pango/pango.modules
eof
PANGO_RC_FILE=pangorc ../bin/pango-querymodules > pango/pango.modules

export PANGO_RC_FILE=$(libtbx.show_build_path)/../base/etc/pangorc
export FONTCONFIG_PATH=$(libtbx.show_build_path)/../base/etc/fonts

**Comment by rjgildea** [comment]
More details required. Using module load/nightly and dials.image_viewer I
see:

(image_viewer.py:18168): Pango-WARNING **: error opening config file
'/scratch/jenkins_slave/workspace/dials_bootstrap_platforms/compilationtarget/native/label/dials-ws133/build_dials/base/etc/pango/pangorc':
Permission denied

but don't have any problems with missing characters (i.e. no [] boxes).

Cheers,

Richard

**Comment by luisodls** [comment]
The same happened in my RHEL6 – WS a couple of years ago when the bootstrap didn’t  succeed and some hack were made to finish installing. How was the install process  in the machine showing this strange behaviour?

Luiso.

**Comment by Anthchirp** [comment]
@rjgildea I can reproduce your warning only on ws133, where the file exists but is not readable. On all other machines the file is missing, and silently ignored. I assume that the deployed versions work as they are installed into their new location via the installer, and then not moved afterwards. So the installer script might already address half of the issues.

**Comment by rjgildea** [comment]
So to confirm this isn't an issue with installations using the installer? I remember Nat mentioning that the installer does some magic that makes the fonts work correctly in the GUI code. However I have no idea what that magic is.

**Comment by Anthchirp** [comment]
With cctbx commit 23385 you can partially fix this issue by running 
```bash
make reconf
```

Instead of missing character boxes you now get a font that is too small to read.

**Comment by Anthchirp** [comment]
cctbx commit 23387 should fix the remaining font issue. ws133 pango warning should also be fixed.
