### ISSUE TITLE
Double check flags in dials.stills_process

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#305]
At least the integrated flags aren't being set on the integrated pickle files.  Check the other processing steps to verify they are using sensible flags.

**Comment by dagewa** [comment]
@phyy-nx is this still relevant, or can it be closed?

**Comment by phyy-nx** [comment]
Hi, I checked and here's what I got.  Looking at reflection tables from a dials.stills_process run using this code snippet:

```
for flag in dir(refls.flags):
    if type(getattr(refls.flags, flag)) is type(refls.flags.integrated):
        count = refls.get_flags(getattr(refls.flags, flag)).count(True)
        if count:
            print("% 6d"%count, flag)
```

Flags from the indexed table of a recent xfel experiment:

```
   888 indexed
   888 predicted
   888 strong
   888 used_in_refinement
```

Compare to output from dials.index (from one of the tests):
```
   346 centroid_outlier
  1453 indexed
  5515 strong
  1098 used_in_refinement
```

Delta of -centroid_outlier, +predicted.  I think that's fine, we don't include the outliers in dials.stills_process output, which I suspect is what centroid_outlier is about.

Flags from the integrated table from dials.stills_process of a recent xfel experiment:

```
   132 background_includes_bad_pixels
   875 indexed
  9262 integrated_sum
    92 overloaded
  9262 predicted
   875 reference_spot
   875 strong
   875 used_in_refinement
```

And from cctbx.xfel.mpi_integrate (used in time dependent ensemble refinement aka cctbx.xfel.stripe_experiment) (same image):
```
   124 background_includes_bad_pixels
   681 indexed
  8895 integrated_sum
    91 overloaded
  8895 predicted
   681 reference_spot
   681 strong
   681 used_in_refinement
```

So those match.  Compare to the output of dials.integrate (from one of the tests):

```
  1612 background_includes_bad_pixels
  2221 failed_during_profile_fitting
   406 failed_during_summation
   406 foreground_includes_bad_pixels
   406 includes_bad_pixels
 19454 indexed
 50567 integrated
 50973 integrated_prf
 52788 integrated_sum
 53194 predicted
 19454 reference_spot
 19454 strong
 19454 used_in_refinement
```

Delta of -failed_during_profile_fitting, -failed_during_summation, -foreground_includes_bad_pixels, -includes_bad_pixels, -integrated, -integrated_prf.  Of these I'd only really like to add the integrated flag.  It appears that is set by ./algorithms/scaling/scaling_library.py, which I didn't expect.  I thought it would be set in one of the integrator classes.  @jbeilstenedmands what do you presume the meaning of the integrated flag is and why is it not set by the integrator itself?  Thanks!

**Comment by jbeilstenedmands** [comment]
The integrated flag is a strange one in that it is a composite of integrated_prf and integrated_sum, both of which are only set by the integrator (so I think -integrated and -integrated_prf is probably equal to integrated_sum?). In the scaling code, it is only set when creating the internal dials data structures for reference integrated data, so I think that is allowed 🙂

**Comment by jbeilstenedmands** [comment]
To clarify, for the dials.integrate output, the 50567 reflections with the integrated flag are those that have both integrated_prf and integrated_sum flags set.

**Comment by phyy-nx** [comment]
Oh I get it.  So that wouldn't happen with dials.stils_process output which doesn't use profile fitting.  Ok, then I'm cool closing this.  Thanks for checking that.
