### ISSUE TITLE
CCP4 dependency

### ISSUE THREAD

**Issue by aryabhatt** [dials/dials#307]
I was trying to install DIALS, using the binary installer. It would be helpful if you could list all the dependencies. I had to figure out after a lot of struggle that and existing CCP4 installation is required. It also would be helpful, if DIALS can fail with an appropriate message, in a case of unmet dependency.

**Comment by graeme-winter** [comment]
For info DIALS developers, here dials error message means “please could xia2 failing with no CLIBD” be more helpful / explicit
