### ISSUE TITLE
Saving datasets from more than one detector in datablock.json

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#309]
Is it possible to save datasets from more than one detector in a datablock.json, e.g.:
```
$ dials.import $(libtbx.find_under_build xia2_regression)/test_data/X4_wide/X4_wide_M1S4_2_000*.cbf $(libtbx.find_under_build xia2_regression)/test_data/i04_bag_training/th_8_2_000*.cbf 
DIALS 1.dev.1175-g063db8e
The following parameters have been modified:

input {
  datablock = <image files>
}


Applying input geometry in the following order:
  1. Manual geometry

Sorry: More than 1 datablock found
```

Also see https://github.com/xia2/xia2/issues/104

**Comment by jmp1985** [comment]
I guess this would be possible. However, I suspect other dials programs may also complain.

________________________________

**Comment by graeme-winter** [comment]
There is a gap between dials programs complaining and this being impossible
yes? Alt: if xia2 would generate > 1 datablock file perhaps problem would
"go away"?

**Comment by jmp1985** [comment]
Of course - it's certainly not impossible! And yes, if xia2 wrote out > 1 datablock then this problem would go away. However, I'm guessing you want them in the same datablock so you can do joint indexing or refinement or something?

________________________________

**Comment by rjgildea** [comment]
It's just that xia2 saves a datablock.json with all the imagesets as xia2-datablock.json. If the images are from > 1 format class then the datablocks.append() fails with an error message. From a user point of view, it doesn't seem logical that dials.import is fine with > 1 dataset from a single beamline, but not with datasets from multiple beamlines (or more specifically from multiple format classes, since different beamlines could in practice have the same format class).

**Comment by jmp1985** [comment]
Fixed.
