### ISSUE TITLE
Windows developer installation instructions incorrect

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#312]
The developer installation instructions for Windows are clearly wrong (reference to svn, etc). Please could someone with access to a Windows machine update/fix the instructions?

https://dials.github.io/documentation/installation_developer.html#installing-dials-from-svn-on-windows

**Comment by rjgildea** [comment]
Also the file http://cci.lbl.gov/cctbx_build/results/current/cctbx_bundle_for_installer.tar.gz no longer exists:
```
Not Found

The requested URL /cctbx_build/results/current/cctbx_bundle_for_installer.tar.gz was not found on this server.
```

**Comment by dagewa** [comment]
In theory I have access to a 64 bit Windows 7 machine in the office next door, so I could look at this. In practice the machine seems to be busy doing something obscure at the moment, so it might wait till later in the week.

**Comment by Anthchirp** [comment]
superseded by #547 I presume
