### ISSUE TITLE
Setting gain for integration needs to be looked at

### ISSUE THREAD

**Issue by dagewa** [dials/dials#321]
There seems to be two ways for a Format to express detector gain

1. Set it directly in the Panels of the detector
2. Provide a `get_gain` method

Only the second of these does anything to dials.integrate, as in `imageset.py`, `fmt.get_gain()` is called. If the Format does not provide `get_gain`, then the gain defaults to `None`, rather than querying the Panels.

The use of the gain in `get_corrected_data` may be incorrect. This does:
```
    '''
    Get the corrected data: (raw_data - pedestal) * gain

    '''
```
but the standard definition of the gain is that it is expressed in pixel values per photon. So a detector with a gain of 2 returns images with values that are about twice as high as the number of photons that interacted with the detector. In that case, the get_corrected_data method should be doing `(raw_data - pedestal) / gain` in order to convert back to photons.

**Comment by dagewa** [comment]
Bump to keep this in view. Please note the handling of gain currently appears to be inverted. This completely messes up I/sigI ratios for high gain detectors.

**Comment by jmp1985** [comment]
Hi David,

I'll have a look at this next week.

James
________________________________

**Comment by jmp1985** [comment]
Hi David,

I've set it such that the gain set in the panel object is queried if no gain is set in the Format class. I've also fixed get_corrected_data so that the gain is applied correctly

James

________________________________

**Comment by dagewa** [comment]
Great thanks! I'll see how this affects my challenging data set :)
