### ISSUE TITLE
Please could we have the fast and slow detector directions marked on in the geometry viewer

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#322]
Would help making sure that the coordinate system is correctly understood - also an arrow along the beam indicating s0 direction...

**Comment by rjgildea** [comment]
Fast/slow pixel coordinates for current mouse position displayed at bottom of screen - this should give you all the information you need?
<img width="1018" alt="screen shot 2017-03-16 at 17 17 14" src="https://cloud.githubusercontent.com/assets/2810624/24009303/774e0d0a-0a6c-11e7-8fee-73dbc151c7d1.png">

**Comment by rjgildea** [comment]
Oh, geometry viewer not image viewer...

**Comment by graeme-winter** [comment]
Looking into this now

**Comment by graeme-winter** [comment]
<img width="1528" alt="screen shot 2017-03-19 at 07 42 04" src="https://cloud.githubusercontent.com/assets/1241716/24079080/998b6efa-0c77-11e7-9c30-618b5357799d.png">

**Comment by graeme-winter** [comment]
Done :)
