### ISSUE TITLE
Flux in dxtbx models

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#323]
Please could we include flux (where available from the image headers) in the dxtbx detector model. This information would be required for BEST.

**Comment by graeme-winter** [comment]
Do you mean flux, or a proxy for this i.e. transmission?

**Comment by rjgildea** [comment]
Ideally both flux and transmission...

**Comment by jmp1985** [comment]
Can not get as beam.get_flux() and beam.get_transmission().

Currently only FormatCBFMini* classes set this as I didn't go through all file formats to figure out how to read this.  Defaul values are 0 for flux and 1.0 for transmission.
