### ISSUE TITLE
Reading Eiger detectors: incorrect mapping from NeXus to imgCIF coordinate frame suspected

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#324]
Also, have had reports of inverted anomalous differences, likely caused by an odd number of inversions .

Geometry viewer confirms that this is a problem

![pilatus](https://cloud.githubusercontent.com/assets/1241716/24138986/36443470-0e12-11e7-94cd-921b55038b01.png)

is pilatus

![eiger](https://cloud.githubusercontent.com/assets/1241716/24138999/409a77b8-0e12-11e7-94b9-dce380f176d8.png)

is eiger

have confirmed with DECTRIS that the readout to file order is the same for both instruments

**Comment by biochem-fan** [comment]
> The NeXus definition of +z is opposite to that in the IUCr International Tables for Crystallography, volume G, and consequently, +x is also reversed.
http://download.nexusformat.org/sphinx/design.html#nexus-coordinate-systems

imgCIF coordinate system is described in:
http://www.iucr.org/__data/iucr/cifdic_html/2/cif_img.dic/Caxis.html

**Comment by graeme-winter** [comment]
Yes, this should be fine - however I am worried that the direction of the detector normal is opposite for one compared with the other - since this is in real space it is independent of coordinate frame

So, I think we are missing something somewhere, I will investigate today

**Comment by graeme-winter** [comment]
I have been looking in to this and am somewhat confused. I think there are some assumptions in the definitions of the beam and goniometer (which are hard coded in the *imgCIF* convention) which are causing some real confusions.

**Comment by graeme-winter** [comment]
Several of us now looking at this, I have to confess that there is a certain quantity of head scratching taking place. A photograph of the beamline could be deeply helpful here.

**Comment by jmp1985** [comment]
cctbx branch dials-324-inverted-world is "a fix" for this. It inverts beam vector, detector origin, fast axis and slow axis

**Comment by jmp1985** [comment]
This was fixed - so now closing
