### ISSUE TITLE
Move scratch/ and doc/developer/ to a separate repository

### ISSUE THREAD

**Issue by dagewa** [dials/dials#33]
Developer notes and other things not required for release should not be kept in the main DIALS repository. The two directories in the title should be moved completely. In other areas there may be files that could also be moved.

**Comment by Anthchirp** [comment]
We could move this into a separate github repository named eg. dials/*scratch*. I could do it so that the history is preserved.

**Comment by nksauter** [comment]
Can I remind everyone simply that it was Herbert Bernstein's request in
July 2012 that DIALS contain an area (now the scratch) area where people
could deposit code still in a developmental form, to make more approachable
than cctbx.  Not sure why we would want to change things now.

Nick

Nicholas K. Sauter, Ph. D.
Computer Staff Scientist, Molecular Biophysics and Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Nick

Sure - We can keep a scratch area in the DIALS repo - should this be in the release though? I would think not. Therefore putting it *next* to the DIALS trunk in the DIALS repo would hit the spot exactly - the aim of this ticket.

Or do you think scratch code, notes and doodles should go out with the release? That’s what is under discussion.

Cheers Graeme

**Comment by nksauter** [comment]
Graeme,

I'm delegating this issue to Tara Michels-Clark.  She is about to embark on
committing a collection of experimental code (two-color indexing) to the
scratch area, and we need to have something that is workable to her.

Nick

Nicholas K. Sauter, Ph. D.
Computer Staff Scientist, Molecular Biophysics and Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Nick

Sure thing. Tara are you also seeing this ticket? Understand you need to get stuff done. 

Thanks Graeme

**Comment by tmmclark** [comment]
Hi Graeme,

I see the email thread but not the ticket.

Tara

**Comment by tmmclark** [comment]
Hello Graeme,

I am writing to get some clarification. Does this mean that there would
exist a separate dials repository that contains the DIALS package, i.e.
__init__.py and scons etc and that the scratch would exist separately but
maintain its dependencies on the DIALS sources, just not be included in the
release bundle? I want to make sure that I could still commit to it and
that it would have access to the dials base packages that I am using like
the integrator and real space grid search etc.

Thank you,
Tara




On Tue, Jan 12, 2016 at 12:37 PM, Tara Michels-Clark <tmichels-clark@lbl.gov
> wrote:

> Hi Graeme,
>
> I see the email thread but not the ticket.
>
> Tara
>
> On Tue, Jan 12, 2016 at 12:33 PM, Graeme Winter <notifications@github.com>
> wrote:
>
>> Nick
>>
>> Sure thing. Tara are you also seeing this ticket? Understand you need to
>> get stuff done.
>>
>> Thanks Graeme
>>

**Comment by graeme-winter** [comment]
Hi Tara

Exactly this. You would be just fine.

Best wishes Graeme

**Comment by tmmclark** [comment]
Hi Graeme,

Do you mind describing this so that we understand it at the same level as
if we were to do the work here at LBL? We just want to be clear on exactly
where things are going to end up.

Thank you,
Tara

**Comment by graeme-winter** [comment]
Hi Tara

Sorry, just moved house and have *no* net connection at new dwelling, so
was pecking out on phone (#1980's)

OK, so essentially the thought process runs like this - we have

  Fetch URL: git@github.com:dials/dials.git

right now for everything - what we are talking about is using the main
dials for stuff we would want to see in a release and then making beside
this

  Fetch URL: git@github.com:dials/dials-scratch.git

say which would have all of the stuff we want to share, want to work on,
and want in revision control, but not to send to world+dog in a ccp4 or
phenix release. This means we can put bigger stuff into the scratch area
and misc junk which a developer would find interesting but not a user.

Kind of a goal would be that at any time phenix or ccp4 or whoever could
pull from the dials master for a release and we would be happy with that.

I think what we should do here at Dials East is to fix this up so there is
a scratch area with everything in, then send out a small note on how to
pull that next to your dials and get back to everything working nicely - I
think that should be pretty straightforward.

Cheerio Graeme

@All re: git: I confess here and now I know like a total of four git
commands, no more. I seem to get by :o) that said I have colleagues here
who can do the git power user stuff like moving things around and
preserving the history.

**Comment by Anthchirp** [comment]
Dear Tara,

I have now moved /scratch and /doc/developer into a new dials_scratch repository, preserving the file history.
What you need to do, is go into your modules directory, so one level up from the dials directory, and there run

   git clone git@github.com:dials/dials_scratch.git
   libtbx.configure dials_scratch

Any questions, let me know.

Best wishes,
-Markus

**Comment by nksauter** [comment]
Graeme,

Nevertheless, I feel that what Markus has gone ahead and made a fundamental
change before we were all in agreement on this side.

Nick

Nicholas K. Sauter, Ph. D.
Computer Staff Scientist, Molecular Biophysics and Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by tmmclark** [comment]
Dear Markus,

Does this mean that a separate commit has to be made to a separate
repository "dials_scratch"? This is what Nick and I were hoping to avoid.

Tara

**Comment by graeme-winter** [comment]
Dear Tara

Are you near a telephone? I think a quick conversation would be helpful
right now

Thank you Graeme

**Comment by tmmclark** [comment]
Hi Graeme,

Sure, do you have a toll free number to call? I only have my cell.

Tara

**Comment by graeme-winter** [comment]
HI Tara

I can can call your cell # - am at the office (someone else's bill)

Thanks Graeme

**Comment by tmmclark** [comment]
Hi Graeme,

My cell is 931-360-0799

Tara
