### ISSUE TITLE
dials.integrate scan_range

### ISSUE THREAD

**Issue by dagewa** [dials/dials#330]
`dials.integrate` interprets the `scan_range` parameter as an array range not an image range. That seems a surprise because

```
dials.integrate refined.pickle refined_experiments.json scan_range=1,30
```

does not 'do the obvious thing', which would be integrate images 1 to 30. Some other commands, like `dials.slice_sweep`, appear to treat `scan_range` as an image range.

**Comment by dagewa** [comment]
I appreciate that this is a convention, and indeed `dials.index` seems to follow the same convention, so perhaps `dials.slice_sweep` is the outlier. But it is not even clear from the help what `scan_range` is going to do

```
scan_range = None
  .help = "Explicitly specify the images to be processed. Only applicable when"
          "experiment list contains a single imageset."
```
Perhaps we need an `image_range` parameter as well, which would be clearer in what it is going to do, and more likely match the user expectation of calling the first image number 1?

**Comment by jmp1985** [comment]
scan_range should set the images to be processed in integration.

I would guess that this starts from zero. One of the items for the dxtbx refactor was to possibly get rid of the array range property in the scan and just use image_range every where.


________________________________

**Comment by dagewa** [comment]
It seems that `dials.slice_sweep` breaks the convention then. I'm not sure about other programs with a `scan_range` parameter.

I'm in favour of using image range everywhere. Internally, refinement always uses the `get_array_range` method, but as long as the result of all calls to `get_image_range` are modified to produce the previous array range values then there should be no problem.

**Comment by rjgildea** [comment]
How about having "modifier" parameters as part of the option parser that would modify in place the datablock/experiments/reflections that were passed as input? E.g. selecting a scan_range/image_range, d_min, subset of reflections, etc.
