### ISSUE TITLE
dials.generate_masks ice_rings width should be in d*2

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#332]
In `dials.generate_masks ` the ice rings width is specified in units of d-spacing. This means that the masked regions start out narrow at low resolution and get progressively wider towards high resolution. Perhaps specifying width in terms of d_star_sq would be more appropriate?

```
ice_rings {
  filter = False
  unit_cell = 4.498,4.498,7.338,90,90,120
    .help = "The unit cell to generate d_spacings for powder rings."
  space_group = 194
    .help = "The space group used to generate d_spacings for powder rings."
  width = 0.06
    .help = "The width of an ice ring (in d-spacing)."
  d_min = None
    .help = "The high resolution limit (otherwise use detector d_min)"
}
```
![ice_rings_mask](https://cloud.githubusercontent.com/assets/2810624/24659654/3eb11720-1945-11e7-9d27-72bbae4b6379.png)

**Comment by jmp1985** [comment]
I've changed this to width in 1/d**2. However, you still get way more rings than you ever see in a real image.
