### ISSUE TITLE
In dials.integrate, can we record a histogram of the mean transformed reflection profile

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#351]
So we can see if the shoebox is "sensible"

I would guess output similar to the XDS reflection shoebox output would hit the spot... 

Can then use this to generate a pea-in-a-box visualisation in dials.report.

**Comment by dagewa** [comment]
+1 we are lacking tools to visualise reflection profiles, and their fit to reflections other than a basic CC. `dials.reflection_viewer` does not seem to fit the gap. In Oulu we had a case where we suspected overlaps were affecting integration (down a 6-fold screw axis "absent" reflections neighbouring allowed reflections had significant intensity) but we had no means to easily investigate this from DIALS output

**Comment by luisodls** [comment]
I think we can reuse some low level code from dials.reflection_viewer to build a new visualization tool, the same way I am reusing the bitmap generator for my image viewer in DUI, if you need some help connecting or reusing my old code just let me know.

 Luiso.
________________________________

**Comment by jmp1985** [comment]
The debug log contains some of this output. I think you can also set debug.reference.output=True to get a pickle file which you could read into the GUI.

James

________________________________

**Comment by graeme-winter** [comment]
grep -A132 "Profile [0-9]" dials.integrate.debug.log

**Comment by graeme-winter** [comment]
OK, got reference_profiles.pickle; now working out what to go do with it...

**Comment by graeme-winter** [comment]
You do this:

```
> dev.xia2.check_mosaic reference_profiles.pickle 
  1   7  23  51  84 100  84  51  22   6   1 
```

**Comment by graeme-winter** [comment]
@dagewa I think this does not meet your needs, since you want to inspect specific reflections (i.e. look at the profiles for axial reflections) 

Will have a think about a tool for this, may be a hobby project for next week...

**Comment by dagewa** [comment]
Can this be closed?

**Comment by dagewa** [comment]
Assuming this can indeed be closed.
