### ISSUE TITLE
dials.discover_better_experimental_model got it deeply wrong

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#353]
Should have given something like 

```
Selecting subset of 10000 reflections for analysis
Running DPS using 10000 reflections
Found 2 solutions with max unit cell 47.91 Angstroms.
Old beam centre: 212.48, 220.00 mm (1235.3, 1279.1 px)
New beam centre: 212.67, 219.90 mm (1236.5, 1278.5 px)
Shift: -0.19, 0.10 mm (-1.1, 0.6 px)
```

gave

```
Selecting subset of 10000 reflections for analysis
Running DPS using 10000 reflections
Found 1 solutions with max unit cell 47.86 Angstroms.
Old beam centre: 212.48, 220.00 mm (1235.3, 1279.1 px)
New beam centre: 215.98, 220.17 mm (1255.7, 1280.0 px)
Shift: -3.50, -0.17 mm (-20.3, -1.0 px)
```

RLV kinda crazy looking as a result of this... and indexing totally failed :(

**Comment by rjgildea** [comment]
`Found 2 solutions with max unit cell 47.91 Angstroms.`
or
`Found 1 solutions with max unit cell 47.86 Angstroms.`
Doesn't look like fft1d could identify many basis vectors either way...

**Comment by graeme-winter** [comment]
files in /dls/mx-scratch/dials/issues/353

**Comment by graeme-winter** [comment]
Setting max cell to bigger number helped...

**Comment by rjgildea** [comment]
Also now grammatically correct...

**Comment by graeme-winter** [comment]
This helps - since it now bombs out xia2 works fine, because the input was effectively correct anyway :)

**Comment by graeme-winter** [comment]
Would be very interesting to know *why* DPS does not work though... data pretty reasonable, should work fine.

**Comment by dagewa** [comment]
I think this can be closed
