### ISSUE TITLE
Review export MTZ, including address all FIXME

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#355]
As it says on the tin.

TODO verify that the UB matrix; HKL etc are identical to MOSFLM output

**Comment by graeme-winter** [comment]
Specific worries:

- legend "FIXME" occurs several times in an innocuous piece of code which is on the _critical path_ for processing
- around line 515 a lot of important stuff (i.e. assignment of M/ISYM values) is delegated to 

```
  m.replace_original_index_miller_indices(cb_op_to_ref.apply(
    integrated_data['miller_index']))
```

- Issues relating to the experimental geometry could be "a thing" e.g.

```
    # FIXME hard-coded assumption on indealized beam vector below... this may be
    # broken when we come to process data from a non-imgCIF frame
```

and

```
   # apply the fixed rotation to this to unify matrix definitions - F * U
    # was what was used in the actual prediction: U appears to be stored
    # as the transpose?! At least is for Mosflm...
    #
    # FIXME Do we need to apply the setting rotation here somehow? i.e. we have
    # the U.B. matrix assuming that the axis is equal to S * axis_datum but
    # here we are just giving the effective axis so at scan angle 0 this will
    # not be correct... FIXME 2 not even sure we can express the stack of
    # matrices S * R * F * U * B in MTZ format?...
    _U = dials_u_to_mosflm(F * _U, _unit_cell)
```

probably enough to be going on with

**Comment by graeme-winter** [comment]
While looking at stuff like this, consider why we have no reflections usually centred on image[0] but do have lots on image[n]...

**Comment by graeme-winter** [comment]
UB matrix questions - MOSFLM says (for monoclinic small molecule)

```
 Crystal Parameters
 ===================
 Crystal identifier (used as template for image file names (IDENT): NIDPPE_8_8_1
 Space group (SYMMETRY)    3 (P2)
 Real cell parameters (CELL):
     11.168    13.109    31.147    90.000    99.546    90.000
 Reciprocal cell parameters :
   0.053605  0.045037  0.019221     90.00     80.45     90.00

 Mosaic spread (MOSAIC) 0.050 degrees
 Mosaic block size (BLOCKSIZE) 100.00 microns
 Rotation matrix U defining standard setting :
              0.89742  0.43121 -0.09319
             -0.41948  0.76863 -0.48296
             -0.13663  0.47251  0.87067

 Orientation Matrix [A], Components of A*,B*,C*
    Along X   0.048107  0.019420  0.001094
    Along Y  -0.022486  0.034616 -0.010492
    Along Z  -0.007324  0.021280  0.016068
           Misorientation Angles
         0.000    0.000    0.000
```

for *same data* XDS _via_ POINTLESS says:

```
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 

 Orientation data for batch       1     area detector data  

   Crystal number ...................       1
   Associated dataset ID ............       1
   Cell dimensions ..................   11.34   13.30   15.80   90.00   98.83   90.00
   Cell fix flags ...................      -1      -1      -1       0      -1       0 
   Orientation matrix U .............   -0.8980    0.4311    0.0883 
       (including setting angles)        0.4183    0.7739    0.4755 
                                         0.1367    0.4640   -0.8752 
   Reciprocal axis nearest PHI..   c*
   Mosaicity ........................  0.088 
   Datum goniostat angles (degrees)..    0.000
   Scan axis ........................  PHI 
   Start & stop Phi angles (degrees).    0.000    0.200 
   Range of Phi angles (degrees).....    0.200 
   Start & stop time (minutes).......     0.00     0.00 
    Crystal goniostat information :-  
      Number of goniostat axes..........       1 
      Goniostat vectors..... PHI ....    0.0000    0.0000    1.0000 
                       .....  ....    0.0000    0.0000    0.0000 
                       .....  ....    0.0000    0.0000    0.0000 
    Beam information :- 
      Idealized X-ray beam vector.......    -1.0000    0.0000    0.0000 
      X-ray beam vector with tilts......   -0.9999    0.0000   -0.0128 
      Wavelength and dispersion ........   0.59038   0.00000 
 Detector information :-
   Number of detectors...............      1 
      Crystal to Detector distance (mm).  177.172
   Detector swing angle..............    0.000
   Pixel limits on detector..........    1.0 2463.0    1.0 2527.0
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

DIALS via pointless says

```
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 

 Orientation data for batch       2     area detector data  

   Crystal number ...................       1
   Associated dataset ID ............       1
   Cell dimensions ..................   11.35   13.31   15.82   90.00   98.82   90.00
   Cell fix flags ...................      -1      -1      -1      -1      -1      -1 
   Orientation matrix U .............   -0.1354    0.4647    0.8751 
       (including setting angles)       -0.4171    0.7744   -0.4758 
                                        -0.8987   -0.4294    0.0890 
   Reciprocal axis nearest AXIS..   none
   Mosaicity ........................  0.000 
   Datum goniostat angles (degrees)..    0.000
   Scan axis ........................  AXIS 
   Start & stop Phi angles (degrees).    0.000    0.200 
   Range of Phi angles (degrees).....    0.200 
   Start & stop time (minutes).......     0.00     0.00 
    Crystal goniostat information :-  
      Number of goniostat axes..........       1 
      Goniostat vectors..... AXIS ....    1.0000    0.0000    0.0000 
                       .....  ....    0.0000    0.0000    0.0000 
                       .....  ....    0.0000    0.0000    0.0000 
    Beam information :- 
      Idealized X-ray beam vector.......     0.0000    0.0000   -1.0000 
      X-ray beam vector with tilts......    0.0231    0.0000   -1.6937 
      Wavelength and dispersion ........   0.59038   0.00000 
 Detector information :-
   Number of detectors...............      1 
      Crystal to Detector distance (mm).  178.049
   Detector swing angle..............    0.000
   Pixel limits on detector..........    0.0 2463.0    0.0 2527.0
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

i.e. this is _completely different_

**Comment by graeme-winter** [comment]
BATCH header from MOSFLM

```
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 

 Orientation data for batch       1     oscillation data  

   Crystal number ...................       0
   Associated dataset ID ............       1
   Cell dimensions ..................   11.04   13.11   15.61   90.00   98.75   90.00
   Cell fix flags ...................      -1      -1      -1       0      -1       0 
   Standard orientation matrix U ....    0.8956    0.4382   -0.0763 
                                        -0.4175    0.7691   -0.4839 
                                        -0.1533    0.4653    0.8718 
   Missetting angles PhiX PhiY PhiZ..   0.00   0.00   0.00
   Reciprocal axis nearest ..   c*
   Mosaicity ........................  0.100 
   Datum goniostat angles (degrees)..    0.000
   Scan axis ........................   
   Start & stop Phi angles (degrees).    0.000    0.200 
   Range of Phi angles (degrees).....    0.000 
   Start & stop time (minutes).......     0.00     0.00 
    Crystal goniostat information :-  
      Number of goniostat axes..........       1 
      Goniostat vectors.....  ....    0.0000    0.0000    1.0000 
                       .....  ....    0.0000    0.0000    0.0000 
                       .....  ....    0.0000    0.0000    0.0000 
    Beam information :- 
      Idealized X-ray beam vector.......    -1.0000    0.0000    0.0000 
      X-ray beam vector with tilts......   -1.0000    0.0000    0.0000 
      Wavelength and dispersion ........   0.59038   0.00020   0.00000 
      Divergence .......................   0.020   0.020 
 Detector information :-
   Number of detectors...............      1 
      Crystal to Detector distance (mm).  174.960
   Detector swing angle..............    0.000
   Pixel limits on detector..........    0.0 2527.0    0.0 2463.0
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

So this is the same as XDS modulo rotation of 180 degrees about Y (I think)

**Comment by graeme-winter** [comment]
Hmm - pixel limits on detector - dials export agrees with XDS via POINTLESS and not with MOSFLM *happy days* - that one may be worth reporting to PRE

**Comment by graeme-winter** [comment]
#info beam in mosflm headers has length 1; in dials has length 1/l

**Comment by graeme-winter** [comment]
Re: BATCH header for MOSFLM above; looks like beam direction is opposite to what is claimed in MOSFLM documentation at http://www.mrc-lmb.cam.ac.uk/harry/mosflm/mosflm_user_guide.html#a3 i.e. 

```
                                                   /!
                      Y-axis                      / !
                        ^                        /  !
                        !                       /   !
                        !                      /    !
                        !   /                 /  Xd !
                        !  /                 / * ^  !
                        ! /                  ! 3 !  !
                        !/      X-ray beam   !   !  !
                        /-----------------------/--!---->X-axis
                       /                     !  / *1!
                    <-/-                     ! /    !
                     /  \+ve phi             ! Yd  /
                    /   /                    ! 2  /
                   /                         ! * /
                  Z-axis                  Ys ^ _/ 
                Rotation                     ! /| Xs
                 axis                        !/
                                             O                          
                             Figure. 3

```

????

**Comment by graeme-winter** [comment]
We use ISYM derived from:

```
        cctbx::sgtbx::rt_mx s = sg(0, 0, i_smx);
        hr_ = h * s.r();
        if (asu.is_inside(hr_)) {
          //ht_ = cctbx::sgtbx::ht_mod_1(h, s.t());
          isym = (i_smx + 1) * 2 - 1;
          break;
        }
        else if (asu.is_inside(-hr_)) {
          hr_ = -hr_;
          //ht_ = cctbx::sgtbx::ht_mod_1(h, s.t());
          isym = (i_smx + 1) * 2;
          break;
```

in iotbx/mtz/object.cpp; i.e. we post-multiply the symmetry operation and see if we are inside.

**Comment by graeme-winter** [comment]
Funny thing: take data through this route

```
find spots -> index -> refine bravais settings -> refine (scan vary) -> integrate -> export -> pointless
```

or 

```
find spots -> index in P1 with correct unit cell -> refine (scan vary) -> integrate -> export -> pointless
```

get different M/ISYM column for same reflection - route B

```
  -16   0   1    2   644     -0.77      1.32     -0.13      0.59
                              1.00   1355.93   2423.26    128.28
                              0.76
```

vs. route A

```
  -16   0   1    1   644     -0.71      1.27     -0.13      0.59
                              1.00   1355.73   2424.65    128.28
                              0.76

```

This is _the same reflection_

**Comment by graeme-winter** [comment]
Ah OK, the U matrix was somehow rotated by 180 degrees - this is therefore fine. 

```
   Orientation matrix U .............   -0.1252    0.0950   -0.9876 
       (including setting angles)       -0.8907   -0.4492    0.0697 
                                        -0.4370    0.8884    0.1408 
```

vs. 

```
   Orientation matrix U .............    0.1256    0.0952    0.9875 
       (including setting angles)        0.8908   -0.4489   -0.0701 
                                         0.4366    0.8885   -0.1412 
```

**Comment by nksauter** [comment]
I imagine the space group is different in cases A vs. B
Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
No they are the same, but in case A assigned in DIALS case B assigned in POINTLESS though the reindex operation was h,k,l (i.e. no reindex) however the initial matrix was rotated - still correct just different.

**Comment by graeme-winter** [comment]
Subsequent investigation showed ISYM defined consistently for 222; can move on to rest of FIXMEs i.e. DIALS in P1 => POINTLESS gave same result as DIALS in P222 => POINTLESS

**Comment by graeme-winter** [comment]
Other FIXME's (in addition to one in #358)

```
  # FIXME in here work on including partial reflections => at this stage best
  # to split off the partial refections into a different selection & handle
  # gracefully... better to work on a short list as will need to "pop" them &
  # find matching parts to combine.
```

```
  # FIXME TODO for more than one experiment into an MTZ file:
  #
  # - add an epoch (or recover an epoch) from the scan and add this as an extra
  #   column to the MTZ file for scaling, so we know that the two lattices were
  #   integrated at the same time
  # - decide a sensible BATCH increment to apply to the BATCH value between
  #   experiments and add this
  #
  # At the moment this is probably enough to be working on.
```

```
    # FIXME hard-coded assumption on indealized beam vector below... this may be
    # broken when we come to process data from a non-imgCIF frame
    o.set_so(flex.float(s0n)).set_source(flex.float((0, 0, -1)))
```

**Comment by dagewa** [comment]
The full information about what parameters were refined is written into `dials.refine.debug.log`, but that does not help here. However, for a static crystal model this can be inferred if the cell parameter e.s.d.s have been set.

```
>>> from dxtbx.model.experiment_list import ExperimentListFactory
>>> el=ExperimentListFactory.from_json_file('refined_experiments.json')
>>> xl=el[0].crystal
>>> xl.get_unit_cell().parameters()
(57.783489636995306, 57.81049645104299, 150.03269219046038, 89.9896263613754, 90.01071090515569, 89.98950547676341)
>>> xl.get_cell_parameter_sd()
(4.840810053187664e-08, 0.00016924115573914317, 0.00028791773435587505, 0.00014977980717745422, 0.00018758396180192135, 0.0001723908125541873)
```
Parameters with e.s.d.s close to zero (i.e. here _a_) will not have been modified by refinement. This is not exactly zero, because the real space cell parameters are not immediately parameters in refinement, instead the metrical matrix elements are parameters and there is some funky maths to derive the errors in real space cell parameters. I guess this is subject to some rounding error.

The cell parameter e.s.d.s might not get set by refinement though. This won't happen for example if the sparse LevMar engine is used, or the LBFGS based engines. In that case, this method won't work.

If you have done scan-varying refinement, this may not be what you want either. It will report the cell error on the last static refinement, but you might have fixed different parameters during scan-varying refinement. In that case you might be better off looking for parameters that do not change significantly over the whole scan instead. There is some numerical error in this too. Here `crystal.unit_cell.fix_list=Crystal1g_param_0` was set to fix the first cell parameter, but there is some variation anyway due to limitations in how the Gaussian smoother can represent a straight line:

```
>>> cells=[xl.get_unit_cell_at_scan_point(i).parameters() for i in range(xl.num_scan_points)]
>>> (a, b, c, aa, bb, cc) = zip(*cells)
>>> max(a) - min(a)
1.322094142608421e-06
>>> max(b) - min(b)
0.030880807888308937
>>> max(c) - min(c)
0.013786175717314109
>>> max(aa) - min(aa)
0.006824744223521861
>>> max(bb) - min(bb)
0.005801905892681702
>>> max(cc) - min(cc)
0.010096290069753877
```

**Comment by ndevenish** [comment]
Did this:
> TODO verify that the UB matrix; HKL etc are identical to MOSFLM output
Ever get resolved or even attempted?

If not I'd be tempted to split out any remaining FIXMEs into separate tickets rather than carrying this ticket forward forever (it's the last remaining ticket for dials... 1.6, and I'm wondering whether to shift it forwards to 1.8)

**Comment by graeme-winter** [comment]
@ndevenish no I don't think so

Please do feel free to split out remaining tasks

**Comment by graeme-winter** [comment]
First step for this I think is setting up clean phil parameters for export MTZ (only) and passing these through to thin down the function call. Should also define base Exporter class to reduce boiler plate.

**Comment by dagewa** [comment]
I came across this looking at inconsistencies in geometry when importing MTZs from DIALS vs those from XDS (both from xia2 runs) https://github.com/dials/dials/tree/import_mtz. Seems there is still much to do.

Information [here](http://www.sb.fsu.edu/~xray/Manuals/CCP4/mtzlib.html#orientation) is useful. Interesting that there is (unused?) padding that could be set to store some of the currently missing geometry information, like pixel size.

**Comment by dagewa** [comment]
> Re: BATCH header for MOSFLM above; looks like beam direction is opposite to what is claimed in MOSFLM documentation at http://www.mrc-lmb.cam.ac.uk/harry/mosflm/mosflm_user_guide.html#a3 i.e.
> 
> ```
>                                                    /!
>                       Y-axis                      / !
>                         ^                        /  !
>                         !                       /   !
>                         !                      /    !
>                         !   /                 /  Xd !
>                         !  /                 / * ^  !
>                         ! /                  ! 3 !  !
>                         !/      X-ray beam   !   !  !
>                         /-----------------------/--!---->X-axis
>                        /                     !  / *1!
>                     <-/-                     ! /    !
>                      /  \+ve phi             ! Yd  /
>                     /   /                    ! 2  /
>                    /                         ! * /
>                   Z-axis                  Ys ^ _/ 
>                 Rotation                     ! /| Xs
>                  axis                        !/
>                                              O                          
>                              Figure. 3
> ```
> 
> ????

Specifically answering this question, the beam vector is stored as
```
R    SOURCE(3)    Idealized (ie excluding tilts) source vector 
                   (antiparallel to beam), in Cambridge 
                   laboratory frame 
R    S0(3)        Source vector (antiparallel ! to beam), in 
                   Cambridge laboratory frame, including tilts
```
that is, MTZ stores the sample-to-source vector, not the wavevector direction.

**Comment by dagewa** [comment]
My general feeling here is that for the least surprise for downstream applications, the DIALS experimental geometry should always be rotated to the Cambridge frame on MTZ export. That is, +Z along the omega axis, beam in the X-Z plane with s0 close to +X.

Always rotating for export means we would be treating DIALS as a general, coordinate frame agnostic program, which it is (or is intended to be) and MTZ as a coordinate-frame specific format, which for practical purposes, it is. This would allow us to address this specific here-be-dragons warning

>     # FIXME hard-coded assumption on indealized beam vector below... this may be
>     # broken when we come to process data from a non-imgCIF frame

**Comment by dagewa** [comment]
We are currently down to three `FIXME`s in `export_mtz.py`:

https://github.com/dials/dials/blob/5b33026b9688ff83d08963dc2fbb0bba39781ac7/src/dials/util/export_mtz.py#L270-L271

https://github.com/dials/dials/blob/5b33026b9688ff83d08963dc2fbb0bba39781ac7/src/dials/util/export_mtz.py#L335

https://github.com/dials/dials/blob/5b33026b9688ff83d08963dc2fbb0bba39781ac7/src/dials/util/export_mtz.py#L584-L590

Only the first of these mentions this issue, referring to this comment: https://github.com/dials/dials/issues/355#issuecomment-305509522. 

It is worth noting that Gemmi's `xds2mtz` does not bother to set this at all, because "it's probably not used by any program anyway."

https://github.com/project-gemmi/gemmi/blob/cf11d41d5308928e608e92fbc3c4a4cd0158c839/prog/xds2mtz.cpp#L196-L198

I think this issue can be closed as the most pressing issues appear to have been dealt with.
