### ISSUE TITLE
If all reflections failed in profile fitting dials.export happily exports mtz file containing zero reflections

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#357]
This is probably not the correct behaviour - it should probably raise an error if there are no reflections to export?
```
$ module load dials/latest
$ dials.export  experiments=/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/002/DEFAULT/NATIVE/SWEEP1/integrate/13_integrated_experiments.json reflections=/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/002/DEFAULT/NATIVE/SWEEP1/integrate/13_integrated.pickle
Read 4609 predicted reflections
Selected 0 integrated reflections
Removing 0 reflections with I/Sig(I) < -5.0
Removing 0 profile reflections with I/Sig(I) < -5.0
...
```

**Comment by graeme-winter** [comment]
So if no reflections integrated by profile fitting will raise Sorry and suggest use profile is False.

**Comment by graeme-winter** [comment]
@rjgildea says

2 likely cases:
- ignore_profile_fitting = False, no profile-fitted intensities -> suggest to user to set ignore_profile_fitting=True
- ignore_profile_fitting = True, no integrated intensities -> this is much worse, tell user such

wilco
