### ISSUE TITLE
Integrate / profile modelling for structured reflections

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#361]
Related to #360 - cope with stuff like

<img width="990" alt="screen_shot_2017-06-05_at_07 01 01" src="https://cloud.githubusercontent.com/assets/1241716/26775288/2543968e-49cc-11e7-9c54-d1c88296b69e.png">

In integration / profile modelling. This is probably research.

**Comment by dagewa** [comment]
Worth revisiting ↑ data with #752's changes

**Comment by graeme-winter** [comment]
@dagewa I think @benjaminhwilliams did take a look but you are right we should revisit this - I think it will work much better with the new spot finding.
