### ISSUE TITLE
Add ML mosaicity to crystal model and bandpass/spectrum to beam model

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#364]
For still spot prediction, we representing the crystal mosaic parameters (domain size and domain mosaic angle spread based on Colin Nave's work) as the parameters ML_domain_size_ang and ML_half_mosaicity_deg (ML stands for maximum likelihood).  These parameters are computed in indexing/nave_parameters.py as described in Sauter 2014 and are used by the NaveStillsReflectionPredictor.  However, they are not part of the C++ crystal model.  Instead, we save them as python members on the boost python C++ crystal object like this:

  crystal._ML_domain_size_ang = ML_domain_size_ang

Then, when the crystal model's to_dict or from_dict methods are called, we serialize/deserialize these properties to json explicitly.

There are several issues here:
- These parameters should be parameters of the C++ object so they can be added to the copy constructor.
- The dxtbx Crystal object has a get/set mosaicity function pair.  Near as I can tell, nowhere in dials or cctbx is this actually used to do any work, but there is a lot of boilerplate to carry it around.
- Crystal.change_basis() creates a new Crystal model, but doesn't copy either the ML mosaic parameters or the Crystal's mosaic parameter.  Likewise, anywhere else that creates a crystal model without using the copy constructor has the same problem.

There are a couple options here.  One is to derive a new class, NaveCrystal or MosaicCrystal and add the ML properties.  Another is to add the ML properties to crystal model directly.  A third is to rename get/set mosaicity to get/set half_mosaic_angle_deg and add a get/set mosaic_domain_ang.  Personally, I prefer that third option, since no one is using get/set mosaicity anyway.

While we're at it, I also need to add bandpass to the beam model.  The proposal is to add get/set methods to support either a gaussian bandpass or a full spectrum that has been binned:

- bandpass_fwhm: bandpass full width half maximum in angstroms, assuming a gaussian spectrum centered on the beam's wavelength
- spectrum_bin_centers: flex.double of bin centers in angstroms
- spectrum_bin_width: width of each bin in angstroms
- spectrum_heights: height of each bin (arbitrary units)

For sure I need the first one, but the spectrum stuff is speculative.

**Comment by graeme-winter** [comment]
+1 for storing spectral information 

Will want to properly support pink beam in near future

**Comment by phyy-nx** [comment]
I've prepared two new branches for dxtbx and dials in which I've refactored the C++ Beam and Crystal models to be polymorphic.  Today I rebased them against the dxtbx ImageSet refactor that James P checked in last week and all the tests look good.  The details:

Branch polymorphic_crystal_and_beam: refactors Crystal and Beam models to be polymorphic using base classes with virtual methods.
Branch new_dxtbx_models: remove mosaicity from Crystal model.  Add two classes that derive from Crystal: MosaicCrystalKabsch2010 (single mosaic parameter expressed as an angle) and MosaicCrystalSauter2014 (two mosaic parameters, domain size and angle).

Diffs (master to polymorphic_crystal_and_beam):
https://github.com/cctbx/cctbx_project/compare/polymorphic_crystal_and_beam
https://github.com/dials/dials/compare/polymorphic_crystal_and_beam

Diffs (polymorphic_crystal_and_beam to new_dxtbx_models):

https://github.com/cctbx/cctbx_project/compare/polymorphic_crystal_and_beam...new_dxtbx_models

https://github.com/dials/dials/compare/polymorphic_crystal_and_beam...new_dxtbx_models

I'd like to merge these soon, say tomorrow morning PST.  Any objections?

**Comment by jmp1985** [comment]
Hi Aaron. If all the tests pass then I'm happy for you to go ahead!

**Comment by phyy-nx** [comment]
Closed by cctbx/cctbx_project#67, cctbx/cctbx_project#68, #443 and #444.
