### ISSUE TITLE
Needed: integrated_pickle.as_miller_array(experiment)

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#365]
As title - to be able to get a cctbx miller array from a DIALS integrated.pickle (or, indexed.pickle even I guess) with the aid of an experiments.json.

**Comment by dagewa** [comment]
Is this kind of like what is done in https://github.com/dials/dials/blob/master/algorithms/scaling/observation_manager.py
?

**Comment by graeme-winter** [comment]
Quite possibly - seems like a useful thing to have (TM)

**Comment by dagewa** [comment]
Can be closed?

**Comment by graeme-winter** [comment]
I would still find this functionality useful...

**Comment by jbeilstenedmands** [comment]
Added a method to the reflection table. So to get a miller array, a spell such as this now works:

from dxtbx.serialize import load
from dials.array_family import flex
reflections = flex.reflection_table.from_pickle("integrated.pickle")
experiments = load.experiment_list("experiments.json")
i_obs = reflections.as_miller_array(experiments[0], intensity='prf')
