### ISSUE TITLE
Show cell in DIALS reciprocal lattice viewer

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#368]
```
when loading an experiment.json with indexed.pickle into the reciprocal space viewer
it would be useful if the cell parameters were listed in the menu to the left.
```

(ticket ```I19-71```)

**Comment by graeme-winter** [comment]
Also useful: provide option to "look down" a* b* c* axis

**Comment by Anthchirp** [comment]
aka #279 aka different issue?

**Comment by graeme-winter** [comment]
Thought it rang a bell.

Though through this discovered show_reciprocal_cell=true option :o)

**Comment by graeme-winter** [comment]
N.B. if > 1 lattice in experiment; show first lattice
