### ISSUE TITLE
Issues processing data with missing images

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#369]
Test - take bag training data; remove *[0-9]00.cbf

Graceless error message

```
[gw56@ws133 00]$ dials.import template=../../images/th_8_2_0###.cbf
DIALS 1.dev.1441-g641b44a
The following parameters have been modified:

input {
  template = "../../images/th_8_2_0###.cbf"
}

Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 734, in <module>
    halraiser(e)
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 732, in <module>
    script.run()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 625, in run
    datablocks = map(metadata_updater, datablock_importer())
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 185, in __call__
    format_kwargs=format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 393, in __init__
    imageset = self._create_imageset(fmt, template, paths, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 408, in _create_imageset
    assert(all(x+1==y for x, y in zip(numbers, numbers[1:])))
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

**Comment by graeme-winter** [comment]
Doing

```
[gw56@ws133 00]$ dials.import ../../images/th_8_2_0*.cbf allow_multiple_sweeps=true
DIALS 1.dev.1441-g641b44a
The following parameters have been modified:

input {
  allow_multiple_sweeps = True
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatCBFMiniPilatusDLS6MSN100.FormatCBFMiniPilatusDLS6MSN100'>
  num images: 535
  num sweeps: 6
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
```

will clearly work however yes will create the error as expected from export

**Comment by graeme-winter** [comment]
actually get error earlier, as scan varying won't work.

**Comment by graeme-winter** [comment]
only sane way to go is split experiments at this stage then take experiments 0...5 through by hand and sort reflections together at the end i.e.

```
[gw56@ws133 00]$ dials.split_experiments indexed.pickle experiments.json 
The following parameters have been modified:

input {
  experiments = experiments.json
  reflections = indexed.pickle
}

Saving experiment 0 to experiments_0.json
Saving reflections for experiment 0 to reflections_0.pickle
Saving experiment 1 to experiments_1.json
Saving reflections for experiment 1 to reflections_1.pickle
Saving experiment 2 to experiments_2.json
Saving reflections for experiment 2 to reflections_2.pickle
Saving experiment 3 to experiments_3.json
Saving reflections for experiment 3 to reflections_3.pickle
Saving experiment 4 to experiments_4.json
Saving reflections for experiment 4 to reflections_4.pickle
Saving experiment 5 to experiments_5.json
Saving reflections for experiment 5 to reflections_5.pickle
```

then for j in 0 1 2 3 4 5; do 

``
[gw56@ws133 00]$ cd 0
[gw56@ws133 0]$ dials.refine ../experiments_0.json ../reflections_0.pickle scan_varying=true
DIALS 1.dev.1441-g641b44a
The following parameters have been modified:

refinement {
  parameterisation {
    scan_varying = True
  }
}
input {
  experiments = ../experiments_0.json
  reflections = ../reflections_0.pickle
}

Configuring refiner

Summary statistics for 20995 observations matched to predictions:
-------------------------------------------------------------------------
|                   | Min     | Q1       | Med       | Q3      | Max    |
-------------------------------------------------------------------------
| Xc - Xo (mm)      | -0.2995 | -0.03463 | -0.00451  | 0.03045 | 0.2965 |
| Yc - Yo (mm)      | -1.098  | -0.02481 | 0.003102  | 0.02664 | 0.7564 |
| Phic - Phio (deg) | -1.215  | -0.01553 | -0.001945 | 0.01234 | 1.279  |
| X weights         | 177.7   | 372.1    | 393.7     | 402.6   | 405.6  |
| Y weights         | 153.1   | 362      | 389       | 401.2   | 405.6  |
| Phi weights       | 305.3   | 517.7    | 529.4     | 533.3   | 533.3  |
-------------------------------------------------------------------------

Detecting centroid outliers using the MCD algorithm
3022 reflections have been flagged as outliers

Summary statistics for 17973 observations matched to predictions:
---------------------------------------------------------------------------
|                   | Min      | Q1       | Med       | Q3      | Max     |
---------------------------------------------------------------------------
| Xc - Xo (mm)      | -0.1588  | -0.03201 | -0.002541 | 0.03048 | 0.1533  |
| Yc - Yo (mm)      | -0.09692 | -0.01904 | 0.00478   | 0.02534 | 0.1031  |
| Phic - Phio (deg) | -0.05755 | -0.01281 | -0.001242 | 0.01144 | 0.05636 |
| X weights         | 191.2    | 379.7    | 395.7     | 403     | 405.6   |
| Y weights         | 169.5    | 371.4    | 392.1     | 402     | 405.6   |
| Phi weights       | 380.4    | 518.2    | 528.8     | 533.3   | 533.3   |
---------------------------------------------------------------------------

Performing refinement of a single Experiment...

Refinement steps:
-------------------------------------------------
| Step | Nref  | RMSD_X   | RMSD_Y   | RMSD_Phi |
|      |       | (mm)     | (mm)     | (deg)    |
-------------------------------------------------
| 0    | 17973 | 0.043741 | 0.03456  | 0.018821 |
| 1    | 17973 | 0.043247 | 0.034237 | 0.018469 |
| 2    | 17973 | 0.043211 | 0.03423  | 0.018166 |
| 3    | 17973 | 0.043207 | 0.034183 | 0.017977 |
| 4    | 17973 | 0.043226 | 0.034052 | 0.017901 |
| 5    | 17973 | 0.043274 | 0.033848 | 0.017861 |
| 6    | 17973 | 0.04334  | 0.033702 | 0.017842 |
| 7    | 17973 | 0.043373 | 0.033656 | 0.017838 |
| 8    | 17973 | 0.043378 | 0.03365  | 0.017838 |
| 9    | 17973 | 0.043378 | 0.033649 | 0.017837 |
-------------------------------------------------
RMSD no longer decreasing

RMSDs by experiment:
---------------------------------------------
| Exp | Nref  | RMSD_X | RMSD_Y  | RMSD_Z   |
| id  |       | (px)   | (px)    | (images) |
---------------------------------------------
| 0   | 17973 | 0.2522 | 0.19564 | 0.11892  |
---------------------------------------------

Final refined crystal model:
Crystal:
    Unit cell: (57.808, 57.781, 150.028, 89.988, 90.009, 89.990)
    Space group: P 1
    U matrix:  {{-0.3455,  0.2589, -0.9020},
                {-0.8914, -0.3909,  0.2292},
                {-0.2933,  0.8833,  0.3658}}
    B matrix:  {{ 0.0173,  0.0000,  0.0000},
                {-0.0000,  0.0173,  0.0000},
                { 0.0000, -0.0000,  0.0067}}
    A = UB:    {{-0.0060,  0.0045, -0.0060},
                {-0.0154, -0.0068,  0.0015},
                {-0.0051,  0.0153,  0.0024}}
    A sampled at 100 scan points

Saving refined experiments to refined_experiments.json
Updating predictions for indexed reflections
Saving reflections with updated predictions to refined.pickle

Total time taken: 10.18s
```
and integrate etc. as usual

**Comment by graeme-winter** [comment]
todo: fix this through improved documentation

**Comment by dagewa** [comment]
Another version is this, after static refinement:

```
dials.split_experiments refined_experiments.json refined.pickle 
dials.combine_experiments experiments_*.json reflections_*.pickle \
  reference_from_experiment.goniometer=0 \
  reference_from_experiment.detector=0 \
  reference_from_experiment.beam=0
dials.refine combined_experiments.json combined_reflections.pickle scan_varying=true
```
which ensures the split is only temporary and just to duplicate the crystal model N times. Then joint scan-varying refinement works fine. This is no easier for a user to understand than the original version though.

**Comment by dagewa** [comment]
There is one potential advantage of the second version: the beam and detector models are refined jointly during scan-varying refinement. It probably doesn't make much of a difference to integration though.

**Comment by graeme-winter** [comment]
Please feel free to update the rst :)

**Comment by graeme-winter** [comment]
Documentation now exists
