### ISSUE TITLE
dials.image_viewer memory leak

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#378]
Clicking forward+back increments memory usage as demonstrated by commit e897873fd58b8e8043aa3b5724d020155bc882a6

> With this test case, ```dials.image_viewer /dls/tmp/david/Lys2_grid3_diffraction_lamella2_noSA_1.ser``` the first press of 'Next' gains 18M of memory footprint, subsequent presses all gain 128M. RAM usage monitored manually using htop. We don't know where the remaining memory leak lies yet.

**Comment by graeme-winter** [comment]
@phyy-nx I have a hunch that this comes down to the flex image objects leaking out someplace; please could you take a look? Y'all over that way probably have more of an idea about this stuff that us Euro's...

**Comment by Anthchirp** [comment]
Used [this script](https://github.com/dials/dials/files/1080246/image_loading.txt) to load 1000 images from a rotation set and memory usage is constant.

**Comment by phyy-nx** [comment]
Reproduced using the eiger16MNov2015 dataset by loading it and pressing
next a few times.

Memory usage: 931.9 MB
Memory usage: 1089.1 MB
Memory usage: 1227.6 MB
Memory usage: 1365.9 MB
Memory usage: 1504.3 MB

Haven't starting looking where the leak is though.
-Aaron

**Comment by nksauter** [comment]
More information:

Same result on an old ADSC Q4 dataset from JCSG.  Seems to rule out any
involvement of HDF5 or CBFlib.
Linux:  32 MB memory increase/Q4 image
Mac OSX:  also 32 MB increase, but reaches a ceiling at 4.4 GB.

Does this suggest a garbage collection issue on Linux python?

Nick


Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by nksauter** [comment]
Memory leak nothing whatsoever to do with my FlexImage class, thanks,
Graeme.

Everything to do with lifetime management within the get_raw_data() member
functions in
cctbx_project/rstbx/slip_viewer/frame.py
dials/util/image_viewer/spotfinder_frame.py

I can cure the cctbx.image_viewer memory leak with a simple patch to
frame.py:

@@ -34,8 +34,9 @@ class chooser_wrapper(object):



   def get_raw_data(self):

     if self._raw_data is None:

-      self._raw_data = self.image_set[self.index]

-    return self._raw_data

+      return self.image_set[self.index]

+    else:

+      return self._raw_data


Aaron & Richard could you please have a look to see if this fix is
compatible with multi-tile raw data and whether this type of fix can be
ported over to the dials.image_viewer within the spotfinder_frame.py module?

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Nick, made this change to the cctbx slip viewer frame; get the following memory behaviour on OS X

```
Graemes-MacBook-Pro-5:thaumatin-9kev-20160221 graeme$ dials.image_viewer data_1_*.cbf.gz
The following parameters have been modified:

input {
  datablock = <image files>
}

Memory usage: 125536.0 MB
Memory usage: 657284.0 MB
Memory usage: 657284.0 MB
Memory usage: 805640.0 MB
Memory usage: 811708.0 MB
Memory usage: 887856.0 MB
Memory usage: 983672.0 MB
Memory usage: 1073868.0 MB
Memory usage: 1164276.0 MB
Memory usage: 1254424.0 MB
Memory usage: 1344620.0 MB
Memory usage: 1434784.0 MB
Memory usage: 1525056.0 MB
Memory usage: 1542164.0 MB
Memory usage: 1542164.0 MB
Memory usage: 1542164.0 MB
Memory usage: 1542164.0 MB
Memory usage: 1542164.0 MB
Memory usage: 1542164.0 MB
Memory usage: 1542164.0 MB
Memory usage: 1542164.0 MB
Memory usage: 1542164.0 MB
```

i.e. does stabilise

**Comment by graeme-winter** [comment]
Reverting change makes memory appear to grow endlessly

```
Graemes-MacBook-Pro-5:thaumatin-9kev-20160221 graeme$ dials.image_viewer data_1_*.cbf.gz
The following parameters have been modified:

input {
  datablock = <image files>
}

Memory usage: 125452.0 MB
Memory usage: 656888.0 MB
Memory usage: 656888.0 MB
Memory usage: 804200.0 MB
Memory usage: 814224.0 MB
Memory usage: 883080.0 MB
Memory usage: 982716.0 MB
Memory usage: 1073052.0 MB
Memory usage: 1163264.0 MB
Memory usage: 1253416.0 MB
Memory usage: 1343608.0 MB
Memory usage: 1433800.0 MB
Memory usage: 1523936.0 MB
Memory usage: 1614120.0 MB
Memory usage: 1704332.0 MB
Memory usage: 1794588.0 MB
Memory usage: 1884800.0 MB
Memory usage: 1975004.0 MB
Memory usage: 2065172.0 MB
Memory usage: 2155324.0 MB
Memory usage: 2245488.0 MB
Memory usage: 2335660.0 MB
Memory usage: 2425808.0 MB
Memory usage: 2515984.0 MB
Memory usage: 2606236.0 MB
Memory usage: 2696420.0 MB
Memory usage: 2786604.0 MB
Memory usage: 2876800.0 MB
Memory usage: 2967028.0 MB
```

(multi-tile images from #380)

**Comment by graeme-winter** [comment]
https://github.com/cctbx/cctbx_project/commit/6ac1099e1fa10420402747a19854bdc7c901f025

**Comment by graeme-winter** [comment]
Then

https://github.com/cctbx/cctbx_project/commit/702e1e9aae136bba8ba4de19b08a51498508e01c

:-(

**Comment by graeme-winter** [comment]
Nick, OK so made this change you proposed and it does not actually seem to "fix" the memory growth problem with single or multi-panel images - confused now 

```
Graemes-MacBook-Pro-5:thaumatin-9kev-20160221 graeme$ dials.image_viewer data_1_0*
The following parameters have been modified:

input {
  datablock = <image files>
}

Memory usage: 125348.0 MB
Memory usage: 656952.0 MB
Memory usage: 656952.0 MB
Memory usage: 804092.0 MB
Memory usage: 814076.0 MB
Memory usage: 882740.0 MB
Memory usage: 982676.0 MB
Memory usage: 1073004.0 MB
Memory usage: 1163408.0 MB
Memory usage: 1253556.0 MB
Memory usage: 1343900.0 MB
Memory usage: 1434080.0 MB
Memory usage: 1524476.0 MB
Memory usage: 1614668.0 MB
Memory usage: 1704840.0 MB
Memory usage: 1795024.0 MB
Memory usage: 1885208.0 MB
Memory usage: 1975412.0 MB
Memory usage: 2065580.0 MB
Memory usage: 2155796.0 MB
Memory usage: 2245960.0 MB
Memory usage: 2336124.0 MB
Memory usage: 2426272.0 MB
Memory usage: 2516460.0 MB
Memory usage: 2606624.0 MB
Memory usage: 2696812.0 MB
Memory usage: 2786996.0 MB
Memory usage: 2877216.0 MB
Memory usage: 2967452.0 MB
Memory usage: 3057596.0 MB
Memory usage: 3147800.0 MB
Memory usage: 3237976.0 MB
Memory usage: 3328168.0 MB
Memory usage: 3418324.0 MB
Memory usage: 3508500.0 MB
Memory usage: 3598664.0 MB
Memory usage: 3688856.0 MB
Memory usage: 3779028.0 MB
Memory usage: 3869188.0 MB
Memory usage: 3959328.0 MB
Memory usage: 4049488.0 MB
Memory usage: 4139648.0 MB
Memory usage: 4229820.0 MB
Memory usage: 4319960.0 MB
```

**Comment by graeme-winter** [comment]
@rjgildea logic in dials image viewer looks rather different because you are able to look at mean variance dispersion etc - and we do not stash the raw data

**Comment by nksauter** [comment]
Hi Graeme,

The change you tried does not seem to be the same as my proposed patch to
frame.py that fixes the memory situation with cctbx.image_viewer.  Please
check again:

@@ -34,8 +34,9 @@ class chooser_wrapper(object):



   def get_raw_data(self):

     if self._raw_data is None:

-      self._raw_data = self.image_set[self.index]

-    return self._raw_data

+      return self.image_set[self.index]

+    else:

+      return self._raw_data

As to the situation with dials.image_viewer it is not clear to me, but code
in spotfinder_frame.py like line 38:

    if not isinstance(raw_data, tuple):

      raw_data = (raw_data,)
seems to lead immediately to a memory increase in my tests.
Nick


Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by nksauter** [comment]
Markus, Graeme,

One further thought.  Are you sure the "memory leak" is truly a bug?
Consider the following contrasting scenarios:

a) The class SpotFrame within spotfinder_frame.py keeps the raw data from
all images previously encountered in a cache, so it can access the data in
the future without a file read.  In this case, the memory usage is a design
feature rather than a bug.

b) The raw data from previously encountered images is kept in memory but no
handles exist to access that memory.  So future displays of these images
will require a file read.  This is a bug.

Can you think of tests to distinguish these cases?

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by Anthchirp** [comment]
Nick

You can edit dxtbx/filecache.py and enable the debug output:
https://github.com/cctbx/cctbx_project/blob/master/dxtbx/filecache.py#L54
This will print out all file read operations. I recommend ```export PYTHONUNBUFFERED=1``` and then running the image viewer with ```|tee output``` and then run ```tail -f output | grep Memory usage``` in a separate terminal.

Going back and forward in the image viewer on the originally reported file always causes data to be read from disk. Using this on a standard Pilatus rotation dataset I can that files are always fully read from disk, additionally that there are a lot of _Instance connected/disconnected_ messages, indicating that whenever we open an image we pass it to a set of ```Format```-classes to determine which one can open it. This is presumably a bit of a waste since we already open each file at the start - separate issue though.

Now, even if this were down to a caching layer it may be a bug. The dataset that @dagewa initially reported having problems with is a single 7.4 GB file. Not all users will have a machine that can easily fit all this into working memory. I would argue that a caching algorithm that can cause the system to essentially run out of memory is broken.

**Comment by Anthchirp** [comment]
on loading an image the image viewer [sets the cached raw_data to None](https://github.com/dials/dials/blob/509e7bab278d6d2871cb62d8eb33a4a819f77e39/util/image_viewer/spotfinder_frame.py#L736) before reading raw_data. This in effect flushes the cache and causes an image reload. I guess the original cache content is still referenced from somewhere so that it does not get garbage collected.

**Comment by graeme-winter** [comment]
NickD you expressed an interest in taking a look - could be helpful; principally in working out what is happening in here & learning your way around...

**Comment by rjgildea** [comment]
As far as I can tell the memory leak is related to the instantiation of FlexImage:

```
$ dials.image_viewer /Users/rjgildea/data/EIGER/DECTRIS/2015_11_10/insu6_1_master.h5 > out.txt
Richards-MacBook-Pro:build rjgildea$ grep usage out.txt 
Memory usage: 648296.0 MB
Memory usage before _get_flex_image: 674684.0 MB
Memory usage after _get_flex_image: 1120396.0 MB
Memory usage: 1120396.0 MB
Memory usage before _get_flex_image: 1120396.0 MB
Memory usage after _get_flex_image: 1407092.0 MB
Memory usage: 1407092.0 MB
Memory usage before _get_flex_image: 1407092.0 MB
Memory usage after _get_flex_image: 1651796.0 MB
Memory usage: 1651796.0 MB
Memory usage before _get_flex_image: 1651796.0 MB
Memory usage after _get_flex_image: 1652968.0 MB
Memory usage: 1652968.0 MB
Memory usage before _get_flex_image: 1652968.0 MB
Memory usage after _get_flex_image: 1795132.0 MB
Memory usage: 1795132.0 MB
Memory usage before _get_flex_image: 1795132.0 MB
Memory usage after _get_flex_image: 1936124.0 MB
Memory usage: 1936124.0 MB
Memory usage before _get_flex_image: 1936124.0 MB
Memory usage after _get_flex_image: 2078628.0 MB
Memory usage: 2078628.0 MB
Memory usage before _get_flex_image: 2078628.0 MB
Memory usage after _get_flex_image: 2220224.0 MB
Memory usage: 2220224.0 MB
Memory usage before _get_flex_image: 2220224.0 MB
Memory usage after _get_flex_image: 2362024.0 MB
Memory usage: 2362024.0 MB
Memory usage before _get_flex_image: 2362024.0 MB
Memory usage after _get_flex_image: 2503076.0 MB
```

**Comment by nksauter** [comment]
Richard,

Good luck with that.  I went down that road for several hours on Friday,
and eventually concluded it wasn't a problem in the wrapped FlexImage class
per se, but something to do with a Python reference that wasn't being
garbage collected properly.  I fixed a problem in the cctbx.image_viewer as
you saw in Graeme's commit message but was unable to locate the problem in
the dials.image_viewer.

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by ndevenish** [comment]
I also spent some time chasing down loops in the python Garbage collection. At the very least, FlexImage_d classes are being destroyed by python. Still working on other avenues, since on the diamond infrastructure at least, valgrind crashes with our version of Boost.

**Comment by ndevenish** [comment]
So I've identified the exact moment the unrecovered object is being created, on a copy of the image data (python stacktrace below). I don't know how much time this memory churning is taking, but if the image viewer frame refresh needs to be faster (I have no idea) things like this might not be helping.

Still tracking down the reference tree to see where the reference is stuck, but the owner appears to be an undestroyed `chooser_wrapper`, at least.

```
Large Allocation: 47MiB at 0x118cac000
  File "dials-dist/base/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "dials-dist/base/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "dials-dist/modules/dials/command_line/image_viewer.py", line 203, in <module>
    runner()
  File "dials-dist/modules/dials/command_line/image_viewer.py", line 136, in __call__
    self.view()
  File "dials-dist/modules/dials/command_line/image_viewer.py", line 144, in view
    reflections=self.reflections)
  File "dials-dist/modules/dials/util/image_viewer/spotfinder_wrap.py", line 45, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "dials-dist/modules/dials/util/image_viewer/spotfinder_frame.py", line 470, in load_image
    show_untrusted=show_untrusted)
  File "dials-dist/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 345, in load_image
    get_raw_data=get_raw_data)
  File "dials-dist/modules/cctbx_project/rstbx/slip_viewer/tile_generation.py", line 256, in set_image
    self.raw_image.set_raw_data(get_raw_data(self.raw_image))
  File "dials-dist/modules/dials/util/image_viewer/spotfinder_frame.py", line 737, in get_raw_data
    raw_data = image.get_raw_data()
  File "dials-dist/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 37, in get_raw_data
    return self.image_set[self.index]
  File "dials-dist/modules/cctbx_project/dxtbx/imageset.py", line 1158, in __getitem__
    return self.get_corrected_data(item)
  File "dials-dist/modules/cctbx_project/dxtbx/imageset.py", line 585, in get_corrected_data
    r = r / g
```

(Used memory profiler to find the memory allocation that's never destroyed, and then altered `af::aligned_malloc` to print the python stacktrace for any large memory allocations. Then just a matter of matching the memory addresses. dtrace FTW)

**Comment by dagewa** [comment]
Hi Nick, yes, it would be a nice bonus if we eventually end up with an image viewer that is faster at browsing through frames.

**Comment by ndevenish** [comment]
Yep, `chooser_wrapper` objects were the cause, but not a leak per se. Raw image data for everything loaded so far was being cached, and never flushed from cache. However, since this cached data was never used I just discard it after loading the next image (the image is always reloaded, into the same cache, probably a minor bug).

I can't reproduce the memory problem with going back to previous images - *except* for the fact that the memory report seemed to be prior to image loading - e.g. it's a click behind. So if you go forward (to a new image) and then back it looks like it's increased going backwards, but actually hasn't. I put the report down to this for now.

This was a fun one to track down with no a priori knowledge of the UI. The image viewer panel stores the image objects and raw data on the `wx.Chooser` widget's client data inside a `chooser_wrapper`, so from the garbage collection's perspective it's got a reference but no listed entries in `gc.get_referrers`.

I've also left the basic memory log statement in for now.

**Comment by dagewa** [comment]
Just a note to close this out with results from the original test case - looks sensible now:

```
Memory usage: 118.0 MB
Memory usage: 730.9 MB
Memory usage: 730.9 MB
Memory usage: 876.5 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 876.6 MB
Memory usage: 877.3 MB
Memory usage: 877.3 MB
Memory usage: 877.3 MB
Memory usage: 877.3 MB
```
