### ISSUE TITLE
Print pixel to mm strategy in dials.show etc

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#383]
@phyy-nx 

See

```
commit e72e8e59ec721018220d48ce40a10be3515a8b7a
Author: Aaron Brewster <asbrewster@lbl.gov>
Date:   Mon Jun 19 23:06:58 2017 -0700

    Attempt to add __str__ methods to the PxMmStrategy classes and use it when printing panels.
    
    Doesn't quite work yet. For panel.h, I'm getting a memory address instead of the PxMmStrategy's operator<< method.
```

getting 

```
Graemes-MBP-5:tmp graeme$ libtbx.python "/Users/graeme/svn/cctbx/modules/dials/test/command_line/tst_show.py" 
--- 
+++ 
@@ -14,6 +14,7 @@
   fast_axis: {1,0,0}
   slow_axis: {0,-1,0}
   origin: {-212.478,220.002,-190.18}
+  pixel to millimeter strategy: 0x100712720
 
 Max resolution (at corners): 1.008178
 Max resolution (inscribed):  1.204283

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/modules/dials/test/command_line/tst_show.py", line 174, in <module>
    run()
  File "/Users/graeme/svn/cctbx/modules/dials/test/command_line/tst_show.py", line 71, in run
    """, strip_trailing_whitespace=True)
AssertionError
```

at the moment (as an aside; also test fails now...)

@jmp1985 got any "pointers" on this (deliberate pun, will get coat) since this is your area of expertise?

**Comment by jmp1985** [comment]
This appears to work for me.

$dials.show experiments.json
Experiment 0:
Detector:
Panel:
  name: Panel
  type: SENSOR_UNKNOWN
  identifier:
  pixel_size:{0.172,0.172}
  image_size: {2463,2527}
  trusted_range: {-1,495976}
  thickness: 0
  material:
  mu: 0
  gain: 1
  fast_axis: {0.999955,0.00211593,0.00923308}
  slow_axis: {0.002125,-0.999997,-0.000972639}
  origin: {-211.536,219.453,-192.706}
  pixel to millimeter strategy: PxMmStrategy


________________________________

**Comment by phyy-nx** [comment]
Hi James, it should be printing out SimplePxMmStrategy or
ParallaxCorrectedPxMmStrategy.
See panel.h.  I was hoping one call to operator<< would force the class
specific operator<< function to be called.  Perhaps the definitions of
operator<< in pixel_to_millimeter.h need to be virtual instead of friend?

-Aaron

**Comment by dagewa** [comment]
Also get the same as James, but causes tst_show to fail

```
$ dials.python /home/fcx32934/sw/cctbx/modules/dials/test/command_line/tst_show.py
--- 
+++ 
@@ -14,6 +14,8 @@
   fast_axis: {1,0,0}
   slow_axis: {0,-1,0}
   origin: {-212.478,220.002,-190.18}
+  pixel to millimeter strategy: PxMmStrategy
+
 
 Max resolution (at corners): 1.008178
 Max resolution (inscribed):  1.204283

Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/modules/dials/test/command_line/tst_show.py", line 174, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/modules/dials/test/command_line/tst_show.py", line 71, in run
    """, strip_trailing_whitespace=True)
AssertionError

```

**Comment by jmp1985** [comment]
OK, I've now fixed this so that it prints it out correctly.
