### ISSUE TITLE
dials.import option to override gain

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#385]
There doesn't appear to be a way in dials.import to override the gain value for the panel/format class. Also, the lookup.gain parameter appears to expect a file containing an array of individual gain values for each pixel - how does one generate such a file?

**Comment by rjgildea** [comment]
See also https://github.com/dials/dials/issues/321

**Comment by dagewa** [comment]
It still seems the case that you cannot override the overall gain during import, except with a pixel-by-pixel lookup table. Having a constant override would be very useful when dealing with images that are picked up by generic format classes.

**Comment by jmp1985** [comment]
Added this - will push on Monday ;)
