### ISSUE TITLE
max_cell estimation failed for 3 x screening images

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#386]
Thaumatin images so 57 57 150 90 90 90 unit cell; get 

```

Found max_cell: 71.1 Angstrom
Setting d_min: 1.39
FFT gridding: (256,256,256)
Number of centroids used: 1308
Candidate solutions:
```

and

```
------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 185      | 140        |
| 1        | 269      | 232        |
| 2        | 281      | 212        |
------------------------------------
```

setting max_cell=200 get

```
model 3 (479 reflections):
Crystal:
    Unit cell: (58.065, 58.107, 150.393, 90.040, 89.971, 90.104)
    Space group: P 1
    U matrix:  {{ 0.6554, -0.1993, -0.7285},
                {-0.0847,  0.9391, -0.3331},
                { 0.7505,  0.2800,  0.5986}}
    B matrix:  {{ 0.0172,  0.0000,  0.0000},
                { 0.0000,  0.0172,  0.0000},
                {-0.0000,  0.0000,  0.0066}}
    A = UB:    {{ 0.0113, -0.0034, -0.0048},
                {-0.0014,  0.0162, -0.0022},
                { 0.0129,  0.0048,  0.0040}}

------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 323      | 2          |
| 1        | 457      | 44         |
| 2        | 479      | 14         |
------------------------------------
```

so correct solution

**Comment by graeme-winter** [comment]
[d386.zip](https://github.com/dials/dials/files/1096848/d386.zip)

**Comment by graeme-winter** [comment]
Command:

```
 dials.index *SWEEP* 'indexing.method=fft3d' 'indexing.nproc=20' 'reflections_per_degree=100' 'close_to_spindle_cutoff=0.020000' 'outlier.algorithm=auto' max_cell=200
```

In related news; fft1d fails completely to index unless set max_cell=200; in which case it works correctly

**Comment by rjgildea** [comment]
This is probably a result of the orientation of the crystal in this particular dataset meaning that there aren't many observations of the 150 A cell dimension in the images collected:
```
$ dev.dials.nearest_neighbour_analysis *_SWEEP* 
Found max_cell: 71.1 Angstrom
```
![nn_hist](https://user-images.githubusercontent.com/2810624/27488945-6f1b1d3c-57fe-11e7-89e8-bbaaeebc1649.png)

**Comment by rjgildea** [comment]
Tweaking the parameters to the nearest neighbour analysis can result in a better max_cell estimate in this particular case, but this may make things worse in other cases...
$ dev.dials.nearest_neighbour_analysis *_SWEEP* max_height_fraction=0.1
Found max_cell: 199.7 Angstrom
![nn_hist](https://user-images.githubusercontent.com/2810624/27490369-a1ba3e8a-5803-11e7-83c1-2f724a685974.png)

**Comment by rjgildea** [comment]
$ dev.dials.nearest_neighbour_analysis *_SWEEP* binning=linear
Found max_cell: 196.5 Angstrom
![nn_hist](https://user-images.githubusercontent.com/2810624/27490400-bbb7bc22-5803-11e7-905c-6af16d5ed11b.png)

**Comment by rjgildea** [comment]
Another example:
https://ispyb.diamond.ac.uk/dc/visit/in17188-2/id/1761453
Max cell should be ~200A, barely any observations of 200A in nearest neighbour histogram:
![nn_hist](https://user-images.githubusercontent.com/2810624/27494110-02627dac-5812-11e7-8998-0315491660d2.png)

**Comment by rjgildea** [comment]
See http://jira.diamond.ac.uk/browse/MXSW-904?focusedCommentId=109779&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-109779 for example of when binning=logarithmic does a better job of filtering out noise from e.g. ice.

**Comment by rjgildea** [comment]
Another example (thaumatin again, incorrect max_cell leads to poor indexing, leading to incorrect dials.align_crystal results):
https://ispyb.diamond.ac.uk/dc/visit/cm16781-4/id/1914281
![nn_hist](https://user-images.githubusercontent.com/2810624/30280686-4db06050-9708-11e7-98eb-5d31c7aa2206.png)

**Comment by rjgildea** [comment]
New option nearest_neighbor_percentile added to dials.index (and also xia2):

```
$ dev.dials.nearest_neighbour_analysis 2_SWEEP* 5_SWEEP* 8_SWEEP* percentile=0.95
Found max_cell: 199.0 Angstrom
```
![nn_hist](https://user-images.githubusercontent.com/2810624/30333226-5be9c23e-97d4-11e7-9a51-808c50ccb503.png)

```
$ xia2.strategy image=thaum_1_0001.cbf multi_sweep_indexing=True min_images=1 profile_fitting=False index.method=auto trust_beam_centre=True failover=True percentile=0.95
-------------------- Spotfinding SWEEP1 --------------------
864 spots found on 1 image
-------------------- Spotfinding SWEEP2 --------------------
715 spots found on 1 image
-------------------- Spotfinding SWEEP3 --------------------
563 spots found on 1 image
---------------- Autoindexing SWEEPS 1 to 3 ----------------
All possible indexing solutions:
tP  57.87  57.87 150.31  90.00  90.00  90.00
oC  81.84  81.87 150.33  90.00  90.00  90.00
oP  57.88  57.87 150.32  90.00  90.00  90.00
mC  81.86  81.85 150.32  90.00  89.97  90.00
mP  57.88  57.87 150.30  90.00  89.98  90.00
aP  57.89  57.87 150.31  89.98  89.98  89.99
Indexing solution:
tP  57.87  57.87 150.31  90.00  90.00  90.00
```

**Comment by Anthchirp** [comment]
Change appears to have broken 3ish tests, eg dials.test.command_line.tst_discover_better_experimental_model.3:

```
Traceback (most recent call last):
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_discover_better_experimental_model.py", line 188, in <module>
    run(sys.argv[1:])
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_discover_better_experimental_model.py", line 180, in run
    exercise()
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_discover_better_experimental_model.py", line 157, in exercise_3
    result = easy_run.fully_buffered(command=command).raise_if_errors()
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/cctbx_project/libtbx/easy_run.py", line 39, in raise_if_errors
    raise Error(msg)
RuntimeError: child process stderr output:
  command: 'dials.discover_better_experimental_model /scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials_regression/indexing_test_data/phi_scan/datablock.json /scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials_regression/indexing_test_data/phi_scan/strong.pickle'
  Sorry: Not enough solutions: found 2, need at least 3
```
