### ISSUE TITLE
tst_phil.py fails on windows

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#387]
Cause: mock not available in windows python.

  Standard error:
    Traceback (most recent call last):
      File "c:\users\builder\slave\phenix-nightly-intel-windows\modules\dials\test\tst_phil.py", line 6, in <module>
        from mock import Mock, patch
    ImportError: No module named mock

From @Anthchirp:
we are bundling mock and pytest since April 2016. They have been used in dials/test/util/test_procrunner since then as well...

...I just noticed that that test is not run via run_tests.py, I guess that's why it didn't come up before.

Two ways to deal with it I guess - pip install mock pytest, or alternatively something along the lines of
try:
  import mock
except ImportError:
  print "Skipped"
  import sys
  sys.exit(0)

Both packages are only ever used in tests.

**Comment by ndevenish** [comment]
Is this a case of `bootstrap` not installing mock on windows distributions?

**Comment by Anthchirp** [comment]
working on the missed existing test in #389

**Comment by phyy-nx** [comment]
Hi, yah I belive mock must not be part of the python that is built on
windows. There is documentation here on how the windows build works:

https://www.phenix-online.org/documentation/WindowsBuild.html

I'm cc'ing Rob Oeffner who might have some ideas on how to proceed with
this issue.

-Aaron

**Comment by Anthchirp** [comment]
I suspect that since we now enforce prerequisites in the libtbx_refresh in a manner similar to a proper setup.py this is now no longer an issue.
