### ISSUE TITLE
Parallelism on windows needs fixing

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#39]

**Comment by dagewa** [comment]
This is a general issue with easy_mp in cctbx, not limited to DIALS. Using phenix.python and a trivial easy_mp.parallel_map script demonstrates failures on Windows. It is not clear how to proceed.

**Comment by Anthchirp** [comment]
possibly relevant: https://sourceforge.net/p/cctbx/code/HEAD/tree/trunk/libtbx/tst_easy_mp_state.py

**Comment by jmp1985** [comment]
I'm going to add an:
if windows==True:
  dont_do_multiprocessing()
thing somewhere
