### ISSUE TITLE
dials.reindex "Unsuitable value for rational rotation matrix"

### ISSUE THREAD

**Issue by dagewa** [dials/dials#391]
As reported by Melanie. Files available at DLS (too big to attach here):
```
The following parameters have been modified:

change_of_basis_op = "-3/2*h-1/2*k,-1/2*h+1/2*k,-l"
output {
  experiments = "/dls/tmp/ghp45345/xia2_stresstest/20170621/3QNK/DEFAULT/scale/120_experiments_reindexed.json"
  reflections = "/dls/tmp/ghp45345/xia2_stresstest/20170621/3QNK/DEFAULT/scale/120_reflections_reindexed.pickle"
}
input {
  experiments = /dls/tmp/ghp45345/xia2_stresstest/20170621/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/67_integrated_experiments.json
  reflections = /dls/tmp/ghp45345/xia2_stresstest/20170621/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/67_integrated.pickle
}

Traceback (most recent call last):
  File "/dls/science/users/ghp45345/dials/build/../modules/dials/command_line/reindex.py", line 243, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/ghp45345/dials/build/../modules/dials/command_line/reindex.py", line 197, in run
    cryst_reindexed = cryst_orig.change_basis(change_of_basis_op)
RuntimeError: cctbx Internal Error: /dls/science/users/ghp45345/dials/modules/cctbx_project/cctbx/sgtbx/rot_mx.cpp(19): Unsuitable value for rational rotation matrix.
# command line:
# dials.reindex  '/dls/tmp/ghp45345/xia2_stresstest/20170621/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/67_integrated_experiments.json' 'output.experiments=120_experiments_reindexed.json' '/dls/tmp/ghp45345/xia2_stresstest/20170621/3QNK/DEFAULT/WAVE2/SWEEP2/integrate/67_integrated.pickle' 'output.reflections=120_reflections_reindexed.pickle' 'change_of_basis_op=-3/2*h-1/2*k,-1/2*h+1/2*k,-l'
```

**Comment by graeme-winter** [comment]
From https://github.com/xia2/xia2/issues/143

**Comment by graeme-winter** [comment]
TBH this is probably not a real bug; was nonsense side-effect of problematic processing as identified in xia2 ticket above; tempted to close with prejudice?

**Comment by dagewa** [comment]
Fair enough, if this can't be caught earlier somehow, then GIGO applies

**Comment by nksauter** [comment]
More helpful if you spell out acronyms like TBH and GIGO...can't interpret.
Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Nick

To be honest
Garbage in garbage out

Pretty common when we're using phones to respond 

All the best Graeme

**Comment by nksauter** [comment]
:)

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by dagewa** [comment]
Given that xia2/xia2#143 is closed, I will close this too.

**Comment by splintersu** [comment]
I encountered the same problem- in my case problem can work-around by setting pipeline=dials-full, and get reasonably good result
