### ISSUE TITLE
dials.reciprocal_lattice_viewer noisy when can't calculate beam centre

### ISSUE THREAD

**Issue by dagewa** [dials/dials#394]
dials.reciprocal_lattice_viewer tries to calculate the beam centre like this:
```
    try:
      panel_id, beam_centre = detector.get_ray_intersection(beam.get_s0())
    except RuntimeError, e:
      print "Error calculating beam centre:", str(e)
```
so whenever the beam centre can't be calculated you get output like this
```
Error calculating beam centre: dxtbx Internal Error: /home/david/sw/cctbx/modules/cctbx_project/dxtbx/model/detector.h(797): DXTBX_ASSERT(w_max > 0) failure.
```
However, this is a reasonable situation, whenever the beam does not intersect a panel in a multi-panel detector.

One possibility is that we don't need the error message at all. After all, we pass and move on anyway. Another is that it could be made a bit less scary. A third is that we could catch this case and then loop through all the panels using `detector[i].get_beam_centre(beam.get_unit_s0())`, which always returns a value even when outside the panel limits, then choose _which_ beam centre to return.

**Comment by rjgildea** [comment]
Sounds good, feel free to add the change.

**Comment by dagewa** [comment]
Which one?

**Comment by dagewa** [comment]
Easiest is probably just suppress output. Happy to do that.

**Comment by rjgildea** [comment]
See also beam_centre_mm function in dials/command_line/show.py:
https://github.com/dials/dials/blob/master/command_line/show.py#L43
