### ISSUE TITLE
Make the dials.export partial options sane

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#396]
Currently include_partials=maybe include_all_partials=no include_nearly_full=ok min_partiality=about-half etc - complete nonsense, got out of hand, needs to be made more sensible; see #388 for trigger

**Comment by dagewa** [comment]
Yes please. I work it out when I need it, then immediately forget what it all means so it looks insane again next time I need it

**Comment by rjgildea** [comment]
Also see https://github.com/dials/dials/issues/16

**Comment by jbeilstenedmands** [comment]
My recent commits to the refactor-export-mtz branch are my attempts to address this issue, alongside issues #15 #16 #555 . See commit messages for details, but this basically reduces the options to combine_partials=True/False and partiality_threshold=0.5. These changes are also applied to xds and sadabs exporting.
I'm happy to discuss the changes further or receive feedback - this also involves changing the interface for export so would need some care before pulling in to the main code.

**Comment by graeme-winter** [comment]
If interface changes need to make sure corresponding changes made in xia2...
