### ISSUE TITLE
Minimizer: explore Eigenvalue filtering for matrix minimisation for scaling

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#401]
@dagewa will also add words here

**Comment by dagewa** [comment]
This is what Aimless does, following [Fox & Holmes](http://scripts.iucr.org/cgi-bin/paper?S0365110X66002007). However, Aimless does not then use an algorithm specific to non linear least squares, like Levenberg Marquardt, but a general purpose BFGS algorithm (apparently taken from Phaser)
