### ISSUE TITLE
Design data structures to record integrated data for efficient handling in scaling

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#402]
i.e. ways / methods to extend our reflection tables to allow access in ways which are efficient for scaling, perhaps indexing with unique indices etc?

**Comment by phyy-nx** [comment]
Cxi.merge, PRIME and the XFEL GUI all interact with this problem in different ways. Each has advantages but I'm not super happy with any of them. Happy to go into more detail as needed. 

-Aaron

**Comment by dagewa** [comment]
@jbeilstenedmands @graeme-winter Can this be closed? I'm not totally sure what it refers to any more, perhaps the issue that @jbeilstenedmands solved using sparse matrices?

**Comment by jbeilstenedmands** [comment]
Yes, I'm happy that my sparse matrix solution is good for now, but always happy to reconsider new ideas in future.
