### ISSUE TITLE
Implement basic target function for scaling i.e. HRS

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#403]
Working with data structures in #402 compute target for minimisation, with derivatives

**Comment by dagewa** [comment]
The general expression for the derivatives of the HRS target function wrt abstract parameters has been worked out (see dials_regression/doc/notes/scaling/scaling.pdf) and tested for the simple case where parameters of the model are individual scale factors. The more interesting case is when scale factor g=C*T*S*L, where C is a phi-dependent scale factor, T is a B-factor, S describes absorption and L is a "tails correction" (what Aimless does, but may not really be appropriate here)

**Comment by jbeilstenedmands** [comment]
HRS target for scaling has been implemented, closing.
