### ISSUE TITLE
'Experiment ids' buttons in RLV don't do anything

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#407]
Steps to reproduce:
```dials.reciprocal_lattice_viewer strong.pickle datablock.json``` with dataset with >1 sweeps. Click Experiment ids buttons to try and isolate data from one sweep. All data is shown.

This works with ```dials.reciprocal_lattice_viewer indexed.pickle experiments.json```.

**Comment by rjgildea** [comment]
The experiments id button shouldn't appear, and if they did, then I wouldn't expect them to do anything anyway as they are for selecting experiments (there are none in a datablock.json). Instead use the imageset id buttons:
`$ dials.reciprocal_lattice_viewer $(libtbx.find_in_repositories dials_regression)/indexing_test_data/multi_sweep/SWEEP*/index/*import.json $(libtbx.find_in_repositories dials_regression)/indexing_test_data/multi_sweep/SWEEP*/index/*strong.pickle marker_size=50`

Behaves as expected for me:
<img width="1137" alt="screen shot 2017-07-04 at 09 16 30" src="https://user-images.githubusercontent.com/2810624/27821301-b995600e-6099-11e7-9775-dae16ccb002b.png">
<img width="1137" alt="screen shot 2017-07-04 at 09 16 43" src="https://user-images.githubusercontent.com/2810624/27821304-bb8a33d0-6099-11e7-8432-e71c0e612ead.png">

**Comment by Anthchirp** [comment]
Sounds plausible, however:
```dials.reciprocal_lattice_viewer /dls/tmp/wra62962/directories/jTdJHufE/*-4*```
![image](https://user-images.githubusercontent.com/2102431/27824006-f3dfca0c-60a2-11e7-94d4-299502da9e4c.png)

**Comment by Anthchirp** [comment]
It does work on the regression data.

**Comment by Anthchirp** [comment]
Fixed. Many thanks. Earmarked for 1.6.4
