### ISSUE TITLE
Implement scaling with exponential models

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#411]
i.e. parameterise as product of exponentials; good for likelihood.

**Comment by dagewa** [comment]
Zbyszek Otwinowski, Dominika Borek, Wladyslaw Majewski, and Wladek Minor. [Multiparametric scaling of
diffraction intensities](http://scripts.iucr.org/cgi-bin/paper?we0011). Acta Crystallographica Section A: Foundations of Crystallography, 59(3):228–234,
2003. ISSN 01087673. doi: 10.1107/S0108767303005488.
