### ISSUE TITLE
dials.discover_better_experimental_model --> dials.search_beam_position

### ISSUE THREAD

**Issue by dagewa** [dials/dials#418]
See discussion on dials-support:

> Harry thinks DIALS is still new enough that renaming dials.discover_better_experimental_model as dials.beam_centre_search would be possible without inconveniencing many users.
> 
> Can we do this? Is there any sense in which dbem is not in fact a beam centre search?
> 
> Harry says: "I would definitely do this - you don't want to get stuck with unusual (and really meaningless, in this case - a better experimental model might be to invert your rotation vector, which is probably not what this method does) method names that are of "historical interest" only."

> Hi David,
> 
> Thoughts:
> - change dispatcher name
> - add lightweight dispatcher with old name that gives deprecation warning and then runs other script
> - after >=1 stable release remove lightweight dispatcher
> - do everything with reference to a ticket
> 
> I personally see a beam_centre_search vs beam_center_search discussion coming on, otherwise I think this makes sense.
> 
> -Markus

> Hi Markus,
> 
> All sounds good.
> 
> dials.beam_position_search?
> 
> Cheers
> David

**Comment by graeme-winter** [comment]
Discussion topic:s 

1. what does DBEM do if rotation axis is inverted?
2. could this actually discover better experimental models? i.e. could we get it to search for the right rotation axis direction across cardinal directions (or !cardinal, even)
3. doing [2] by eye kinda-sorta works - I was running exactly this t'other day on $funnydataset where I figured it was a phi scan on a kappa goniostat (I think)

**Comment by graeme-winter** [comment]
Renamed, so closing; will create new ticket for enhancements to "real" dbem

**Comment by rjgildea** [comment]
All relevant documentation (and probably also tests) - sphinx documentation and "cheatsheet" needs to be modified to use the new name. Also xia2 should use the new name.

**Comment by jmp1985** [comment]
I realise this is a bit late but I'm not sure about this renaming. 

We have generally named dials programs using the scheme "dials.do_something", which dials.discover_better_experimental_model fits with. dials.beam_position_search is more like "dials.something". Is the loss of consistency worth the very small reduction in characters?

**Comment by jmp1985** [comment]
@Anthchirp I think I would prefer that since it's more consistent.

**Comment by dagewa** [comment]
Suggested still to do:

- Rename command line program to the new name, make old name the mere alias
- Change imports accordingly
- Emit deprecation warning when the old name is used
- Remove old dispatcher in DIALS 1.8

**Comment by Anthchirp** [comment]
Reading through this I will work on the assumption that the renaming should go ahead, and will pick this up.

**Comment by Anthchirp** [comment]
new name is ```search_beam_position``` as per discussion

**Comment by Anthchirp** [comment]
Todo: 
* remove old dispatcher for DIALS 1.9 and later

**Comment by Anthchirp** [comment]
* [x] add new dispatcher for DIALS 1.9 and later
* [ ] remove old dispatcher for DIALS 1.10 and later
