### ISSUE TITLE
dials.export_mtz: make it easier to get the original indices

### ISSUE THREAD

**Issue by dagewa** [dials/dials#420]
dials.export reduces h,k,l to the asu and encodes the transform to recover original indices into the M/ISYM column. Is this really necessary? AFAIK pointless and aimless are happy with original indices, and keeping them makes it easier to track reflections from integration through scaling.

Noted a few weeks ago on the BB:

> This reminds me - one of the sensible things in SCALEPACK unmerged is it lists explicitly:
>  (h k l) unique followed by (h' k' l') measured. I think the M/ISYM was introduced to save file space but it is kind of redundant now! and a bit flawed, as it depends on assigned symop numbering ,   Is it time to chang?? 

At the very least, is it a good idea to allow the _option_ of the original indices being recorded alongside the reduced indices (not on by default)?

**Comment by dagewa** [comment]
N.B. M/ISYM is mandatory input to Pointless, but could consist only of the partiality flag part, M

**Comment by dagewa** [comment]
Recording the original indices alongside the reduced ones doesn't seem a useful approach because Pointless strips away the extra columns. Hmmm. Next will just try to write original indices _instead_. Do these survive all the way through to Aimless output? Ultimately I want to be able to write OUTPUT UNMERGED from Aimless, which has a SCALEUSED column, and hopefully will keep the original indices. If not, will just have to expand them from M/ISYM.

**Comment by rjgildea** [comment]
Getting the original indices from mtz using cctbx is trivial, e.g.:
```
indices = mtz_object.extract_original_index_miller_indices()
intensities = intensities.customized_copy(indices=indices, info=intensities.info())
```

**Comment by dagewa** [comment]
Well, that's good because it seems that Pointless doesn't like it when the original indices are left in the file (or I broke the M/ISYM flag)
```
pointless hklin integrated.mtz hklout test.mtz >pointless2.log
get_from_asu - ISYM out of range
```
So I suppose the 'right' way to do this is let Pointless and Aimless do their thing, then `extract_original_index_miller_indices` afterwards
