### ISSUE TITLE
Excessively large mosacity estimate from dials.integrate

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#421]
From /dls/i03/data/2017/cm16791-3/processing/gw/20170719/TLN/TLN_2/strategy/DEFAULT/NATIVE/SWEEP1/integrate/17_dials.integrate_INTEGRATE.log
```
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.050166 degrees
 sigma m: 21.895118 degrees
```
This will likely not end well.

**Comment by rjgildea** [comment]
Scan varying crystal parameters gone a bit mad:
file:///dls/i03/data/2017/cm16791-3/processing/gw/20170719/TLN/TLN_2/strategy/DEFAULT/NATIVE/SWEEP1/refine/16_dials.refine.report.html
![image](https://user-images.githubusercontent.com/2810624/28365680-62622cce-6c81-11e7-97bf-32abd354135a.png)

**Comment by rjgildea** [comment]
dials.check_indexing_symmetry has messed things up.

After dials.index things look reasonably good:
/dls/i03/data/2017/cm16791-3/processing/gw/20170719/TLN/TLN_2/strategy/DEFAULT/NATIVE/SWEEP1/index/5_dials.index.log
```
RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 9000 | 0.46245 | 0.54561 | 1.1596   |
---------------------------------------------
```

However, /dls/i03/data/2017/cm16791-3/processing/gw/20170719/TLN/TLN_2/strategy/DEFAULT/NATIVE/SWEEP1/index/7_dials.check_indexing_symmetry.log:
```
dH dK dL   Nref    CC
-1 -1  1  10469 0.726
 0  0  0  16418 0.628
```

Which reindexing/refinement gives /dls/i03/data/2017/cm16791-3/processing/gw/20170719/TLN/TLN_2/strategy/DEFAULT/NATIVE/SWEEP1/index/9_dials.refine.log:
```
RMSDs by experiment:
--------------------------------------------
| Exp | Nref  | RMSD_X | RMSD_Y | RMSD_Z   |
| id  |       | (px)   | (px)   | (images) |
--------------------------------------------
| 0   | 30991 | 1.7899 | 6.6367 | 16.48    |
--------------------------------------------
```

**Comment by jmp1985** [comment]
Can this issue be closed @rjgildea? The problem here is obviously the really bad RMSD_Z which makes the mosaicity explode.

**Comment by rjgildea** [comment]
I don't think the underlying issue with dials.check_indexing_symmetry has been fixed, so there is still a bug within DIALS, even if not necessarily with mosaicity estimation.

**Comment by dagewa** [comment]
The bug with `dials.check_indexing_symmetry` is issue #287, so this can be closed.
