### ISSUE TITLE
dials.refine_bravais_settings: only need to use 360 degrees of data?

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#430]
More than this adds no new information...

**Comment by rjgildea** [comment]
Can't you just run dials.slice_sweep before hand? Rather than have every program coding separately to only get the first 360 degrees of a scan...

**Comment by graeme-winter** [comment]
http://xia2.blogspot.co.uk/2017/08/massive-eiger-data-sets-ie-100k-frames.html

**Comment by graeme-winter** [comment]
There are a few special cases where there are real savings to be made at no additional cost - indexing would want the entire run (though perhaps not, for basis determination) however deciding on the lattice gains nothing for > 1 turn of data. 

Slicing sweep takes you on a tangent in the workflow & would mean you would need to re-create the experiments-with-all-images jsons afterwards.

**Comment by graeme-winter** [comment]
OK, I realise now that this could be more complicated when you have > 1 one as input, as may occur for example after multi-sweep indexing. Will make this an *option* so that we can switch it on from $outside if appropriate
