### ISSUE TITLE
(Repository meta): QuantifiedCode shut down

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#431]
On https://www.quantifiedcode.com/ and shown on any links into previously valid pages:

> Notice: The Software-As-A-Service version of QuantifiedCode was shut down on July 31. We are happy to offer an open-source edition of our solution, which you can self-host free of charge.

I've removed the broken-link badge from the `README`, but there are probably some repository hooks that also need to be tidied up?

**Comment by Anthchirp** [comment]
I think there is nothing else that needs to be done.
