### ISSUE TITLE
Discover better experimental model could in principle actually do that

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#432]
At the moment just finds better beam centre (or aims to) but could actually "discover" correct gonio orientation / spindle direction etc. also in principle:

1. what does DBEM do if rotation axis is inverted?
2. could this actually discover better experimental models? i.e. could we get it to search for the right rotation axis direction across cardinal directions (or !cardinal, even)
3. doing [2] by eye kinda-sorta works - I was running exactly this t'other day on $funnydataset where I figured it was a phi scan on a kappa goniostat (I think)

**Comment by ndevenish** [comment]
Related: #418 (remove/rename `discover_better_experimental_model`)
