### ISSUE TITLE
dials.index: resolution limit of macrocycles not printed for fft1d

### ISSUE THREAD

**Issue by dagewa** [dials/dials#439]
With the default fft3d the resolution of macrocycles is printed to the log:
```
------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 2435     | 91         |
------------------------------------
Increasing resolution to 2.22 Angstrom

################################################################################
Starting refinement (macro-cycle 3)
################################################################################
```
However, this does not appear to be the case for `indexing.method=fft1d`:
```
------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 2480     | 159        |
------------------------------------

################################################################################
Starting refinement (macro-cycle 3)
################################################################################
```

**Comment by rjgildea** [comment]
This is correct, because fft1d uses all reflection in refinement, whereas fft3d starts out with only using reflections that were used in the initial basis vector determination. The resolution cutoff for basis vector determination is necessary in the fft3d case because reflections are mapped to a relatively coarse 3D grid, which means the initial basis vectors are less accurate than for fft1d, hence it is better to only use only the low resolution reflections initially to refine the initial basis vectors. No such restriction exists for fft1d.

**Comment by dagewa** [comment]
I see, thanks for the explanation... that's why the `#indexed` is high even on the first macrocycle for fft1d. Why does the refinement for fft1d still use macrocycles?

I thought that the bootstrapping out to higher resolution shells was a feature in all cases, not just a response to the restriction of fft3d. My reasoning was that the curvature in columns of relps caused by poor initial geometry is often small enough that at low resolution indexing is trustworthy, but indexing the high resolution spots might be more problematic. By bootstrapping the low resolution solution out to higher resolution gradually I thought that the curvature might be progressively straightened out.

**Comment by dagewa** [comment]
Perhaps answering my own question here - the macrocycles of refinement for fft1d will tend to fix any misindexed spots at high resolution anyway, because you would hope that each cycle leaves you closer to the truth and following that with reindexing of all the spots will hopefully correct any that are wrong, or more likely, correctly label any that were outside the 0.3 integer tolerance on a previous macrocycle and therefore increase the number indexed. Does that sound about right?

**Comment by rjgildea** [comment]
Yes, the macrocycles of refinement combined with re-indexing all spots between each macrocycle should tend to "fix" any high resolution misindexed spots. For fft3d there is an obvious means to calculate a suitable starting d_min, based on the calculation for which reflections to include in basis vector determination:

https://github.com/dials/dials/blob/master/algorithms/indexing/fft3d.py#L102

For fft1d it is less obvious what would be a suitable starting d_min. I have never systematically tested how doing the refinement in macrocycles improves the reliability or accurateness of the indexing results, but doing it as we currently do seems to work reasonably well in most cases.

**Comment by dagewa** [comment]
Understood. Current behaviour may be advantageous anyway because in situations where you have very few spots to play with you may well want them all for refinement to remain stable/possible. Thanks for the clarifications.
