### ISSUE TITLE
dials.image_viewer: position of predictions seems to be wrong

### ISSUE THREAD

**Issue by dagewa** [dials/dials#442]
The display of predictions in the `dials.image_viewer` seems to be incorrect. For example, for i04-bag-training data, I index and find the spot on image 4 at around pixel (slow, fast) 1840,1835. I display the calculated centroid and the predicted centroid. Reading off values from the status bar I estimate the positions of the cross and the red spot as follows:

```
From image viewer
=================
            slow     fast
observed:   1840.785 1835.312
predicted:  1841.535 1835.812
```
Note that this implies there is a residual of about 0.9 pixels which seems rather high. Here are the images with values read off the status bar, highlighting where I had the cursor, as that was hidden while taking a screenshot:

![centroid](https://user-images.githubusercontent.com/11502083/30336349-d10b1a6a-97dc-11e7-944d-99d99d57f972.png)
![predicted](https://user-images.githubusercontent.com/11502083/30336362-de1d15be-97dc-11e7-8c5b-40a571465d1b.png)

Loading the reflection table in dials.python and selecting that reflection I can get at the real values for `r['xyzobs.px.value']` and `r['xyzcal.px']`

```
>>> r['xyzobs.px.value']
(1835.2916666666667, 1840.75, 3.75)
>>> r['xyzcal.px']
(1835.289794544969, 1841.0089880829669, 3.7675501624336776)
```

So, the real residual on the image should only be 0.26 pixels, which better matches the RMSDs from indexing. Tidying up:
```
From reflection table
=====================
            slow     fast
observed:   1840.750 1835.292
predicted:  1841.009 1835.290
```
Comparing with the above table -- reminder:
```
From image viewer
=================
            slow     fast
observed:   1840.785 1835.312
predicted:  1841.535 1835.812
```
the observed position, i.e. the cross, seems to be about right whilst the prediction is way off.

**Comment by nksauter** [comment]
David,

Just as a comment to this:  when I originally wrote the viewer in Jan 2012
all the overlays were exact to numerical precision.  I suspect the effect
shown here arises from either rounding or failing to keep track of whether
pixels have their center or corner at the registered position.  No other
insights.

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by dagewa** [comment]
An easy way to investigate the issue is to set the predictions equal to the observations:
```
>>> from dials.array_family import flex
>>> rt=flex.reflection_table.from_pickle('indexed.pickle')
>>> rt['xyzcal.px']=rt['xyzobs.px.value']
>>> rt.as_pickle('pred_eq_obs.pickle')
```
Then all the spots show the same offset.
![offset](https://user-images.githubusercontent.com/11502083/30345026-84ee9c8c-97fb-11e7-9ca6-0af2c4244359.png)

It does indeed look like a 0.5 pixel issue, in each direction.
