### ISSUE TITLE
Missing time in dials.integrate output?

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#451]
When running dials.integrate on 3 screening images, the total time taken is ~3x the sum of the individual times reported for various steps. Presumably some time is not being recorded somewhere (possibly in the predictions)?
```
$ dials.integrate bravais_setting_9.json reindexed_reflections.pickle nproc=3
... 
--------------------------------
         Read time | 0.86 seconds
      Extract time | 0.18 seconds
  Pre-process time | 0.05 seconds
      Process time | 2.55 seconds
 Post-process time | 0.00 seconds
        Total time | 4.48 seconds
         User time | 0.00 seconds
 --------------------------------

Saving 35340 reflections to integrated.pickle
 time taken: 0.181779
Saving the experiments to integrated_experiments.json
 time taken: 0.0112579

Total time taken: 25.119368
```
Sum of times in table plus writing output files (aside: could the time for writing output files be included in the above table instead of being listed separately?) is 8.31s, compared to total time taken of >25.119368s (possibly overly precise?).

**Comment by jmp1985** [comment]
So the table refers just to the time taken to integrate reflections. There is also a table reported after reference profile formation. The total time at the bottom refers to the time taken for the whole program to run. I agree that this may not be clear so I've added some additional text to make it clearer.
