### ISSUE TITLE
Prediction takes majority of runtime when running dials.integrate on a single image

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#452]
When running dials.integrate on a single image, according to profiling 57% of the runtime is spent in prediction, which seems excessive. This is particularly important when processing screening images for strategy determination which requires extremely rapid feedback.
```
curl -L https://github.com/BestMX/BestMX/blob/master/example_data/th_8_1_0001.cbf?raw=true > th_8_1_0001.cbf
dials.import th_8_1_*.cbf
dials.find_spots datablock.json
dials.index datablock.json strong.pickle indexing.method=fft1d space_group=P4
dials.python -m cProfile -o out.prof $(libtbx.find_in_repositories dials)/command_line/integrate.py experiments.json indexed.pickle
runsnake out.prof
```
<img width="945" alt="screen shot 2017-09-21 at 16 02 38" src="https://user-images.githubusercontent.com/2810624/30702993-5a76cece-9ee6-11e7-8199-0b892e2947a0.png">

**Comment by graeme-winter** [comment]
If this is predicting all reflections but only using a handful will be ++ expensive (I have seen > half of time in "predicting reflections"

Happy to have predictor=single-image in command line or similar as the existing behaviour is sensible for side wedges of data - here we know _a priori_ that we only want to integrate one image or 1, 2, 3 lone images

**Comment by rjgildea** [comment]
Interestingly things are much faster if we run scan-varying refinement first:

Scan-static integration:
```
$ time dials.integrate experiments.json indexed.pickle
real	0m10.392s
user	0m9.268s
sys	0m0.621s
```
Scan-varying integration:
```
$ dials.refine experiments.json indexed.pickle scan_varying=True
$ time dials.integrate integrated_experiments.json integrated.pickle 
real	0m5.694s
user	0m4.733s
sys	0m0.572s
```

**Comment by jmp1985** [comment]
I agree, this sounds like the best way forward.

James
________________________________

**Comment by rjgildea** [comment]
I have added a force_scan_varying parameter to prediction (to mirror the existing force_static parameter): https://github.com/dials/dials/commit/6ba11951f56c8f58adaf1e77b191577f6c7d09cc

Scan-static prediction:
```
$ time dials.integrate experiments.json indexed.pickle
real	0m10.376s
user	0m9.380s
sys	0m0.609s
```
Scan-varying prediction:
```
$ time dials.integrate experiments.json indexed.pickle force_scan_varying=True
real	0m4.380s
user	0m3.490s
sys	0m0.562s
```

**Comment by jmp1985** [comment]
I think this issue is closed, since Richard has implemented a fix.

**Comment by rjgildea** [comment]
I think this issue should be kept open as my "fix" was just a workaround - to use scan-varying prediction instead of scan-static. Could scan-static prediction be modified to use the Reeke algorithm as @dagewa suggested?

**Comment by jmp1985** [comment]
ScanStaticReflectionPredictor and ScanVaryingReflectionPredictor give slightly different results. The difference in the angle between the predicted diffracted beam vectors is around 1e-4 degrees but this translates to a difference in the predicted pixel position of > 1e-3 pixels.

This then causes the following tests to fail non-trivially:

test/command_line/tst_export_best.py
test/algorithms/indexing/tst_assign_indices.py

I'm going to commit the changes back to a new branch called use_reeke_algorithm but I've copied a script below (since I can't attached .py files) which illustrates the difference in predicted positions. 

I will look at the predictions to see if I can figure out why there is a difference but it looks like some things in indexing and export_best that are very sensitive to the predicted position which might be one for @rjgildea 

 
```
from __future__ import division

def run():
  from dials.algorithms.spot_prediction import ScanVaryingReflectionPredictor
  from dials.algorithms.spot_prediction import ScanStaticReflectionPredictor
  from dials.array_family import flex
  from dxtbx.model.experiment_list import ExperimentListFactory
  import libtbx.load_env
  from os.path import join
  try:
    dials_regression = libtbx.env.dist_path('dials_regression')
  except KeyError:
    print 'SKIP: dials_regression not configured'
    exit(0)


  filename = join(dials_regression, "centroid_test_data/experiments.json")

  experiments = ExperimentListFactory.from_json_file(filename)
  experiment = experiments[0]

  predictor1 = ScanStaticReflectionPredictor(experiment)
  predictor2 = ScanVaryingReflectionPredictor(experiment)

  experiment.detector[0].set_px_mm_strategy(None)

  reflections1 = predictor1.for_ub(experiment.crystal.get_A())

  A = [experiment.crystal.get_A() for i in
         range(experiment.scan.get_num_images()+1)]
  reflections2 = predictor2.for_ub(flex.mat3_double(A))

  print len(reflections1)  
  print len(reflections2)  

  index1 = flex.size_t(sorted(range(len(reflections1)), key=lambda x: reflections1['miller_index'][x]))
  index2 = flex.size_t(sorted(range(len(reflections2)), key=lambda x: reflections2['miller_index'][x]))

  reflections1 = reflections1.select(index1)
  reflections2 = reflections2.select(index2)

  for r1, r2 in zip(reflections1, reflections2):
    h1 = r1['miller_index']
    h2 = r2['miller_index']

    s1 = r1['s1']
    s2 = r2['s1']

    e1 = r1['entering']
    e2 = r2['entering']

    f1 = r1['flags']
    f2 = r2['flags']

    p1 = r1['panel']
    p2 = r2['panel']

    mm1 = r1['xyzcal.mm']
    mm2 = r2['xyzcal.mm']
    
    px1 = r1['xyzcal.px']
    px2 = r2['xyzcal.px']

    assert h1 == h2
    assert e1 == e2
    assert p1 == p2
    assert f1 == f2
    assert abs(s1[0] - s2[0]) < 1e-3
    assert abs(s1[1] - s2[1]) < 1e-3
    assert abs(s1[2] - s2[2]) < 1e-3
    assert abs(mm1[0] - mm2[0]) < 1e-3
    assert abs(mm1[1] - mm2[1]) < 1e-3
    assert abs(mm1[2] - mm2[2]) < 1e-3
    assert abs(px1[0] - px2[0]) < 1e-2
    assert abs(px1[1] - px2[1]) < 1e-2
    assert abs(px1[2] - px2[2]) < 1e-2

  angle = reflections1['s1'].angle(reflections2['s1'], deg=True)
  d_s1_0 = reflections1['s1'].parts()[0] - reflections2['s1'].parts()[0]
  d_s1_1 = reflections1['s1'].parts()[1] - reflections2['s1'].parts()[1]
  d_s1_2 = reflections1['s1'].parts()[2] - reflections2['s1'].parts()[2]
  d_mm1_0 = reflections1['xyzcal.mm'].parts()[0] - reflections2['xyzcal.mm'].parts()[0]
  d_mm1_1 = reflections1['xyzcal.mm'].parts()[1] - reflections2['xyzcal.mm'].parts()[1]
  d_mm1_2 = reflections1['xyzcal.mm'].parts()[2] - reflections2['xyzcal.mm'].parts()[2]
  d_px1_0 = reflections1['xyzcal.px'].parts()[0] - reflections2['xyzcal.px'].parts()[0]
  d_px1_1 = reflections1['xyzcal.px'].parts()[1] - reflections2['xyzcal.px'].parts()[1]
  d_px1_2 = reflections1['xyzcal.px'].parts()[2] - reflections2['xyzcal.px'].parts()[2]

  print "D S1[0] = ", flex.max(flex.abs(d_s1_0))
  print "D S1[1] = ", flex.max(flex.abs(d_s1_1))
  print "D S1[2] = ", flex.max(flex.abs(d_s1_2))
  print "Max angle S1,S2 = ", flex.max(angle)
  print "D MM[0] = ", flex.max(flex.abs(d_mm1_0))
  print "D MM[1] = ", flex.max(flex.abs(d_mm1_1))
  print "D RAD = ", flex.max(flex.abs(d_mm1_2))
  print "D PX[0] = ", flex.max(flex.abs(d_px1_0))
  print "D PX[1] = ", flex.max(flex.abs(d_px1_1))
  print "D IMG = ", flex.max(flex.abs(d_px1_2))
```

**Comment by jmp1985** [comment]
After looking at the code, I think I understand why we don't get the same results. 

For ScanStaticRayPredictor where we have a single A matrix, the reciprocal lattice vector is rotated and the intersection with the Ewald sphere is calculated. 

For the ScanVaryingRayPredictor where we have an A matrix for the start of the frame and an A matrix at the end of the frame, we find the reciprocal lattice vector for each matrix and then draw a straight line intersecting the Ewald sphere. 

Doing this means that if the A matrix is the same for the beginning of the frame as it is at the end of the frame, the predicted intersection with the Ewald sphere is not the same. What's more, the length of the reciprocal lattice vector is not even the correct length. However, it's not clear to me how this can be done better in the general case. @dagewa do you have any ideas? Solving the general problem seems to be quite non-linear.

**Comment by dagewa** [comment]
Yes, you're right, it is non-linear.

But we don't need to use the ScanVaryingRayPredictor in order to make use of the Reeke index generator. The Reeke algorithm just generates a list of HKLs that are close to the Ewald sphere. After that we can use ScanStaticRayPredictor as always

**Comment by jmp1985** [comment]
Sure, I figured I could just pass in the same A matrix for each scan point and just use the scan varying predictor.
