### ISSUE TITLE
@jmp1985

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#455]
Hi @jmp1985 

Could you please give me a one-liner short description of commit a52ccc3d4834 for the 1.7.3 release notes? I'll then cherry pick for the update next Tuesday

**Comment by jmp1985** [comment]
The profile fitting variances are now computed after the last iteration of the profile fitting algorithm fixing a bug where the variances reported for profile fitting were too small.

**Comment by Anthchirp** [comment]
much obliged!
