### ISSUE TITLE
Support multiple lattices in dials.reciprocal_lattice_viewer

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#46]
Request by JeppeC:

Can I run dials.reciprocal_lattice_viewer and either give it, say, 4 pairs of datablock.json/strong.pickle files and have them shown in different colours and the option to individually show and hide them.
Or, possibly even more useful, have one merged datablock.json/strong.pickle file and still have these options.

**Comment by graeme-winter** [comment]
This is a good idea and not limited to I19

**Comment by Anthchirp** [comment]
Colour palette suggestion by DW: http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0000HT
