### ISSUE TITLE
Make applying mm to pixel offset map snappy 

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#461]
i.e. it exists but is ++ slow; find out why; make nice & fast => 😄

**Comment by jmp1985** [comment]
This should be a bit snappier and more user friendly.

I have modified the imageset code to treat the DX/DY maps in the same way as gain/mask etc (i.e. they are read from file and stored in the imageset). When the imageset is serialised as json only the filenames are stored and the data is read from disk when the imageset is reloaded from json. 

The pixel to mm strategy contains a shared ptr to the image data stored in the imageset so the image data is not stored twice.

dials.import now has a lookup.dx=DX.pickle lookup.dy=DY.pickle option to load the offset maps. The map files contain a tuple of maps with elements equal to the number of panels.

So once you have generated a DX.pickle and DY.pickle just do the following:

dials.import /path/to/images*.cbf dx=DX.pickle dy=DY.pickle 

Then process as normal.

**Comment by graeme-winter** [comment]
Awesome, will test 😄

**Comment by graeme-winter** [comment]
To be clear: dx, dy.pickle are pickled flex arrays of 2 dimensions, same dimensions as image, in pixel offset units in which direction?

**Comment by jmp1985** [comment]
So dx and dy are pickled tuples of flex arrays such that the number of flex arrays in the tuple is equal to the number of panels in the detector. Each flex array then has the same dimensions as the panel it corresponds to.

The units of the offset arrays are in pixels. The offset is applied in the following way:

to_millimeter:

1. Subtract the offset from the pixel coordinate
2. Perform the parallax correction

to_pixel:

1. Perform the parallax correction
2. Add the offset to the pixel coordinate

James

________________________________
