### ISSUE TITLE
dials.export failure for multiple crystal dataset

### ISSUE THREAD

**Issue by dagewa** [dials/dials#465]
Normally I would `dials.split_experiments` first and export individual crystals as separate MTZs, but out of curiosity I wondered what would happen if I passed a two experiment integrated json+pickle to `dials.export`.  It didn't like it, which might indeed be the right behaviour, but it would be nicer to fail more gracefully:

```
$ dials.export integrated_experiments.json integrated.pickle 
DIALS 1.dev.1817-ge8838e1
The following parameters have been modified:

input {
  experiments = integrated_experiments.json
  reflections = integrated.pickle
}

Warning: Experiment crystals differ. Using first experiment crystal for file-level data.
Read 796841 predicted reflections
Selected 673706 integrated reflections
Removing 18 reflections with I/Sig(I) < -5.0
Removing 0 profile reflections with I/Sig(I) < -5.0
Removing 11025 incomplete reflections
Beam vector: 0.0147 0.0000 -0.9999
Beam vector: 0.0147 0.0000 -0.9999
Traceback (most recent call last):
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/export.py", line 712, in <module>
    exporter.export()
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/export.py", line 275, in export
    apply_scales=params.mtz.apply_scales)
  File "/home/david/sw/cctbx/modules/dials/util/export_mtz.py", line 723, in export_mtz
    assert len(set(len(v) for v in merged_data.values())) == 1, "Column length mismatch"
AssertionError: Column length mismatch

```

**Comment by jbeilstenedmands** [comment]
Hi David @dagewa,
Is this still an issue? I remember coming across this issue a while ago (but probably after you opened this issue) and I think Nick and I corrected an error higher up in the code that was causing this. Recently I've been exporting a multi-dataset scaled.pickle and scaled_experiments.json without issue, although of course it only uses the first experiment crystal which may need to be looked at for multi-dataset work going forward.

**Comment by dagewa** [comment]
Quick test suggests this now works, thanks :+1:
