### ISSUE TITLE
dials.find_spots: smoothing of dispersion map

### ISSUE THREAD

**Issue by dagewa** [dials/dials#470]
Particularly FAO @jmp1985 

I've been trying to find differences between spot finding in XDS vs DIALS. I have a dataset with a high gain, but probably low point spread. XDS estimates the gain to be about 3.21, dials.estimate_gain gives about 3.25, so quite consistent. I force dials.find_spots to use the same gain as XDS to compare results. There is quite a difference in the number of accepted found spots [EDIT: updated with `sigma_s=4` to match `STRONG_PIXEL=    4.00` from the XDS job]

XDS: 9100
DIALS: 5814

Indexing works okay with the XDS spots but fails with the DIALS spots. So I take the XDS solution and use it to index the DIALS spots. Now I can qualitatively compare the results in the reciprocal lattice viewer:

**XDS spots**
![xds_spots](https://user-images.githubusercontent.com/11502083/32790368-26c7400a-c956-11e7-8b4b-167b9bfc8fec.png)

**DIALS spots**
![dials_spots](https://user-images.githubusercontent.com/11502083/32837251-aefeb9a4-ca04-11e7-97e5-c30a6fd29213.png)

Interesting that DIALS gives cleaner-looking spot finding results at high resolution with fewer noise peaks amongst the indexed relps, and fewer spots overall. However, DIALS finds far too many peaks at low resolution in the scatter around the backstop. XDS appears to do a better job of adapting the spot-finding settings locally on regions of the detector.

[EDIT: the following is misleading - GAIN.cbf is important, but it is clearly not the same as the per image dispersion maps used for spot finding. There is only one GAIN.cbf after all]
Wondering why that is, I compared GAIN.CBF with the DIALS dispersion map. AFAIK these are equivalent entities, used to determine areas that are "probably background". Possibly XDS uses one map for the whole dataset, whereas DIALS does it per image, I'm not sure.

![gain cbf_vs_dispersion](https://user-images.githubusercontent.com/11502083/32790604-c99bae06-c956-11e7-81f0-de1ddd8523c9.png)

What is striking is that the XDS dispersion map looks significantly smoothed compared to the DIALS version. Can anyone confirm whether there is a smoothing step performed by XDS? Is it because of this smoothing that XDS suffers less from finding noise peaks round the backstop?

**Comment by dagewa** [comment]
> The result is smoothed.

https://strucbio.biologie.uni-konstanz.de/xdswiki/index.php/Gain

**Comment by graeme-winter** [comment]
Also, just checking but is it a "known thing" that the kernel sizes for the spot finding are the same? That would give a different outcome as well... also the gain is accumulated across a number of images, so is likely to be better behaved?

**Comment by graeme-winter** [comment]
=> testing out these calculations on a sequence of pixel array detector images of a smooth background i.e. background with no spots in could be insightful, will be able to see if the maps look the same (re: your comparison above)

**Comment by dagewa** [comment]
The kernel sizes were the same in this test. I tried to get all equivalent parameters set to the same values

**Comment by dagewa** [comment]
I think what I wrote above is not quite right - GAIN.CBF just sets the local expected value for the index of dispersion, then individual variance over mean maps are calculated for each image and compared to this. It is the fact that the gain map is not uniform that means that XDS has locally variable spot finding. In this case, at low res around the backstop GAIN.CBF has higher values, which makes the spot finding a bit less sensitive in this region and suppresses some of the noise spots.

**Comment by dagewa** [comment]
I'll try forcing a flat gain map and see if that makes XDS behave the same as DIALS...

**Comment by dagewa** [comment]
I flattened the XDS GAIN.cbf using https://github.com/dials/dials_scratch/commit/84a80eb3325e1e4e227ffa255a428b301ff971b5 which sets a mean gain value of 3.207 everywhere in the map (except for points flagged -3), then re ran COLSPOT.

This make a huge difference to the spot-finding in XDS! Now it finds many more spots:
```
 NUMBER OF STRONG PIXELS EXTRACTED FROM IMAGES      339600

 NUMBER OF DIFFRACTION SPOTS LOCATED                 23770
 IGNORED BECAUSE OF SPOT CLOSE TO UNTRUSTED REGION      19
 WEAK SPOTS OMITTED                                      0
 NUMBER OF DIFFRACTION SPOTS ACCEPTED                23751
```
and there is much more noise around the backstop, like for the DIALS job.
![xds_spots2](https://user-images.githubusercontent.com/11502083/32836610-5028b49a-ca02-11e7-988a-e77a86ebbb75.png)

It is not the end of the story because the number of spots found by XDS is very different to DIALS, so this wasn't sufficient to make the algorithms behave in the same way.

However, it confirms that XDS uses GAIN.cbf to make the spot finding algorithm locally sensitive. [It is claimed](https://strucbio.biologie.uni-konstanz.de/xdswiki/index.php/Gain) that this is to handle a detector gain that really does vary across the active surface. However, in this case it mainly acts to suppress false positives at low resolution. The gain of the detector is not really different around the backstop, it is just that the process used to determine GAIN.cbf, as a smoothed dispersion map, makes it look like this is the case.

If you don't interpret GAIN.cbf as actually meaning the local gain, but take it to mean the locally expected value of the index of dispersion then it looks like a useful thing to have in these cases where spot finding is problematic.

**Comment by jmp1985** [comment]
Hi David. Very interesting. 

When I first implemented spot finding, I tried to implement an algorithm to compute a gain map but the result was very noisy even after applying smoothing so it never made it to dials proper. 

I would imagine that some of the differences in output may also be a result of different filtering of spots after applying the spot finding filters.

**Comment by dagewa** [comment]
Another piece of information: XDS does not like to do spot-finding if BKGINIT.cbf is missing or incorrectly formatted, but one can replace all the values with some constant and there is no effect on spot-finding. Therefore, it appears BKGINIT.cbf is **not** used in spot finding.
