### ISSUE TITLE
dials.import convert_stills_to_sweeps=True does not work with EIGER

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#476]
I have EIGER datasets that lack rotation information. By default, `dials.import` (correctly) imports them as stills.

I want to import them as oscillation datasets by supplying scan information.

1.  `geometry.scan` and `geometry.goniometer` do not affect the choice between sweep or stills.
 This is because the decision is made by FormatMultiImage.get_imageset(), which does not use user supplied information but the file header.

2.  The above is not problematic as long as `convert_stills_to_sweeps=True` works. However, it doesn't:
```
$ dials.import test_data_master.h5 geometry.scan.oscillation=0,0.2 geometry.goniometer.axes=0,1,0 convert_stills_to_sweeps=True
(omit)
Traceback (most recent call last):
  File "/app/dials/modules/dials/command_line/dials_import.py", line 821, in <module>
    halraiser(e)
  File "/app/dials/modules/dials/command_line/dials_import.py", line 819, in <module>
    script.run()
  File "/app/dials//modules/dials/command_line/dials_import.py", line 712, in run
    datablocks = map(metadata_updater, datablock_importer())
  File "/app/dials/modules/dials/command_line/dials_import.py", line 494, in __call__
    imageset = updater(imageset)
  File "/app/dials/modules/dials/command_line/dials_import.py", line 315, in __call__
    imageset = self.convert_stills_to_sweep(imageset)
  File "/app/dials/modules/dials/command_line/dials_import.py", line 413, in convert_stills_to_sweep
    template, indices = template_regex_from_list(imageset.paths())
  File "/app/dials/modules/cctbx_project/dxtbx/sweep_filenames.py", line 67, in template_regex_from_list
    return common_prefix + template, indices
```
  This is because `template` is `None` and `indices` are all `0`.

**Comment by dagewa** [comment]
There is work ongoing that touches similar use cases. #1036 #1014 etc. When the dust clears we should revisit this error.

**Comment by graeme-winter** [comment]
On master for me right now - where I do have a gonio in the example - I am getting

```
Grey-Area sweep :) $ dials.import ../insu_7_testbeamline_2_master.h5 convert_stills_to_sequences=1 geometry.scan.oscillation=0,0.2 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1144-g37323628a
The following parameters have been modified:

input {
  experiments = <image files>
}
geometry {
  scan {
    oscillation = 0 0.2
  }
  convert_stills_to_sequences = True
}


Applying input geometry in the following order:
  1. Manual geometry

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNexusEigerDLS16M.FormatNexusEigerDLS16M'>
  num images: 81
  sequences:
    still:    1
    sweep:    0
  num stills: 0
--------------------------------------------------------------------------------
Writing experiments to imported.expt
```

i.e. it is not importing as sweep, will look - thanks for pointers.

**Comment by graeme-winter** [comment]
The output is a lie - these _are_ imported as sweeps when actually used 🤔

**Comment by graeme-winter** [comment]
@biochem-fan please could you share the example set for this so I can reproduce your problem? Appreciate it was a long time ago.

**Comment by jbeilstenedmands** [comment]
This should have been fixed in https://github.com/dials/dials/pull/2273 and is now explicity tested for. Feel free to reopen this issue if this is still a problem.
