### ISSUE TITLE
dials.import_xds does not appear to work

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#480]
i.e. 

```
[gw56@ws133 integrate]$ dials.import_xds XDS_ASCII.HKL 
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-8-2/build/../modules/dials/command_line/import_xds.py", line 473, in <module>
    halraiser(e)
  File "/dls_sw/apps/dials/dials-v1-8-2/build/../modules/dials/command_line/import_xds.py", line 471, in <module>
    script.run()
  File "/dls_sw/apps/dials/dials-v1-8-2/build/../modules/dials/command_line/import_xds.py", line 449, in run
    importer(params, options)
  File "/dls_sw/apps/dials/dials-v1-8-2/build/../modules/dials/command_line/import_xds.py", line 197, in __call__
    raise RuntimeError('No XDS file found')
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: No XDS file found

```

**Comment by graeme-winter** [comment]
dials.import_xds $PATH worked => documentation revisit needed? Was user report

**Comment by graeme-winter** [comment]
Documentation != helpful:

```
[gw56@ws133 integrate]$ dials.import_xds  
Usage: dials.import_xds [options] (SPOT.XDS|INTEGRATE.HKL)

Options:
  -h, --help            show this help message and exit
  -c, --show-config     Show the configuration parameters.
  -a ATTRIBUTES_LEVEL, --attributes-level=ATTRIBUTES_LEVEL
                        Set the attributes level for showing configuration
                        parameters
  -e EXPERT_LEVEL, --expert-level=EXPERT_LEVEL
                        Set the expert level for showing configuration
                        parameters
  -v                    Increase verbosity
```

**Comment by TKaminishi** [comment]
Hello,
it would be extremely nice if reflections in XDS format can be together converted to a pickle file, so that  dials.reciprocal_lattice_viewer can immediately visualize the reflections that have been already indexed by XDS. Thank you very much, Graeme!

**Comment by dagewa** [comment]
Hi,

I do this already:

dials.import_xds method=reflections /path/to/SPOT.XDS

You can then use dev.dials.combine_datablocks to put the XDS spots and
DIALS spots into the same files for immediate comparison in a single
dials.reciprocal_lattice_viewer instance.

A caveat about spot_xds.pickle: this file does not have the weights that
dials.refine wants for refinement, so if you take this file onwards for
processing you might not get the best possible results. One can work around
that by indexing off the spot_xds.pickle, then using the resulting
experiments.json to index a DIALS spot list.

Cheers

-- David

**Comment by dagewa** [comment]
Motivational screenshot:
![spot_xds_comparison](https://user-images.githubusercontent.com/11502083/33617553-ebce0fe6-d9d7-11e7-9e40-ef1d84cc87d7.png)

DIALS spots in orange, XDS in blue. It was at this point that I realised that XDS had only found spots in the first half of the scan in this case.
