### ISSUE TITLE
dials.report - please could we make plots more useful for multi-panel detectors

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#482]
At the moment detectors like the P12M make some of the plots in the report a little unhelpful

If we know a priori the geometry, could pass in => can make more easily interpreted plots (say with 24 modules for the rmsd plots)

**Comment by dagewa** [comment]
Duplicate of #304

**Comment by graeme-winter** [comment]
Found that adding (195+17)*panel_no to y coordinates in mm made all of this do $sensible things

**Comment by rjgildea** [comment]
Closed as duplicate issue
