### ISSUE TITLE
dials.stills_process fails with MemoryError if given data file too large to fit into memory

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#483]
The problem is this line of code: https://github.com/dials/dials/blob/master/command_line/stills_process.py#L165
```
  try:
    datablocks = DataBlockFactory.from_json_file(filename)
  except ValueError:
    datablocks = DataBlockFactory.from_filenames([filename])
```
If the input data file (e.g. .h5) is too large to fit into memory, then attempting to read it as a json file will fail with an uncaught MemoryError.

**Comment by phyy-nx** [comment]
Thanks for the debugging @rjgildea
