### ISSUE TITLE
In reciprocal lattice viewer, if indexed, give option to show in crystal frame

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#487]
i.e. divide through by U matrix so that multiple crystals (which are differently orientated) will be shown in same local coordinate system. 

This is complicated because:
 - indexing ambigiuty
 - different symmetries

But would still be useful to assess e.g. completeness of data from _n_ samples if indexed.

**Comment by graeme-winter** [comment]
Reason for this occurred to me - if multi crystal, show _which_ crystals give you which reflections...

**Comment by graeme-winter** [comment]
i.e. different to multiplicity viewer

**Comment by ndevenish** [comment]
Duplicate of #279
