### ISSUE TITLE
Retire, link, or mark orphaned documentation pages

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#489]
The following pages are orphaned, ie. not linked to from any other page:
1. https://dials.github.io/basel.html
1. https://dials.github.io/diamond.html
1. https://dials.github.io/workshops/dials3d.html
1. https://dials.github.io/workshops/DIALS-1.html
1. https://dials.github.io/documentation/tutorials/small_molecule_tutorial.html

Orphaned pages that are not marked as such cause errors when building the documentation.

For each of them there are three possible resolutions:
1. Keep the page as it is, do not link to it, but mark it as orphaned. I will do this for all of them now to fix the immediate problem, but this is a legitimate resolution of the issue.
2. Keep the page as it is, link to it from another place. For example a main 'workshops' page may be useful to resolve 1., 2., and 4.
3. Delete the page. The small molecule tutorial seems a good candidate for this.

Discuss.

**Comment by dagewa** [comment]
basel.html is not useful. That could be deleted too, I think

**Comment by nksauter** [comment]
Pages 3 and 4 are indeed linked to on the Workshops page, and yes we want
to keep them.
Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by Anthchirp** [comment]
I see that there is a workshop page. 
I'll look into why 3, 4 are reported as orphaned even though they are being linked to.
