### ISSUE TITLE
dials.integrate crash: reference spots have an invalid experiment id

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#49]
dials.integrate (from xia2) died with:

```
Processing reference reflections
 read 941 strong spots
 removing 464 unindexed reflections
Sorry:
        Invalid input for reference reflections.
        16 reference spots have an invalid experiment id
```
debugging shows that reference spots have id == -1

Command to reproduce:
```
dials.integrate  'input.experiments=/dls/tmp/wra62962/directories/4ams57d2/x/DEFAULT/NATIVE/SWEEP1/refine/10_refined_experiments.json' 'nproc=20' 'input.reflections=/dls/tmp/wra62962/directories/4ams57d2/x/DEFAULT/NATIVE/SWEEP1/refine/10_refined.pickle' 'output.experiments=11_integrated_experiments.json' 'output.reflections=11_integrated.pickle' 'output.report=11_integration_report.json' 'output.include_bad_reference=True' 'profile.fitting=True' 'outlier.algorithm=null' 'background.algorithm=glm' 'prediction.d_max=9.582297'
```

xia2 run directory in /dls/tmp/wra62962/directories/4ams57d2/x/
data in /dls/tmp/wra62962/directories/4ams57d2/data

Probably related commits https://github.com/dials/dials/commit/35564d6e709525420aa4ec3ff9b2ae1834478235 and https://github.com/dials/dials/commit/44765063e08438f6153fd7a0a43f8f2c161cefbc and consensus seems that @jmp1985 might know what's going on?

**Comment by jmp1985** [comment]
Not a bug in dials.integrate
