### ISSUE TITLE
Helen Ginn's spotfinding algorithm

### ISSUE THREAD

**Issue by dagewa** [dials/dials#494]
Helen Ginn's spotfinding algorithm uses a very different approach to the standard `dispersion` algorithm in `dials.find_spots`. In particular, it might be useful in cases where some properties of the detector, such as gain, are suspect. The core code is in DIALS, but requires some work to clean up and make consistent with the standard algorithm. After meeting with Helen, we came up with at least these points for a TODO list:

- [ ] Write a test!
- [ ] Rename such that `algorithm=blob`, not `algorithm=helen`
- [ ] Make defaults consistent with the default `dispersion` algorithm. In particular, `global_threshold=100` should be `global_threshold=0`? NB the default of 100 may have come from CS-PAD processing
- [ ] The algorithm writes a lot of debugging stuff to the screen. Clean up this output
- [ ] It is computationally expensive. It would be worth profiling the code to see if there are any easy improvements we can make.

**Comment by ndevenish** [comment]
"Make defaults consistent" - My interpretation of this is "Make defaults work with pilatus/CCD data" - I don't know if lowering the threshold is sufficient or if any other of the parameters need to be tweaked?
