### ISSUE TITLE
dials.show should show something about the stills_process pickle

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#497]
`dials.stills_process` appears to spit out (amongst others) `idx-*_strong`, `idx-*_integrated`, `idx-*_indexed` and then an `int-*.pickle` files. 

It'd be nice if `dials.show` could be extended to show some useful information about these latter `int-*.pickle` files; at the moment it just ~~crashes with an obtuse error~~ does nothing (thanks Richard).

**Comment by rjgildea** [comment]
`dials.show` is intended to show information about relevant `dxtbx` objects (i.e. detector, beam, scan, goniometer, crystal, reflections). The pickle files output by dials.stills_process appears to contain none of this information. It is read by the `dxtbx` format class `FormatPy.py`, but the resulting datablock object appears to contain absolutely no useful information (i.e. no dxtbx models, no data, no nothing).

**Comment by rjgildea** [comment]
I.e. there is currently no way to get hold of any useful information from the pickle file inside dials.show, as the pickle file is swallowed up by the format class, losing all potentially useful information along the way.

**Comment by phyy-nx** [comment]
Hi folks, the int pickles produced by dials.stills_process are inputs to cxi.merge and PRIME. cxi.print_pickle can be used to show their contents. These pickles are not dxtbx files.  We needed some way to store integrated information from xfels before dxtbx was available. 

If FormatPy tries to understand them I doubt that’s on purpose.

One of these days, will make it so our merging programs can read dials output natively, which will obsolete these files.

I don’t think there’s any need for dials.show to read these.  Thanks,
-Aaron

**Comment by ndevenish** [comment]
I merely observed:
- User runs **dials**.stills_process
- User gets assortment of pickle files
- User tries to run **dials**.show on pickle files
- User gets sad - this normally works on pickle files!

It's a user interface issue regardless of if there is a complex technical reason behind it ("it's not a pickle file, it's a dxtbx file, but there is no way for you to know that"), or priority. "This is not a supported file" is more useful to the user than a stack trace, obscure `repr` output, or the reply "You are holding it wrong".

But I see this is tied to the long-standing issue and many related problems of the "throw and see what sticks" file parsing we use, so obviously it's not important enough to fix.
