### ISSUE TITLE
Setting seed in dials.search_beam_position

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#501]
Wondering about this:
https://github.com/dials/dials/commit/827a47baf2dc8db892bebe9fa497c8e1423e2b2b

Q1: should this be there? Why?

Q2: should this be at the file level? I would not necessarily expect this behaviour from ```import dials.command.search_beam_position```.

**Comment by Anthchirp** [comment]
thanks for Q2. Still not sure what the point of it is though :)

**Comment by rjgildea** [comment]
So that the results are reproducible between program runs - the simplex minimisation algorithm uses a random starting point (we also use a random subset of reflections for analysis). You can now set seed=None to have a random random seed
