### ISSUE TITLE
dials.import doesn't work well with large numbers of images

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#504]
e.g. Graeme's import of 100k images hung for three hours. We should check to see what's taking so long with this and if there's anything obvious we can do to fix it.

**Comment by dagewa** [comment]
Something to look at as part of "performance week"?

**Comment by ndevenish** [comment]
I did have a mostly working branch of improvements to this is https://github.com/ndevenish/cctbx_project/tree/fasterimport - but it got hit by the move of dxtbx (easy) and the switch to ExperimentList (harder).

Also, loading from template (e.g. only reading metadata from first image) worked around this, as does reading from H5 files (because it was lots of redundant IO/access), so it workable around in many cases.

**Comment by ndevenish** [comment]
heat death issue \o/ should have been mostly solved by ImageSequences
