### ISSUE TITLE
Do something about tests not included in runner

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#506]
After running a quickly whipped together [find_missing_tests.py](https://gist.github.com/ndevenish/279d0b74860587ae9327199fa33d9ae5) there appear to be 17 tests named `tst_*.py` that are not run with `run_tests.py`. These are:
* [x] test/tst_libtbx_import.py
* [x] test/algorithms/background/tst_normal_discriminator.py
* [ ] test/algorithms/background/tst_background_subtraction.py
* [ ] test/algorithms/reflection_basis/tst_rebin_pixels.py
* [ ] test/algorithms/integration/tst_shoebox_flattener.py
* [ ] test/algorithms/integration/tst_interpolate_profile2d.py
* [x] test/algorithms/integration/profile/tst_profile_helpers.py
* [ ] test/algorithms/integration/profile/tst_stereographic_projection_sampler.py
* [x] test/algorithms/symmetry/tst_origin.py
* [x] ~~test/algorithms/refinement/tst_centroid_analysis.py~~
* [x] ~~test/algorithms/refinement/tst_goniometer_parameters.py~~
* [x] test/algorithms/indexing/tst_index_synthetic.py
* [x] test/algorithms/peak_finding/tst_merge_spot_lists.py
* [ ] test/command_line/tst_compare.py
* [x] test/command_line/tst_hot_pixel_mask_to_xy.py
* [x] framework/dftbx/tst_dftbx.py
* [x] ~~algorithms/refinement/analysis/tst_vs_R.py~~

These should either be removed, added to the test runner, or ported to pytest.

As a start: `tst_libtbx_import.py` appears to have been added in 56f344a573005828419ddb923c0e14d4ec5204ee and then removed from running a day later in 89b7a96ab69292fa9a5e46d115c8cba1080d14fd. Do you remember the original purpose/whether still needed @Anthchirp ?

Possible solution: Add them all, and remove/fix as breakages occur (which they will)

**Comment by Anthchirp** [comment]
[test/algorithms/integration/profile/tst_stereographic_projection_sampler.py](https://github.com/dials/dials/blob/master/test/algorithms/integration/profile/tst_stereographic_projection_sampler.py) is an interactive test only. @jmp1985, do you want to keep this?

**Comment by Anthchirp** [comment]
suggest splitting this issue up into individual issues, assigning them to whoever is responsible for the file.

**Comment by ndevenish** [comment]
I've made separate tickets for all of these remaining now, so closing this.
