### ISSUE TITLE
Use message pack not pickle for reflection data

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#512]
https://msgpack.org/index.html

**Comment by graeme-winter** [comment]
More future proof... and more secure

**Comment by graeme-winter** [comment]
Security:

http://www.benfrederickson.com/dont-pickle-your-data/

**Comment by graeme-winter** [comment]
implement to / from message pack in reflection table, then work out whether we want to use it (should be fairly cheap)

**Comment by graeme-winter** [comment]
This is all going on in https://github.com/dials/dials/pull/535

**Comment by Anthchirp** [comment]
We now support this. Set to become default in DIALS 2.0

**Comment by dagewa** [comment]
@nksauter requests that support for historical data in .pickle format is retained in future versions of DIALS. Given the security concerns, we cannot do this automatically. Two possibilities that would be acceptable:

1. Add something like `allow_read_pickle=True` parameters so the user takes responsibility for reading a legacy format
2. Provide a pickle-->mpack converter

These are longer-term future concerns, but noting now as agreed today to avoid deprecating pickle entirely.

**Comment by graeme-winter** [comment]
Converter probably better solution in long game as will allow working with p3, unlike pickle...

**Comment by dagewa** [comment]
#535 superseded by #783
