### ISSUE TITLE
dials.image_viewer impossibly slow on nexus files

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#514]
Steps to reproduce:
1. ```dials.image_viewer /dls/mx/data/cm19647/cm19647-1/processing/gw/je_01/datablock.json```
2. Wait for 10 minutes.

**Comment by ndevenish** [comment]
This should be much better with 14523490e6bad11946afb12e44870688080134ef, though still seems to be some slowness, so still WIP

**Comment by Anthchirp** [comment]
anecdotes:
DIALS 1.8.6 with attached ```strace -tye trace=open```:
* 7 minutes sleep before window appears
* 3 minutes sleep before window is drawn
* total time start to drawn window: 10 minutes 20 seconds

with patch:
* 8 minutes sleep before window appears
* total time start to drawn window: 8 minutes 55 seconds

**Comment by ndevenish** [comment]
This should be mostly fixed, though the datablock loading-time remains a small but noticeable delay on startup.

**Comment by Anthchirp** [comment]
Thank you

(fyi: If you use the words "closes #514" or "fixes #514" or "resolve #514" ... in the commit message github will automatically close the ticket)

**Comment by Anthchirp** [comment]
DIALS 1.9.0:
* 4 second sleep followed by an 11 second sleep before window appears and is drawn
* total time start to drawn window: 27 seconds

Well done.

**Comment by ndevenish** [comment]
I know but couldn’t make the sentence work 😊

I think the Datablock parsing might be able to be cut down (n² lookup possibly) but otherwise might have to just be “Please wait” if the file looks large.
