### ISSUE TITLE
dials.image_viewer doesn't update when selecting "show mask"

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#520]
```
$ module load dials/1.9
$ dials.import /dls/i03/data/2017/cm16791-5/20171122/protk/shadowing_chi30/protk_2_100*.cbf
$ dials.image_viewer datablock.json
```
1) Click on "show mask" checkbox, mask doesn't appear.
2) Move image slider, mask then appears.

Using dials/1.8 the mask appears as soon as "show mask" is selected.

**Comment by ndevenish** [comment]
This should have fixed it (and added to patch branch) - If you get a chance @rjgildea I'd appreciate checking e.g. the mask tool - I've never quite understood how to use it and what should/shouldn't give visual output.
