### ISSUE TITLE
DIALS optionparser dies on empty .phil file

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#522]
```bash
SOMEIMAGE=~/local/testsets/TestsetMX/2A4_1_0001.cbf
# just some importable example file

dials.import $SOMEIMAGE # this works
echo verbosity=2 > extra.phil
dials.import $SOMEIMAGE extra.phil # this works
echo > extra.phil # 1 byte file containing a single newline
dials.import $SOMEIMAGE extra.phil # this works
echo -n > extra.phil # 0 byte file
dials.import $SOMEIMAGE extra.phil # boom
```
```
Sorry: Unable to handle the following arguments:
```

**Comment by Anthchirp** [comment]
Apparently this is due to the following logic:
* optionparser tests whether a file is a json by trying to import is as json
* any phil file will fail, so is not a json
* anything that is not json is phil
* 1 byte file fails, so is not a json, so is phil => all good
* 0 byte file succeeds, because is valid json, so is not phil (doesn't matter on phil side)
* but if file == json then expect some content, thus boom

**Comment by graeme-winter** [comment]
Option parser should ignore empty files then?

**Comment by graeme-winter** [comment]
Not obvious what we would define as the correct behaviour...

**Comment by Anthchirp** [comment]
proposed solution
* if file ends in .json then try to parse it as JSON. if fails then fall over crying
* if file ends in .phil then try to parse it as PHIL, if fails then fall over crying
* if file ends in neither .json nor .phil then fall over crying (or do something different)

**Comment by ndevenish** [comment]
Another potential solution, with bc6f4c197db35e72d6c8e4c406997fcbc56fb3d7, would be to require that PHIL files are always passed in via the `--phil` parameter?

**Comment by dagewa** [comment]
Updating the example for the modern age:
```bash
SOMEIMAGE=$(dials.data get -q centroid_test_data)/centroid_0001.cbf
# just some importable example file

dials.import $SOMEIMAGE # this works
echo output.experiments=foo.json > extra.phil
dials.import $SOMEIMAGE extra.phil # this works
echo > extra.phil # 1 byte file containing a single newline
dials.import $SOMEIMAGE extra.phil # this works
echo -n > extra.phil # 0 byte file
dials.import $SOMEIMAGE extra.phil # boom
```

After fixing a couple of traps in `Format` classes, the example again fails with
```
Sorry: Unable to handle the following arguments:
```

**Comment by ndevenish** [comment]
```
$ dials.import $SOMEIMAGE extra.phil
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1549-gaa0ee89a6
Sorry: Unable to handle the following arguments:
  extra.phil
```
