### ISSUE TITLE
Slider based interface performs poorly

### ISSUE THREAD

**Issue by nksauter** [dials/dials#527]
Recently a new image-selection widget was implemented in dials.image_viewer, using a slider-based widget to replace the ComboBox.  In my hands the slider is poorly performing.  Suppose there are 2000 images and I want to go to a specific number, say 734.  In this use case, it is near impossible to drag the slider to the exact image number desired.  Instead, I have to go to the approximate sequence number and then use the Prev and Next buttons to select 734.  So a single combobox operation is replace with many key clicks.  It would help if user could type in the exact image number wanted (by adding a new widget to the menu bar).  --Nick Sauter

**Comment by ndevenish** [comment]
There is a text box explicitly for this purpose, to the right of the next/previous buttons. Is that not functioning?

**Comment by ndevenish** [comment]
In addition; the combo box was explicitly slowing down the UI; those things weren’t designed for thousands of entries. In what way is the slider causing poor performance? Or do you just mean UI ‘ease-of-use’?

**Comment by graeme-winter** [comment]
Just reading through a few tickets - catching up - @nksauter is this still a problem for you?

![screen shot 2018-04-19 at 13 35 12](https://user-images.githubusercontent.com/1241716/38991730-8f6691e2-43d6-11e8-961d-d25456025cd7.png)

**Comment by nksauter** [comment]
Graeme,

The slider is OK for many use cases, but not for the case where the user
provides a heterogeneous list of file names.  In this case, I'd like the
choice box as it was before.  Ideally, the viewer could switch it's control
widget depending on the context.

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Nick

Understood now

One issue with that was that it meant loading an eiger data set with 100,000 images could take 30 minutes before showing an image

If we can have loading in finite time and a pull down for your use case simultaneously that would be great

I’m not sure they’re compatible though...

Cheers Graeme

**Comment by graeme-winter** [comment]
OK, discussed with @ndevenish - propose adding a "list" button which will pop up a window, where you can scroll and select a filename - this will remain open so you can click on other windows.

**Comment by graeme-winter** [comment]
"A wx.ListBox widget is used for displaying and working with a list of items. As its name indicates, it is a rectangle that has a list of strings inside. We could use it for displaying a list of MP3 files, book names, module names of a larger project or names of our friends. A wx.ListBox can be created in two different states: In a single selection state or a multiple selection state. The single selection state is the default state. There are two significant events in wx.ListBox. The first one is the wx.EVT_COMMAND_LISTBOX_SELECTED event. This event is generated when we select a string in a wx.ListBox. The second one is the wx.EVT_COMMAND_LISTBOX_DOUBLE_CLICKED event. It is generated when we double click an item in a wx.ListBox. The number of elements inside a wx.ListBox is limited on GTK platform. According to the documentation, it is currently around 2000 elements. The elements are numbered from zero. Scrollbars are displayed automatically if needed."

Limiting to around 2000 elements - likely to be a blocker?

**Comment by graeme-winter** [comment]
Seems a non-issue on OS X - got to 300,000 elements without it slowing down, construction took ~ 3s:

```
#!/usr/bin/python

# listbox.py

import wx

ID_CLEAR = 1
ID_LOTS = 2

class ListBox(wx.Frame):
    def __init__(self, parent, id, title):
        wx.Frame.__init__(self, parent, id, title, size=(350, 220))

        panel = wx.Panel(self, -1)
        hbox = wx.BoxSizer(wx.HORIZONTAL)

        self.listbox = wx.ListBox(panel, -1)
        hbox.Add(self.listbox, 1, wx.EXPAND | wx.ALL, 20)

        btnPanel = wx.Panel(panel, -1)
        vbox = wx.BoxSizer(wx.VERTICAL)
        clr = wx.Button(btnPanel, ID_CLEAR, 'Clear', size=(90, 30))
        lts = wx.Button(btnPanel, ID_LOTS, 'Lots', size=(90, 30))

        self.Bind(wx.EVT_BUTTON, self.OnClear, id=ID_CLEAR)
        self.Bind(wx.EVT_BUTTON, self.OnLots, id=ID_LOTS)

        vbox.Add((-1, 20))
        vbox.Add(clr)
        vbox.Add(lts, 0, wx.TOP, 5)

        btnPanel.SetSizer(vbox)
        hbox.Add(btnPanel, 0.6, wx.EXPAND | wx.RIGHT, 20)
        panel.SetSizer(hbox)

        self.Centre()
        self.Show(True)

    def OnClear(self, event):
        self.listbox.Clear()

    def OnLots(self, event):
        for j in range(1000):
            text = "frame_%05d.cbf" % j
            self.listbox.Append(text)

        
app = wx.App()
ListBox(None, -1, 'ListBox')
app.MainLoop()


```

gives something like


<img width="462" alt="screen shot 2018-04-20 at 14 56 40" src="https://user-images.githubusercontent.com/1241716/39055023-0c980e1e-44ab-11e8-9030-b8d2cc34a23a.png">

**Comment by biochem-fan** [comment]
Also fine with 300K elements on Scientific Linux 7.0.

**Comment by graeme-winter** [comment]
BTW, I am not suggesting that we _actually use_ this code, more was a few minute demo that it would be _a_ direction we could look in...
