### ISSUE TITLE
dials.reciprocal_lattice_viewer freezes when increasing marker size

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#53]
Steps to reproduce:
1. start dials.reciprocal_lattice_viewer with json and pickle file
2. do not click anywhere else in the GUI
3. click on the increase marker size arrow
4. dials.reciprocal_lattice_viewer freezes

(5. sometimes it recovers after a while, sometimes it does not.)

**Comment by graeme-winter** [comment]
This does not appear to be limited to NX operation BTW.

**Comment by graeme-winter** [comment]
Offending example was datablock and strong in /dls/tmp/abn41727/dir-hwV16 - seems to work OK on my box tho :(
