### ISSUE TITLE
Banner causes trouble in tutorials

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#533]
https://dials.github.io/documentation/tutorials/processing_in_detail_betalactamase.html

**Comment by ndevenish** [comment]
I have a fix for this, combined with making the extraction of sub-sections more robust, in https://github.com/ndevenish/dials/commit/8b86dfe675434fe86774f81bf8199edd184dcb21 - but it currently uses Sphinx 1.5, 1.6 features, so needs https://github.com/cctbx/cctbx_project/pull/169 to be accepted.

**Comment by Anthchirp** [comment]
sphinx update has landed, so this can now be deployed?

**Comment by Anthchirp** [comment]
merging, let's see what happens
