### ISSUE TITLE
dials.image_viewer: Display -2 as "masked" occurs for non-Pilatus images

### ISSUE THREAD

**Issue by dagewa** [dials/dials#536]
An example is in the backstop region of this image:
```
dials.image_viewer $(libtbx.find_in_repositories dials_regression)/image_examples/ESRF_BM14/mar225_1_001.mccd
 ```
![mask_marccd](https://user-images.githubusercontent.com/11502083/38770507-f348e9ea-400b-11e8-95fd-1d33ad5b7d5c.png)

For those with access, the images in `/dls/mx-scratch/rjgildea/fisher/013_021_G4` are worse, with many "masked" pixels across the image

**Comment by rjgildea** [comment]
This is a known thing, and I'm not sure a fix is possible without a significant reworking of how the display is handled in the FlexImage class:
https://github.com/cctbx/cctbx_project/blob/master/iotbx/detectors/display.h#L236

**Comment by dagewa** [comment]
I wonder if @nksauter would like to comment? Why do we need special code to display -2 as masked anyway? Shouldn't the masked pixels be defined by the mask?

**Comment by rjgildea** [comment]
The code in FlexImage long-predates dxtbx and image masks (and also Pilatus detectors) - judging by labelit svn logs it dates back to 2004.

**Comment by dagewa** [comment]
I haven't yet tried it, but I thought for a simple fix that this line: https://github.com/cctbx/cctbx_project/blob/master/iotbx/detectors/display.h#L199 
should instead be
`bool has_pilatus_inactive_flag = false;`
and then it is set `true` individually for DECTRIS detectors based on `vendortype` and then doesn't end up true for e.g. CCD datasets

**Comment by rjgildea** [comment]
Yes, but then it won't be possible to view image masks for CCD images. The problem is that the image viewer is (ab)using the functionality in FlexImage flagging the special Pilatus -2 pixels in order to display dxtbx image masks.

**Comment by graeme-winter** [comment]
I would definitely say that @nksauter would hold an opinion here as clearly this must also be a problem for pedestal subtracted CSPAD images…. 

Properly supporting the concept of a mask not derived from pixel values seems like a good idea…

**Comment by rjgildea** [comment]
https://github.com/dials/dials/blob/42fcf5ff99de386d37c0390407dfc06d20a322c4/util/image_viewer/spotfinder_frame.py#L1077-L1080

**Comment by dagewa** [comment]
I made the change anyway to see what happens. I defined a rectangular mask, imported with that then viewed in the image viewer. When "Show mask" is selected the -2 valued pixels are no longer red, and the masked region becomes white.
![mask](https://user-images.githubusercontent.com/11502083/38821653-0c7d9a30-4199-11e8-9548-9693f65b5028.png)

**Comment by dagewa** [comment]
Original code gets the red coloured mask, which is obviously better, but has the spurious -2 pixels "masked" as well.
![mask2](https://user-images.githubusercontent.com/11502083/38823080-5256075a-419d-11e8-95ff-33e957fae8c8.png)

**Comment by rjgildea** [comment]
Presumably they are only appearing as white because of the code above that sets the masked pixels to -2, and -2 is a "small number", so the display is set to white (or close to white) for those pixels (with that colour scheme).

**Comment by nksauter** [comment]
I'd like the opportunity to work on this problem, so that we can account
for both the Pilatus inactive pixels, and the possibility of displaying
masks separately.  Realistically my first opportunity to even think about
the problem would be during the week of May 6.  If we can hold the issue
open till then I'll have a look.

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by dagewa** [comment]
Hi @nksauter, I don't think any of us are going to touch this until you have a chance to take a look. Thanks.

**Comment by dagewa** [comment]
See also https://github.com/cctbx/cctbx_project/issues/49

**Comment by dagewa** [comment]
Just noting that I get problems with this particularly with electron diffraction datasets where there may be genuine negative-valued pixels. I'd like to see what the values are, but of course the image viewer always tells me they are -2.
