### ISSUE TITLE
4K screen issues on Linux

### ISSUE THREAD

**Issue by dagewa** [dials/dials#541]
A few warts for Linux users with 4K screens: slider height and width, menu titles ("Settings"), width of some fields ("find_spots.phil")

![4k_issues](https://user-images.githubusercontent.com/11502083/39050915-0909b876-449f-11e8-9aa5-0de379cea3d7.png)

**Comment by graeme-winter** [comment]
It's interesting that this problem is limited to linux (or at least, not a problem on OS X) 

When I am running on a 4k screen everything _seems_ fairly sensible...

**Comment by dagewa** [comment]
Well, to be fair, it is not necessarily Linux, but Ubuntu/Unity that has
poor HiDPI support here
