### ISSUE TITLE
Windows build instructions out of date

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#547]
The Windows build instructions look to be horrendously out of date. Either they need updating, or removing entirely.

https://dials.github.io/documentation/installation_developer.html#build-dials-windows

"Installing DIALS from SVN on Windows" (SVN - haha!)

**Comment by Anthchirp** [comment]
This looks more useful:
https://github.com/cctbx/cctbx_project/wiki/How-to-build-CCTBX-on-Windows

**Comment by Anthchirp** [comment]
Rob's email at https://github.com/dials/dials/issues/135#issuecomment-217848199 contains some useful information.

**Comment by Anthchirp** [comment]
Out-of-date instructions are no longer on said page.
