### ISSUE TITLE
Make images in dials.image_viewer more viewable

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#55]
(ticket for myself)

User complained, particularly on low-count I-19 images that viewing images with dials.image_viewer is not particularly easy. Investigate what can be done about this.

**Comment by graeme-winter** [comment]
Please can you add accumulate spots if sum images

**Comment by rjgildea** [comment]
@graeme-winter: does this help?
dials.image_viewer datablock.json sum_images=10 (e.g.)

**Comment by graeme-winter** [comment]
Yes but need spot list accumulated too

**Comment by Anthchirp** [comment]
Original bug fixed with https://sourceforge.net/p/cctbx/code/24040/

**Comment by Anthchirp** [comment]
To see the patch in action have a look at these [before](http://s23.postimg.org/4xmxn8jrv/Screenshot_1.png) and [after](http://s9.postimg.org/je4tk2d4f/Screenshot.png) images.
