### ISSUE TITLE
Filtering of non-profile-fitted intensities in export_mtz

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#555]
In dials.export_mtz we currently only export reflections that succeeded in both profile fitting and summation integration, i.e. any reflections that failed in profile fitting but do have summation integrated intensities are removed:

https://github.com/dials/dials/blob/master/util/export_mtz.py#L221

Is this the correct thing to do? Should we not be exporting all reflections that have either a profile-fitted or summation integrated intensity?

**Comment by dagewa** [comment]
This is why Marcus Fischer got a badly incomplete dataset before the profile fitting fixes. At least it flagged the problem there, but I think it isn't the right thing to do in general.

**Comment by rjgildea** [comment]
See also https://github.com/dials/dials/issues/15

**Comment by graeme-winter** [comment]
Discussing this now - I propose:

 - if we have a missing value we write CCP4 MNF in there

Opinions?

**Comment by dagewa** [comment]
Fixed by #396, and less important in the modern age anyway, as we are now most likely to export the _scaled_ intensities.
