### ISSUE TITLE
clean up dials_regression tests

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#557]
Currently there is a test in ```dials_regression``` that fails on Windows. ```dials_regression``` still has monolithic tests which makes it difficult to figure out what exactly is going wrong - especially when not debugging directly on a Windows machine. (I run automated build tests on a Windows machine but do not have direct access to it.)

I would like to rewrite the tests so that they follow the same structure as the dxtbx tests, ie.
* split the one big test running over many images into many small tests running on one image each

and, as part of that work,
* retire ```quick_test.sh``` (as far as I can tell this is @dagewa's private test script and probably not used by anyone else)
* clean up ```run_tests.py```
* convert all tests to pytest
* complete any obvious Python3 remedial work

Let me know if there are any objections, otherwise I will look into this after we branched DIALS 1.10 (#519, aiming for next week).

**Comment by graeme-winter** [comment]
More fine-grained tests here would be welcome thank you.

**Comment by dagewa** [comment]
`quick_test.sh` is ancient and can go. I assume no one else uses this, as nobody complained after I last edited it

**Comment by nksauter** [comment]
- clean up run_tests.py
   - convert all tests to pytest

Please hold off on this until the Berkeley group buys in to the use
of pietist.

Sauter

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
@bkpoon @nksauter @Anthchirp @ndevenish @phyy-nx did you guys arrange a catch up to discuss properties of pytest? Seems a precondition on Berkeley group buy in.

**Comment by Anthchirp** [comment]
we no longer run these tests
