### ISSUE TITLE
Importing wth dui shows just a piece of the diffraction image

### ISSUE THREAD

**Issue by murpholinox** [dials/dials#558]
![screenshot from 2018-05-17 12-31-23](https://user-images.githubusercontent.com/732802/40196877-ffa6207c-59ce-11e8-9db7-e93cb97f230d.png)

**Comment by graeme-winter** [comment]
Hello

Would it be possible for you to attach a zip file with a single diffraction image in so we can check the behaviour of the underlying dials tools?

Many thanks Graeme

**Comment by murpholinox** [comment]
[d10_001.zip](https://github.com/dials/dials/files/2014404/d10_001.zip)

**Comment by murpholinox** [comment]
You can close this issue. It was related to the diffraction image being compressed as `*.bz2`. Happens the same with the `dials.image_viewer`. So before importing any files you have to decompress them.

**Comment by murpholinox** [comment]
I used the parallel version of `bzip2` (i.e. `pbzip2`). This is not installed by default (at least not in Fedora). Maybe there's something special about it. Although the images compresses as `.bz2` worked fine with XDSGUI.

**Comment by graeme-winter** [comment]
Oh, OK - could be that the compression format that pbz2 makes is different enough that the Python bz2 module does not read the images correctly. XDS / XDSGUI uses the command line bzip2 which would probably cope...
