### ISSUE TITLE
Spot finding is not good enough, not even changing min_spot_size

### ISSUE THREAD

**Issue by murpholinox** [dials/dials#559]
As suggested here http://dials.diamond.ac.uk/documentation/getting_started.html, changing min_spot_size to 6 is not useful for spot finding.
Ps. The images were taken in the beam line X6A at the National Synchrotron Laboratory Source (NSLS), Brookhaven, on a 2k × 2k CCD detector (ADSC). Very old images. 
`[murph@localhost d01]$ dials.find_spots min_spot_size=6 datablock.json`
(I will show only the list)
Found 81 strong pixels on image 1
Found 44 strong pixels on image 2
Found 37 strong pixels on image 3
Found 22 strong pixels on image 4
Found 10 strong pixels on image 5
Found 12 strong pixels on image 6
Found 26 strong pixels on image 7
Found 13 strong pixels on image 8
Found 30 strong pixels on image 9
Found 8 strong pixels on image 10
Found 14 strong pixels on image 11
Found 21 strong pixels on image 12
Found 29 strong pixels on image 13
Found 40 strong pixels on image 14
Found 20 strong pixels on image 15
Found 11 strong pixels on image 16
Found 40 strong pixels on image 17
Found 25 strong pixels on image 18
Found 13 strong pixels on image 19
Found 14 strong pixels on image 20
Found 8 strong pixels on image 21
Found 23 strong pixels on image 22
Found 14 strong pixels on image 23
Found 27 strong pixels on image 24
Found 24 strong pixels on image 25
Found 13 strong pixels on image 26
Found 16 strong pixels on image 27
Found 40 strong pixels on image 28
Found 20 strong pixels on image 29
Found 57 strong pixels on image 30
Found 60 strong pixels on image 31
Found 47 strong pixels on image 32
Found 34 strong pixels on image 33
Found 40 strong pixels on image 34
Found 21 strong pixels on image 35
Found 18 strong pixels on image 36
Found 8 strong pixels on image 37
Found 27 strong pixels on image 38
Found 85 strong pixels on image 39
Found 62 strong pixels on image 40
Found 77 strong pixels on image 41
Found 87 strong pixels on image 42
Found 28 strong pixels on image 43
Found 30 strong pixels on image 44
Found 78 strong pixels on image 45
Found 107 strong pixels on image 46
Found 124 strong pixels on image 47
Found 57 strong pixels on image 48
Found 53 strong pixels on image 49
Found 22 strong pixels on image 50
Found 35 strong pixels on image 51
Found 46 strong pixels on image 52
Found 43 strong pixels on image 53
Found 33 strong pixels on image 54
Found 18 strong pixels on image 55
Found 30 strong pixels on image 56
Found 75 strong pixels on image 57
Found 24 strong pixels on image 58
Found 24 strong pixels on image 59
Found 16 strong pixels on image 60
Found 25 strong pixels on image 61
Found 16 strong pixels on image 62
Found 17 strong pixels on image 63
Found 7 strong pixels on image 64
Found 2 strong pixels on image 65
Found 4 strong pixels on image 66
Found 2 strong pixels on image 67
Found 6 strong pixels on image 68
Found 5 strong pixels on image 69
Found 8 strong pixels on image 70
Found 1 strong pixels on image 71
Found 5 strong pixels on image 72
Found 3 strong pixels on image 73
Found 8 strong pixels on image 74
Found 0 strong pixels on image 75
Found 0 strong pixels on image 76
Found 12 strong pixels on image 77
Found 7 strong pixels on image 78
Found 0 strong pixels on image 79
Found 1 strong pixels on image 80
Found 2 strong pixels on image 81
Found 1 strong pixels on image 82
Found 0 strong pixels on image 83
Found 0 strong pixels on image 84
Found 3 strong pixels on image 85
Found 4 strong pixels on image 86
Found 0 strong pixels on image 87
Found 9 strong pixels on image 88
Found 3 strong pixels on image 89
Found 13 strong pixels on image 90
Found 3 strong pixels on image 91
Found 0 strong pixels on image 92
Found 10 strong pixels on image 93
Found 2 strong pixels on image 94
Found 0 strong pixels on image 95
Found 5 strong pixels on image 96
Found 2 strong pixels on image 97
Found 2 strong pixels on image 98
Found 11 strong pixels on image 99
Found 2 strong pixels on image 100
....
Saved 101 reflections to strong.pickle
Time Taken: 33.685535

**Comment by murpholinox** [comment]
Same thing here. After decompressing the diffraction images, the spot finder works! :+1: 
Here is the list updated (only showing first five lines) 
Found 17036 strong pixels on image 1
Found 16316 strong pixels on image 2
Found 16768 strong pixels on image 3
Found 16758 strong pixels on image 4
Found 15787 strong pixels on image 5

**Comment by murpholinox** [comment]
Same thing here. After decompressing the diffraction images, the spot finder works! :+1: 
Here is the list updated (only showing first five lines) 
Found 17036 strong pixels on image 1
Found 16316 strong pixels on image 2
Found 16768 strong pixels on image 3
Found 16758 strong pixels on image 4
Found 15787 strong pixels on image 5

**Comment by murpholinox** [comment]
Yup.

**Comment by graeme-winter** [comment]
OK, I think there must be something special with pbz2 - your original image

```
Finding spots in image 1 to 1...
Setting chunksize=1
Extracting strong pixels from images
 Using multiprocessing with 1 parallel job(s)

Found 15840 strong pixels on image 1

Extracted 1538 spots
Removed 688 spots with size < 6 pixels
Removed 0 spots with size > 100 pixels
Calculated 850 spot centroids
Calculated 850 spot intensities
Filtered 840 of 850 spots by peak-centroid distance

Histogram of per-image spot count for imageset 0:
840 spots found on 1 image
```

compressed with OS X bzip2

```
Finding spots in image 1 to 1...
Setting chunksize=1
Extracting strong pixels from images
 Using multiprocessing with 1 parallel job(s)

Found 15840 strong pixels on image 1

Extracted 1538 spots
Removed 688 spots with size < 6 pixels
Removed 0 spots with size > 100 pixels
Calculated 850 spot centroids
Calculated 850 spot intensities
Filtered 840 of 850 spots by peak-centroid distance

Histogram of per-image spot count for imageset 0:
840 spots found on 1 image
```

=> literally identical as expected.

**Comment by Anthchirp** [comment]
I can confirm this is a format difference

**Comment by graeme-winter** [comment]
@dagewa points out 

https://docs.python.org/2/library/bz2.html#de-compression-of-files

"Note This class does not support input files containing multiple streams (such as those produced by the pbzip2 tool). When reading such an input file, only the first stream will be accessible. If you require support for multi-stream files, consider using the third-party bz2file module (available from PyPI). This module provides a backport of Python 3.3’s BZ2File class, which does support multi-stream files."

Guess we could try importing this as bz2 module and if fails, import the vanilla => end user could pip install...

**Comment by Anthchirp** [comment]
with this patch and pypi module bz2file installed it works.
This is also fixed on Python3 without any extra dependencies required there.
