### ISSUE TITLE
publications page broken

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#568]
https://dials.github.io/publications.html
* 4th paper listed as _DIALS_ instead of correct title
* ```[PMID:(...)]``` is just noise and serves no purpose
* ```[PMC reprint:(...)]``` is mostly noise, reformat

**Comment by Anthchirp** [comment]
Dates should just be years

**Comment by phyy-nx** [comment]
Don't drop PMID or PMC reprint IDs.  Useful for funding.

Thanks

**Comment by nksauter** [comment]
Berkeley prefers the current style (Pubmed)


Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by Anthchirp** [comment]
Error in title is in upstream database, not because of parsing

**Comment by graeme-winter** [comment]
@Anthchirp thanks for following up on the original issue, i.e. the title of the DIALS background modelling paper (which looks on _our_ web pages like the main reference, because of this mangled formatting)

Since this is a bug in biopython I guess we need it to be fixed upstream then updated? There is no way we can fix our own page source here? 😕strikes me as not ideal

**Comment by nksauter** [comment]
Nevertheless we need the PMID and PMCID for NIH funding compliance.
Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by rjgildea** [comment]
@graeme-winter the main link from the article title takes you directly to the publisher's URL (via the doi.org). I suppose it's also a question of whether this publications page is mainly intended for _users_ or to satisfy funding bodies?

**Comment by nksauter** [comment]
Richard & Graeme,

I'm asking you to drop the issue please.

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Ok, the titles continue to be wrong, which causes confusion, but will close based on instruction

**Comment by nksauter** [comment]
I've opened a trouble ticket with IUCr regarding the improper listing of
the article as "DIALS" instead of "Robust background modelling in DIALS."

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
![screen shot 2018-09-07 at 08 02 59](https://user-images.githubusercontent.com/1241716/45203547-76918980-b274-11e8-91e8-8b7199361866.png)

possibly worth noting that nothing has moved on this? Has side effect that many who were involved with DIALS development particularly at LBL are getting no recognition of their work as people continue to think this paper is the canonical reference.

**Comment by graeme-winter** [comment]
Following up - discussion with @Anthchirp indicates that this is an error in biopython (reminded about comment https://github.com/dials/dials/issues/568#issuecomment-395573415) => workaround may be easier since the text here is not changing?

**Comment by dagewa** [comment]
My view: we just commit the workaround. There is no reason for this to remain an issue for 3 months

**Comment by rjgildea** [comment]
Just working on the workaround now.

**Comment by graeme-winter** [comment]
@rjgildea thanks for the workaround on this one :)
