### ISSUE TITLE
make sure the left side buttons in the GUI should be in a scrollable area 

### ISSUE THREAD

**Issue by luisodls** [dials/dials#57]
The scrollable area solves several problems related to incompatibility between sizes of the GUI and size of the screen . But I am not sure this is the solution for the CLI steps shown as buttons in the left side of the GUI.

**Comment by luisodls** [comment]
If you want to see the source code; look in bzr repo in https://fg.oisin.rc-harwell.ac.uk/

**Comment by dagewa** [comment]
@luisodls  Left side buttons no longer relevant? Assuming I can close this
