### ISSUE TITLE
dials.export_bitmaps broken for I23

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#575]
```
$ dials.export_bitmaps /dls/i23/data/2018/cm19648-3/20180619/scint/test_19_0001.cbf format=jpeg quality=95 binning=4 brightness=60
The following parameters have been modified:

binning = 4
brightness = 60
format = *jpeg png tiff
jpeg {
  quality = 95
}
input {
  datablock = <image files>
}

Sorry: Currently only single panel detectors are supported by dials.export_bitmaps
```
original issue: https://jira.diamond.ac.uk/browse/SCI-7471

**Comment by rjgildea** [comment]
Not broken as such, just doesn't support them. The issue is the same as in https://github.com/dials/dials/issues/304 - dxtbx doesn't currently have a mechanism to describe how to map a multi-panel detector on to a 2d plane.

**Comment by graeme-winter** [comment]
This is true, however we know the list of such things is short so would not be beyond the wit of man to hard code something, or add a map_to_2d() method or something to multi-panel detectors?

**Comment by rjgildea** [comment]
Yes, but no one has bothered enough to actually do it in the last 18 months! I would definitely be against hard-coding things, and adding a method in dxtbx format class, which could be used by the image viewer, export_bitmaps, report plotting, etc.

**Comment by graeme-winter** [comment]
@rjgildea acknowledged

**Comment by Anthchirp** [comment]
how does ```dials.image_viewer``` do it?

**Comment by rjgildea** [comment]
Hard coded. This is A Bad Thing.
https://github.com/cctbx/cctbx_project/blame/master/rstbx/slip_viewer/tile_generation.py#L135
