### ISSUE TITLE
dials.predict is slow

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#585]
Running this on a test cluster node:
```bash
time dials.import /dls/i19-1/data/2018/mt18953-1/wx14155/wx141155_01_0*.cbf
time dials.find_spots datablock.json nproc=20
time dials.index datablock.json strong.pickle
time dials.create_profile_model experiments.json indexed.pickle
```

Times:
- import: 23s
- spot finding: 14s
- indexing: 33s
- profile modelling: 3 minutes

```
The following parameters have been modified:

input {
  experiments = experiments.json
  reflections = indexed.pickle
}

Processing reference reflections
 read 45534 strong spots
 removing 25325 unindexed reflections
 removing 5363 reflections marked as centroid outliers
 using 14846 indexed reflections
 found 30688 junk reflections
 time taken: 0.016726
 masked neighbouring pixels in 41 shoeboxes

================================================================================

Predicting reflections

Prediction type: scan static prediction
Predicted 683784 reflections
Matching reference spots with predicted reflections
 14846 observed reflections input
 683784 reflections predicted
 14802 reflections matched
 14802 reflections accepted

********************************************************************************
Warning: 44 reference spots were not matched to predictions
********************************************************************************

Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.050150 degrees
 sigma m: 0.408176 degrees
Sigma B: 0.050150
Sigma M: 0.408176
Wrote experiments to experiments_with_profile_model.json...................0.01s
```

**Comment by Anthchirp** [comment]
By request of @rjgildea:
```time dials.create_profile_model indexed.pickle experiments.json``` on same ```indexed.pickle``` and ```experiments.json``` created by DIALS 1.5 takes

| version | time |
|-----|-------------------|
| 1.5 | 20.7 seconds |
| 1.7 | 41.7 seconds |
| 1.10 | 258 seconds |

**Comment by Anthchirp** [comment]
looks like the time mostly goes into ```dials.predict``` [```experiments.json```](https://github.com/dials/dials/files/2137655/experiments.json.txt)

| version | time |
|-----|-------------------|
| 1.5 | 11.6 seconds |
| 1.7 | 18.4 seconds |
| 1.10 | 230 seconds |

**Comment by dagewa** [comment]
Could be because of the changes for single image prediction in #452?

**Comment by graeme-winter** [comment]
Discussing with DGW => is using Reeke algorithm => slow? If Reeke to get [hkl] then predict should be OK; if Reeke and predict for _each_ image could be slow?

**Comment by graeme-winter** [comment]
@jmp1985 do you have a comment on this?

**Comment by jmp1985** [comment]
I think the original change to use the Reeke algorithm was to improve performance for single images. Previously, all hkl were predicted and then filtered based on whether they were predicted within the image. The Reeke algorithm I understand should be faster.

**Comment by graeme-winter** [comment]
I think it depends how it is used...

**Comment by jmp1985** [comment]
OK, Looking at the code, it looks like ReekeIndexGenerator is called for each image. Which makes sense in the scan varying case. I guess it could be made more efficient in the static case.

**Comment by dagewa** [comment]
I think index generator called for each, say, 0.5 degree block makes sense,
as long as prediction is then done for all hkls in one go on the
concatenated indices.

For some scan width it'll be faster doing things the old way, but I don't
know at what width that would happen.

Reeke could in principle be done in parallel too.

**Comment by jmp1985** [comment]
For static prediction, can we not just do the index generation once for the whole wedge? Or would that not work?

**Comment by dagewa** [comment]
That wouldn't work for Reeke. It uses the orientation of the crystal wrt the Ewald sphere to come up with an hkl list of relps close to the Ewald sphere in _that_ orientation. So, as the crystal rotates you have to periodically generate new indices close to the sphere.

**Comment by dagewa** [comment]
We are discussing this now in the context of [DUI](https://github.com/ccp4/DUI/issues/8). I think this is a big part of it so I'll take this issue on now.

**Comment by dagewa** [comment]
My intention is to change the index generator calls to one per each 0.5 deg of data rather than once per image, plus also switch over to full sphere index generation at whatever point this proves to be more efficient.

**Comment by dagewa** [comment]
The new method (`ReekeIndexGenerator`) scales with the number of images whereas the old method (`IndexGenerator`) has fairly constant execution time.
![dials predict-timing](https://user-images.githubusercontent.com/11502083/49795153-2cb3b600-fd31-11e8-96c2-a7c5309ceed2.png)

The crossover point for [```experiments.json```](https://github.com/dials/dials/files/2137655/experiments.json.txt) is just over 60 images. I suspect this will be similar for other datasets.

**Comment by dagewa** [comment]
The particular dataset does make a significant difference. For the I04 BAG training data the crossover is at about 140 images. For DPF3 it is about 70 images. For the mosflm tutorial dataset it is about 50 images. This is probably related to fineness of slicing.

**Comment by rjgildea** [comment]
Is it proportional to the prediction width in degrees, rather than images?

**Comment by dagewa** [comment]
The ReekeIndexGenerator version has an explicit loop over images, but I think the slice width is important because it affects what proportion of indices generated at each step will be accepted as predictions or thrown out.

**Comment by dagewa** [comment]
It should be possible to avoid using the `ReekeIndexGenerator` for each image, and using it in small blocks of, say, 0.5° instead†. However, to do this would require a significant refactoring of the current prediction code. That may be best left for another time. For now it is simple enough to switch to `IndexGenerator` prediction at some crossover point. The ideal point varies according to properties of the dataset, but because the `IndexGenerator` approach is 'safe' (it runs in essentially constant time) it makes sense to switch over to that earlier rather than later. I think setting this point to 50 images makes sense for now, until this issue can be revisited in more detail. I have checked the resulting reflection tables from the two methods and apart from difference in sort order they are identical.

†For scan-static prediction, that is. For scan-varying prediction the `ReekeIndexGenerator` has to be used separately for each image because **UB_start** and **UB_end** differ.

**Comment by Anthchirp** [comment]
```dials.predict``` user times:

| version | time |
|-----|-------------------|
| 1.5.1 | 7.6 seconds |
| 1.6.4 | 13.7 seconds |
| 1.7.4 | 12.3 seconds |
| 1.8.6 | 13.6 seconds |
| 1.9.3 | 181.2 seconds |
| 1.10.4 | 162.1 seconds |
| 1.11.0 | 175.0 seconds |
| 1.11.4 | 169.8 seconds |
| 1.12.0 | 164.0 seconds |
| 1.12.3 | 164.2 seconds |
| 1.12.4 | 13.0 seconds |
| 1.12.5 | 13.0 seconds |
| latest | 12.8 seconds |

Confirmed fixed 👍
