### ISSUE TITLE
dials.refine_bravais_settings outlier rejection and speed

### ISSUE THREAD

**Issue by dagewa** [dials/dials#586]
I was thinking about the issue of speed of `dials.refine_bravais_settings` raised at the LMB meeting yesterday. At the moment, `dials.refine_bravais_settings` performs Tukey outlier rejection for each refinement in a different setting. Although this is reasonably quick, it can take a significant portion of the total runtime of a refinement job.

Thinking about it further, outlier rejection might even be problematic for cases where the metric fit and rmsds are rather high. It may be better to initially select only the reflections that were `used_in_refinement` from indexing, and then not do any further outlier rejection at all for the setting refinement jobs. We could go even further, and completely determine the subset of reflections to use for refinement in advance of any of the refinement jobs. That would mean passing less data around to each `easy_mp` job, and also guarantee that the same reflections are used for refinement for each case.

**Comment by dagewa** [comment]
In a not very rigorous test, I ran `dials.refine_bravais_settings` using the first 3600 images of the low dose, high multiplicity [thermolysin dataset](https://zenodo.org/record/49559#.WzX0gxzTXA0), timing it exactly once and got:
**`wall clock time: 43.67 seconds`**

I then created a subset of reflections, containing only the reflections used in refinement during indexing:
`dev.dials.filter_reflections indexed.pickle inclusions.flag=used_in_refinement`
I ran `dials.refine_bravais_settings` using this input, after also changing the outlier rejection method to `null`. The total runtime was better than halved:
**`wall clock time: 19.06 seconds`**

Looking at the logfiles, the results are essentially identical in terms of metric fit, RMSD and unit cell (but this is not a case where the choice of setting is difficult to make). The min/max CCs differ in the second decimal place, but the filtering in advance means that there is less data to use for the CC calculation. If the filtering was instead done within `dials.refine_bravais_settings` then it could potentially be done only for the refinement step and not for CC calculation.

All data:
```
-----------------------------------------------------------------------------------------------------------------
Solution Metric fit  rmsd  min/max cc #spots lattice                                 unit_cell  volume      cb_op
-----------------------------------------------------------------------------------------------------------------
*     12     0.0092 0.044 0.913/0.913  36000      hP  92.34  92.34 127.71  90.00  90.00 120.00  943009    -a,b,-c
*     11     0.0078 0.044 0.906/0.956  36000      oC  92.33 159.94 127.71  90.00  90.00  90.00 1885950 a,-a+2*b,c
*     10     0.0092 0.044 0.907/0.933  36000      oC  92.34 159.93 127.71  90.00  90.00  90.00 1886117 b,-2*a+b,c
*      9     0.0080 0.044 0.907/0.941  36000      oC  92.34 159.93 127.71  90.00  90.00  90.00 1885992  a-b,a+b,c
*      8     0.0072 0.044 0.956/0.956  36000      mC 159.94  92.33 127.71  90.00  90.00  90.00 1886003  a-2*b,a,c
*      7     0.0051 0.044 0.916/0.916  36000      mC 159.93  92.34 127.71  90.00  90.01  90.00 1885985  2*a-b,b,c
*      6     0.0071 0.045 0.941/0.941  36000      mC  92.34 159.93 127.71  90.00  90.01  90.00 1885881  a-b,a+b,c
*      5     0.0080 0.044 0.912/0.912  36000      mC 159.93  92.34 127.71  90.00  90.00  90.00 1886086 a+b,-a+b,c
*      4     0.0029 0.044 0.906/0.906  36000      mC  92.33 159.94 127.71  90.00  90.01  90.00 1885955 a,-a+2*b,c
*      3     0.0092 0.044 0.933/0.933  36000      mC  92.34 159.93 127.71  90.00  90.00  90.00 1886024 b,-2*a+b,c
*      2     0.0078 0.044 0.907/0.907  36000      mP  92.33 127.71  92.34  90.00 120.00  90.00  942985  -a,-c,a-b
*      1     0.0000 0.044         -/-  36000      aP  92.33  92.34 127.71  90.00  90.01  60.00  942956      a,b,c
-----------------------------------------------------------------------------------------------------------------
```
Filtered:
```
-----------------------------------------------------------------------------------------------------------------
Solution Metric fit  rmsd  min/max cc #spots lattice                                 unit_cell  volume      cb_op
-----------------------------------------------------------------------------------------------------------------
*     12     0.0092 0.044 0.947/0.947  36000      hP  92.34  92.34 127.71  90.00  90.00 120.00  942999    -a,b,-c
*     11     0.0078 0.044 0.937/0.980  36000      oC  92.33 159.94 127.71  90.00  90.00  90.00 1885982 a,-a+2*b,c
*     10     0.0092 0.044 0.937/0.959  36000      oC  92.34 159.93 127.71  90.00  90.00  90.00 1885999 b,-2*a+b,c
*      9     0.0080 0.044 0.937/0.971  36000      oC  92.34 159.93 127.71  90.00  90.00  90.00 1885989  a-b,a+b,c
*      8     0.0072 0.044 0.980/0.980  36000      mC 159.94  92.33 127.71  90.00  90.00  90.00 1885889  a-2*b,a,c
*      7     0.0051 0.044 0.951/0.951  36000      mC 159.93  92.34 127.70  90.00  90.01  90.00 1885835  2*a-b,b,c
*      6     0.0071 0.044 0.971/0.971  36000      mC  92.34 159.93 127.70  90.00  90.01  90.00 1885809  a-b,a+b,c
*      5     0.0080 0.044 0.946/0.946  36000      mC 159.93  92.34 127.71  90.00  90.01  90.00 1886030 a+b,-a+b,c
*      4     0.0029 0.044 0.943/0.943  36000      mC  92.33 159.94 127.71  90.00  90.01  90.00 1885921 a,-a+2*b,c
*      3     0.0092 0.044 0.959/0.959  36000      mC  92.34 159.93 127.71  90.00  90.00  90.00 1886026 b,-2*a+b,c
*      2     0.0078 0.044 0.937/0.937  36000      mP  92.33 127.71  92.34  90.00 120.00  90.00  942991  -a,-c,a-b
*      1     0.0000 0.044         -/-  36000      aP  92.33  92.34 127.70  90.00  90.01  60.00  942917      a,b,c
-----------------------------------------------------------------------------------------------------------------
```

**Comment by rjgildea** [comment]
RBS actually does two rounds of refinement per Bravais setting, with different values of iqr_multiplier. Presumably this gave better/more reliable results in marginal cases!
https://github.com/dials/dials/commit/7efba569ebad0bff96de1ad942903ee6917f6327

**Comment by dagewa** [comment]
This probably helps to work around the fact that outlier rejection could be quite unreliable immediately after the symmetry constraint is applied, if there has been any significant change to the cell. On the second round of refinement, the outlier rejection should be more reliable.

**Comment by dagewa** [comment]
Testing with the same images today, RBS on master takes `wall clock time: 51.93 seconds` whilst on speed-up-rbs it takes `wall clock time: 35.24 seconds`. PR incoming.
