### ISSUE TITLE
Problem with predicted positions in dials.index

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#59]
@dagewa This might be related to another prediction bug. The following output is from the i04 bag training data. The output shows that when the predictions from the experimental models are compared with the predictions input from dials.index they differ by more than 2 pixels in most cases. The same output run on the refined results shows all reflections are matched within 2 pixels. NOTE - this is matching predictions to predictions, they should be the same (to within some small error).

Doing dials.integrate after dials.index:

Matching reference spots with predicted reflections
 114690 observed reflections input
 374134 reflections predicted
 114531 reflections matched
 8099 reflections accepted

Do dials.integrate after dials.refine with scan_varying=False

 114690 observed reflections input
 374129 reflections predicted
 114532 reflections matched
 114532 reflections accepted

Doing dials.integrate after dials.refine with scan_varying=True

Matching reference spots with predicted reflections
 114690 observed reflections input
 374020 reflections predicted
 114528 reflections matched
 114528 reflections accepted

To reproduce do the following:
dials.import th_8_2_*.cbf
dials.find_spots datablock.json
dials.index datablock.json strong.pickle
dials.integrate experiments.json indexed.pickle
dials.refine experiments.json indexed.pickle scan_varying=False
dials.integrate refined_experiments.json refined.pickle
dials.refine experiments.json indexed.pickle scan_varying=True
dials.integrate refined_experiments.json refined.pickle

**Comment by rjgildea** [comment]
The refinement used inside dials.index only predicts for the reflections used in refinement, which in this case must be 8099. So the "errors" in predictions must be as a result of comparing to un-predicted reflections, i.e. (0,0,0).
