### ISSUE TITLE
In dials.report HTML output; the density histogram picture of difference in Z is not trustworthy

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#594]
See https://github.com/dials/dials/issues/591

Detailed analysis suggests that the plot should not be trusted => is some feature of numpy 2D histogram, or some data wrangling issue, but there is something very wrong here. 

@rjgildea @jmp1985 would welcome your input

**Comment by ndevenish** [comment]
Possibly problem fixed in 0109af821efce5f630234e518f152be71449c9ca?

**Comment by graeme-winter** [comment]
@ndevenish @benjaminhwilliams  yes fixed in that commit 👍
