### ISSUE TITLE
sigma_m blows up for a particular input to dials.integrate

### ISSUE THREAD

**Issue by dagewa** [dials/dials#599]
The tarball [here](https://stfc365-my.sharepoint.com/:u:/g/personal/david_waterman_stfc_ac_uk/EbjMffnGAWBEjkQV91cMRsIBXH5zd9jTQnJ8dQ9xcEeXPg?e=XPBzvE) contains a small wedge dataset (6 images) and two alternate refinement results.

```
-rw-rw-r-- 1 54966718 Jul 19 17:27 multi003_data_000001.h5
-rw-rw-r-- 1 27182341 Jul 19 17:23 multi003_master.h5
-rw-rw-r-- 1   573666 Jul 19 17:24 refined_01.pickle
-rw-rw-r-- 1   573651 Jul 19 17:25 refined_02.pickle
-rw-rw-r-- 1     7171 Jul 19 17:25 refined_experiments_01.json
-rw-rw-r-- 1     7161 Jul 19 17:25 refined_experiments_02.json
```

With `dials.integrate refined_experiments_01.json refined_01.pickle prediction.d_min=3.0` the `sigma_m` estimation blows up horribly (`sigma m: 20.849865 degrees`) and all profile fitting fails.

With `dials.integrate refined_experiments_02.json refined_02.pickle prediction.d_min=3.0` the `sigma_m` estimation seems reasonable (`sigma m: 0.386280 degrees`) and profile fitting proceeds.

The refinement results are not grossly different. For 01:
```
RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 272  | 0.65156 | 0.55715 | 0.2663   |
---------------------------------------------

Final refined crystal model:
Crystal:
    Unit cell: (55.559(15), 64.677(5), 161.54(9), 90.0, 90.0, 90.0)
```
For 02:
```
RMSDs by experiment:
--------------------------------------------
| Exp | Nref | RMSD_X | RMSD_Y  | RMSD_Z   |
| id  |      | (px)   | (px)    | (images) |
--------------------------------------------
| 0   | 180  | 0.4783 | 0.45247 | 0.23041  |
--------------------------------------------

Final refined crystal model:
Crystal:
    Unit cell: (55.543(14), 64.720(6), 161.96(9), 90.0, 90.0, 90.0)
```
Any ideas why the `sigma_m` estimate > 20° for the 01 version? The whole dataset is only 6°...

**Comment by dagewa** [comment]
this is probably one for @jmp1985

**Comment by graeme-winter** [comment]
I’ve seen this quite a lot with misindexed data...

**Comment by dagewa** [comment]
Sigh. It looks as though STFC OneDrive won't give up the file without requiring a log in. For those at DLS, I also put a copy at `/dls/mx-scratch/fcx32934/sigma_m_issue.tar.gz`

**Comment by dagewa** [comment]
@graeme-winter In this case the indexing solution is basically the same in the two cases.
```
dials.combine_experiments refined_experiments_01.json refined_experiments_02.json refined_01.pickle refined_02.pickle
dials.reciprocal_lattice_viewer combined_experiments.json combined_reflections.pickle 
```
Pretty much perfect overlay between the two solutions.
![overlay](https://user-images.githubusercontent.com/11502083/42960065-adcc042a-8b82-11e8-8651-8bfb767fd821.png)

**Comment by graeme-winter** [comment]
🤔 interesting. Would be fun to compare the individual reflections. I’ll bet there’s one or more misindexed ones...

**Comment by jmp1985** [comment]
When the mosaicity blows up it usually means that there are reflections with phi prediction a massive distance away from where they are observed. 20 degrees mosaicity seem pretty extreme though! I'll have a look at this when I'm back in on Monday!

**Comment by dagewa** [comment]
Thanks James. The residuals of reflections going into refinement look fairly typical, about 6° +/- the observed position at the extremes, prior to outlier rejection. Here's the relevant bit of the table:
```
-----------------------------------------------------------------------
|                   | Min    | Q1       | Med       | Q3      | Max   |
-----------------------------------------------------------------------
| Phic - Phio (deg) | -5.878 | -0.2296  | 0.01427   | 0.2529  | 6.424 |
```
It is possible that there are indexed reflections with greater residuals than this that are rejected by refinement even before outlier rejection (too close to spindle for example). Does mosaicity estimation only use reflections `used_in_refinement`, or could it be taking other indexed strong reflections too?

**Comment by dagewa** [comment]
After outlier rejection, the phi residuals of reflections that do get used in refinement looks sensible:

`| Phic - Phio (deg) | -0.7435 | -0.2246  | -0.03141  | 0.1446  | 0.6255 |
`

**Comment by dagewa** [comment]
```
>>> from dials.array_family import flex
>>> r1=flex.reflection_table.from_pickle('refined_01.pickle')
>>> r2=flex.reflection_table.from_pickle('refined_02.pickle')
>>> zo1 = r1['xyzobs.px.value'].parts()[2]
>>> zc1 = r1['xyzcal.px'].parts()[2]
>>> zdiff1 = zc1-zo1
>>> zo2 = r2['xyzobs.px.value'].parts()[2]
>>> zc2 = r2['xyzcal.px'].parts()[2]
>>> zdiff2 = zc2-zo2
>>> from scitbx.math import five_number_summary
>>> five_number_summary(zdiff1)
(-42.36702605570531, -4.2863174543998195, -2.2592549479738837, -0.5, 20.24041196150219)
>>> five_number_summary(zdiff2)
(-42.36702605570531, -4.274460251297653, -2.4005142781250206, -0.5, 6.294596401164806)
```
Both datasets have one reflection with a large negative residual (Zcalc - Zobs) of -42.37 images. This seems to be related to a failure in reflection prediction.
```
>>> flex.first_index((zdiff1 == -42.36702605570531), True)
336
>>> r1[336]
{'imageset_id': 0, 'xyzcal.mm': (0.0, 0.0, -1.1102230246251565e-16), 'intensity.sum.value': 1113.0, 'n_signal': 7, 'xyzobs.px.variance': (0.08450343867711882, 0.0835616000466962, 0.08345430557741658), 'intensity.sum.variance': 1113.0, 's1': (0.0, 0.0, 0.0), 'shoebox': <dials_model_data_ext.Shoebox object at 0x7f85224e1ec0>, 'miller_index': (8, -7, -23), 'rlp': (0.22629353197832197, -0.012494699011494515, 0.0240110415501425), 'xyzobs.mm.variance': (0.00047533188771289647, 0.00047003404491350123, 2.5421635235084162e-05), 'xyzcal.px': (0.0, 0.0, -37.00000000000001), 'flags': 36, 'bbox': (2369, 2373, 1606, 1608, 4, 6), 'entering': False, 'xyzobs.mm.value': (177.78709855599405, 120.53820045427945, 0.7394440989502841), 'xyzobs.px.value': (2370.909703504043, 1607.1801437556155, 5.367026055705301), 'id': 0, 'panel': 0}
```
See **'xyzcal.mm': (0.0, 0.0, -1.1102230246251565e-16)** but **'xyzcal.px': (0.0, 0.0, -37.00000000000001)**
My guess is that prediction failed for reflection (8, -7, -23), resulting in xyzcal.mm being assigned (0.0, 0.0, 0.0), but because the dataset oscillation starts at 37° this is converted to (0.0, 0.0, -37.0) in pixels/images.

This seems... unfortunate. There is a predicted flag, but it seems this isn't set for any reflection
```
>>> r1.get_flags(r1.flags.predicted).count(True)
0
```

**Comment by dagewa** [comment]
Note that this large negative residual isn't even the problem in the mosaicity estimation, because this reflection is present in both reflection tables. The two tables differ in the positive extreme residual, with the version that fails having a residual of 20.2 images and the version that works having a residual of 6.3 images.

**Comment by dagewa** [comment]
The large positive residual from `refined_01.pickle` (20.2 images) seems to be due to this spot indexed along the backstop shadow
![indexed_along_backstop](https://user-images.githubusercontent.com/11502083/43895166-46cee08a-9bcc-11e8-90c6-ac5d3cee316d.png)

**Comment by dagewa** [comment]
Whereas the largest positive residual from `refined_02.pickle` (6.3 images) comes from the spot indexed (-1.-1, 1) in the backstop scatter (spot near the top of the image)
![screenshot from 2018-08-09 12-08-16](https://user-images.githubusercontent.com/11502083/43895430-2dda1a12-9bcd-11e8-8afc-f06ceadab4fa.png)

**Comment by dagewa** [comment]
I suppose the moral of the story is always to mask out the backstop and shadows, though it gets tedious when looking at a few hundred wedges, unless they are the same all the time.

Nevertheless, could `dials.integrate` do more to filter out reflections with extremely high residuals before mosaicity calculation? These reflections are both chucked away by outlier rejection in refinement, so do not affect the quality of the refined model.

**Comment by rjgildea** [comment]
@dagewa you're suggesting that dials.integrate is using reflections that have been marked as outliers in refinement? Surely dials.integrate should not be using such reflections for profile modelling etc?

**Comment by dagewa** [comment]
@rjgildea I'm not sure yet (only have the circumstantial evidence so far), but I'll dig into the mosaicity estimation code next to find out what is happening - unless @jmp1985 beats me to it!

**Comment by jmp1985** [comment]
@dagewa In command_line/integrate.py in the function process_reference, reflections marked as "centroid_outlier" are removed and not used in the profile modelling. However, I don't check for "used_in_refinement".

**Comment by dagewa** [comment]
I think that's reasonable, as refinement might have been done with a small subset of reflections. I still don't understand why this case blows up then

**Comment by rjgildea** [comment]
Ah, so it was thrown out of refinement before it got chance to be flagged as a centroid outlier. Perhaps there needs to be a generic "outlier/untrusted" flag for such cases? Or maybe a specific too-close-to-spindle flag? Any thoughts?

**Comment by dagewa** [comment]
Yes, it turns out this one is too-close-to-spindle and is thrown out _before_ outlier rejection. Perhaps a specific too-close-to-spindle flag makes sense, though dials.integrate has its own measure of too-close-to-spindle via the zeta function, right?

**Comment by dagewa** [comment]
There are currently up to 5 reasons to exclude reflections before passing on to outlier rejection:
1. Miller index is (0,0,0)
2. Reflection is overloaded
3. Too close to spindle
4. Observed phi lies outside the scan range
5. Close to the edges of the scan (optional #457)

Perhaps a general `valid_for_refinement` flag could be set after these tests. The `used_in_refinement` and `centroid_outlier` flags would select subsets of this. For mosaicity estimation `valid_for_refinement & ~centroid_outlier` would be the right selection. Does this sound sensible?

**Comment by dagewa** [comment]
It is possible that the original reason for this was to support data taken from elsewhere. For defensive reasons I am inclined to leave that check in.
