### ISSUE TITLE
Unhelpful error message from dials.import when passing a directory containing some non-image files 

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#600]
Calling `dials.import <path/to/directory/>`  fails, as it should, if the target contains non-image files.  The error message, however, is unhelpful.  For example:

```
$ dials.import <directory/containing/image/and/non-image/files>

############################################################################
#                                                                          #
# The DIALS reference paper has now been published:                        #
#                                                                          #
# DIALS: implementation and evaluation of a new integration package (2018) #
# https://doi.org/10.1107/S2059798317017235        Acta Cryst. D74, 85-97. #
#                                                                          #
############################################################################


DIALS 1.dev.2699-g7c15234
Sorry: Unable to handle the following arguments:
```
And that's all you get.

**Comment by dsclassen** [comment]
I am receiving the same error. I had no idea it was a handful of jpeg and txt files that was preventing dials.import from working. This really needs a fix.

**Comment by graeme-winter** [comment]
Agreed

Perhaps 

```
dials.import /path/to/directory
```

should silently ignore "junk" whilst 

```
dials.import *.cbf kitten.jpg
```

should swear (which I think is the current behaviour). Silent failure is very unhelpful. 

Since we know dials.import does not want to read .png .log .docx. etc we could add a list of deliberately ignored file suffices to the directory import mode? Effectively common file types which are  known to be junk to dials.

**Comment by graeme-winter** [comment]
Though it must be said that this is also unhelpful

```
Silver-Surfer:gpxpy graeme$ dials.import NOTICE.txt 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 1.dev.2823-g3655edb79
Sorry: Unable to handle the following arguments:
```

Guess this is the are-you-a-file-or-phil-parameter conundrum?

**Comment by dagewa** [comment]
I agree we should silently ignore non-image files when doing directory import. It shouldn't be an error. Plenty of data-collection set ups produce some extraneous files, like `.log`, `.xml` and so on

**Comment by ndevenish** [comment]
```
$ dials.import ~/dials/data/betalactamase/
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1549-gaa0ee89a6
Sorry: Unable to handle the following arguments:
  /Users/nickd/dials/data/betalactamase/mask.pickle
```
