### ISSUE TITLE
Cannot index still images from multi-image formats by dials.index

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#601]
I noticed that I can no longer index still images from `dials.index`, while  `dials.stills_process` works fine.
Of course we use `dials.stills_process` for batch processing, but `dials.index` is useful for testing parameters. I am sure this was working before.

```
$ dials.import dials_regression/image_examples/run266702-0-subset.h5 # contains 4 still images
$ dials.find_spots datablock.json
$ dials.index datablock.json strong.pickle scan_range=1,1

Traceback (most recent call last):
  File "/home/sacla_sfx_app/packages/dials/build/../modules/dials/command_line/index.py", line 181, in <module>
    run(sys.argv[1:])
  File "/home/sacla_sfx_app/packages/dials/build/../modules/dials/command_line/index.py", line 142, in run
    if (imageset.get_goniometer() is not None and
  File "/home/sacla_sfx_app/packages/dials/modules/cctbx_project/dxtbx/imageset.py", line 182, in get_goniometer
    format_instance = self.get_format_class()._current_instance_
AttributeError: type object 'FormatMultiImage' has no attribute '_current_instance_'
```

**Comment by biochem-fan** [comment]
This happens only for multi image classes (e.g. SACLA MPCCD and EIGER). For single image classes like Rayonix TIFF, `dials.index` just works fine.

**Comment by graeme-winter** [comment]
Could this relate to the lazy loading interface changes? That’s probably the most obvious difference which has appeared lately.

**Comment by phyy-nx** [comment]
Hi, I'm following this and hope to fix it soon, but the GRC will likely get in the way a bit.  For what it's worth, it has to do with cctbx/cctbx_project#203.  I'll likely need to replace instances of _current_instance_ with a class method on Format that checks if the class global _current_instance_ is available and loads it if not.
