### ISSUE TITLE
dials.generate_masks doesn't work with multiple imagesets

### ISSUE THREAD

**Issue by dagewa** [dials/dials#604]
Sometimes this is a reasonable thing to want to do:
> because of the limitation of the partial chi goniometer, I collect 360° as two sweeps of 180° around omega, with phi = 0 and phi = 180°.  I can dials.import and process them as one dataset with allow_multiple_sweeps=True.  One little problem is that I cannot simply generate a mask to cover all images, even though the beamstop shadow or unmasked noisy pixels are unchanged throughout the entire dataset.  The error message is "Sorry: datablock must contain exactly 1 imageset".

**Comment by benjaminhwilliams** [comment]
Belatedly picking up on this.  Happy to take it on.  @dagewa, did you previously investigate?

**Comment by benjaminhwilliams** [comment]
Oh sorry, I didn't look at the commit in any detail.  I see this fixes the exact problem you reported, but not the case of multiple imagesets belonging to different `Experiment`s, as in a multi-sweep small-molecule data collection.  I'm going to try to extend `dials.generate_mask`  to accommodate the latter case too.

**Comment by benjaminhwilliams** [comment]
It seems some of the proposed changes in #728 may cause a stealthy regression here, there doesn't seem to be a test.  @dagewa, could you build a test around the original reported problem, or a similar case?  That way, we'll spot it before it happens again.

**Comment by benjaminhwilliams** [comment]
It seems some of the proposed changes in #728 may cause a stealthy regression here, there doesn't seem to be a test.  @dagewa, could you build a test around the original reported problem, or a similar case?  That way, we'll spot it before it happens again.

**Comment by benjaminhwilliams** [comment]
e1f7ef0 added a test for a four-sweep data set, but I don't have test data for the exact case (a split sweep) originally reported by @dagewa, so I can't build a test for that.  @dagewa, are you happy with the fix in e1f7ef0?  If not, or if you have data for your test case, feel free to reopen this issue if/when it is closed by the merging of #728.

**Comment by dagewa** [comment]
Hi @benjaminhwilliams, sorry, didn't see this earlier. I don't think I have data for a test case at hand - the issue originally came from a user and I fixed it "blind"

**Comment by benjaminhwilliams** [comment]
OK, I think the fix should work for your case too.  That's the case on master at least, I haven't double-checked the state of 1.14
  :-/
