### ISSUE TITLE
Sphinx documentation generation broken

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#607]
Dies with
```
dials.command_line.scale.help_message:31:Inline emphasis start-string without end-string.
```

Cause appears to be:
https://github.com/dials/dials/blob/77cce2513e119865aa5542fa4a74cc4d7ad5be23/command_line/scale.py#L31
suspect trailing slash is an emphasis marker.

Same will apply to line 39
https://github.com/dials/dials/blob/77cce2513e119865aa5542fa4a74cc4d7ad5be23/command_line/scale.py#L39

**Comment by jbeilstenedmands** [comment]
I think I have fixed this issue with my latest commit, however I'm getting another error due to the
beta lactamase log file so I haven't pushed any updated documentation to the dials.github.io repo. I will wait to see if it is successfully built tonight, then hopefully this issue can be closed.

**Comment by Anthchirp** [comment]
Not there yet
```
(..)/modules/dials/doc/sphinx/documentation/programs/dials_scale.rst:document isn't included in any toctree
```

**Comment by Anthchirp** [comment]
Fixed.
