### ISSUE TITLE
Processing ED images with discontinuous beam centre between images

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#608]
At the ECM/computing school, I've been talking to Bin Wang, who would like to use DIALS for electron diffraction data analysis, but has so far been unable to get DIALS to work with his data. 

As far as I understand, the experiments they are attempting are continuous rotation electron diffraction, so similar to an MX experiment. However, there is a beam drift issue between frames, and often this can be discontinuous jumps that are non-negligible. I guess this is not compatible with our current workflow where we assume a constant beam centre throughout a sweep?

Bin can do some preprocessing/filtering on the images to find the beam centre to a good level of accuracy, and could translate the images to give a common centre. I guess the question is whether this preprocessing should be sufficient to allow standard processing like an MX experiment, or whether this would give further issues, or are there other suggestions? Or can DIALS already support a different beam centre per image?

**Comment by asdfdsa** [comment]
Thank you for bringing up the issue, James! DIALS works quite well for some of our data sets, but may encounter some problem in indexing or refinement when there is beam drift. /Bin

**Comment by dagewa** [comment]
@jbeilstenedmands answering your first question, it is possible to refine a _smoothly-varying_ beam centre in DIALS, but discontinuous jumps cannot be modelled (in a single scan). There are details about this now published in [Clabbers _et al._ 2018](http://scripts.iucr.org/cgi-bin/paper?rr5161) and a [tutorial](https://dials.github.io/documentation/tutorials/dials_for_ed.html) that goes through the steps required to process the data sets described in the paper.

I suppose that small discontinuities (say sub-half-pixel) on top of a smoothly-changing beam drift could be tolerated by the scan-varying beam model of DIALS and allow reasonable integration results. Big discontinuities would need some other approach, like pre-processing to translate the pixel values as mentioned.

**Comment by asdfdsa** [comment]
@dagewa Thank you for your reply. I am wondering if DIALS has the plan to include the pre-processing i.e. translate the pixel values into the workflow, or otherwise we should still do it on our side for the near future. /Bin

**Comment by asdfdsa** [comment]
Yes, I do have some code for the purpose. Then it's clear, thanks for replying! /Bin
