### ISSUE TITLE
Rationalise experiment ID assumptions

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#615]
There exist several useful methods for manipulating reflection tables that depend on the experiment ID having integer value ≥ 0, such as the `ReflectionTable` method `split_by_experiment_id`.  These clearly predate a design decision to denote unindexed reflections by a dummy experiment ID value of -1.  A reflection table that includes some indexed and some unindexed reflections therefore causes problems.  To illustrate this, take a pickle file (here `indexed.pickle`) containing both indexed and unindexed reflections, and do the following:
`>>> from dials.util.phil import ReflectionTableConverters`
`>>> rtable = ReflectionTableConverters().from_string("indexed.pickle").data`
`>>> rtable.split_by_experiment_id()`
`RuntimeError: dials Internal Error: /home/ekm22040/DIALS/modules/dials/array_family/boost_python/flex_reflection_table.cc(441): DIALS_ASSERT(id[i] >= 0) failure.`

It would be useful to be able to make use of such methods without have to preempt unindexed reflections and make special allowance for them.

**Comment by benjaminhwilliams** [comment]
Another example of this design dissonance:
Given a reflection table ``rtable``, containing both indexed and unindexed reflections, and a corresponding experiment list ``elist``:
``>>> rtable.compute_d(elist)``
``---------------------------------------------------------------------------``
``AssertionError                            Traceback (most recent call last)``
``<ipython-input-19-c1569faa10ea> in <module>()``
``----> 1 rtable.compute_d(elist)``

``/dls/science/users/ekm22040/dials/modules/dials/array_family/flex.pyc in compute_d(self, experiments)``
``    767     for i, e in enumerate(experiments):``
``    768       uc[i] = e.crystal.get_unit_cell()``
``--> ``**``769     assert self['id'].all_ge(0)``**
``    770     self['d'] = uc.d(self['miller_index'], flex.size_t(list(self['id'])))``
``    771     return self['d']``

``AssertionError:``

**Comment by jbeilstenedmands** [comment]
I have been thinking more about this now that we're trying to introduce the use of experiment identifiers.
I think this use of the id column (setting -1) should be completely retired, particularly given that there is an 'indexed' flag which presumably can be used for this? (Or if this is not suitable another flag could be made). This leaves the id column free to be used for identifying which dataset/experiment the data belong to, through the use of the reflection_table.experiment_identifiers() map.  Of course this may be some effort to go through the codebase to remove this behaviour, but it is the required resolution to this issue.

**Comment by phyy-nx** [comment]
Hi James, you are not proposing removing the 'id' column entirely, just the
use of -1 to indicate unindexed?  Seems reasonable.

**Comment by jbeilstenedmands** [comment]
Hi Aaron, you are correct, I'm only talking about removing the use of -1 to indicate unindexed. However I have no plans to do this work in the near future :) and would probably make a pull request anyway if I were to do this. Do you use this convention much in stills_process, of setting id values to -1?

**Comment by phyy-nx** [comment]
The stills indexer knows this convention, but the rest of the dials still process doesn’t need to know about it. 

-Aaron
