### ISSUE TITLE
detector == operation in dxtbx seems to not do a true comparison

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#62]
I hear it reported in other tickets that if origin not the same d1==d2 will still be true.

**Comment by graeme-winter** [comment]
See http://sourceforge.net/p/cctbx/code/23604

**Comment by graeme-winter** [comment]
@jmp1985 please could you look into this one?

**Comment by jmp1985** [comment]
Hi Graeme,

Will do.

James

**Comment by jmp1985** [comment]
@graeme-winter So this is probably a bit confusing but there are two methods in use here.

The operator== method just checks the image_size, pixel_size and trusted_range values. Then there is the is_similar_to method which checks the origin, fast and slow vectors with a user specified tolerance value.

I honestly don't remember why I was asked to change this but there was a reason for removing the fast/slow/origin comparison from == and just having it in is_similar_to. I'll check my emails to see if I can figure out why.

The correct method to use is the is_similar_to method.

**Comment by graeme-winter** [comment]
James, this does not help when you are looking up a detector in a list and it asks if d == item[j] until it comes back with true. == is part of the language spec which Python uses.

See https://docs.python.org/2/reference/datamodel.html

```
object.__lt__(self, other)
object.__le__(self, other)
object.__eq__(self, other)
object.__ne__(self, other)
object.__gt__(self, other)
object.__ge__(self, other)
New in version 2.1.

These are the so-called “rich comparison” methods, and are called for comparison operators in preference to __cmp__() below. The correspondence between operator symbols and method names is as follows: x<y calls x.__lt__(y), x<=y calls x.__le__(y), x==y calls x.__eq__(y), x!=y and x<>y call x.__ne__(y), x>y calls x.__gt__(y), and x>=y calls x.__ge__(y).

A rich comparison method may return the singleton NotImplemented if it does not implement the operation for a given pair of arguments. By convention, False and True are returned for a successful comparison. However, these methods can return any value, so if the comparison operator is used in a Boolean context (e.g., in the condition of an if statement), Python will call bool() on the value to determine if the result is true or false.

There are no implied relationships among the comparison operators. The truth of x==y does not imply that x!=y is false. Accordingly, when defining __eq__(), one should also define __ne__() so that the operators will behave as expected. See the paragraph on __hash__() for some important notes on creating hashable objects which support custom comparison operations and are usable as dictionary keys.

There are no swapped-argument versions of these methods (to be used when the left argument does not support the operation but the right argument does); rather, __lt__() and __gt__() are each other’s reflection, __le__() and __ge__() are each other’s reflection, and __eq__() and __ne__() are their own reflection.
```

**Comment by jmp1985** [comment]
Hi Graeme,

I’ve modified the == operator to do essentially what the is_similar_to method does (except with a fixed tolerance). I’m currently running to tests to ensure nothing breaks but will commit the change once the tests pass.

James

**Comment by jmp1985** [comment]
Fixed

**Comment by graeme-winter** [comment]
Obliged :)
