### ISSUE TITLE
Units missing in dials.report plots

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#626]
For example:

![newplot 3](https://user-images.githubusercontent.com/1241716/46454523-8ce22500-c7e1-11e8-9b75-8a52ecbe1c24.png)

**Comment by rjgildea** [comment]
I'm not entirely certain what the units _should_ be for this plot. The code generating it is here:
https://github.com/dials/dials/blob/297f19248cb4267da2f68c00c1d6db5631538708/command_line/report.py#L760-L785

The histogram appears of sqrt(Δx^2 + Δy^2 + Δz^2), where x and y are in pixels, and z is in images.

**Comment by dagewa** [comment]
I suppose it is a Euclidean distance in _pixels_, where pixels also have a "depth" in Z. Calling this a distance in pixels is probably less confusing than calling it a distance in voxels.
