### ISSUE TITLE
Add raw/corrected data toggle to image viewer

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#634]
Image viewer uses get_corrected_data implemented by imageset.h.  This is fine, but sometimes we want to see the raw data.  A checkbox would help.

Stretch goal: only show the checkbox if corrections are being applied, and if they are, somehow indicate which corrections are being applied.  Would require checking the results of get_gain and get_pedestal on the imageset.

**Comment by dagewa** [comment]
Confusingly this goes through https://github.com/dials/dials/blob/9f8cd7d76b30423b264f729c7d2496a256316e89/util/image_viewer/slip_viewer/frame.py#L52-L55 which despite the name actually returns the corrected data!

**Comment by benjaminhwilliams** [comment]
Apparently this is done.
