### ISSUE TITLE
Let dials export to xds_ascii format for multi-dataset files

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#637]
I has been suggested that the xds_ascii option in dials.export should allow exporting of multi-dataset files (mainly relevant for post-scaling), to support workflows where downstream processing uses files in this format. Both XDS and XSCALE write in xds_ascii format, so these files can support multiple datasets.
I shall ask around to get a good example so we are confident of the format, unless anyone has some?

**Comment by jbeilstenedmands** [comment]
I now have example files I can use so I will have a go at this

**Comment by graeme-winter** [comment]
Not sure what the use case is here but I suggest we have a chat - 

 - XDS will write out XDS_ASCII.HKL, one per "run"
 - XSCALE will write out a format similar to this which can have > 1 "run" in

but they are subtly different...
