### ISSUE TITLE
dials.image_viewer segfault

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#64]
This command crashes with a segfault, but only on i19-ws001 and i19-ws002, not on nx-staff.
```
 $ dials.image_viewer /dls/i19-1/data/2016/mt11397-3/TKR948/TKR948_08_00001.cbf
The following parameters have been modified:

input {
  datablock = <image files>
}

Segmentation fault (core dumped)
```

Weird:
```
 $ dials.import /dls/i19-1/data/2016/mt11397-3/TKR948/TKR948_08_00001.cbf
(..)
 $ dials.image_viewer datablock.json 
```
works.

Furthermore, and most annoyingly,
```
 $ strace dials.image_viewer /dls/i19-1/data/2016/mt11397-3/TKR948/TKR948_08_00001.cbf
```
works, too.

Is this a timing issue/race condition?
What can cause a segfault?

**Comment by nksauter** [comment]
Markus,

If this is a flex image issue I can debug.  Send the data.

Nick

Nicholas K. Sauter, Ph. D.
Computer Staff Scientist, Molecular Biophysics and Integrated Bioimaging
Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by Anthchirp** [comment]
Nick suggested this could be WX related. It works on the builds on my local machine, where
$ dials.python -c "import wx; print wx.version()"
'2.8.12.1 (gtk2-unicode)'

but not on the distributed builds, where
$ dials.python -c "import wx; print wx.version()"
3.0.2.0 gtk2 (classic)

**Comment by Anthchirp** [comment]
Have now updated my machine to new wx version, and now it crashes here, too.

**Comment by Anthchirp** [comment]
Nice try, but not fixed yet.
