### ISSUE TITLE
Add extra log levels to dials/util/log

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#645]
TRACE 5
VERBOSE 15
NOTICE 25

come to mind

**Comment by rjgildea** [comment]
If we do add a VERBOSE 15 level, should most existing calls to logger.debug() be changed to logger.verbose()?

**Comment by Anthchirp** [comment]
There is no logger.verbose() function by default, you'd have to specifically ```logger.log(VERBOSE, ...)```.
I think the debug level and our use of it is fine as it is?
