### ISSUE TITLE
dials.report probability plots store excessive amounts of data

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#648]
The recently added probability plots in dials.report generate several plots that have data points for every reflection in the dataset. This may be fine for small unit cells, but the file size can be come excessively large for typical MX unit cells. Any scatter plots for all data should probably be replaced by 2d heatmaps that are pre-calculated in numpy, and 1d histograms pre-calculated and plotted as bar charts.

https://dials.github.io/_downloads/dials-report.html

See also https://github.com/dials/dials/commit/e198ffe7c9e48d4a2dd6a782d0a42539fc585f59

**Comment by benjaminhwilliams** [comment]
The class `ZScoreAnalyser` still exists but is unused.  Should I fix it up to histogram the data sensibly to solve this issue, or are we already doing that elsewhere, in which case, I'll remove it.  @jbeilstenedmands, I guess you know best what we do with this info in `dials.report`.
