### ISSUE TITLE
make the dials GUI to auto detect screen resolution and re-size all widgets accordingly

### ISSUE THREAD

**Issue by luisodls** [dials/dials#65]

**Comment by dagewa** [comment]
@luisodls is this still relevant?

**Comment by luisodls** [comment]
no, and this should NOT be in this repo, there is a repo created especially for issues on DUI

**Comment by dagewa** [comment]
Oh yes, I remember https://github.com/dials/DUI. In that case, could you please close all DUI issues within this issue tracker? Thanks.
