### ISSUE TITLE
Post-integration workflow requires assigning identifiers for >1 dataset

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#655]
I'm having a go at analysing some data and it seems that integrate > cosym > symmetry > scale or integrate > symmetry > scale doesn't work for more than one experiment, as the information about which reflections come from which experiment are getting lost when reindexed_reflections are output as a single table from cosym or symmetry.
I have only noticed this now, as usually I do dev.dials.assign_experiment_identifiers > cosym/symmetry. Also this is not an issue at the moment for xia2 where the ids are manually managed. 

I could update cosym and symmetry to call the experiment identifier setting code as a first step as scaling does, but am concerned that this would probably break other things in unexpected ways. Any thoughts?

**Comment by graeme-winter** [comment]
Thoughts are that this sounds like a fairly serious FIXME - probably something when defining the behaviour in an abstract manner then implementing to that abstract specification would be the way forward, in preference to trying to "fix" the problem. 

Happy to help with this process.

**Comment by jbeilstenedmands** [comment]
Actually for this dataset I can't even analyse with experiment identifiers set at the moment, as the identifier map isn't updated if datasets are removed from cosym, but that's a slightly separate issue I can work on now

**Comment by graeme-winter** [comment]
I would think starting from a flow diagram of what we want then implementing to this could be easier? i.e. if we have 
![dials flow chart](https://user-images.githubusercontent.com/1241716/48911114-c80be680-ee69-11e8-9d6b-0fdd8732eb61.png)

for multiple sweeps, what should be happening?
