### ISSUE TITLE
image viewer: request for a "play" button

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#661]
i.e. step through the images one at a time with some configurable delay. Also requested from DLS beamlines for Eiger work though more generally useful.

**Comment by ndevenish** [comment]
Yes. *But*, this needs us to sort out the performance issues with image viewer. Once those are gone it's a slightly natural progression to this.

Eventual improvements like this were one of the intentions behind splitting the core off so we can restructure it more fully.
