### ISSUE TITLE
dials.find_spots reports spots on 2 images for a single image

### ISSUE THREAD

**Issue by dagewa** [dials/dials#667]
This might be format specific, in that it doesn't appear to be an issue for BAG training cbfs. However, it does appear to affect at least some (all?) SMV format images:

`dials.find_spots $DIALS_REGRESSION/ESRF_ID231/q315r_7_001.img`

```
Found 33663 strong pixels on image 1

Extracted 5156 spots
Removed 3443 spots with size < 6 pixels
Removed 13 spots with size > 100 pixels
Calculated 1700 spot centroids
Calculated 1700 spot intensities
Filtered 1367 of 1700 spots by peak-centroid distance

Histogram of per-image spot count for imageset 0:
1367 spots found on 2 images (max 684 / bin)
```

Note
> Found 33663 strong pixels on image **1**

but
> 1367 spots found on **2** images (max 684 / bin)

**Comment by dagewa** [comment]
Ok, not format dependent, but depends on the min and max Z found for the single image (which should be == 0.5?)

https://github.com/dials/dials/blob/9a10a9202ea81838b932ae074474bf6086df5238/util/ascii_art.py#L34-L39

In the case I am looking at

```
In [5]: min_z
Out[5]: 0.49999991716938474

In [6]: max_z
Out[6]: 0.5000000577013091
```

**Comment by graeme-winter** [comment]
Reproduced, weird. Suspect is symptom of how histogram produced 

```
Histogram of per-image spot count for imageset 0:
1367 spots found on 2 images (max 684 / bin)
**
**
**
**
**
**
**
**
**
**
01
```

split evenly

**Comment by graeme-winter** [comment]
_I know what this is_ says he.

We dither to avoid resonances.

This

**Comment by graeme-winter** [comment]
Should not dither if #images < #bins

**Comment by rjgildea** [comment]
```
xmin = int(round(min_z + 1e-16)) 
xmax = int(round(max_z))
```

Perhaps these should be math.floor/ceil instead of round?

**Comment by graeme-winter** [comment]
Feel free to pick up, else will do

**Comment by dagewa** [comment]
The code attempts to not produce a histogram for 1 image (23cbfcd91), but num images is incorrectly calculated in this case. The fact that min_z and max_z are not exactly 0.5 is perhaps concerning too...?

**Comment by dagewa** [comment]
Rounding to, say, 5 decimal places fixes this case

```diff
-  xmin = int(round(min_z + 1e-16))
-  xmax = int(round(max_z))
+  xmin = int(round(min_z + 1e-16, 5))
+  xmax = int(round(max_z, 5))
```
But it seems surprising that `dials.find_spots` gives differences of > 1e-7 in the z values for a single image.
