### ISSUE TITLE
Error in reflection_manager.

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#67]
When doing stills indexing, a check is performed to reject reflections based on whether they lie outside a scan range. This results in an exception because there is no scan object. Commenting out lines 302-303 of algorithms/refinement/reflection_manager.py fixes this.

For example, 
cd /dls/i24/data/2015/nt11175-131/processing/dials/dials_west
dials.index index.phil datablock.json strong.pickle

**Comment by dagewa** [comment]
This can only occur when a goniometer is present and yet stills refinement is being performed (that's why it wasn't picked up before). I'll think about the tidiest way to fix this.
