### ISSUE TITLE
Avoiding loss of information after dials.two_theta_refine

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#670]
For multi-crystal work, a proposed post-integration workflow in DIALS might be:

1) Analysis of indexing ambiguities - dials.cosym
2) Determination of symmetry - dials.symmetry
3) Refinement of "best overall" unit cell - dials.two_theta_refine
4) Scaling - dials.scale

Passing the resulting refined_cell.json from dials.two_theta_refine to dials.scale ensures that the correct "best overall" unit cell is written into the output mtz files for downstream analysis, and that the correct (single) unit cell parameters are used for applying any resolution cutoff in scaling (so that the same miller indices are included/excluded for each sweep).

However, this results in the loss of information of the original individual unit cells and orientation, which would be useful for e.g. unit cell clustering analysis, and analysis of the distribution of the crystal orientation. dials.two_theta_refine overwrites the input crystal models with a single crystal model and orientation (presumably the orientation of the first experiment?) which is shared across all experiments. This seems like a bit of a hack, and could also lead to problems if the user tried to use the resulting file for further refinement or integration, as the predictions would be nonsensical.

I welcome suggestions for how we can improve the current situation.

**Comment by rjgildea** [comment]
Could we instead attach an additional crystal model attribute to the experiment list? E.g. experiment_list.best or experiment_list.overall?

**Comment by dagewa** [comment]
The fact that `dials.two_theta_refine` overwrites orientation sounds like a bug. This should be addressed anyway, whatever we do with the experiment list.

In the presented workflow `dials.two_theta_refine` is essentially doing a form of global post-refinement. Perhaps the dxtbx `Crystal` should have a new attribute, like `post_refinement_unit_cell`, or `best_unit_cell`, and `dials.two_theta_refine` should only alter that leaving each crystal's static model intact. That would avoid attaching additional attributes at the global experiment list level, which might get problematic if you later extended an experiment list with another (for whatever reason).

**Comment by graeme-winter** [comment]
Extending the crystal to have an explicit "best" unit cell seems like a neat solution - at the moment do we keep the cell constants in a unit cell or a B matrix? If we were to keep the two separate conceptually then we could update only the cell in global cell refinement and continue to use the B for predictions etc.

Then when you update B you would update the cell, but updating the cell would not apply the same modifications. So getting the cell constants should always give best values. 

Need to review how these are modelled. 

I could see this being useful also if you process everything in P1 but want to use the globally refined cell in e.g. P4 for estimating resolution of reflections.

**Comment by graeme-winter** [comment]
Currently modelled as 

```
  "crystal": [
    {
      "__id__": "crystal", 
      "real_space_a": [
        57.07339145998769, 
        51.22640189487629, 
        45.58700478936758
      ], 
      "real_space_b": [
        83.3434138017003, 
        -56.64272888637999, 
        -40.60705989148142
      ], 
      "real_space_c": [
        5.879404781127044, 
        71.32251224510499, 
        -87.46562987418542
      ], 
      "space_group_hall_symbol": " P 1", 
      "B_covariance": [
        2.8724639161618914e-14, 
        1.585403522356684e-30, 
----- 8< ----- (numbers)
        6.223117041295225e-16, 
        8.614859044450528e-17, 
        2.0775992844763132e-14
      ]
    }
  ], 
```

so effectively collapsed to A = UB => cannot update cell without somehow modifying orientatation

**Comment by dagewa** [comment]
Further discussion suggests we need a new attribute that can be set at the experiment list level, to cover multiple crystals. It would be worth following the lead of scaling output here, which already sets information across multiple experiments. I propose that this cell be stored in the form of a B-matrix, along with its refinement errors if available from `dials.two_theta_refine`.

**Comment by dagewa** [comment]
After thinking the design through some more, I no longer think setting the "best cell" for groups of crystals at the global experiment list level is the best approach. While it does suit the joint refinement case, it doesn't make much sense in the situation where `dials.two_theta_refine` is used after integration to refine a _single_ crystal's cell. Instead, we can set the "best cell" as a new attribute of the `Crystal`. For the multi-crystal use case presented above this implies refining a single cell which is then set for every crystal involved.
