### ISSUE TITLE
dials.find_spots should work with experiments as input

### ISSUE THREAD

**Issue by dagewa** [dials/dials#674]
This would allow the following workflow:

import, find spots, index, refine...

[At this point better geometry determined (better resolution rings etc)]

determine mask, apply mask (#673), find spots, index, refine, integrate

**Comment by dagewa** [comment]
#545 is also relevant. If import of crystal-less experiments is possible, then find_spots has to support this anyway

**Comment by rjgildea** [comment]
This is already implemented in https://github.com/dials/dials/pull/613

**Comment by jmp1985** [comment]
Since this is implemented in the #613 and will be available in dials 2.0, I'm going to close this issue.
