### ISSUE TITLE
Error in stills prediction

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#68]
When doing refinement on stills an exception occurs in the file algorithms/spot_prediction/stills_ray_predictor.h at line 67 "DIALS_ASSERT(tmp > 0.0)". It looks like this is checking whether a reflection can be rotated into the Ewald sphere. Presumably, this should be used to reject certain reflections from prediction; however, it causes the rest of refinement to crash.

For example:
cd /dls/i24/data/2015/nt11175-131/processing/dials/dials_west
dials.refine experiments.json indexed.pickle

**Comment by dagewa** [comment]
This was caused by passing 0,0,0 miller indices into the predictor. We decided to keep the current behaviour (fail on assert)
