### ISSUE TITLE
Distil wisdom on our PHIL parameter expert level convention

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#684]
Can we add some developer documentation (in the wiki perhaps?) on what we meaning we attribute to different PHIL parameter expert levels?  Do we just use `1` for muggles, `2` for wizards (`3` for teachers of defence against the dark arts?).

**Comment by rjgildea** [comment]
The default (i.e. no expert_level defined) is expert_level = 0

**Comment by dagewa** [comment]
As far as I know, we have never really defined guidance, but it is a good idea and is very relevant and timely for how things are presented to users in e.g. [DUI](https://github.com/ccp4/DUI/) (and see also #662)

For the xia2 task in ccp4i2 I have two groups: `expert_level` level missing or explicitly == 0 creates the basic interface, advanced additionally includes `expert_level=1`, and everything above that is removed entirely. This is not very fine-grained, but works ok for something like xia2.

For DIALS I would suggest something a bit more along the lines of

- **0** Basics: filenames, certain algorithm choices like fft1d/fft3d indexing, resolution limits etc.
- **1** Proficient user: spot-finding parameters, override geometry at import
- **2** Expert user: Things like set `sigma_m`, `sigma_b`
- **3** Developer: Almost everything else except...
- **4+**  _"My special advanced option, seek_and_destroy_kittens=True, do not use!"_

User interfaces should make it reasonably easy to access options up to **2**.

**Comment by benjaminhwilliams** [comment]
Sorry for being slow to pick up on this.  Good suggestions @dagewa, thank you.  I've added this (including the xia2-specific) advice to the DIALS wiki.
