### ISSUE TITLE
dials.integrate pixel masking should use scan varying models

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#697]
Pixels in the refined reflections shoebox are masked if they are closer to adjacent reflections than than the reflection itself. This masking is done using the static models, this should use the scan varying models. This came up after problems integrating a dataset using a scan varying beam model. @dagewa suggests a sanity check should also be added for the scan varying models.

**Comment by graeme-winter** [comment]
@jmp1985 any news on this? Seems like something which should be fixed...
