### ISSUE TITLE
Decide on best general way for DIALS programs to return objects (when called via functional interface) or write to file (when called as standalone programs from the command-line)

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#702]
Now that we have some agreed boilerplate for a functional interface, we still have the outstanding question of whether/how to return objects.  Are there situations in which we would like to return an object without writing to file?  This may become complicated in cases where, at present, the file output is conditional (as in the case of the modified (masked) datablock from `dials.find_spots output.datablock=something.json ...`).

**Comment by phyy-nx** [comment]
@benjaminhwilliams cctbx has recently added a program template that includes a data manager, i.e. a bucket for various kinds of data:

https://cctbx.github.io/libtbx/libtbx.program_template.html

The data manager is an object that holds whatever data is being used by the program.  It's basically a fancy bookkeeping mechanism that separates file IO from program logic and user interfaces.  A dials 'data manager' would have a reflection table and experiment list, but could also have other things, and could easily be passed between programs.  The data manager consistently handles error trapping and unicode paths.

Again, the data manager is a bucket that holds data.  The bucket can be specialized to handle different data types, but the general interface of passing around a data manager is consistent.

I'm not saying use the cctbx data manager (it's likely more complicated than is necessary for DIALS), but the concept of data bucket may be useful here.

**Comment by benjaminhwilliams** [comment]
Thanks @phyy-nx.  Really, I was just wondering about giving each DIALS script a `return` statement (and how to handle the more gnarly cases of conditional returned values) and also whether to make it possible for file output from intermediate stages to be optional in some cases where the pipeline is automated, like in xia2.

The concept of keeping track of a program's associated data with a sort of archivist object is nice, and something I'll look into, but I think its scope is broader than was intended for this task.  We're in the process of identifying features for the next major release of xia~2~(3?), so I'll add it to the list of design decisions to be made.  Thanks for the suggestion!
