### ISSUE TITLE
dials.generate_mask doesn't work on ExperimentList

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#711]
I wanted to build a mask based on a reference data geometry that I'd just refined. I needed to reimport. This is probably important also if we're moving away from datablocks.

```
$ dials.generate_mask refined_experiments.json resolution_range=2.13,2.08 resolution_range=1.84,1.80 rectangle=0,840,810,850
...
Sorry: Unable to handle the following arguments:
  refined_experiments.json did not appear to conform to any  expected format:
    - DataBlock: Expected __id__ 'DataBlock', but found 'ExperimentList'
```

**Comment by rjgildea** [comment]
I believe it should do in the dials-2.0 branch: https://github.com/dials/dials/blame/dials-2.0/command_line/generate_mask.py#L64

**Comment by jmp1985** [comment]
I can confirm that this does work in dials-2.0 branch
