### ISSUE TITLE
DIALS 2 documentation changes

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#714]
Currently we build the documentation from the installer, which takes a considerable amount of time and means we can only update the documentation once a day, unless we also build a new installer.
Building the documentation also depends on DIALS itself, which means it is basically impossible to build it using online tools.

* Move the output files created by ```dev.dials.generate_tutorial_text``` into a separate repository
* See if we can use [ReadTheDocs](https://readthedocs.org/) to build the documentation rather than Jenkins
* Drop explicit documentation dependencies from ```libtbx_config```/```libtbx_refresh.py```

**Comment by ndevenish** [comment]
It'd be nice to use the RTD versioned documentation to have a stable and "dev" version of the documentation. Not that there is a lot of difference right now, but would make it easier in the future.

**Comment by Anthchirp** [comment]
* check if we can move screenshots there, too. Would prefer not having those in the code repository.

**Comment by Anthchirp** [comment]
Discussed with @ndevenish. Outcome so far is to move the entire ```/doc```* tree plus the generated DIALS output to a separate repository which will (or: can) be added to the dials repository as a submodule. The generated DIALS output is maintained/updated by Jenkins, and the submodule link can also be maintained/updated by Jenkins whenever the actual documentation changes.

Then build it and host it on RTD.


* ND prefers writing it as ```doc/```, but we mean the same thing.

**Comment by Anthchirp** [comment]
This is all nice and feasible until you hit the stumbling block of libtbx.sphinx plugins.
There are 3 of them:
#### libtbx.sphinx.pubmed
Reference lookup mechanism. Looks easily extractable into the documentation repository itself, so no problem.
#### libtbx.sphinx.python_string
Imports a file and then extracts a string variable from it. Could be extracted into the documentation repository and the libtbx import mechanism could be replaced by ast parsing which does not require files to be importable, so again not a big problem
#### libtbx.sphinx.phil
Adds dependencies on libtbx and iotbx, requires files to be importable which means it adds dependencies on everything, and this is a big problem.

I can only see three ways out of this:
1. dropping phil and finding another mechanism to do configuration and generate documentation - not going to happen.
2. making DIALS a real installable package - not going to happen for a long time
3. preprocessing the documentation from within a DIALS environment to the replace the phil placeholders with the real information - not sure how to do this and wondering whether that makes the entire process too complex.

It may be easier to come up with our own versioning mechanism on dials.github.io

**Comment by Anthchirp** [comment]
Resolution: Copy existing site to dials.github.io/1.14 or so, which will no longer be updated. Link to tutorials/build pages there for 1.14 users

**Comment by Anthchirp** [comment]
Dials tutorial output generation and documentation building are now separated.

The tutorial output is generated into https://github.com/dials/dials.github.io/tree/master/tutorial_data and updated once a week.

**Comment by Anthchirp** [comment]
DIALS 1.14 tutorials are now available at https://dials.github.io/dials-1.14/documentation/tutorials/index.html, which is separately built from the main documentation on the root level.

**Comment by Anthchirp** [comment]
https://dials.github.io/documentation/tutorials/index.html
Current tutorials link to 1.14 versions.
1.14 versions link to current tutorials.

Basically this is done.

Not so nice side effect: the download links for the most current DIALS releases on the master version of the documentation is now static and needs to be updated manually. I guess I'll address this some other time.
