### ISSUE TITLE
Reflection flags are undocumented

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#718]
I'm collating information on the as-yet undocumented DIALS reflection flags.  @jmp1985, @jbeilstenedmands and @dagewa wrote them.  Could you please flesh out this table with info on their designed purpose?

[Reflection flags documentation on the DIALS wiki](/dials/dials/wiki/Reflection-flags)

Sorry if the formatting of that table is rather mangled by constraints of the Github wiki layout.

**Comment by dagewa** [comment]
The `scaled` flag is not currently documented.
