### ISSUE TITLE
dials.import please can we understand xia2 syntax

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#726]
I appreciate that xia2 and dials.import are _different_ programs but it would be real nice to have

```
dials.import /tmp/thing_master.h5:1:1800 
```

actually work

**Comment by graeme-winter** [comment]
Alias to

```
dials.import /tmp/thing_master.h5 scan.image_range=1,1800
```

**Comment by dagewa** [comment]
One problem with this is that for one image per file cases `dials.import th_8_2_0*cbf:1:20` does not get the shell expansion of `th_8_2_0*cbf`. Still, it could be done here:
https://github.com/dials/dials/blob/cb1759bcfbe9b7eefc378d4d8aab23f33707c108/util/options.py#L435-L437
with those elements of `args` that have the form `image_file*.ext:start:end` being expanded into `image_file_001.ext`, `image_file_002.ext` etc. by `glob`, and `start` and `end` being kept track of and then being set in `params.geometry.scan.image_range` here:
https://github.com/dials/dials/blob/cb1759bcfbe9b7eefc378d4d8aab23f33707c108/util/options.py#L495-L496

The question is whether this is worth it?

**Comment by dagewa** [comment]
My view is that we have enough issues with filename handling (#600, #563, cctbx/dxtbx#133 etc.) that adding more syntax to parse will be unhelpful. Please reopen if you disagree.
