### ISSUE TITLE
Why no Sorry?

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#729]
Apparently using libtbx `Sorry` exception in DIALS code has now been unilaterally decided to A Bad Thing. Why is this? See e.g. ~~https://github.com/dials/dials/commit/2d69451640099755064897b93401afe57d2002f0 [didn't keep this - Nick]~~

To me it seems a sensible way to distinguish between user errors (or problems in user input) that shouldn't raise a traceback, and programming errors which should raise a traceback. If not `Sorry`, then what mechanism should we be using instead?

Usage of Sorry is already quite engrained in DIALS code:
```
$ find . -name "*.py" -type f | xargs grep "raise Sorry" | wc -l
     289
```

**Comment by ndevenish** [comment]
Note that that was an interim commit, but based on second or third hand information that `Sorry` had been decided to be 'bad', so suspect some element of chinese whispers here.

**Comment by Anthchirp** [comment]
my £.02: in my view there are two cases which should be treated differently.

1. code in ```dials/command_line```

At times there is no need to show the user tracebacks. Throwing ```Sorry``` is perfectly reasonable.

With the caveat that ```Sorry``` adds a potentially expensive import dependency and relies on some special trace-dropping generic exception handler being installed. Both of which is completely unnecessary, as you can get the exact same effect with either ```sys.exit("message")``` or ```raise SystemExit("message")```. So I have replaced ```libtbx.util.Sorry``` in all of DIALS with ```dials.util.Sorry``` (7b8cd72632d61db49c3ce07240f77e703ce14b8f) with the view of having dial's ```Sorry``` become a subclass of ```SystemExit```.

2. code everywhere but ```dials/command_line```

Now we're in functional interface land. Code here should be treated as a library. Libraries do not throw ```SystemExit()```. They throw [everything else that Python allows throwing](https://docs.python.org/2/library/exceptions.html#exception-hierarchy), custom exception types if appropriate. If errors should not result in a trace then I believe this should be caught and dealt with at the user-facing layer, ie the stuff in ```dials/command_line```.

**Comment by ndevenish** [comment]
So what's your preference for functional command_line, which bridges both of these?

**Comment by ndevenish** [comment]
Because it arose because it's technically an API call, but needs to distinguish between throwing a call to show to the user and actual errors that might have bubbled up from underneath.

A compromise seemed to be a custom exception but ISTR you are against those for various reasons some of which I agree with? Exception handling/naming is one of the areas we don't seem to converge on easily...

**Comment by Anthchirp** [comment]
may need discussing what exactly you understand by _functional command_line_. If contains no processing logic and is called by user then anything goes. If contains processing logic and is called by function then 2) applies.

Custom exceptions...
I do not mind very much, especially when they are derived from the closest sensible existing one.
But they must not follow a naming pattern of ```DIALS*Exception``` and should not be defined in ```dials/exception.py``` 😊

**Comment by ndevenish** [comment]
I mean https://github.com/dials/dials/projects/10

**Comment by graeme-winter** [comment]
Surely for functional interface stuff, we have:

```
def useful_thing(args)
  '''I am a library function'''
  raise ValueError("args is not 4")

def main():
  "human facing code"

  # check args
  if args is bad:
    raise Sorry("human readable error")

  try:
    useful_thing(args)
  except exception as e:
    # do something with stack trace - dials.function.error file? <-- can send to devs
    raise Sorry(e)
```

?

**Comment by graeme-winter** [comment]
Even better [1] would be having 

```
dials/command_line
```

be the only place we use Sorry, and have this only contain thin wrappers over e.g. 

```
dials/functional_interfaces
```

or similar which contain the actual logic => cleaner separation of UI code

[1] IMHO of course

**Comment by Anthchirp** [comment]
That's how I understood the general aim of the project. Where those interfaces live is of course a matter of ~bikeshed~ taste (```dials/functional_interfaces``` vs ```dials/algorithms/*```).
However I thought more of
```
  try:
    useful_thing(args)
  except IndexError:
    sys.exit("This stuff does not index.")
```
so any unexpected exceptions will still give you a trace plus "plz email" output - I find that more useful than "please send us this file" which will invariably result in a screenshot contained in a word document.

**Comment by dagewa** [comment]
Are there any conclusions here? Is this something we want to tidy up for DIALS 2.0?

**Comment by Anthchirp** [comment]
I think there was general agreement, but I think it needs writing up itot in some kind of code style guide (which we discussed previously as something that might be useful)
