### ISSUE TITLE
deprecate idials?

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#732]
Is idials still used?
@ndevenish suggested to ask @jmp1985 and @luisodls

**Comment by jmp1985** [comment]
According to Luiso it's not used in dui so currently not really used anywhere else.

**Comment by luisodls** [comment]
As long as it stays in the history, so I can study it eventually. I don't mind deprecating it, and blowing it up.

git already keeps the history for us, but if we want to keep it with an academic purpose, maybe we can move it to scratch.

**Comment by ndevenish** [comment]
This seems to be a go for elimination

**Comment by graeme-winter** [comment]
![image](https://user-images.githubusercontent.com/1241716/54361403-d53e2280-465e-11e9-82d6-685d5518f441.png)

**Comment by graeme-winter** [comment]
This was not called execution. It was called retirement.

**Comment by Anthchirp** [comment]
opening the git rm bay doors
