### ISSUE TITLE
Beam centre info going missing in reciprocal_lattice_viewer and image_viewer?

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#747]
Problem only in DIALS 2.0, absent in 1.14, suspect datablock->expt lists has chucked useful beam centre info for multiple sweep datasets **(TEST AGAINST MULTIPLE SWEEP DATASETS?!)**

To reproduce, process a multiple-sweep dataset with different beam centres on different sweeps (i.e. different detector 2θ positions), such as a typical I19 dataset:  https://zenodo.org/record/51405#.XKdNaFVKiV4

View images in image_viewer or take a look at reciprocal space with reciprocal_lattice_viewer.

Some spots in r_l_v are sane, some are not.  Beam centre for the sweep read first appears OK in image_viewer.  In subsequent sweeps the beam centre does not shift when the detector does.  Perhaps info on beam centre is taken from the first imageset only.

Filed in haste.

**Comment by benjaminhwilliams** [comment]
![Peek 2019-04-05 13-29](https://user-images.githubusercontent.com/11389015/55628673-37df9580-57a9-11e9-9ac7-940d58d73e6a.gif)
![Screenshot from 2019-04-05 13-50-01](https://user-images.githubusercontent.com/11389015/55628866-bc321880-57a9-11e9-9c10-0e27a6e8a2b7.png)
![Screenshot from 2019-04-05 13-50-21](https://user-images.githubusercontent.com/11389015/55628877-c3592680-57a9-11e9-8e5f-6603ee63c98a.png)

**Comment by rjgildea** [comment]
It looks like the RLV code still uses imagesets, when it would be better off using experiments.

**Comment by benjaminhwilliams** [comment]
A working fix to #806 fixed this.  We still use imagesets, but it's good enough for now.
