### ISSUE TITLE
Strange output in dials.integrate

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#75]
275 [20  ]:
 276 [56  ]: **
 277 [84  ]: ***
 278 [104 ]: ****
 279 [130 ]: ******
 280 [154 ]: *******
 281 [178 ]: ********
 282 [206 ]: *********
 283 [232 ]: **********
 284 [261 ]: ************
 285 [289 ]: *************
 286 [314 ]: **************
 287 [354 ]: ****************
 288 [376 ]: *****************
 289 [400 ]: ******************
 290 [429 ]: *******************
 291 [451 ]: ********************
 292 [481 ]: **********************
 293 [506 ]: ***********************
 294 [527 ]: ************************
 295 [558 ]: *************************
 296 [578 ]: **************************
 297 [608 ]: ****************************
 298 [646 ]: *****************************
 299 [670 ]: *******************************
 300 [1446]: *******************************************************************
 301 [1417]: *****************************************************************
 302 [1394]: ****************************************************************
 303 [1369]: ***************************************************************
 304 [1350]: **************************************************************
 305 [1335]: *************************************************************
 306 [1311]: ************************************************************
 307 [1286]: ***********************************************************
 308 [1264]: **********************************************************
 309 [1226]: ********************************************************
 310 [1201]: *******************************************************
 311 [1169]: ******************************************************
 312 [1147]: *****************************************************
 313 [1112]: ***************************************************
 314 [1084]: **************************************************
 315 [1058]: *************************************************
 316 [1025]: ***********************************************
 317 [1001]: **********************************************
 318 [978 ]: *********************************************
 319 [946 ]: *******************************************
 320 [916 ]: ******************************************
 321 [890 ]: *****************************************
 322 [868 ]: ****************************************
 323 [848 ]: ***************************************
 324 [809 ]: *************************************

**Comment by jmp1985** [comment]
[data.zip](https://github.com/dials/dials/files/128317/data.zip)

**Comment by dagewa** [comment]
Hi James, what was the cause of this? It came from something I was looking at with Pierre. Cheers, David

**Comment by jmp1985** [comment]
Hi David,

The result of this is that the block size is < the size of most of the reflections. Looking at the histogram of reflection sizes, most covered > 40 images! I think this is from data where pierre was inputting the refined_experiments.json with the indexed.pickle files and this was resulting in some weird behaviour. I think Pierre reran the processing  with the correct combination of files so it would be interesting to see if the same behaviour is observed.

James
