### ISSUE TITLE
dials.refine parameter naming confusion

### ISSUE THREAD

**Issue by dagewa** [dials/dials#750]
Parameter fixing via the `fix_list=` specification uses full parameter names including a prefix that specifies which model each parameter refers to. These names can be identified from the `dials.refine.debug.log`. For example, for experiments including two beams, setting `beam.fix=None` includes every possible beam parameter for refinement, and lists them by name in lines like this:

```
Parameter 013 : Beam1Mu1
Parameter 014 : Beam1Mu2
Parameter 015 : Beam1nu
Parameter 016 : Beam2Mu1
Parameter 017 : Beam2Mu2
Parameter 018 : Beam2nu
```

If I only want to refine `Beam2nu`, I could set up the job like this:
```
dials.refine ... beam.fix=None beam.fix_list=Beam1nu,Mu
```

This is confusing for at least two reasons. The first is that `beam.fix=None` is used in order to wipe out the default fixes for Beam models (`Mu1` and `nu`) and leave everything free, before the `fix_list` takes effect. It is not obvious that it works in this order though, and not that `beam.fix=None` overrides the `fix_list`.

The second is that this specification ends up fixing every parameter of Beam1 (`Beam1Mu1`, `Beam1Mu2`, `Beam1nu`). In that situation, no parameterisation is created for Beam1, only for Beam2, but because this is the first and only Beam parameterisation the parameters then get named `Beam1Mu1`, `Beam1Mu2` and `Beam1nu`. As a result, the dials.refine.debug.log shows only one beam parameter as expected:
```
Parameter 013 : Beam1nu
```
but the naming is confusing. We asked for `Beam1nu` to be fixed, but the `fix_list` refers to the full possible set of free parameters, not the names that they might end up being given in a refinement job that includes some constraints.

It may be time to overhaul the system for fixing/freeing parameters entirely.

**Comment by jbeilstenedmands** [comment]
I wonder if having experiment identifiers will help here, as then there is a strong tie to a given dataset.
Perhaps a phil option of style
refine_parameter=expid:model:parameter might help.
(.type = strings, .multiple = True) 
e.g refine_parameter=1:Beam:Nu
Then you just need a simple custom parser to split on the colons.
Maybe you could also have the option fix_parameter=expid:model:parameter.
These are then mutually exclusive, you can have either one or the other, and the assumption is that any that aren't specified as fixed are refined and vice versa. Maybe this is not suitable for your case but I found this style of phil option helpful for specifying image exclusion in dials.util.exclude_images

**Comment by dagewa** [comment]
Yes, I think experiment identifiers might be the key here, thanks. As a first pass I can perhaps just replace the serial number in e.g. `BeamN` with the experiment identifier, which makes problem 2 go away. Then after that, address an improved interface to parameter fixing/freeing

**Comment by dagewa** [comment]
What is the plan for experiment identifiers? I just looked at a multi-experiment experiment list and found that `e.identifier == ''` for all `e in experiments`, so I guess these are not being set yet?

**Comment by jbeilstenedmands** [comment]
No these are not being set by default yet, I think this is a to-do for DIALS 2.0 but requires some more planning as to the implementation and making sure the correct thing happens at all points where experiments can be split. We're starting to use these in cosym, scaling but using a function defined in dials.util.multi_dataset_handling. The current implementation probably won't be general enough to work for all cases though.

**Comment by dermen** [comment]
So if one has many experiments (too many to manually list), then one would need to programmatically generate the fix_list (or refine_list) ?

**Comment by dagewa** [comment]
On second thoughts, I'm backtracking on experiment identifiers being the solution here. The issue is that models are shared between experiments, so maybe I have 1000 experiments but just two beam models. I would like these to be Beam1 and Beam2, and not N:Beam and M:Beam where N and M are arbitrarily chosen from the list of experiments that contain either Beam1 or Beam2.

I have a fix in development that solves the second issue described above, by naming the models once at the start, so even if the parameterisation for Beam1 is eventually dropped, Beam2 will not then get renumbered Beam1 when the report is printed. 

At the moment, fixing parameters is done by partial name matching, so if I want to fix the Phi parameters for every crystal I could just put `fix_list=Phi`, which will automatically match Crystal1Phi1, Crystal1Phi2, Crystal1Phi3 and so on for every CrystalN. It is therefore rare to have to write a very long `fix_list` - that would only be necessary if you wanted special constraints for a subset of some large number of models. But often that case can be looked after by e.g. `auto_reduction.action=fix`.

Still thinking about how best to do this, but I think the incoming fix solves the worst of the confusing issues.

**Comment by dagewa** [comment]
I think this can be closed. Possible future improvements to the parameter constraints and restraints interfaces could be addressed separately as an enhancement, but I don't think the need is pressing.
