### ISSUE TITLE
Suboptimal spot-finding parameters can negatively impact integration

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#752]
In some cases integration results appear to be very sensitive to spot-finding parameters.

An example case is for a germanate dataset from DLS beamline I23.

Raw image:
![image](https://user-images.githubusercontent.com/2810624/55895566-5207e200-5bb4-11e9-9754-b67df09ff3b2.png)

Threshold map with default spot-finding parameters:
![image](https://user-images.githubusercontent.com/2810624/55895624-6b109300-5bb4-11e9-802b-426b57709edc.png)

Threshold map with kernel_size=20,20 sigma_b=10 sigma_s=5:
![image](https://user-images.githubusercontent.com/2810624/55895675-88456180-5bb4-11e9-9e2a-adb09780abb4.png)

1) Process with default parameters:
```
$ xia2 anomalous=True read_all_image_headers=False image=/dls/i23/data/2019/nr23017-1/20190302/germ_9keV/data_1_0001.cbf
```
2) Process with larger kernel size for spotfinding:
```
$ cat find_spots.phil 
spotfinder {
  filter.max_spot_size=10000
  threshold {
    dispersion {
      kernel_size = 20 20
      sigma_background = 10
      sigma_strong = 5
    }
  }
}
$ xia2 anomalous=True read_all_image_headers=False dials.find_spots.phil_file=find_spots.phil image=/dls/i23/data/2019/nr23017-1/20190302/germ_9keV/data_1_0001.cbf
```

Comparison of the results show markedly improved I/sigI and merging R-factors for the larger kernel size in spotfinding:
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/55895737-af9c2e80-5bb4-11e9-8bb3-24de618fed04.png)
![r_pim](https://user-images.githubusercontent.com/2810624/55895751-b3c84c00-5bb4-11e9-804e-3564f4c4ab6c.png)

Profile model determined using default spot-finding parameters:
sigma b: 0.042689 degrees
sigma m: 0.076268 degrees

Profile model determined using modified spot-finding parameters:
Modified spot-finding parameters:
sigma b: 0.062064 degrees
sigma m: 0.107637 degrees

**Comment by rjgildea** [comment]
With the larger kernel size in spotfinding, the <Ibg> reported by dials.integrate is lower, suggesting that if the kernel size is too small, then signal is leaking into the background:
![i_bg](https://user-images.githubusercontent.com/2810624/55897490-82ea1600-5bb8-11e9-8d28-8d07b60e735f.png)

**Comment by rjgildea** [comment]
Comparison of processing results with varying kernel sizes used in spot-finding:
```
$ cat run.sh 
module load global/testcluster

first_image=/dls/i23/data/2019/nr23017-1/20190302/germ_9keV/data_1_0001.cbf

for n in 3 5 10 15 20 25 30 35 40 45 50
do
    echo $n
    mkdir kernel_$n
    cd kernel_$n
    cat > find_spots.phil << EOF
spotfinder {
  filter.max_spot_size=10000
  threshold {
    dispersion {
      kernel_size = $n,$n
      sigma_background = 10
      sigma_strong = 5
    }
  }
}
EOF

    cat > run.sh << EOF
module load dials/latest
xia2 anomalous=True read_all_image_headers=False \
  dials.find_spots.phil_file=find_spots.phil \
  image=$first_image
EOF
    qsub -q medium.q -pe smp 4 run.sh
    cd ../
done
```
Rpim appears to keep on improving up to kernel_size=20,20, while I/sigI improves further still with larger kernel sizes:
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/55946392-9478ff80-5c44-11e9-9d2a-4417d87f8232.png)
![r_pim](https://user-images.githubusercontent.com/2810624/55946421-9a6ee080-5c44-11e9-930a-fbb2b56245e6.png)

Plot of sigma b and sigma m vs kernel size:
![chart](https://user-images.githubusercontent.com/2810624/55947287-1289d600-5c46-11e9-9714-715d9e0419b3.png)

**Comment by ndevenish** [comment]
So, I assume that this is driven by the indexing result? Unless I'm completely wrong - I was under the impression that the only information that drove integration was the predicted centroids e.g. cell parameters - themselves driven by the indexing/refinement. Shouldn't spotfinding kernel size be reasonably removed from this? (not questioning findings, just confused how the information is leaking through).

**Comment by biochem-fan** [comment]
My understanding is that estimation of `sigma_m` and `sigma_b` uses strong pixels from spot finding.

I and @keitaroyam have observed similar issues on MicroED datasets.

**Comment by rjgildea** [comment]
@ndevenish have a look at section 3.1 of http://journals.iucr.org/d/issues/2010/02/00/dz5178/index.html which describes the XDS algorithm for determination of profile parameters. Essentially all strong pixels contribute to the calculation of sigma b and sigma m.

**Comment by graeme-winter** [comment]
Our implementation is different to the Kansan 2010 description however the phenomenon is similar. Tricky problem is coming up with a heuristic to arrive at a sensible kernel size. Share same problem with small molecules data. 

Should also dig out data with a large cell and finer spots to get the counter case i.e. what goes bad when you have too large a kernel?

**Comment by rjgildea** [comment]
I04 Thaumatin EIGER dataset:
image=/dls/i04/data/2019/cm23004-1/20190109/Eiger/gw/Thaum/Thau_4/Thau_4_1_master.h5
![cc_one_half](https://user-images.githubusercontent.com/2810624/56199158-42651f00-6034-11e9-9a3d-499c0bd31e15.png)
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/56199166-46913c80-6034-11e9-8217-ca6b922f8caa.png)
![r_pim](https://user-images.githubusercontent.com/2810624/56199175-4a24c380-6034-11e9-9c4a-6e10c436f18e.png)
![chart-1](https://user-images.githubusercontent.com/2810624/56199199-56a91c00-6034-11e9-9302-18d42a67a6dc.png)

**Comment by rjgildea** [comment]
I04 Thaumatin pilatus (the dataset formerly known as i04_bag_training)
image=/dls/science/groups/scisoft/DIALS/dials_data/thaumatin_i04/th_8_2_0001.cbf
* for kernel_size=40 and 45 xia2 incorrectly chose a lower symmetry space group

![cc_one_half](https://user-images.githubusercontent.com/2810624/56199415-c61f0b80-6034-11e9-8e13-2c97f57ea2ac.png)
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/56199428-cddeb000-6034-11e9-8e29-ae5bc65222fd.png)
![r_pim](https://user-images.githubusercontent.com/2810624/56199445-d33bfa80-6034-11e9-97fd-fc7da6551fa2.png)
![chart-2](https://user-images.githubusercontent.com/2810624/56199516-f666aa00-6034-11e9-8267-38712895388c.png)

**Comment by rjgildea** [comment]
"X4_wide" dataset:
image=/dls/science/groups/scisoft/DIALS/dials_data/x4wide/X4_wide_M1S4_2_0001.cbf
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/56199669-3d549f80-6035-11e9-9f5a-ed8115f06392.png)
![r_pim](https://user-images.githubusercontent.com/2810624/56199675-40e82680-6035-11e9-857a-784f2de6e988.png)
![chart-3](https://user-images.githubusercontent.com/2810624/56199704-52c9c980-6035-11e9-896f-fb2be3b32992.png)

**Comment by rjgildea** [comment]
VMXi thaumatin
image=/dls/science/groups/scisoft/DIALS/dials_data/vmxi_thaumatin/image_15799_master.h5
![cc_one_half](https://user-images.githubusercontent.com/2810624/56199775-7725a600-6035-11e9-8d97-57da2f0a9ea0.png)
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/56199837-8f95c080-6035-11e9-8c00-e890c1623af5.png)
![r_pim](https://user-images.githubusercontent.com/2810624/56199850-945a7480-6035-11e9-9b8b-0a65f398c623.png)
![chart-4](https://user-images.githubusercontent.com/2810624/56199876-a0463680-6035-11e9-8bd9-d3b5370ecd54.png)

**Comment by rjgildea** [comment]
Insulin dataset:
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/56200001-e26f7800-6035-11e9-9041-b2d884adddbc.png)
![r_pim](https://user-images.githubusercontent.com/2810624/56200020-ea2f1c80-6035-11e9-9f58-ccd76df5cffb.png)
![chart-5](https://user-images.githubusercontent.com/2810624/56200109-0e8af900-6036-11e9-88cb-2b4cf7b61c73.png)

**Comment by jmp1985** [comment]
I've been having a look at the spot finding to see what effect changing the kernel size has. In some cases, it looks like having a larger kernel can result in a more noisy threshold image. For example, this is for the original dataset posted with a 50x50 kernel and sigma_background=10 and sigma_strong=5. I also see a similar effect for the IO4 bag training data. 
![data_1_0001_50x50_10_5](https://user-images.githubusercontent.com/2241889/56201014-de445a00-6037-11e9-9307-e30b8189a24e.png)

**Comment by rjgildea** [comment]
I03 ProtK EIGER:
image=/dls/i03/data/2019/cm23003-2/proteinasek/protk_1_7/protk_1_7_1_master.h5
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/56203260-c6230980-603c-11e9-9202-de92e06fcd55.png)
![r_pim](https://user-images.githubusercontent.com/2810624/56203271-cb805400-603c-11e9-8ab1-7d5cb851c0a9.png)
![chart-6](https://user-images.githubusercontent.com/2810624/56203299-d9ce7000-603c-11e9-921b-b640915cfff3.png)

**Comment by alyubimov** [comment]
This is very interesting! There was a similar issue with the 2014 version of cctbx.xfel (in that case, image processing was very sensitive to spot_height and spot_area parameters), which we solved by a grid search and a two-step "best result" selection heuristic (using the Ewald Proximal Volume and number of strong spots). Here's the article: https://www.ncbi.nlm.nih.gov/pubmed/27275148

Richard, do any of your test datasets exhibit significant image-to-image variability of spot sizes and shapes? This is fairly typical for small datasets from fixed-target serial experiments, which is what led us to developing the grid search approach. If you want such a test dataset, the one that really benefitted from the grid search approach is here: https://data.sbgrid.org/dataset/365/

**Comment by dagewa** [comment]
If this is merged, can it be closed?

**Comment by rjgildea** [comment]
The PR was merged, but the default was reverted to the old algorithm in caa46334d385499ee50214ea1776f6cdcb7d0453, so this issue should remain open until we use the new algorithm as default.

**Comment by Anthchirp** [comment]
Issue that caused the reversion was https://github.com/dials/dials/issues/816

**Comment by dagewa** [comment]
Discussing this at the DIALS catch up. General agreement that the improved spot finding improves data in _most_ cases. The failures due to increased memory use will be solved by #833 and related work on integration.

**Comment by rjgildea** [comment]
Does anyone object to setting the new algorithm as default?

**Comment by phyy-nx** [comment]
#816 is still open though?

Lemme try an xfel test today.  I'll post some results by end of day.

**Comment by rjgildea** [comment]
#816 is really a separate issue about integration memory issues, which should in theory be resolved/improved by the threaded integrator (which also is still not default - see #833). The issue only arises in that specific case because spotfinding does a better job of finding strong pixels, and hence leads to better (i.e. larger) profile model parameters. Integration only worked before because spotfinding did a bad job!

I don't think the integration memory issues should have any impact on xfel datasets.

**Comment by phyy-nx** [comment]
Re: #816, gotcha thanks.

The test I'm running this morning is on one of the thermolysin runs from
Brewster 2018.  I'm just curious what the impact of algorithm=dispersion
vs algorithm=dispersion_extended has on it.  These are 1-3 pixel
reflections on the CSPAD so it's a pretty tough case.  I'll be looking at
the run time and the indexing rates.

**Comment by phyy-nx** [comment]
Here's the phil text for the new algorithm:

```
  threshold
    .help = "Extensions for threshold algorithms to be used in spot finding."
  {
    algorithm = *dispersion dispersion_extended helen single
      .help = "The choice of algorithm"
      .type = choice
    dispersion
      .help = "Extensions to do dispersion threshold."
    {
      <snip, parameters are gain, kernel_size, etc>
    }
    dispersion_extended
      .help = "Extensions to do dispersion threshold."
    {
       # no parameters
    }
  }
```

Does dispersion.gain, etc affect dispersion_extended?  If so, that's not clear from the documentation.

**Comment by dagewa** [comment]
They do indeed appear to:
https://github.com/dials/dials/blob/2326062e4569084ea4e716917d88fe6080b7ae98/extensions/dispersion_extended_spotfinder_threshold_ext.py#L58-L66
I agree this is not very clear from the documentation, or indeed whether there is any reason to have a separate `dispersion_extended` scope. @jmp1985 ?

**Comment by phyy-nx** [comment]
Hi, results from my cspad test. I had a 100K frame dataset (thermolysin run 26) with a hit rate of 12.3% (n frames with at least 40 spots) and an indexing rate of 11.1% of the 100K images. 

Using dispersion_extended I get a hit rate of 12.0%, indicating fewer reflections found per image, but an indexing rate of 11.4%, indicating more successful indexing results. So there is an effect (not surprising) but it is at least fairly neutral if not a bit positive. 

I’m ok to change the default to dispersion_extended, if we get the phil documentation sorted. 

Thanks,

-Aaron

**Comment by rjgildea** [comment]
I've removed the empty `dispersion_extended` phil scope which should hopefully help avoid any confusion: https://github.com/dials/dials/commit/f05fd880c200e2af94ec30e80f000e8215b8faec

**Comment by rjgildea** [comment]
```
$ dials.find_spots -c -e2
...
  threshold {
    algorithm = *dispersion dispersion_extended helen single
    dispersion {
      gain = None
      kernel_size = 3 3
      sigma_background = 6
      sigma_strong = 3
      min_local = 2
      global_threshold = 0
    }
    helen {
      exp_spot_dimension = 3
      global_threshold = 100
      min_blob_score = 0.7
      num_passes = 0
      debug = False
    }
    single {
      global_threshold = 0
    }
  }
}
...
```
