### ISSUE TITLE
Jenkins: stop configuring dials_regression

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#755]
The aim of this work is to remove the need to have to configure dials_regression in each Jenkins workspace individually, speeding up the builds ever so slightly and reducing the disk space requirements.

**Comment by ndevenish** [comment]
Probably within scope of what you are planning here, but you can still configure a softlinked directory, but you might fall over with e.g. "compileall" steps.

Another approach: Don't configure, just add to the `PYTHONPATH` - I think that we don't use the `libtbx` infrastructure for finding `dials_regression` any more?
