### ISSUE TITLE
Documentation confusing: uses 1.x command with 2.0 output

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#766]

**Comment by Anthchirp** [comment]
related: #740. Will pick this up again soon.

**Comment by ndevenish** [comment]
Since we're in the middle of changing lots of things over, should we just pin the documentation to the last pre-2 version and turn off nightly updates for now?

**Comment by ndevenish** [comment]
#714 will solve the problem more generally by having versioned docs, but until then.

**Comment by Anthchirp** [comment]
sounds like a plan. Will disable Jenkins job and revert dials.github.io to appropriate version

**Comment by rjgildea** [comment]
Can we still build the documentation in the Jenkins job, just not update the website? Then we still get build notifications if the documentation is broken. Otherwise I foresee us switching it back on in a few months time and discovering it's now broken in 1e3 different ways.

**Comment by Anthchirp** [comment]
Good idea. Done that.
