### ISSUE TITLE
Conflicting stills vs. sweep specific defaults

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#77]
Consider using Auto for these known offenders (sweeps default, stills default):
refinement.refinement_protocol.n_macro_cycles = (5,1) 
refinement.parameterisation.treat_single_image_as_still=(False,True)
refinement.reflections.outlier.algorithm=(auto,null)

Helpful defaults for stills:
refinement.parameterisation.auto_reduction.min_nref_per_parameter=(5,1)

Currently a silent override:
params.refinement.reflections.weighting_strategy.delpsi_constant=1000000.

**Comment by dagewa** [comment]
Small correction to the first one:

indexing.refinement_protocol.n_macro_cycles = (5,1)

i.e. it is a an option in the indexing scope

**Comment by dagewa** [comment]
For the second one, I don't know if there's any sensible way to make this Auto. It is an override for the case where the image header is lying to you. Normally you want to trust the image header if it says this is a single oscillation image. Back in October 2014 Richard reported that scans refinement for single image scans gave better results than stills refinement. I think if we have a goniometer and apparently a scan with a non-zero width then we ought to treat it as a scan. The option treat_single_image_as_still is then an override for this behaviour.

**Comment by rjgildea** [comment]
If the stills indexer was explicitly chosen with indexer=still then it
should probably set
refinement.parameterisation.treat_single_image_as_still=True
- otherwise it can not possibly work given an image with an oscillation
reported in the header.

**Comment by dagewa** [comment]
I don't understand the third one either. Currently the string "auto" is selected as default from the options within a variable of type "choice". This is just to work around problems with using libtbx.Auto in a choice. But the behaviour is just that - to choose the option automatically given the input. At the moment, mcd gets selected for all scans and sauter_poon for all stills. There may be scope for some more sophisticated choice of outlier rejection type based on the input data, but essentially it is already automatic.

**Comment by rjgildea** [comment]
The point is that it is/was automatic, but now that the stills indexer is
default for still images, it isn't "automatic enough", i.e. the stills
indexer should override the parameter. If the stills indexer will only
possibly work with a specific value of a given parameter, then it should
probably always either ignore or override that parameter as appropriate.

**Comment by dagewa** [comment]
Yes, this seems correct. It should either use the overrides, or explicitly
delete the scan and goniometer so that the internal representation of the
experiment for downstream actions cannot be anything other than the
requested "still"

-- David

**Comment by phyy-nx** [comment]
FYI, the reason for the failure cases right now is I didn't want to
silently override user provided phil parameters.  I would rather use an
auto parameter or fail with a clear error message.  I think silently
overriding user parameters is dangerous, hence this issue being opened.

Deleting the scan and the goniometer if the user is forcing the stills
indexer seems reasonable to me.  Then the downstream applications shouldn't
need  treat_single_image_as_still.  I like putting that in the
from_parameters method of indexer_base and removing the
treat_single_image_as_still
assert.

As for refinement.reflections.outlier.algorithm, I can also change
from_parameters to to check for auto and change it to null.  I will still
assert there that the value is auto or null for stills.

Thanks,
-Aaron
