### ISSUE TITLE
Can't read large msgpack file - memory error

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#770]
Integrated reflection file for high resolution proteinase K dataset, 5.7m reflections:
- reading integrated pickle file succeeds
- writing mpack file succeeds (after 35749d4a0671acfdcc4ba2b91c244c5472a621b6)
- reading mpack file consumes all available memory and eventually the process is killed
```
$ dials.python -c 'from dials.array_family import flex; refl = flex.reflection_table.from_pickle("/dls/i03/data/2019/cm23003-2/processed/proteinasek/protk_1/protk_1_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1_reflections.pickle"); print(refl.size()); refl.as_msgpack_file("tmp.pickle"); refl2 = flex.reflection_table.from_msgpack_file("tmp.pickle")'
5707387
Killed
```

**Comment by rjgildea** [comment]
Available memory:
```
$ free -h
             total       used       free     shared    buffers     cached
Mem:           15G        15G       134M       3.4M       1.2M        32M
-/+ buffers/cache:        15G       167M
Swap:         7.8G       7.1G       759M
```

**Comment by graeme-winter** [comment]
If you run this on a “big” computer and profile the amount of RAM used, is it unreasonable? This is after all rather a substantial data set. That said, since pickle works would hope that message pack also works.

**Comment by rjgildea** [comment]
Peak memory usage according to top:
`32492 hko55533  20   0   20.6g  19.0g  35588 R 100.0 60.8   1:05.06 python2.7`

**Comment by rjgildea** [comment]
msgpack memory usage also appears to be killing xia2.multiplex/dials.cosym performance 😞

**Comment by jmp1985** [comment]
I've been having a look into this and I can see that the problem occurs in the msgpack::unpack function. I'm currently exploring the streaming interface to see if I can make this more efficient.

**Comment by jmp1985** [comment]
I've implemented some general improvements that reduce the memory consumption and I'm also looking at zlib compression of the entire thing and each array separately. The results of a few tests are below. 

In summary:

1. Memory usage is much reduced (previously was taking ~22GB).
2. Compression of entire thing seems to give smallest file sizes.
3. Compression of each array separately uses the smallest amount of memory (when no shoeboxes are present).
4. The serialization of shoeboxes is horribly inefficient. The array of shoeboxes is stored as shown below which results in lots of calls to compress small arrays when each array is compressed separately - not good!
5. The shoeboxes result in worse performance for both compression attempts.
6. Alternative would be to put shoebox array into buffer and compress in one go.

### Current shoebox layout

```
[
    [
        PANEL_NUMBER,
        BBOX -> [ X0, X1, Y0, Y1, Z0, Z1 ],
        DATA -> COMPRESSED BIN
        MASK -> COMPRESSED BIN
        BACKGROUND -> COMPRESSED BIN
    ],
    ...
]
```

### Pickle files

**Reading pickle file**
 Time taken: 9.178718 seconds

**Writing pickle file**
 Time taken: 14.200984 seconds

**Writing pickle file no shoebox**
 Time taken: 12.406037 seconds

**Reading pickle file**
 Time taken: 11.406775 seconds
 Memory usage: 7.805456 GB

**Reading pickle file no shoebox**
 Time taken: 6.730951 seconds
 Memory usage: 4.543368 GB


### Msgpack files compress entire thing

**Writing msgpack file with level: 0**
 Time taken: 9.547955 seconds

**Writing msgpack file with level: 1**
 Time taken: 60.076152 seconds

**Writing msgpack file with level: 2**
 Time taken: 65.257289 seconds

**Writing msgpack file no shoebox with level: 0**
 Time taken: 5.362999 seconds

**Writing msgpack file no shoebox with level: 1**
 Time taken: 57.195720 seconds

**Writing msgpack file no shoebox with level: 2**
 Time taken: 68.989529 seconds

### Msgpack files compress each array separately

**Writing msgpack file with level: 1**
 Time taken: 112.105740 seconds

**Writing msgpack file no shoebox with level: 1**
 Time taken: 57.355430 seconds

### Msgpack files decompress entire thing

**Reading msgpack file with level: 0**
 Time taken: 14.091802 seconds
 Memory usage: 13.226512 GB

**Reading msgpack file no shoebox with level: 0**
 Time taken: 8.609760 seconds
 Memory usage: 6.589560 GB

**Reading msgpack file with level: 1**
 Time taken: 23.381594 seconds
 Memory usage: 12.170092 GB

**Reading msgpack file no shoebox with level: 1**
 Time taken: 17.658921 seconds
 Memory usage: 5.833144 GB

**Reading msgpack file with level: 2**
 Time taken: 23.004792 seconds
 Memory usage: 12.164136 GB

**Reading msgpack file no shoebox with level: 2**
 Time taken: 17.500894 seconds
 Memory usage: 5.828480 GB

### Msgpack files decompress each array separately

**Reading msgpack file with level: 1**
ERROR

**Reading msgpack file no shoebox with level: 1**
 Time taken: 10.986804 seconds
 Memory usage: 4.031672 GB

### Files sizes for compressing entire thing

total 17G
-rw-r----- 1 upc86896 2.1G May  7 14:17 AUTOMATIC_DEFAULT_SAD_SWEEP1_reflections.pickle
-rw-r--r-- 1 upc86896 1.4G May  9 10:41 tmp_no_shoebox.mpack
-rw-r--r-- 1 upc86896 3.6K May  9 11:45 test.py
-rw-r--r-- 1 upc86896 2.1G May  9 11:46 tmp.pickle
-rw-r--r-- 1 upc86896 2.4G May  9 11:46 tmp_0.mpack
-rw-r--r-- 1 upc86896 1.4G May  9 11:47 tmp_1.mpack
-rw-r--r-- 1 upc86896 1.4G May  9 11:48 tmp_2.mpack
-rw-r--r-- 1 upc86896 1.9G May  9 11:48 tmp_no_shoebox.pickle
-rw-r--r-- 1 upc86896 2.1G May  9 11:48 tmp_no_shoebox_0.mpack
-rw-r--r-- 1 upc86896 1.4G May  9 11:49 tmp_no_shoebox_1.mpack
-rw-r--r-- 1 upc86896 1.4G May  9 11:50 tmp_no_shoebox_2.mpack


### Files sizes for compressing each array separately

-rw-r--r-- 1 upc86896 2.1G May  9 13:23 tmp.pickle
-rw-r--r-- 1 upc86896 1.9G May  9 13:25 tmp_no_shoebox.pickle
-rw-r--r-- 1 upc86896 1.7G May  9 13:25 tmp_1.mpack
-rw-r--r-- 1 upc86896 1.4G May  9 13:26 tmp_no_shoebox_1.mpack

**Comment by graeme-winter** [comment]
Discussed with @jmp1985 => put shoebox information into fixed-size data sets for bbox etc. then stream of pixel values to keep things simple & reduce overhead of compression.
