### ISSUE TITLE
Add pre-commit to reject adding large files

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#777]
Would suggest adding the `check-added-large-files` pre-commit with a setting to reject everything above 200kB. That should leave a considerable margin of error for usual files and avoid cluttering the repository by accident.

The limit can of course be overridden by running `git commit` with the `-n` flag if needed.

**Comment by graeme-winter** [comment]
👍

**Comment by benjaminhwilliams** [comment]
Sounds very sensible to me.
