### ISSUE TITLE
dials.export cannot export multiple wavelengths in mtz format

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#780]
An assumption in export_mtz is that there is only a single wavelength:

https://github.com/dials/dials/blob/93adff18177bdfea417c8072f6f6fdbb717efb07/util/export_mtz.py#L342

This causes issues for example in xia2 for MAD datasets processed with dials-full, which fails at the export step of scaling.

Should this now be implemented, I guess there is specification in the mtz format for this.

**Comment by Anthchirp** [comment]
(Corollary of this is that xia2 currently can't process MAD data with the default pipeline)

**Comment by jbeilstenedmands** [comment]
An update. I've been having a go at this, following the guidelines in http://www.ccp4.ac.uk/html/mtzformat.html#fileformat
which give the data hierarchy as; File -> Crystal -> Dataset -> Datalist -> Column

The recommended approach is to add multiple Datasets for a given crystal, one for each wavelength. My premilinary work for adding this to export_mtz is on my multi-wavelength-mtz branch on my fork jbeilstenedmands/dials. 
Unfortunately it doesn't look like the current implementation of iotbx/mtz is able to support multiple datasets without errors - one can add new datasets, but sometimes when trying to set dataset-specific properties (like n_reflections), the call acts on the whole mtz file object and interferes with data in other datasets, so it looks like this work is dependent on a more in-depth look into the functioning of iotbx/mtz

**Comment by graeme-winter** [comment]
@jbeilstenedmands hang fire - unmerged MTZ files are "special"
