### ISSUE TITLE
Rename .json => .expt .pickle => .refl

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#784]
```
Grey-Area dials :) [master] $ grep -R '\.pickle' . | grep '\.py:'|wc -l
     605
Grey-Area dials :) [master] $ grep -R '\.json' . | grep '\.py:'|wc -l
     772
```

.refl will mean format agnostic, no more explaining what are pickles etc.

**Comment by jmp1985** [comment]
I'm in favour of this:

*.refl or *.ref

and

*.expt or *.exp

**Comment by jbeilstenedmands** [comment]
See #785 for examples

**Comment by dagewa** [comment]
`*.refl` and `*.expt`. The 3 char extensions are more likely to clash with 3rd party software leading to user confusion (at the very least, wrong icons on Windows file explorer)

**Comment by rjgildea** [comment]
> `*.refl` and `*.expt`. The 3 char extensions are more likely to clash with 3rd party software leading to user confusion (at the very least, wrong icons on Windows file explorer)

I agree, extra character => more likely to be unique and unambiguous

**Comment by Anthchirp** [comment]
vote for keeping 8+3 format, ie. `output.ref` and `output.exp` to retain compatibility with https://github.com/microsoft/MS-DOS

**Comment by dagewa** [comment]
I'll pick this and #785 up
