### ISSUE TITLE
Discussion on filename renaming for dials 2.0

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#785]
During the recent msgpack work and associated filename changes, it has been suggested that a more general and endurable approach would be to change the names of the file extensions for experiments and reflection files, regardless of the storage format used.

For example, if the extensions .expt and .refl were used, these would not need to change in future even if the format changes and avoids user confusion/needing to know about .pickle, .mpack etc.

As part of removing datablocks for dials 2.0, this has also lead to some thoughts on making filenames more consistent across the main dials commands (e.g some programs go for the style scaled_reflections.pickle, whereas others the style scaled.pickle). If we are going to rename the extensions, then the 'reflections' and 'experiments' can also be dropped from within certain filenames. 

To open the discussion on this, I thought I would provide a suggestion as a starting point for further discussion.
The main dials workflow could use filenames as follows:
```
dials.import > imported.expt
dials.find_spots > strong.refl
dials.index > indexed.expt, indexed.refl
dials.refine_bravais_settings > bravais_setting_{x}.expt    (with {x} = 1, 2, 3 etc)
dials.reindex > reindexed.expt, reindexed.refl
dials.refine > refined.expt, refined.refl
dials.integrate > integrated.expt, integrated.refl
dials.symmetry > symmetrized.expt, symmetrized.refl  (not sure on this one but ideally want a different name to dials.reindex?)
dials.scale > scaled.expt, scaled.refl
```
It is my opinion that dials.cosym could also use the same extensions as dials.symmetry as it performs an analogous task. Apart from this there are no name clashes for the main program output files.

Suggestions for the other commonly used dials programs that give output:
```
dials.generate_mask > pixels.mask (or perhaps mask.pixels?)
dials.apply_mask > masked.expt
dials.search_beam_position > optimised.expt
dials.create_profile_model > models_with_profiles.expt  (unsure on this)
dials.predict > predicted.refl
dials.slice_sweep > sliced.expt, sliced.refl
dials.combine_experiments > combined.expt, combined.refl
```
A default name could also be used if there is not an obvious name for a new utility:
```
dials.x > models.expt, observations.refl
```

**Comment by dagewa** [comment]
`pixels.mask` not `mask.pixels` IMO

**Comment by phyy-nx** [comment]
👍👍👍

**Comment by dagewa** [comment]
Any more comments on this? I'm happy to make the changes to meet @jbeilstenedmands' suggestions above.

**Comment by nksauter** [comment]
Yes, the experiment reader interface should still work if the user provides
*.json and *.pickle.

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by rjgildea** [comment]
> Yes, the experiment reader interface should still work if the user provides *.json and *.pickle.

As far as I am aware, determination of file type on reading is done purely on the _contents_ of the file, not the _name_ of the file, so this should be unaffected by the suggested changes. All this changes is the default names of the output files.

**Comment by dagewa** [comment]
Many of our tests rely on data, e.g. in dials_regression, that are still `.pickle` and `.json` format. I have no intention of converting these files, both the old names and new names will work.
