### ISSUE TITLE
dials.image_viewer unreadable text in Mojave/wxpython4

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#787]
Using a wxpython4 build on macOS Mojave much of the text in the dials.image_viewer settings panel is unreadable as a consequence of being white text on a light grey background:
<img width="373" alt="Screenshot 2019-05-16 at 10 09 16" src="https://user-images.githubusercontent.com/2810624/57841601-c5f46600-77c2-11e9-8e24-1f2e663c3519.png">

**Comment by rjgildea** [comment]
This appears to be an issue with Mojave "dark mode" - in "light mode" appearance is as expected, i.e. black text.

**Comment by ndevenish** [comment]
It looks like this is a known problem, and that there has been some work on it: https://trac.wxwidgets.org/ticket/18146
