### ISSUE TITLE
End-of-life for MacOS 10.6 builds

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#793]
10.6 is 9 years old, the 10.6 builds were made to work around some changes in 10.10. 10.10 will have its 5th anniversary in October 2019. To reduce the load on our build environments I propose to drop MacOS <10.10 support for new DIALS releases from October 2019 onwards.

That would make DIALS ~2.1 the last MacOS 10.6 release.

Opinions?

**Comment by Anthchirp** [comment]
The revised release schedule (cf #842) will make DIALS 2.0 the last MacOS 10.6 release.

**Comment by Anthchirp** [comment]
10.6 builds removed.

For reference:
```bash
export MACOSX_DEPLOYMENT_TARGET=10.6
python ${WORKSPACE}/jenkins/box.py MacOSX deployment target set to $MACOSX_DEPLOYMENT_TARGET

(...)

cd dist
mv dials-installer-dev.tar.gz ${WORKSPACE}/dials-macosx-10.6.tar.gz
mv dials-*.pkg ${WORKSPACE}/dials-macosx-10.6.pkg
```

**Comment by ndevenish** [comment]
So, what is our minimum supported MacOS version now? A quick lookaround suggests that models <2007 supported up to (max) 10.7, and the next cutoff seems to be 2007-2009 models which supports up to 10.11

**Comment by ndevenish** [comment]
So I guess 10.10 or 10.11? Is there a reason we know of to stick to 10.10 because that's where the change was?

**Comment by Anthchirp** [comment]
No idea.
