### ISSUE TITLE
dials.combine_found_spots has no documentation

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#794]
`dials.combine_found_spots` has (and always has had) an empty help string.  I'm not sure exactly what it was designed for, beyond the title of #115.  Should it be dev.dials.combine_found_spots?   Or is it deliberately user-facing?  If the latter, perhaps we could tell the user how to use it.

**Comment by Anthchirp** [comment]
not used in dlstbx, dials, xia2 or zocalo.

**Comment by benjaminhwilliams** [comment]
`dials.combine_found_spots` is untested.  After a conversation with @jmp1985, it seems likely it is just a legacy program, superseded by `dials.combine_experiments`.  Since it is undocumented, untested, seemingly unused and unnecessary, I'll remove it.

**Comment by rjgildea** [comment]
> Since it is ... untested

Not entirely true:
https://github.com/dials/dials/blob/33fa5472920dbca6332b2391ea2951bf2a96b7c3/test/command_line/test_combine_found_spots.py
which will presumably fail now that you've removed the program it is testing.

**Comment by Anthchirp** [comment]
Yes, would have failed in next dials_regression run.
