### ISSUE TITLE
Potential bug in flex.reflection_table_selector

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#807]
This looks like a real bug identified by flake8?
F841 local variable 'value' is assigned to but never used
https://github.com/dials/dials/blob/f809cd500b3bf02c831e2b18e4fd31b2259cfb15/array_family/flex.py#L1575-L1600

Introduced by @jmp1985 in 9bbed2f8ae5deaa2d134cd256762a03424044fdc.

**Comment by graeme-winter** [comment]
Methinks excess `self.` late in from this code block? though would need to see what it is _supposed_ to do...

**Comment by dagewa** [comment]
Fixed (probably) in 6a7e6ca (at least, all tests pass)
