### ISSUE TITLE
flake8 complaints from PR

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#809]
PR #751 is generating some interesting complaints, and some of them appear to be real bugs:

Running flake8 on changed files

- [ ] algorithms/refinement/parameterisation/configure.py:639:39: F821 undefined name 'beam'
- [ ] algorithms/refinement/parameterisation/configure.py:656:31: F821 undefined name 'beam'
- [x] algorithms/refinement/refiner.py:727:20: F841 local variable 'num_rows' is assigned to but never used
- [x] algorithms/refinement/refiner.py:735:13: F402 import 'flex' from line 23 shadowed by loop variable
- [x] algorithms/refinement/refiner.py:796:12: E713 test for membership should be 'not in'
- [x] algorithms/refinement/refiner.py:872:17: F841 local variable 'temp' is assigned to but never used
- [x] algorithms/refinement/refiner.py:926:13: F841 local variable 'temp' is assigned to but never used
- [x] algorithms/refinement/reflection_manager.py:180:19: F821 undefined name 'Sorry'
- [x] algorithms/refinement/reflection_manager.py:281:23: F821 undefined name 'Sorry'
- [x] algorithms/refinement/reflection_manager.py:293:23: F821 undefined name 'Sorry'
- [x] command_line/generate_tutorial_text.py:344:8: E713 test for membership should be 'not in'
- [x] command_line/generate_tutorial_text.py:347:8: E713 test for membership should be 'not in'
- [x] test/algorithms/refinement/test_constraints.py:18:1: F401 'libtbx.test_utils.open_tmp_directory' imported but unused
- [x] test/algorithms/refinement/test_constraints.py:171:5: F841 local variable 'result' is assigned to but never used
- [x] test/algorithms/refinement/test_refine_multi_wedges.py:13:1: F401 'dials.array_family.flex' imported but unused
- [x] test/command_line/test_refine.py:40:5: F841 local variable 'result' is assigned to but never used
- [x] test/command_line/test_refine.py:94:5: F841 local variable 'result1' is assigned to but never used
- [x] test/command_line/test_refine.py:95:5: F841 local variable 'result2' is assigned to but never used
- [x] test/command_line/test_refine.py:144:5: F841 local variable 'result1' is assigned to but never used
- [x] test/command_line/test_refine.py:177:5: F401 'random.randint' imported but unused
- [x] test/command_line/test_refine.py:177:5: F401 'random.uniform' imported but unused

Working through these now

**Comment by graeme-winter** [comment]
@dagewa I have fixed almost all of these but the first two I think are serious:

```
Running flake8 on changed files:
algorithms/refinement/parameterisation/configure.py:639:39: F821 undefined name 'beam'
algorithms/refinement/parameterisation/configure.py:656:31: F821 undefined name 'beam'
```

issue also present on master:

```
Grey-Area dials :) [master] $ flake8 --select=E711,E712,E713,E714,E721,E722,E901,F401,F402,F403,F632,F811,F812,F821,F822,F841,F901,W191,W602,W603,W604,W605,W606 algorithms/refinement/parameterisation/configure.py
algorithms/refinement/parameterisation/configure.py:638:39: F821 undefined name 'beam'
algorithms/refinement/parameterisation/configure.py:655:31: F821 undefined name 'beam'
```

**Comment by rjgildea** [comment]
Highlights opportunities for improved test coverage 🙂
