### ISSUE TITLE
Added dependency on 'futures' breaks Python 3 environment

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#811]
The indexing branch merge added `futures`.
https://github.com/dials/dials/blob/53061e0a5d49939b128a7fa757c9aaef59f4ee77/libtbx_config#L18
This is a backport of Python 3.2 code. While this is newer than Python 2.7 the real world has moved on and this package is incompatible with real Python 3. Basically you will see this error message a lot: https://github.com/agronholm/pythonfutures/issues/85

You can't even uninstall the package, as pip will fail with the same error.
We should never install `futures` on Python 3.

Suggested solution: 
1.  @ndevenish, can we have the install conditional on Python <3 in libtbx_config?
2. alternatively move `futures` from libtbx_config into libtbx_refresh.py where we can make it conditional on being run on Python2

**Comment by ndevenish** [comment]
As commented on slack, this was anticipated and the libtbx_config should be fully compatible with [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers). So in principle changing to say `'futures;python_version<"3.0"' should be sufficient, though I'd have to check it's the right syntax so wouldn't want to edit without testing.

**Comment by Anthchirp** [comment]
due to following good practices and not reinventing the wheel this was fixed faster than it took me to write up the issue itself 👍
