### ISSUE TITLE
Cleanup command_line directory

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#812]
1) Contain excessive amounts of code
    - ~28.2k lines of code (out of a total of 91.4k lines of code for the whole project)
    - where appropriate, code should ideally be moved out of the command_line directory

2) Almost half (57 out of 129) of the programs are hidden behind a "dev.dials" dispatcher
    - unlikely to be used (or tested) externally, e.g. via xia2
    - CCP4 do not distribute dev.dials.* dispatchers anyway
    - most likely one-off test scripts that would be better off moved to another repository, e.g. dials_scratch

3) Pollutes the code coverage statistics:
    - https://codecov.io/gh/dials/dials/tree/master/command_line
    - 72 (out of 129) files with 0% test coverage
    - Overall test code coverage for this directory of 37.27% (compared to 62.89% for the whole project)
    - 10,009 (out of 17,108) lines of untested code
    - lack of tests means the scripts are likely to become stale over time as a result of major refactors such as the recent datablock -> experiments move, pickle -> msgpack, or e.g. the recent indexing refactor.

4) Pollutes the LGTM alerts:
    - https://lgtm.com/projects/g/dials/dials/latest/files/?sort=name&dir=ASC&mode=heatmap
    - 92 alerts for command_line directory (out of a total of 227 for the whole project)
    - risks masking genuine errors in code that is actually used in DIALS

**Comment by dagewa** [comment]
@phyy-nx any objections if I remove `stills_detector_hybrid_refine.py`?

**Comment by rjgildea** [comment]
> stills_detector_hybrid_refine

This does at least have a test - with 85% code coverage!

**Comment by phyy-nx** [comment]
Heh, indeed.  I'm not using it at all though.  Everything goes through
dials.refine.

**Comment by dagewa** [comment]
@jbeilstenedmands  @jmp1985 Should `dials.compute_delta_cchalf` be a method of `dials.filter_reflections` (which in turn might be renamed `dials.filter`) rather than a separate program?

**Comment by jbeilstenedmands** [comment]
@dagewa I'm split on this one. While practically these are having a similar outcome i.e. filtering reflections, compute_delta_cchalf is a whole algorithm in itself rather than simple filtering and so perhaps belongs as a distinct program. Although I don't like the name, and
```dials.filter method=deltacchalf``` would be quite nice. Hmmm.

**Comment by dagewa** [comment]
My vote would be putting it all into a new improved `dials.filter`, but various other tidying up jobs in command_line/ should take priority.

**Comment by rjgildea** [comment]
After the pull request https://github.com/dials/dials/pull/824 these are some of the remaining `dev.dials.*` command line dispatchers of interest:

- [ ] `dev.dials.merge_reflection_lists` - this was added by @jmp1985 and does have a test, but doesn't appear to be used anywhere as far as I can tell. Is this still useful/needed, in which case it should be upgraded to `dials.merge_reflection_lists` or can it be removed/moved to dials_scratch?

- [ ] `dev.dials.sort_reflections` - this was added by @dagewa, same comments as above - is tested, but is it still needed?

**Comment by dagewa** [comment]
I think it is useful to have a command to sort reflections in the toolbox as part of the general data manipulation tools. I would keep it, and perhaps it should be `dials.sort_reflections`

**Comment by ndevenish** [comment]
We can re-address this if it becomes enough of an annoyance.
