### ISSUE TITLE
Further reduce pickle dependence

### ISSUE THREAD

**Issue by dagewa** [dials/dials#821]
We are working towards moving the default reflection table format to message pack, but DIALS may still write out a (surprisingly large) number of auxiliary `.pickle` files. It may be worth converting some of these to another format to avoid the security issue.

At least `mask.pickle`, `[dx|dy].pickle` probably ought to be some other format, as these could conceivably be shared.

Here's the list of auxiliary `.pickles` I've found:

- `mask.pickle` made by dials.generate_mask, dials.image_viewer or dev.dials.bad_pixels
- `dx.pickle`, `dy.pickle` distortion maps made by dials.generate_distortion_maps
- `hot_mask.pickle` from dials.find_hot_pixels
- ~~`history.pickle` made by dials.refine~~
- `polar.pickle` made by dev.dials.make_polar_background_image
- `background.pickle` made by dials.model_background
- ~~correlation matrices made by dials.refine or dials.two_theta_refine (filename determined by `correlation_plot.filename=`~~
- `correlation.pickle` made by Helen Ginn's spotfinder in debug mode
- `model.pickle` made by `test_gmodel.py`

**Comment by graeme-winter** [comment]
Any volunteers to pick this one up?

**Comment by graeme-winter** [comment]
Let us be honest, we _should_ do this but probably as part of a future move of experiments and so on to a more sensible container format. In the meantime, main sequence dials processing does not create pickle files, and no one has sent me a pickle in the last 4 years -> closing
