### ISSUE TITLE
Spotfinding does not work in parallel on stills

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#823]
WIP ticket for fixing feature (hey ho towncrier).

Basically still images are now imported as separate experiments with a different imageset for each experiment. Since the spotfinding was run in parallel over a single imageset at a time this now runs very slowly, doing a single image at a time.

Am actively working on this.

**Comment by graeme-winter** [comment]
FWIW this is a blocker for 2.0: with 1.14-series a 192 image scan finds spots in ~ 18s on macbook pro with 8 processes, with master (today) takes ~ 80s for same.

**Comment by graeme-winter** [comment]
WIP in still_sequence_hacks
