### ISSUE TITLE
Finishing off the data reduction workflow in DIALS

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#826]
Something that has become apparent at workshops is that we need to be handling the workflow a bit better after scaling. Currently, you can't take a scaled (unmerged) mtz file into ccp4 for further processing without running the whole pointless/aimless data reduction task. In ccp4 you can import a merged mtz - but this can only be generated by dials.scale with option merged_mtz=.

Suggested solutions include having a merged mtz option for dials export, letting dials.scale output a merged scaled mtz by default in dials.scale, or creating a separate program for merging data from a reflection table. If using a separate program (maybe dials.merge), this could also include a truncate analysis and extensive statistics reporting.
This last solution feels the tidiest - in this sense dials could replicate the ccp4 workflow;
pointless > aimless > ctruncate = dials.symmetry > dials.scale > dials.merge. This would also let dials processing finish at the same point as xia2. Of course dials.export would still exist, so there would be the option of having an unmerged+scaled mtz of Is, or merged+truncated mtz of Fs, depending on preferences for downstream processing.

**Comment by jbeilstenedmands** [comment]
I have been working on this issue this week and there will be a PR incoming in the next few days.
Here is the plan for what the post-integration workflow will look like, any comments welcome.

![post_integration_workflow](https://user-images.githubusercontent.com/30625594/61470123-6825fb00-a978-11e9-93e2-9d98191fb30f.png)

The filenaming and intensity choices for export and merge will happen automagically, so no need for options input by the user except when generating merged but not truncated data (with the idea that the recommended workflow is the bottom path).

**Comment by dagewa** [comment]
1. Is it really `truncated.mtz`, so is the French & Wilson truncate algorithm used to convert negative intensities to positive Fs?
2. What about the post-scale dials.symmetry step for the screw axis check?
3. What happens to anomalous data on merging - that is, do you make I+ sigI+ I- sigI-?

Sorry if I should just look at documentation to answer any of the above ;-)

**Comment by dagewa** [comment]
Thanks @jbeilstenedmands for clarification on (1) and (3), plus your suggested approach to (2) sounds clean and sensible :+1:
