### ISSUE TITLE
image_viewer: write out find_spots.phil?

### ISSUE THREAD

**Issue by dagewa** [dials/dials#83]
This is a request from Ronan. He has been looking at CCD datasets where the default spot finding parameters are not good. Generally, we fiddle with options in the image_viewer until the threshold map looks about right by eye, then find_spots with those parameters.

Would it be sensible for image_viewer to include functionality to write out the current parameters for the spot finding algorithm to a PHIL file for direct use in dials.find_spots?

**Comment by graeme-winter** [comment]
That would make a great deal of sense, nice suggestion!
