### ISSUE TITLE
Make threaded integrator the default

### ISSUE THREAD

**Issue by dagewa** [dials/dials#833]
`integrator=3d_threaded` for DIALS 2.0. Depends on #560

**Comment by benjaminhwilliams** [comment]
Problem dataset for threaded integrator
`/dls/i03/data/2019/cm23003-2/gw/20190424/firehose-collect/protk_1_13
IMAGE protk_1_13_3_master.h5`

**Comment by Anthchirp** [comment]
Missed 2.0

**Comment by dagewa** [comment]
The plan is to look at this in February 2020
