### ISSUE TITLE
refinement test unstable

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#836]
`test.algorithms.refinement.test_centroid_outlier.py::test_centroid_outlier[mcd-colnames1-34]` and
`test.algorithms.refinement.test_centroid_outlier.py::test_centroid_outlier[sauter_poon-colnames2-34]`
are unstable and consistently failing in the Jenking source package build.

I sometimes see 29 outliers or 0.

**Comment by dagewa** [comment]
Hmm, the whole point of these tests was to ensure these algorithms remain stable. It seems they are not. Well, at least the tests did their job!

I thought sorting `stable=True` would be enough (#757). :-(

**Comment by graeme-winter** [comment]
For me on RHEL6:

```
Results (413.46s):
     759 passed
       1 failed
         - ../../../../../../dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/scaling/test_reflection_selection.py:154 test_reflection_selection
       2 xfailed
     118 skipped
```

at

```
>       assert len(indices) > 1710 and len(indices) < 1800
E       assert (1658 > 1710)
E        +  where 1658 = len(<scitbx_array_family_flex_ext.size_t object at 0x7f3709a87578>)

modules/dials/algorithms/scaling/test_reflection_selection.py:186: AssertionError

 algorithms/scaling/test_reflection_selection.py ⨯               100% ██████████

```

**Comment by graeme-winter** [comment]
i.e. smells related

**Comment by dagewa** [comment]
Annoyingly all pass for me

**Comment by Anthchirp** [comment]
annoyingly they also pass on nearly all Jenkins tests. They only fail in the source package build job.

**Comment by Anthchirp** [comment]
if it helps - the command that this is running is
```bash
mkdir pytest
pytest -v -rsxX --basetemp=pytest -n auto --durations=30 --junit-xml=pytest.xml \
  ${WORKSPACE}/test_dials/modules/dials \
  ${WORKSPACE}/test_dials/modules/dxtbx \
  ${WORKSPACE}/test_dials/modules/xia2 || \
    echo One or more tests failed.
```
on a RHEL6 machine with neither dials_regression nor dials-data installed

**Comment by dagewa** [comment]
Now the tests are enabled again, I was going to give it a week or so to see what the Jenkins source build tests show. However, I've just realised that now the test uses data in `dials_regression/` so I suppose it now isn't run at all, given your earlier comment
> on a RHEL6 machine with neither dials_regression nor dials-data installed

So, I may have made the test stable for the source build, but I can't actually tell :see_no_evil:
