### ISSUE TITLE
Imageset design needs improvement

### ISSUE THREAD

**Issue by dagewa** [dials/dials#840]
In discussion. Probably for DIALS 2.1?

**Comment by graeme-winter** [comment]
Possibly something we should not park for 2.1 because https://github.com/dials/dials/issues/879 unless we want to hack in a workaround?

**Comment by graeme-winter** [comment]
WIP in still_sequence_hacks

**Comment by dagewa** [comment]
I'm wondering what has happened to this one?

**Comment by dagewa** [comment]
I can't find a branch with the name `still_sequence_hacks` either in DIALS or dxtbx
