### ISSUE TITLE
DIALS 2.0 release

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#842]
Plan is to release a preview version of DIALS 2.0 at the end of August 2019 for testing with friendly users.
To distinguish these from true DIALS 2.0 releases which will happen at an as-of-yet undetermined point afterwards we will use the standard development version numbers (2.dev.*) as we do for nightly builds. The exact release plan is to be confirmed.

**Comment by Anthchirp** [comment]
Changes in the release process:
* Existing branch `dials-next` will be kept as `dials-next-1.14` in case we need to do another 1.14 release. We will likely keep 1.14 support around until 2.x is released with CCP4 or until the end of the year, whichever happens first.
* `dials-next` branches will be used for 2.x releases as usual, with the support of 2.0 ending with the release of 2.1 and so on.

**Comment by Anthchirp** [comment]
Branch at the most recent stable build at end of play UK time tomorrow.
Anything beyond that will have to go into 2.1.

Since we have Shutdown 5 coming up over the Christmas period we have the option to make 2.0 a short-lived release, with a 2.1 release shortly before Christmas or early next year. Alternatively 2.1 will happen mid-March.

**Comment by graeme-winter** [comment]
Both of these sound reasonable proposals... can see how stable 2.0.x are.

**Comment by Anthchirp** [comment]
DIALS 2.0 branches now exist.

**Comment by Anthchirp** [comment]
Release is out, cf. https://dials.github.io/installation.html
We already found a few big issues, so 2.0.1 won't be far away.
