### ISSUE TITLE
Sensitivity to mask type (list/tuple/bare) in spotfind/integrate etc

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#845]
Mainly as a reminder for me to follow up:
- Passing a mask file of type `flex.bool` apparently passes spotfind (but doesn't mask anything) - integrate falls over with this - Consider this probably a major fail condition, add test etc
- Passing a `Tuple[flex.bool]` is the expected behaviour and works fine
- Passing a `List[flex.bool]` makes at least spotfinding fall over, though a tuple works fine

If anyone has any immediate thoughts on this they'd be welcome but I assume it's some fiddly type conversion nonsense somewhere?

**Comment by ndevenish** [comment]
(another guess - zip iterates over `zip(panels, mask)` and so only every picks up the first - true - pixel of the mask)

**Comment by ndevenish** [comment]
Getting a `List` mask out of image viewer also probably warrants investigation, if can reproduce

**Comment by rjgildea** [comment]
https://github.com/dials/dials/blob/a6f7a7233e2f8d3f087f0d3599dc9217b6d884e6/util/image_viewer/mask_frame.py#L651-673
