### ISSUE TITLE
dials.import dynamic shadowing regression

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#848]
It seems that the shadow mask produced by passing the option `dynamic_shadowing=True` to `dials.import` is inverted.  This is a regression since DIALS 1.14.  To reproduce, find a data set for which dynamic shadowing is necessary (sample in a diamond anvil cell, for example) and do the following:
- Load DIALS 1.14.
- Run `dials.import dynamic_shadowing=True <image_files>`.
- Run `dials.image_viewer show_mask=True datablock.json`.  Make a note of the (correct) mask location.
- Load a development copy of DIALS.
- Run `dials.import dynamic_shadowing=True <image_files>`.
- Run `dials.image_viewer show_mask=True imported.expt`.  Note the inverted mask.

**Comment by rjgildea** [comment]
This is specific to I19-2. Please can you add an example shadowed image for I19-2 to dials_regression/dials_data?

**Comment by benjaminhwilliams** [comment]
I'll see if I can find one that is OK for dissemination.

**Comment by benjaminhwilliams** [comment]
After chatting to Mark Warren, it looks like we need to collect some.

**Comment by benjaminhwilliams** [comment]
This issue is closed by https://github.com/cctbx/dxtbx/commit/09ef840933fd37d056f28712cf26b6a6f7af9f0f

**Comment by rjgildea** [comment]
@benjaminhwilliams I would still like an example image we can use for adding an I19-2 specific test here:
https://github.com/dials/dials/blob/277d1717e9f7883aa694502a96ab4e1d727f9790/test/util/test_masking.py#L16-L35
