### ISSUE TITLE
Command line auto-completion of file names broken

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#849]
Command line auto-completion of file names is broken, probably as a by-product of https://github.com/dials/dials/pull/822.

Auto-completion is presumably still looking for .json and .pickle files, not .expt and .refl files.

**Comment by Anthchirp** [comment]
It should pick up all of the above
https://github.com/dials/dials/blob/277d1717e9f7883aa694502a96ab4e1d727f9790/util/autocomplete.sh#L121-L126

**Comment by rjgildea** [comment]
```
$ ls imp*
imported.expt
$ dials.find_spots imp
```
on pressing <tab> nothing happens... I have up-to-date dials sources, and have run `make reconf`.

**Comment by dagewa** [comment]
This works fine for me on Linux. Is the autocompletion set up a different way on Mac?

**Comment by graeme-winter** [comment]
I can reproduce @rjgildea experience - so presumably is different on mac. Used to work with pickle / json I think...

**Comment by graeme-winter** [comment]
Possible clue:

On fruiter:

```
Grey-Area dials-859 :) $ ls ~/svn/cctbx/build/dials/autocomplete
SConscript			dials.calc_rmsds
bash.sh				dials.combine_found_spots
```

on boringix:

```
cs03r-sc-serv-16 ~ :) $ ls ~/svn/cctbx/build/dials/autocomplete
bash.sh			   dials.geometry_viewer	    dials.reindex
dials.analyse_background   dials.index			    dials.rl_png
dials.calc_rmsds	   dials.integrate		    SConscript
dials.combine_found_spots  dials.reciprocal_lattice_viewer
dials.find_spots	   dials.refine
```

=> auto complete generation != working... presumably in configure / refresh

**Comment by graeme-winter** [comment]
Make reconf restored the files but still does not work...

**Comment by graeme-winter** [comment]
Noteworthy that OS X has ancient version of bash

```
Grey-Area Downloads :) $ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```

even RHEL6 on 4.1 series...

**Comment by graeme-winter** [comment]
Seems to be working right now, and also the files re-appeared:

```
Grey-Area index :) $ ls ~/svn/cctbx/build/dials/autocomplete
SConscript			dials.index
bash.sh				dials.integrate
dials.analyse_background	dials.reciprocal_lattice_viewer
dials.calc_rmsds		dials.refine
dials.combine_found_spots	dials.reindex
dials.find_spots		dials.rl_png
dials.geometry_viewer
```

=> close?
