### ISSUE TITLE
Update the boilerplate

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#858]
https://github.com/dials/dials/wiki/Boilerplate-(or-the-standard-framework-of-a-DIALS-program)
has gone slightly stale:
* black
* experiments/reflections
* cPickle -> `from six.moves import cPickle as pickle`
* upcoming changes for #832

**Comment by dagewa** [comment]
Noted https://github.com/dials/dials/issues/463#issuecomment-507622616 but I should have put the issue in then

**Comment by Anthchirp** [comment]
I'm wondering whether this should go into the main source tree (not `/command_line/` of course)

**Comment by dagewa** [comment]
@ndevenish's example is much better than the existing entry in the wiki, so I'm going to replace it there.

**Comment by rjgildea** [comment]
The current "gold standard" boilerplate example now lives here:
https://github.com/dials/dials/blob/master/doc/examples/boilerplate.py
I.e. somewhere it can be tested and included in the docs (see https://github.com/dials/dials/pull/1042). Perhaps we should remove the boilerplate from the wiki entirely to avoid confusion.

**Comment by dagewa** [comment]
Right, I missed that. Yes, I'll edit the page in the wiki to be "writing a DIALS program" and point to this.
