### ISSUE TITLE
Change dials.refine line in documentation

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#86]
From observations from India:

5.	Some students were confused with the dials.reindex step. Specifically, in the tutorial, because the change of basis operation is “a,b,c”, dials.refine is called with indexed.pickle rather than reindexed_reflections.pickle. Students were then doing this (by copy and paste I think) even when they had more complex change of basis operations. Can we change the tutorial to pass in reindexed_reflections.pickle?

**Comment by dagewa** [comment]
This was fixed at some point
