### ISSUE TITLE
retire PHIL parameter verbosity=

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#860]
There are currently two ways to set verbosity on DIALS commands, cf. 1be6239ad87d45b56bc894a9e1483aaf52d98aca

Since typing `-v` takes less than 18% of the effort of typing `verbosity=2` and is way less confusing (`verbosity=2` == `-v`, `verbosity=1` is the default) I suggest deprecating and removing the `verbosity=` PHIL parameter from all DIALS commands.

The only case `-v` can not cover is `verbosity=0`. For this we could add a `-q` parameter, but I suggest we simply drop support for that case and have the user redirect stdout to `/dev/null` instead.

**Comment by Anthchirp** [comment]
by extension this includes any variants such as `refinement.verbosity` , `refinement_protocol.verbosity` and `scaling_options.verbosity`

Selective logging of specific components can be achieved by having dispatchers set/override the verbosity on specific loggers based on the global log level

**Comment by dagewa** [comment]
The `OptionParser` has a default verbose level of 0 rather than 1
https://github.com/dials/dials/blob/c6e92a39f074f64316ef288a614d59b545aeb75a/util/options.py#L682-L685
I would prefer the default to be 1, because I want to pass this to `RefinerFactory` to get normal output from dials.refine, but retain a `verbosity=0` option for `RefinerFactory` that silences output.

**Comment by dagewa** [comment]
I'm making that change, and removing `refinement.verbosity` in a branch. I'll push that when it is ready so that the other changes can be added

**Comment by rjgildea** [comment]
Is an explicit verbosity option not trying to do kind of the same thing as logging levels?

**Comment by dagewa** [comment]
The [retire-verbosity](https://github.com/dials/dials/tree/retire-verbosity) branch now has no more verbosity parameter within refinement. Control of verbosity should be entirely via logging levels.

@jbeilstenedmands this change also touched `algorithms/scaling/scaling_refiner.py`. I removed the verbosity parameter from the construction of `GaussNewtonIterations` and `LevenbergMarquardtIterations` but didn't change the API of `ScalingGaussNewtonIterations` or `ScalingLevenbergMarquardtIterations`

**Comment by Anthchirp** [comment]
Remaining:
* [ ] generate_mask.py
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ]

**Comment by rjgildea** [comment]
I think these are all gone now. I suspect we can now remove the following lines of code:
https://github.com/dials/dials/blob/a0fb36a3b0fc7b7ddcddfd56b35d9f9dce185bd1/util/options.py#L856-L860
