### ISSUE TITLE
unpythonic data structures: experiment_identifiers, reflection_tables

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#862]
This is how a python dictionary behaves:
```python
>>> x = {0:"0", 1:"1"}
>>> print(x, list(x.keys()), list(x.values()), list(x))
({0: '0', 1: '1'}, [0, 1], ['0', '1'], [0, 1])
```

This is how a `experiment_identifiers()` return value behaves:
```python
>>> x = reflection_table.experiment_identifiers()
>>> print(x, list(x.keys()), list(x.values()), list(x))
(<dials_array_family_flex_ext.experiment_id_map object at 0x7f6be4709758>, [0, 1], ['0', '1'], [(0, '0'), (1, '1')])
```

If the data structure pretends to be a dictionary, which the `.keys()` and `.values()` methods imply, then the default iterable should be working on `.keys()` like a regular dictionary in python.
The current default iterable could be renamed `.items()`, which `experiment_identifiers()` does not currently offer.

The same is true for `reflection_table`.

As this is an API change I suggest to decide on this before the DIALS 2.0 release.

On a related note: `.experiment_identifiers()` appears to be a function that takes no arguments. This feels wrong. Any chance this could be changed to a property?

**Comment by dagewa** [comment]
These sound like useful changes. `experiment_identifiers` stuff is fairly safe, `reflection_table` will need lots of testing across various projects

**Comment by dagewa** [comment]
Just (re)discovered `reflection_table['missing_key']` raises `RuntimeError`, not `KeyError`

**Comment by Anthchirp** [comment]
About the `RuntimeError` vs `KeyError`. As far as I can tell the only implemented exception that we can raise from C++ is `RuntimeError`. No obvious idea how we could raise anything else.

**Comment by ndevenish** [comment]
Should the KeyError thing have a `newsfragment`? Seems like something that would be useful to document. (Maybe we need an API category, though I think 'bug' would be appropriate for this)

**Comment by Anthchirp** [comment]
already written up. https://github.com/dials/dials/pull/908/files#diff-5340eab23dd2989dc9277a1ee45a2a6cR8-R9

**Comment by ndevenish** [comment]
Ah, sorry, missed that because it didn't go in with the `KeyError` change

**Comment by Anthchirp** [comment]
That's because I forgot :smile:
