### ISSUE TITLE
A simple graphical mask creation tool

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#87]
From observations from India:

a.  Because spot finding was finding lots of noise, indexing would often fail (sometimes due to the max_cell being too large). When I removed all the noise from the spot finding output, indexing generally had no problem. I removed the noise by setting global_threshold=15 and d_max=50 and then things generally worked. I also used dials.generate_mask to mask out ice rings. I would really like to have a graphical mask creation function in the image viewer (or in the image viewer for the new GUI), because I think it would be easier for the students to figure out how to remove bad bits of their images than by modifying things like the global_threshold in this case.

**Comment by rjgildea** [comment]
I have added a graphical tool in the image viewer (Menu: Actions -> Show Mask Tool) which will allow you to input values for masking out border, d_min, d_max and creating untrusted rectangles/polygons/circles. There is also an option to switch on modes for drawing untrusted rectangles/circles on top of the image. Work in progress, need to add resolution rings and ice ring options, and a draw polygon mode, and also test with multi-panel detectors. However would welcome feedback on usefulness of current state.

**Comment by dagewa** [comment]
I think this works quite well now. Closing.
