### ISSUE TITLE
call function in nave_parameter only handles a single crystal in experiment_list

### ISSUE THREAD

**Issue by asmit3** [dials/dials#875]
When an experiment list with multiple lattices is passed to stills_indexers' refine function, mosaicity of only the first crystal is determined because the call function in nave_parameter only uses the first crystal to do the calculation. To test the bug, an xfailing test has been added in 5b3338b.

**Comment by asmit3** [comment]
Closing this with 2ba968f

**Comment by dagewa** [comment]
Looks like this was fixed when #888 was merged.
