### ISSUE TITLE
how to add new basis vector search strategies ?

### ISSUE THREAD

**Issue by asmit3** [dials/dials#891]
With the new indexing API changes and introduction of entry points to pick indexing methods (like FFT1D,FFT3D etc), I was unsure how one would be able to add new indexing methods to be picked up by DIALS. For example if I write a new basis vector search strategy in basis_vector_search/strategies.py, would I have to make changes somewhere else to let DIALS know that there is a new search strategy that can be used? I noticed that the current strategies are coded in libtbx_refresh.py which is a non-obvious place to find available indexing methods. Do I have to edit that file and add my search strategy ?

**Comment by rjgildea** [comment]
Yes, if you have a new strategy to add within the dials repository, then you need to add your strategy to this list in dials/libtbx_refresh.py:
https://github.com/dials/dials/blob/a2f9aec4fcaa8dd9257cdaa49e418976b682adb7/libtbx_refresh.py#L16-L23

If your new strategy is in an external module you can define the strategy in that module's libtbx_refresh.py as follows:
```
import libtbx.pkg_utils
libtbx.pkg_utils.define_entry_points(
    {
        "dials.index.basis_vector_search_strategy": [
            "my_strategy = my_module.my_strategy_submodule:MyStrategyClass",
        ],
    }
)
```

**Comment by asmit3** [comment]
@rjgildea Thanks a lot. I was able to use the strategy from an external package as you described.  Closing the issue
