### ISSUE TITLE
Make find_spots and integrate use multiple processors and multiple cluster jobs

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#90]

**Comment by graeme-winter** [comment]
Please could you look into this sometime soon? HJB "DIALS too slow" reminded me about this... Much obliged & cheerio :)

**Comment by jmp1985** [comment]
I've implemented this for spot finding. The new behaviour expects mp.nproc=N to for number of processors on each node (and locally). Then mp.njobs=M and mp,method=METHOD to set the number of cluster jobs.

I've been running this and I noticed that easy_mp with multiple cluster jobs only submits a few jobs at a time, why does it do this? If I say I want 100 cluster jobs, I want it to submit 100 cluster jobs immediately!! Also, might in the long term be better off using drmaa or something like this that uses drmaa http://gridmap.readthedocs.io/en/latest/gridmap.html

**Comment by Anthchirp** [comment]
From what I can see we are not using the cluster scheduling in the most efficient way. I know that you can create 1 job and tell the scheduler that it contains 100 subjobs and, optionally, that it should only run up to $n of those subjobs concurrently.

**Comment by jmp1985** [comment]
Is there anyway of doing this through easy_mp though. In an ideal world I would implement the map operation as a job array. You have experience hacking easy_mp, do you think it would be feasible? Or could we make use of drmaa in easy_mp?
