### ISSUE TITLE
reflection table .as_msgpack() returns string instead of bytes

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#900]
The function
https://github.com/dials/dials/blob/2ddc9340b9399d9d0843d0f250702c9f67329647/array_family/boost_python/flex_reflection_table.cc#L834-L843
returns what appears to be a string object to python land. This is fine in Python 2, but in Python 3 this object is useless. As it is does not contain a valid utf-8 encoded string it can't be decoded into anything and can not be written to a file.

I suspect we need to make the function return the same data, but have it look like a byte array to python.

Traceback:
```
Saving refined reflections to indexed.refl
Traceback (most recent call last):
  File "modules/dials/command_line/index.py", line 268, in <module>
    run()
  File "modules/dials/command_line/index.py", line 264, in run
    indexed.export_reflections(params.output.reflections)
  File "modules/dials/command_line/index.py", line 223, in export_reflections
    self._indexed_reflections.as_msgpack_file(filename=filename)
  File "modules/dials/array_family/flex.py", line 242, in as_msgpack_file
    outfile.write(self.as_msgpack().decode("latin-1"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```

**Comment by ndevenish** [comment]
Fixing this. Is there a simple way to reproduce/a test that tests? I'm getting other errors trying to index...

**Comment by Anthchirp** [comment]
I used `pytest --regression --runxfail algorithms/indexing/test_index.py::test_index_small_molecule_ice_max_cell`
which runs
`dials.index ${DIALSREGRESSION}/indexing_test_data/MXSW-904/1_SWEEP1_experiments.json ${DIALSREGRESSION}/indexing_test_data/MXSW-904/1_SWEEP1_strong.pickle filter_ice=False`

**Comment by ndevenish** [comment]
The test still fails, but for different reasons!

**Comment by Anthchirp** [comment]
test passes with cctbx/cctbx_project#370 merged, so all is fine.

Thank you!
