### ISSUE TITLE
Provide reproducible builds

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#92]
Currently we use the cctbx bootstrap mechanism to builds DIALS. This currently means that we cannot keep proper stable branches, as bootstrap pulls in any number of external dependencies (eg. cctbx, cbflib, a number of 3rd party packages), which may change after a release date.

Fixing this may involve tasks such as
* moving cctbx to git, therefore allowing us to make use of stable cctbx releases
* keep binaries of 3rd party dependencies in some other git repository with release branches parallel to the DIALS repository
* modifying bootstrap to take in a list of revision numbers, git branch names, or commit IDs to use defined versions
* probably quite a bit more

**Comment by Anthchirp** [comment]
A new bootstrap.py is available at 
https://raw.githubusercontent.com/xia2/cctbx/dials-1.1/libtbx/auto_build/bootstrap.py
which, with the help of a small patch
https://github.com/xia2/cctbx/commit/824910733c0003c81d9a2935b125ad9f504e5ab5
a _few_ extra repositories
https://github.com/cctbx/annlib
https://github.com/cctbx/annlib_adaptbx
https://github.com/cctbx/bitshuffle
https://github.com/cctbx/boost
https://github.com/cctbx/ccp4io
https://github.com/cctbx/ccp4io_adaptbx
https://github.com/cctbx/clipper
https://github.com/cctbx/gui_resources
https://github.com/cctbx/HDF5Plugin
https://github.com/cctbx/scons
https://github.com/cctbx/tntbx
https://github.com/dials/cbflib
https://github.com/dials/dependencies
https://github.com/xia2/cctbx
and a content delivery network
https://rawgit.com/
will build the DIALS 1.1 release version.

For now this should do. Though life would be a lot easier if we were to move everything (including _regression repositories) to git, doesn't matter if github or not, and rebuild bootstrap.

**Comment by dagewa** [comment]
Thanks for this Markus!
