### ISSUE TITLE
flake8: E712 comparison to True/False

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#920]
flake8 flags lines such as:
```python
        refl.del_selected(mask != True)                                                                                 
```
with
```E712 comparison to True should be 'if cond is not True:' or 'if not cond:'```

This is not wrong - but also not right.

Since `is` is no option here the only viable alternatives are
1. some sort of alternative construct, eg `refl.del_selected(~mask)` - no idea if that works
2. create an explicit comparison function
3. disable E712

Opinions?

**Comment by graeme-winter** [comment]
+1 for `del_selected(~mask)`

**Comment by graeme-winter** [comment]
`~x` is understood as negation so this would be the most compact representation to me (to expand on comment)

**Comment by benjaminhwilliams** [comment]
I think option 1 works...

MWE:

```python
>>> from dials.array_family import flex
>>> refl = flex.reflection_table()
>>> refl['test'] = flex.int(range(5))
>>> mask = flex.bool([True, False, True, False, True])
>>> refl.del_selected(~mask)
>>> print(refl['test'].as_numpy_array())
[0 2 4]
```

**Comment by benjaminhwilliams** [comment]
Oh, sorry, my page hadn't refreshed.  @graeme-winter got there before me.

**Comment by ndevenish** [comment]
Depends how negation works for non-boolean flex arrays, but I also think `refl.del_selected(~mask)` is a good way of doing this. Can potentially see slight confusion with `!- True` etc.

**Comment by Anthchirp** [comment]
Thank you for testing this. Will update code base accordingly.
