### ISSUE TITLE
Change dials.export to not require data verification by default

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#921]
Only `dials.export format=best` requires it so we should move this to a different program. The `best` output also performs calculations and is not much used, so I think this is low cost with a high benefit that exporting data will _just work_ - a common annoyance for users.

**Comment by graeme-winter** [comment]
Side effect: retire `DIALS_EXPORT_DO_NOT_CHECK_FORMAT` 🙂

**Comment by graeme-winter** [comment]
Working on this in `dials-921` branch.

**Comment by ndevenish** [comment]
See also: #484, #639
