### ISSUE TITLE
New support email address

### ISSUE THREAD

**Issue by dagewa** [dials/dials#925]
On the subject of support emails... would there be any possibility of getting a better support email address? It seems a bit odd to have a sourceforge email address when we no longer use sourceforge at all (as well as the address itself being a bit verbose/cumbersome).

_Originally posted by @rjgildea in https://github.com/dials/dials/issues/830#issuecomment-519833548_

**Comment by graeme-winter** [comment]
Is support@dials.github.io possible?

**Comment by Anthchirp** [comment]
no

**Comment by dagewa** [comment]
What about dials.support@gmail.com?

**Comment by luisodls** [comment]
I like David's google approach, is easier to remember for anyone.


L

________________________________

**Comment by dagewa** [comment]
It seems that name "isn't allowed" (which is different to "already taken"), but dials.helpdesk@gmail.com would work. I have not created it though.
