### ISSUE TITLE
Consistent timing information via logging

### ISSUE THREAD

**Issue by noemifrisina** [dials/dials#932]
Labels are annoyingly inconsistent e.g. in dials.integrate_INTEGRATE.log it's labelled 'Total time taken', in dials.find_spots.log 'Time Taken' and so on... 
And yep, it's case sensitive.

**Comment by dagewa** [comment]
It could perhaps be done consistently using e.g. a decorator around command line program's `run` functions?

**Comment by graeme-winter** [comment]
That seems like a very reasonable suggestion. If we could work in cpu time usage as well would be excellent.

**Comment by dagewa** [comment]
This might be more difficult than I thought, because typically the logger is set up inside the `run` function.

**Comment by dagewa** [comment]
Current discussion is leaning towards prepending each message in the log _file_ by the elapsed time since program start. This can be done by a formatter that is used by the `logging.FileHandler` only, not the stdout to avoid cluttering the live display.

**Comment by dagewa** [comment]
As noted by @Anthchirp https://stackoverflow.com/questions/25194864/python-logging-time-since-start-of-program/25196134#25196134
I'll pick this up
