### ISSUE TITLE
dials.find_spots max_spot_size=1000 should be increased

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#937]
Running dials/nightly on @graeme-winter's "firehose-collect" ProtK dataset, using only the first 3600 images:

Processing in `/dls/mx-scratch/rjgildea/performance_week/firehose/`

Default spotfinding parameters:
```
$ cat 005/run.sh
module load dials/nightly
xia2 atom=S dynamic_shadow=0 atom=S image=/dls/i03/data/2019/cm23003-2/gw/20190424/firehose-collect/protk_1_13/protk_1_13_3_master.h5:1:3600
```

max_spot_size=10000:
```
$ cat 007/run.sh
module load dials/nightly
cat > find_spots.phil << EOF
spotfinder.filter.max_spot_size = 10000
EOF
xia2 atom=S dynamic_shadow=0 atom=S \
    dials.find_spots.phil_file=find_spots.phil \
    image=/dls/i03/data/2019/cm23003-2/gw/20190424/firehose-collect/protk_1_13/protk_1_13_3_master.h5:1:3600
```

Difference in output:
```
$ diff 00{5,7}/DEFAULT/SAD/SWEEP1/index/2_dials.find_spots.log 
3643,3646c3644,3647
< Removed 7209 spots with size > 1000 pixels
< Calculated 270249 spot centroids
< Calculated 270249 spot intensities
< Filtered 217417 of 270249 spots by peak-centroid distance
---
> Removed 16 spots with size > 10000 pixels
> Calculated 277442 spot centroids
> Calculated 277442 spot intensities
> Filtered 217845 of 277442 spots by peak-centroid distance
3650,3651c3651,3652
< 217417 spots found on 3600 images (max 5951 / bin)
<                                         * *****             
---
> 217845 spots found on 3600 images (max 5942 / bin)
>                                         *******             
...
3664c3665
< Saved 217417 reflections to 2_SWEEP1_strong.refl
---
> Saved 217845 reflections to 2_SWEEP1_strong.refl
3666c3667
```

Resulting increase in sigma_b/sigma_m:
```
$ diff 00{5,7}/LogFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1_INTEGRATE.log | grep sigma
<  sigma b: 0.044556 degrees
<  sigma m: 0.203628 degrees
>  sigma b: 0.044941 degrees
>  sigma m: 0.226351 degrees
```

Comparison of scaled results with `xia2.compare_merging_stats`:
```
xia2.compare_merging_stats 00{5,7}/DataFiles/*scaled_unmerged.mtz plot_labels="1e3 1e4" image_dir=compare_3600_max_spot_size
```

Increasing the max_spot_size in dials.find_spots appears to have a small but significant improvement in the merging statistics:
![image](https://user-images.githubusercontent.com/2810624/65051990-cd3ea280-d961-11e9-8290-db4ccb992c11.png)
![image](https://user-images.githubusercontent.com/2810624/65052006-d465b080-d961-11e9-8e55-74630cca7228.png)
![image](https://user-images.githubusercontent.com/2810624/65052012-d92a6480-d961-11e9-9714-ffb6627ca518.png)
![image](https://user-images.githubusercontent.com/2810624/65052022-dc255500-d961-11e9-9711-f0bfdcdc930b.png)

**Comment by graeme-winter** [comment]
I'll buy this - though that is a very large spot! Something like 40 pixels cubed? I would be interested to actually look at the spots in the 1e3 - 1e4 size range but they are few and it appears that the results are slightly better using them.

**Comment by dagewa** [comment]
Should we have `max_spot_size=auto` which translates to (say) `900 * 0.5/scan.get_oscillation()[1]`, so up to 30 by 30 pixels by 0.5 degree (==9000 for the above case)

**Comment by ndevenish** [comment]
Suggest that unless we see this happening "in the wild" often enough to be worth fixing, that we leave it as-is.

Additionally - It improved these data sets but I could very easily imagine data sets that got worse by the inclusion of these megaspots.
