### ISSUE TITLE
New spot finder produces strange mean image in the image viewer

### ISSUE THREAD

**Issue by dagewa** [dials/dials#946]
I have this image:

![65526987-de4f5c80-dee9-11e9-8d4d-7ca753431143](https://user-images.githubusercontent.com/11502083/65535930-4efe7500-defa-11e9-96fd-2f81679c97c1.png)

clicking on the "mean" button in dials.image_viewer produces very strange results:

![65527052-f3c48680-dee9-11e9-831f-a97c49ac83ce](https://user-images.githubusercontent.com/11502083/65536001-70f7f780-defa-11e9-90cb-3ac291261be1.png)

After much messing around I found that when switching the image viewer back to using `DispersionThresholdDebug` instead of `DispersionExtendedThresholdDebug` then the results look more as expected:

![65526906-ba8c1680-dee9-11e9-8d45-2cc416ad80ad](https://user-images.githubusercontent.com/11502083/65536056-8a00a880-defa-11e9-9bec-e9b951dd3994.png)

This seems really weird. Why is the mean map different between these two classes?

**Comment by dagewa** [comment]
It seems that the mean image is no longer what I understand by the mean image using `DispersionExtendedThresholdDebug`. Unfortunately, for the data set I am looking at the new "mean" image produces an almost empty array: 0.0 nearly everywhere, except for along the left hand edge.

**Comment by graeme-winter** [comment]
Seems to do something reasonably sensible with Eiger data... possibly an effect of kernel sizes?

**Comment by dagewa** [comment]
I've tried various kernel sizes with no effect - except at the patches along the left hand edge of the image. I guess at the moment my questions are:

1. What is being displayed when the "mean" image button is clicked now with the dispersion extended code?
2. Is is still reasonable to call this a "mean" image?
3. Why are there non-zero values only along one edge of the image? This last point suggests the algorithm is not symmetric, which if true would be a general concern.

I guess I can test the last point by rotating or transposing the image array prior to the calculation.

**Comment by dagewa** [comment]
As I feared, the last test shows that the algorithm has a directionality with respect to the array. Here's the image transposed in place:

![Screenshot from 2019-09-24 18-29-56](https://user-images.githubusercontent.com/11502083/65535651-c1228a00-def9-11e9-95f0-02467ff45785.png)

and when I select "mean":

![Screenshot from 2019-09-24 18-30-37](https://user-images.githubusercontent.com/11502083/65535670-c97ac500-def9-11e9-906b-ca4d442a431c.png)

this time I increased the kernel size to 10,10 to make the patches show up better on the left hand side. However _they are still on the left hand side_.

**Comment by graeme-winter** [comment]
I have to confess that I am still confused why the mean has changed. The mean is the mean, yes? 🤔 also asymmetry != good 🤨

**Comment by dagewa** [comment]
I agree on both counts!

**Comment by dagewa** [comment]
For reference, here is a section of a diffraction image that demonstrates this effect.
[as_cbf_0001.cbf.zip](https://github.com/dials/dials/files/3649440/as_cbf_0001.cbf.zip)
