### ISSUE TITLE
Timing information after performance week

### ISSUE THREAD

**Issue by noemifrisina** [dials/dials#949]
All the com14 jobs finished so here are a couple of plots showing the timings of integration and spot finding over performance week: 
![small-thaum_dials_time](https://user-images.githubusercontent.com/54588199/65783977-f40e8d00-e148-11e9-9e14-a52d96691339.png)
![fine-sliced-insulin_noH5_dials_time](https://user-images.githubusercontent.com/54588199/65784008-08eb2080-e149-11e9-8c8c-224c699f2a0d.png)
![i03-ins-720_dials_time](https://user-images.githubusercontent.com/54588199/65784010-0983b700-e149-11e9-941b-13457507f398.png)

All the lots and the .txt files containing the information are saved in '/dls/mx-scratch/dials/performance-week/timings'

**Comment by dagewa** [comment]
Thanks, these look good. The integrate time savings are significant. I guess that for find spots the initial uptick is going from the dispersion to dispersion extended algorithm, and then performance week activities took a decent bite out of that additional run time

**Comment by dagewa** [comment]
@noemifrisina you mentioned that there are some additional plots that might be useful?

**Comment by noemifrisina** [comment]
Not sure how useful but there were a couple more on mx_scratch before it disappeared. I'll check and let you know, I should have them (or the script that generated them at least) backed up somewhere.

**Comment by noemifrisina** [comment]
@dagewa I just created a new folder in mx-scratch with all the plots and time data from performance week if you'd like to take a look. I think these three here might be the most useful ones.
Everything is now in `/dls/mx-scratch/dials-timings`
