### ISSUE TITLE
Windows build broken

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#950]
Hi all, after #936 was merged the dials build on windows started failing with a linking error.  We run it nightly by buildbot on pulse.lbl.gov.  Here's the failure:

   Creating library lib\dials_util_ext.lib and object lib\dials_util_ext.exp
ccp4io.lib(library_utils.obj) : error LNK2019: unresolved external symbol __imp_GetUserNameA referenced in function ccp4
_utils_username
lib\dials_util_ext.pyd : fatal error LNK1120: 1 unresolved externals
scons: *** [lib\dials_util_ext.pyd] Error 1120

Any ideas?  Thanks!

**Comment by graeme-winter** [comment]
https://software.intel.com/en-us/forums/intel-c-compiler/topic/286524

Got to link 
/c/Program\Files/Microsoft\SDKs/Windows/v6.0A/Lib/x64/UserEnv.Lib

**Comment by phyy-nx** [comment]
Turns out it was Advapi32.lib.  Fix incoming.

**Comment by graeme-winter** [comment]
Did this fix the build?

**Comment by phyy-nx** [comment]
Dunno! Building the individual library works but the whole build takes foreeeeeeever on pulse. I’ll check it tomorrow am pst and close this issue if it works. 

-Aaron

**Comment by phyy-nx** [comment]
Ok, it compiles and links now.  Thanks.
