### ISSUE TITLE
Slow navigation between different image types

### ISSUE THREAD

**Issue by dagewa** [dials/dials#954]
As as aside, I noticed that a `DispersionExtendedThresholdDebug` (or `DispersionThresholdDebug`) is created every time one of the image type buttons is clicked, which contributes to slow navigation between the types of images. It would be better to create this only when the spot finding parameters are changed, and use the result to provide access to the various types of images, which are then already calculated.

_Originally posted by @dagewa in https://github.com/dials/dials/pull/948#issuecomment-535450372_

**Comment by graeme-winter** [comment]
+1

**Comment by dagewa** [comment]
duplicated by #1213
