### ISSUE TITLE
Clean up MTZWriter add_dataset() API

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#958]
LGTM identified that the `.add_dataset()` call on MTZWriter objects has an inconsistent API.

On the class `MTZWriter` it has this signature:
https://github.com/dials/dials/blob/fb31158b5db8b6cfe7e908d917fe261cf27bcaa5/util/export_mtz.py#L59

In `MergedMTZWriter`, a subclass of `MTZWriter` it has this signature:
https://github.com/dials/dials/blob/fb31158b5db8b6cfe7e908d917fe261cf27bcaa5/util/export_mtz.py#L85-L87

Finally, in `MADMergedMTZWriter`, a subclass of `MergedMTZWriter` it has this signature:
https://github.com/dials/dials/blob/fb31158b5db8b6cfe7e908d917fe261cf27bcaa5/util/export_mtz.py#L110-L119

Each class has their own, incompatible calling convention! Coverage indicates that all three functions are used.

The API should either be consistent among classes, or the classes shouldn't inherit from each other. Since the caller in each case already has to know which type of class it references, it may be worth considering refactoring the code and possibly replacing the three classes with a single class with three different and differently named `.add_dataset()` functions

**Comment by dagewa** [comment]
> The API should either be consistent among classes, or the classes shouldn't inherit from each other.

Just wondering, is this overly strict? If I want to add a new class that inherits from one of these but requires extra information on this call that the base classes have no reason to use then I probably would have done this too. Could this be an occasion where the API just takes `*args, **kwargs` and the call can then raise `ValueError` if the wrong arguments are passed?

**Comment by jbeilstenedmands** [comment]
I agree that the implementation was a bit sloppy. Perhaps a better design is a base class that doesn't have add_dataset, then a separate UnmergedMTZWriter and MergedMTZWriter which don't look that similar apart from their initialisation. Then MADMergedMTZWriter and MergedMTZWriter are very similar and inheritance makes sense. I'll make this proposed change and submit a PR for review.

**Comment by Anthchirp** [comment]
@dagewa function signatures should be compatible with one another.
```python
def parent_class(self, thing, other_thing, **kwargs):
def subclass1(self, thing, other_thing, third_thing=True, **kwargs):
def subclass2(self, thing, other_thing, fourth_thing=True, **kwargs):
```
would probably be fine. (Although one should consider whether passing an object would be more sensible)

Here we had
```python
def parent_class(self):
def subclass1(self, one, two=1, ...):
def subclass2(self, two, one, ...):
```
which is definitely not fine.
