### ISSUE TITLE
Proposal: Re-label ImageSweep to ImageSequence

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#965]
See https://github.com/cctbx/dxtbx/issues/106 for details

Subtleties:

`dials.import allow_multiple_sequences=True`

etc. e.g. user facing changes - is there a mechanism in Phil to allow aliases to be made? Or should this go into the 2.0 refactor?

**Comment by graeme-winter** [comment]
👍 obliged thank you

**Comment by dagewa** [comment]
> `dials.import allow_multiple_sequences=True`

`dials.import allow_multiple_experiments=True`? Sequences might be a bit esoteric for the end user? Ultimately it is experiments they will work with

**Comment by graeme-winter** [comment]
🤔

```
    allow_multiple_sequences = False
      .type = bool
      .help = "If False, raise an error if multiple sequences (sweeps) are found"
      .alias = allow_multiple_sweeps
```

gives

```
Grey-Area sc :( $ dials.import ../INS* allow_multiple_sweeps=1
Sorry: Unknown command line parameter definition: allow_multiple_sweeps = 1
Grey-Area sc :( $ dials.import ../INS* allow_multiple_sequences=1
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.976-ga83887d18
The following parameters have been modified:

input {
  allow_multiple_sequences = True
  experiments = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatCBFMiniPilatusDLS6MSN126.FormatCBFMiniPilatusDLS6MSN126'>
  num images: 1200
  num sequences: 4
  num stills: 0
--------------------------------------------------------------------------------
Writing experiments to imported.expt
```

**Comment by rjgildea** [comment]
You might need to give the full phil path (including scopes) in the alias definition.

**Comment by graeme-winter** [comment]
Nope... 

```
    allow_multiple_sequences = False
      .type = bool
      .help = "If False, raise an error if multiple sequences (sweeps) are found"
      .alias = input.allow_multiple_sweeps
```

does not work - also how would this know if the scope was pulled in from $somewhere else?

**Comment by graeme-winter** [comment]
Also even Billy found weirdness with this feature - https://github.com/cctbx/cctbx_project/issues/63

**Comment by dagewa** [comment]
experiments encompasses both sweeps and sequences? :man_shrugging:

**Comment by Anthchirp** [comment]
or could work around without aliases, ie. change defaults to `None` and if `settledname` is set then use that value otherwise print deprecation warning and use `altname1` if set, otherwise `dials1.14name` otherwise `False`

**Comment by graeme-winter** [comment]
Have to say, I hold no strong opinion so will go with the consensus. I am more keen to get rolling on the actual change, less bothered about bikeshedding on the name of the colour of the rivets used 😉
