### ISSUE TITLE
dials.generate_mask trusted_range bug

### ISSUE THREAD

**Issue by dagewa** [dials/dials#978]
The behaviour of `dials.generate_mask` appears to be to combine untrusted area definitions with the un`trusted_range` mask of the first image of a sequence. This causes overloaded spots on image 1 to be persistently masked throughout a dataset, like a flash burn. This example makes it obvious:
```bash
cat > mask.phil <<+
untrusted {
  rectangle = 0 1375 1246 1300
}
+
dials.import $(dials.data get -q x4wide)/*.cbf trusted_range=-1,100
dials.generate_mask imported.expt mask.phil
dials.import $(dials.data get -q x4wide)/X4_wide_M1S4_2_00*.cbf mask=pixels.mask
```
Now see the strong pixels from the first image masked throughout the whole dataset:
![Screenshot from 2019-10-21 21-15-15](https://user-images.githubusercontent.com/11502083/67241275-0a0f2500-f44b-11e9-84f2-42fabd02a4e5.png)

**Comment by dagewa** [comment]
Probable culprit https://github.com/dials/dials/blob/9780dfd90bc729dd3aa901a01edcfca436df18c7/util/masking.py#L144-L145

**Comment by graeme-winter** [comment]
Good spot. Suspect that this was an attempt in $past to find and mask hot pixels. Ouch.

**Comment by graeme-winter** [comment]
Verified bug but pointy finger of blame misplaced... `print(1/0)` just after this line does not cause crash.

**Comment by graeme-winter** [comment]
```
Silver-Surfer util :) [master] $ rm -rfv masking
masking/__pycache__/__init__.cpython-36.pyc
masking/__pycache__
masking/__init__.pyc
masking
```

- explains condusion - d'oh

**Comment by graeme-winter** [comment]
Branched to `trusted-pixel-range-mask` for fix.

**Comment by graeme-winter** [comment]
We should discuss how this interacts with multi-panel detectors. Also for large image sets could have better way of doing this e.g. with random sampling?

**Comment by dagewa** [comment]
I don't understand - I still see the same behaviour with the test case above while on the trusted-pixel-range-mask branch.

**Comment by graeme-winter** [comment]
```
  551  dials.import $(dials.data get -q x4wide)/*.cbf trusted_range=-1,100
  552  dials.generate_mask imported.expt mask.phil
  553  dials.import $(dials.data get -q x4wide)/X4_wide_M1S4_2_00*.cbf mask=pixels.mask
  554  dials.image_viewer imported.expt 
```

![Screenshot 2019-10-22 at 09 43 51](https://user-images.githubusercontent.com/1241716/67270375-7a9c5d00-f4b0-11e9-8bca-f3efbc331a78.png)

While this may not be helpful, it appears to work for me.

**Comment by dagewa** [comment]
I had old `.pyc` files too... Working now, thanks
