### ISSUE TITLE
dials.image_viewer does not work on sacla h5 dataset

### ISSUE THREAD

**Issue by asmit3** [dials/dials#979]
Command to reproduce:
```dials.image_viewer dials_regression/image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5 ```

Error I get:
```
Traceback (most recent call last):
  File "/net/dials/raid1/asmit/ExaFEL/dials/build/../modules/dials/command_line/image_viewer.py", line 193, in <module>
    runner()
  File "/net/dials/raid1/asmit/ExaFEL/dials/build/../modules/dials/command_line/image_viewer.py", line 131, in __call__
    self.view()
  File "/net/dials/raid1/asmit/ExaFEL/dials/build/../modules/dials/command_line/image_viewer.py", line 137, in view
    self.wrapper.display(experiments=self.experiments, reflections=self.reflections)
  File "/net/dials/raid1/asmit/ExaFEL/dials/modules/dials/util/image_viewer/spotfinder_wrap.py", line 75, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/net/dials/raid1/asmit/ExaFEL/dials/modules/dials/util/image_viewer/spotfinder_frame.py", line 556, in load_image
    show_untrusted=show_untrusted,
  File "/net/dials/raid1/asmit/ExaFEL/dials/modules/dials/util/image_viewer/slip_viewer/frame.py", line 431, in load_image
    get_raw_data=get_raw_data,
  File "/net/dials/raid1/asmit/ExaFEL/dials/modules/dials/util/image_viewer/slip_viewer/tile_generation.py", line 286, in set_image
    self.raw_image.set_raw_data(get_raw_data(self.raw_image))
  File "/net/dials/raid1/asmit/ExaFEL/dials/modules/dials/util/image_viewer/spotfinder_frame.py", line 845, in get_raw_data
    raw_data = image.get_raw_data()
  File "/net/dials/raid1/asmit/ExaFEL/dials/modules/dials/util/image_viewer/slip_viewer/frame.py", line 49, in get_raw_data
    return self.image_set[self.index]
  File "/net/dials/raid1/asmit/ExaFEL/dials/modules/dxtbx/imageset.py", line 90, in __getitem__
    return self.get_corrected_data(item)
RuntimeError: dxtbx Internal Error: /net/dials/raid1/asmit/ExaFEL/dials/modules/dxtbx/imageset.h(690): DXTBX_ASSERT(g[j] > 0) failure.
```

**Comment by graeme-winter** [comment]
@asmit3 where is the gain coming from?

```
        // Apply gain
        if (g.size() > 0) {
          for (std::size_t j = 0; j < r.size(); ++j) {
            DXTBX_ASSERT(g[j] > 0);
            c[j] = c[j] / g[j];
          }
        }
```

if gain not > 0 there are problems. Personally I would argue that this is an issue with the input data.

**Comment by asmit3** [comment]
@graeme-winter I am not exactly sure about the gain but the image viewer used to work on SACLA h5 files about a month or so back. Are these changes in imageset.h new ? If so they clearly have broken this dataset - has there been a change in how the gain is applied now vs in the past ?

**Comment by graeme-winter** [comment]
@asmit3 I suspect you can drive `git diff` as well as I - however I will have a look through the history. 

That said, the changes _did not_ break the data set. The data set _was_ broken but we did not know - if the gain is 0 as shown above it is literally impossible to extract the number of photons which gave rise to the pixel counts in the image.

**Comment by biochem-fan** [comment]
MPCCD uses a constant flat gain of 10, hard-coded to the dxtbx class.
https://github.com/cctbx/dxtbx/blob/master/format/FormatHDF5SaclaMPCCD.py#L222

I don't know why it can be negative.

**Comment by graeme-winter** [comment]
@biochem-fan thank you - I was just looking through the h5 file and had failed to find a gain map. 

However I continue to believe that the code segment above is correct, and that the gain values are (somehow) wrong.

**Comment by dagewa** [comment]
The gain of 10 appears to only get carried through to the first panel's gain map
```
In [2]: self.get_gain(0)
Out[2]: 
(<scitbx_array_family_flex_ext.double at 0x7f3c78399c50>,
 <scitbx_array_family_flex_ext.double at 0x7f3c78399dd0>,
 <scitbx_array_family_flex_ext.double at 0x7f3c76185050>,
 <scitbx_array_family_flex_ext.double at 0x7f3c761851d0>,
 <scitbx_array_family_flex_ext.double at 0x7f3c76185350>,
 <scitbx_array_family_flex_ext.double at 0x7f3c761854d0>,
 <scitbx_array_family_flex_ext.double at 0x7f3c76185650>,
 <scitbx_array_family_flex_ext.double at 0x7f3c761857d0>)

In [3]: for g in self.get_gain(0): print min(g)
10.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
```

**Comment by dagewa** [comment]
Nevertheless, the pain gain is correctly set to 10 in each case. So it would seem we are not constructing gain maps properly

**Comment by graeme-winter** [comment]
I have to ask in here why we are making a map of `10` when the static value would work just the same? i.e. would not need loops over large arrays filled with one value.

**Comment by dagewa** [comment]
That is indeed a valid question. For now, I think I have found the cause of the failure here. Testing now and fix incoming if good

**Comment by biochem-fan** [comment]
Linking to the real fix commit for future reference: https://github.com/cctbx/dxtbx/commit/1bbe863858ad2300c634332fabe010cb98ac3e07

**Comment by dagewa** [comment]
thanks, I forgot what repository I was in when I auto-closed :man_facepalming:

**Comment by asmit3** [comment]
Folks, thanks a lot for the prompt fix. Appreciate it.

**Comment by graeme-winter** [comment]
Some tests which exercise get corrected data on all the regression images would probably be a neat idea

Would have caught this much sooner... surprised that we don’t exercise this code to be honest

**Comment by rjgildea** [comment]
dxtbx/tests/test_regression_images.py::test_read_image exercises `get_raw_data()` but not `get_corrected_data()` but presumably this could easily be extended:
https://github.com/cctbx/dxtbx/blob/869b2b2b0427129ea494c34f2e8b100b6b4c37c8/tests/test_regression_images.py#L191

However, `SACLA_MPCCD_Cheetah` is explicitly skipped from this test for some reason:
https://github.com/cctbx/dxtbx/blob/869b2b2b0427129ea494c34f2e8b100b6b4c37c8/tests/test_regression_images.py#L135-L148
`"MPCCD not supported by iotbx             [2016:nakane@r1540]"`

**Comment by graeme-winter** [comment]
@rjgildea sounds right - we should extend this - I am guessing that the SACLA image is skipped because the `iotbx detectorbase` did not exist - however this would not prevent `get_*_data()` being called. I'll take a look.

**Comment by graeme-winter** [comment]
TIL: most don't have `get_corrected_data` 🤔

**Comment by dagewa** [comment]
Most format classes rely on `ImageSet::get_corrected_data` https://github.com/cctbx/dxtbx/blob/869b2b2b0427129ea494c34f2e8b100b6b4c37c8/imageset.h#L634-L639

When I found the pedestal behaviour was broken, I was also surprised to find this function wasn't explicitly tested anywhere. So I added a test in https://github.com/cctbx/dxtbx/commit/29d9c314764942e2586ae1957c772bc5ac302a3e. Unfortunately that test didn't exercise multiple panels, otherwise I would have found this bug too (but as it turns out only a few hours earlier)
