### ISSUE TITLE
DIALS 2.0 tutorial improvements

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#984]
Alongside the DIALS 2.0 release revisiting the tutorials seems like _a good idea_ - some opinions:

We should have “beginners” and “advanced” tutorials separately.
We should retire old and useless tutorials.
We should include the overall workflow picture in some of the descriptions. 

![DIALS workflow 001](https://user-images.githubusercontent.com/1241716/67551586-33f17180-f701-11e9-8cc3-d2c30a60c885.png)

Precise proposals for change:
 - [x] Processing in detail: beta-lactamase - fix up and merge in the scaling tutorial
 - [ ] Small molecule tutorial: include scaling, ignore allow_multiple_sequences
 - [x] Split into three sections: introductory, advanced, developer
 - [ ] Add "finding your way around the image viewer" and "exploring reciprocal space" tutorials explicitly to reduce load on the processing ones
 - [ ] Expunge the concept of FIXME 😉 from documentation

**Comment by graeme-winter** [comment]
Working in dials-tutorial-improvements branch

**Comment by dagewa** [comment]
See also #928

**Comment by jbeilstenedmands** [comment]
Update from me for the record. I have updated the post-integration section of the Processing in detail: beta-lactamase tutorial, however I haven't verified that the previous sections of the tutorial are all up to date.
Are we planning to keep the Thaumatin processing in detail tutorial? If so, I'll update on Monday. If not then i'll delete, transferring over any useful extra descriptions to beta-lac. It looks like there's isn't anything extra to learn from this tutorial beyond that covered in the beta-lac.

**Comment by dagewa** [comment]
processing in detail gets referred to from other tutorials, but it is possible that these references could also be updated

**Comment by graeme-winter** [comment]
Adding `geometry_viewer` to tutorial page would also be useful...

**Comment by jbeilstenedmands** [comment]
We're a bit passed 2.0 now, some points maybe valid but tutorials have moved on so closing
