### ISSUE TITLE
Write a "what's new in DIALS 2.0" human readable landing page

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#985]
To include:

Headline: from images to MTZ files with only DIALS tools. 

Subtext: complete and flexible toolkit for rotation data processing - free to all users and every line of code open to inspection. 

* new spot finding algorithm - better intensity estimates of found spots
* new reflection / experiment file names - consistent from the start, more sensible
* dials.symmetry, dials.scale, dials.cosym
* xia2 unchanged to the user, changes under the hood - default pipeline is now DIALS only
* xia2.multiplex released - smarter multi-crystal processing
* speed improvements
* improved reporting - better HTML output with misc. fixes
* flexible work flow for handling tricky data sets
* Python 2 / 3 compatible - algorithms can now be combined with modern libraries e.g. for machine learning 

@graeme-winter to collate text, @rjgildea to polish into right formats etc.

**Comment by Anthchirp** [comment]
Need to make clear that Python 3 is compatible but unsupported. xia2 is known incompatible. I would call it 'experimental'. Next release will likely be start of support.

**Comment by graeme-winter** [comment]
@rjgildea something like:

DIALS 2.0: from images to MTZ files with DIALS
Complete toolkit for processing of X-ray diffraction data from area detectors to scaled intensities - free to all users and every line of code available for inspection at https://github.com/dials/dials. 

Thanks to the efforts of everyone in the team we are please to announce the release of DIALS 2.0 for processing of crystallographic rotation data. This includes a large number of changes in particular:

* symmetry determination and scaling - used by default in xia2
* flexible workflows for challenging data
* improvements to speed across the code base to address more challenging data sets
* more consistent output file naming
* multi-crystal analysis with cosym and xia2.multiplex
* large number of small changes
* Python 3 compatible code (experimental: will be fully supported in next major release)

As always we are constantly working on bug fixes and improvements so already we are at 2.0.1. The binaries for download can be found at:

Downloads: https://dials.github.io/installation.html

With the tutorial documentation at:

Documentation at: https://dials.github.io 

If you have any problems please feel free to log issues at:

Issues: https://github.com/dials/dials/issues 

Or drop us a line at dials-support@lists.sourceforge.net

This work is only possible thanks to the support of funding agencies:

Diamond Light Source
CCP4 
Biostruct-X project No. 283570 (EU FP7)
Wellcome Trust (Grant No. 202933/Z/16/Z) 
US National Institutes of Health grants GM095887 and GM117126

Which in turn reflects the support offered from the community for our efforts, so thank you. 

Sent on behalf of the DIALS development group.

**Comment by dagewa** [comment]
Looks pretty good. A few comments:
> * large number of small changes

 I don't think it adds much to state this, especially as above it already says
> This includes a large number of changes in particular:

Linking to release notes would be useful.

I wonder if mentioning auto-formatting and linting tools such as black, clang-format and lgtm would be useful? These help consistency and reduces code smells, both of benefit the users for whom
> every line of code available for inspection

**Comment by rjgildea** [comment]
> Linking to release notes would be useful.

Yes, [release notes](https://github.com/dials/dials/releases/tag/v2.0.0) would be useful  👀

**Comment by Anthchirp** [comment]
Used this as a start for https://github.com/dials/dials/releases/tag/v2.0.0 and ended up rewriting most of it. At least we now _have_ release notes :)
