### ISSUE TITLE
output unindexed reflections does not work

### ISSUE THREAD

**Issue by dagewa** [dials/dials#987]
It appears that this no longer produces a file of unindexed reflections:
```
dials.index imported.expt strong.refl output.unindexed_reflections=unindexed.refl
```

**Comment by rjgildea** [comment]
I would suggest removing this parameter entirely as the unindexed reflections are output in the output.reflections file anyway. If it really is needed to separate them out then this functionality should be added to `dials.filter_reflections` (if it doesn’t exist already).

**Comment by dagewa** [comment]
This seems to do the job:
```
dials.index $(dials.data get -q multi_crystal_proteinase_k)/*_1.*
dials.filter_reflections indexed.refl flag_expression="~indexed"
```
I agree that `output.unindexed_reflections` would be redundant if it worked, so better to remove.
