### ISSUE TITLE
DIALS 1.1.x updates

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#99]
Once the 1.1 release process works, merge in these pending updates on the 1.1 release branch:

dials
====
https://github.com/dials/dials/commit/de775304a44f607ea87c32d291b55c5da5da2bef

cctbx
====
cherry-pick all rjgildea-commits up to r23991:
https://sourceforge.net/p/cctbx/code/23991/log/?path=

cherry-pick https://sourceforge.net/p/cctbx/code/24004/

xia2
====
update to https://github.com/xia2/xia2/commit/17b7accb9645577126b5f511c8bd988b93421592
@rjgildea include this change? https://github.com/xia2/xia2/commit/76c64cdb3e2bf9b1352f805a922376d71f0d2a15

**Comment by jmp1985** [comment]
If there is the possibility of merging into the release branch and Friday isn't too late, I'd quite like the stuff I'm working on now to be in the release (pending some testing etc).

**Comment by Anthchirp** [comment]
The 1.1 release branch does not test with xia2_regression, dials_regression, phenix_regression present for $reasons. The main reason being that we cannot select the proper repository revision on Jenkins.

So any breaking changes **must** be properly tested locally. Using the correct revisions.
For the record, these are (probably)
* dials_regression: r1310
* xia2_regression: 43f4918
* phenix_regression: r3705

**Comment by Anthchirp** [comment]
Eiger fixes by @graeme-winter 
Are these all?

cctbx
====
https://sourceforge.net/p/cctbx/code/23392/
https://sourceforge.net/p/cctbx/code/23393/
https://sourceforge.net/p/cctbx/code/24011/
https://sourceforge.net/p/cctbx/code/24012/

xia2
====
https://github.com/xia2/xia2/commit/515dca93ca2339c48ef33e5d0a141f9f98123d49

**Comment by Anthchirp** [comment]
How to prepare a point release:
https://github.com/dials/dials/wiki/point-release

**Comment by Anthchirp** [comment]
1.1.2 release done. Open new tickets for other changes.

**Comment by jmp1985** [comment]
Hi Markus,

I had a problem with the instructions. I did the following (however, I already have a branch so I did "git checkout faster_dp" which is what I called my branch).


cd dials
git checkout release-1.1
git pull --rebase
git checkout -b update-1.1.1 # or any other name, avoid 'release-'-prefix
git push origin -u

When I did git push origin -u, I got the following output

fatal: The current branch faster_dp has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin faster_dp

I didn't want to do anything in case I messed up. Should I run this command?

Thanks,

James

________________________________
