### ISSUE TITLE
dials.refine leaves panels behind in multipanel refinement

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#990]
A problem we've had for some time, but I thought I'd create an issue for it since I hit it again.  Refining the JF16M. 256 panels arranged in 4 level hierarchy, a lot like the cspad.  Refinement params for level 2:

```
refinement {
  parameterisation {
    auto_reduction {
      min_nref_per_parameter = 3
      action = fail fix *remove
    }
    beam {
      fix = *all in_spindle_plane out_spindle_plane wavelength
    }
    detector {
       hierarchy_level = 2
       fix_list = Group1Tau1,Tau2,Tau3
       constraints {
         parameter = Dist
       }
    }
  }
  refinery {
    engine = *SparseLevMar
  }
  reflections {
    outlier {
      algorithm = None
      separate_experiments = False
      separate_panels = True
    }
  }
}
```

The important bit here is constraints.  All groups at level 2 are constrained to move together along their normal.  However, as is often the case, we don't have data that covers all the panel groups so some are fixed and left behind during refinement.  Result:

![Screenshot from 2019-10-28 11-02-54](https://user-images.githubusercontent.com/13471434/67669791-de240000-f972-11e9-9554-fa7426ec148a.png)

Ideally, after refinement using constraints, the panel groups that weren't refined would have the new deltas applied.

I have code in cspad.cbf_meterology that does this:
https://github.com/cctbx/cctbx_project/blob/master/xfel/command_line/cspad_cbf_metrology.py#L494-L556

But I'd prefer to have this native in dials.refine.

**Comment by graeme-winter** [comment]
@phyy-nx would think this is one for @dagewa however he's offline for a week - so lack of a response is due to logistics nothing else.

**Comment by graeme-winter** [comment]
BTW how come refining individual chip positions within one module - do they really move by a measurable amount? In equivalent system with Eiger we assume they are "perfect" and don't see the chip boundaries in the dx, dy maps.

**Comment by phyy-nx** [comment]
Right, the individual chip positions are at level 3 and are fixed so I'm not refining them.  They are fixed within a module. The hierarchy is 1 detector, 4 quads, 32 modules (4x2) and 256 chips.

**Comment by dagewa** [comment]
Hi @phyy-nx I think I see your point. The constraints imply all panel groups should move together, but because some panel groups have no reflections on them they aren't even parameterised, therefore they sidestep the constraints. Does sound like a bug. I can look at when I'm back, but unlikely before the 11th Nov.

**Comment by dagewa** [comment]
@phyy-nx this is proving to be tricky to solve with modifications to the current code. It may be better to rewrite the whole parameter auto-reduction system. That will, of course, take a bit longer.

**Comment by dagewa** [comment]
Are you using `auto_reduction.detector_reduce=True`?

My proposal is to simplify the procedure by first setting up a full parameterisation without looking at which parameters have the fewest associated reflections (but do take constraints into account). Then calculate gradients once, which will identify columns in the Jacobian with fewer than `min_nref_per_parameter` non-zero entries. This identifies the weakly-supported parameters, which are then fixed and a full parameterisation is created again.

This will give more flexibility and is simpler than the current approach, but I'm not sure what to do about  `auto_reduction.detector_reduce`.

**Comment by phyy-nx** [comment]
Hi, seems like a reasonable solution.  We are not actively using
detector_reduce, even though we were excited about it when it was
created, nor have we published a newsletter article or paper that used it.
I think it could safely go if that made resolving this issue easier.
