### ISSUE TITLE
dials.refine: if multiple experiments in input with 1 crystal and scan varying, please duplicate not crash

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#994]
If I index a multi-sweep data set with a single crystal - as common for e.g. chemical crystallography - when I come to refine with `dials.refine indexed.* scan_varying=auto` it complains with:

```
Sorry: A single scan-varying crystal model cannot be refined when associated with more than one scan or goniometer
```

Obviously what I may expect is for the crystal to be duplicated and then `scan_varying` refinement be performed. 

At the moment we handle this in dials.index with `split_experiments=true` (a hack I added) but @rjgildea suggested this is better handled in refinement and I am minded to agree.

Example data attached. 

[indexed.zip](https://github.com/dials/dials/files/3797061/indexed.zip)

**Comment by graeme-winter** [comment]
At the moment at the end of index we have 

```
    # Save experiments
    if params.output.split_experiments:
        logger.info("Splitting experiments before output")
        indexed_experiments = ExperimentList(
            [copy.deepcopy(re) for re in indexed_experiments]
        )
    logger.info("Saving refined experiments to %s" % params.output.experiments)
    assert indexed_experiments.is_consistent()
    indexed_experiments.as_file(params.output.experiments)
```

So it does exactly what it says on the tin - which may or may not be correct / desired, but does "work" - that said adding this behaviour to the _input_ of dials.refine would be ugly. 🤔 this is not obvious. 

Should it -
 - duplicate experiments in dials.index by default as above
 - duplicate only the _crystal_ in dials.index
 - duplicate the _crystal_ on input to dials.refine
 - split the experiment completely as above on dials.refine

I am kinda-sorta tempted to think that no. 3 is probably the correct solution here.

**Comment by graeme-winter** [comment]
WIP in split_crystals_scan_vary branch.

**Comment by rjgildea** [comment]
I think logically this belongs in `dials.refine`. Modifying the _output_ of `dials.index` based upon what you _may_ want to do in downstream programs seems like the wrong way to go about it. If `dials.index` has done joint refinement on the crystal model, then it makes sense for `dials.index` to output a joint crystal model. If this is handled by `dials.refine`, then you would potentially be able to do further joint static refinement, split static refinement, or split scan-varying refinement on the same output files, without having to re-run `dials.index` to accomplish such a task.

**Comment by graeme-winter** [comment]
This is now fixed.

**Comment by dagewa** [comment]
We were going to add a test?
https://github.com/dials/dials/pull/995#issuecomment-549395040

**Comment by graeme-winter** [comment]
Oh yeh that

**Comment by dagewa** [comment]
I'll write one. `dials_data/l_cysteine_dials_output` exercises the code path
